
package integrasi.ws.gis;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WEB SERVICE SOAP WSDL", targetNamespace = "http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php", wsdlLocation = "http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php?wsdl")
public class WEB_0020SERVICE_0020SOAP_0020WSDL
    extends Service
{

    private final static URL WEB_0020SERVICE_0020SOAP_0020WSDL_WSDL_LOCATION;
    private final static WebServiceException WEB_0020SERVICE_0020SOAP_0020WSDL_EXCEPTION;
    private final static QName WEB_0020SERVICE_0020SOAP_0020WSDL_QNAME = new QName("http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php", "WEB SERVICE SOAP WSDL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEB_0020SERVICE_0020SOAP_0020WSDL_WSDL_LOCATION = url;
        WEB_0020SERVICE_0020SOAP_0020WSDL_EXCEPTION = e;
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL() {
        super(__getWsdlLocation(), WEB_0020SERVICE_0020SOAP_0020WSDL_QNAME);
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEB_0020SERVICE_0020SOAP_0020WSDL_QNAME, features);
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL(URL wsdlLocation) {
        super(wsdlLocation, WEB_0020SERVICE_0020SOAP_0020WSDL_QNAME);
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEB_0020SERVICE_0020SOAP_0020WSDL_QNAME, features);
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WEB_0020SERVICE_0020SOAP_0020WSDL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WEB_0020SERVICE_0020SOAP_0020WSDLPortType
     */
    @WebEndpoint(name = "WEB SERVICE SOAP WSDLPort")
    public WEB_0020SERVICE_0020SOAP_0020WSDLPortType getWEB_0020SERVICE_0020SOAP_0020WSDLPort() {
        return super.getPort(new QName("http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php", "WEB SERVICE SOAP WSDLPort"), WEB_0020SERVICE_0020SOAP_0020WSDLPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WEB_0020SERVICE_0020SOAP_0020WSDLPortType
     */
    @WebEndpoint(name = "WEB SERVICE SOAP WSDLPort")
    public WEB_0020SERVICE_0020SOAP_0020WSDLPortType getWEB_0020SERVICE_0020SOAP_0020WSDLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php", "WEB SERVICE SOAP WSDLPort"), WEB_0020SERVICE_0020SOAP_0020WSDLPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEB_0020SERVICE_0020SOAP_0020WSDL_EXCEPTION!= null) {
            throw WEB_0020SERVICE_0020SOAP_0020WSDL_EXCEPTION;
        }
        return WEB_0020SERVICE_0020SOAP_0020WSDL_WSDL_LOCATION;
    }

}
