
package integrasi.ws.gis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WEB SERVICE SOAP WSDLPortType", targetNamespace = "http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WEB_0020SERVICE_0020SOAP_0020WSDLPortType {


    /**
     * GET latlong  by UPI
     * 
     * @param noJKPTG
     * @param upi
     * @return
     *     returns com.fortiddns.geo.webgis_soap.spatialsoap.SpatialArray
     */
    @WebMethod(action = "urn:http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php/readbyid")
    @WebResult(partName = "return")
    public SpatialArray readbyid(
        @WebParam(name = "NO_JKPTG", partName = "NO_JKPTG")
        String noJKPTG,
        @WebParam(name = "UPI", partName = "UPI")
        String upi);

    /**
     * Read all UPI
     * 
     * @return
     *     returns com.fortiddns.geo.webgis_soap.spatialsoap.SpatialArray
     */
    @WebMethod(action = "urn:http://geo.fortiddns.com/WebGIS-SOAP/spatialsoap.php/readall")
    @WebResult(partName = "return")
    public SpatialArray readall();

}
