

 -- 20201007 cyber

INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'root');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'online_htp');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'online_kjp');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'online_kjpagensi');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'adminppk');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'user_ppk');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'usernegeri_ppk');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)KetuaPenolongPengarah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)KetuaPenolongPengarahUnit');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PelukisPelan');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PembantuTadbirSekyenPengambilanTanah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PembantuTadbirUnitPengambilanTanah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)Pengarah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PengarahTanahdanGalian');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PengarahUnit');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenghantarNotis');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPegawai TanahSeksyenPengambilanTanah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPegawaiTanahUnitPengambilanTanah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPegawaiTanahUnitPengambilanTanah(NT17)');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPegawaiTanahUnitPengambilanTanah(NT27)');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPengarah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PenolongPengarahUnit');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', '(PPT)PentadbirTanahdanDaerah');
INSERT INTO EKPTGHQUAT.ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('FrmPopupTolakPermohonan', 'adminppt');


SELECT * FROM ROLE_MODULE
WHERE MODULE_ID = 'ekptg.view.ppt.FrmPopupTolakPermohonan'

INSERT INTO MODULE
(MODULE_ID, MODULE_TITLE, MODULE_CLASS, MODULE_GROUP, MODULE_DESCRIPTION, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI, MODULE_VERSION)
VALUES('FrmPopupTolakPermohonan', 'popup tolak', 'ekptg.view.FrmPopupTolakPermohonan', 'EKPTG - PPT', NULL, NULL, NULL, NULL, NULL, NULL);

SELECT * FROM module
WHERE MODULE_CLASS LIKE '%FrmPopupTolakPermohonan%'


--9920103172 (60)
--9920103171 (59)

SELECT * FROM TBLRUJSUBURUSANSTATUS
WHERE ID_SUBURUSAN=59
AND ID_STATUS=270


-- 20201007 cyber

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(59, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(60, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);


 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
----HTP
-- 20201007 cyber

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(41, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(41, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(40, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(40, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(39, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(39, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(38, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(38, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(47, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(47, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(46, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(46, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(45, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(45, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(18, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(18, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(17, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(17, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(7, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(7, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);


INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(25, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(25, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(24, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(24, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(23, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(23, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(15, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(15, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(14, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(14, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(13, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(13, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(6, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(6, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(5, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(5, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(4, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(4, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(3, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(3, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(2, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(2, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(1, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(1, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(42, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(42, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

SELECT * FROM TBLRUJSUBURUSAN
WHERE
--ID_URUSAN IN (1,10)
--ID_URUSAN IN(2)
--ID_URUSAN IN(3)
--ID_URUSAN IN(108)
ID_URUSAN IN(14)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--HTP


SELECT * FROM TBLRUJSUBURUSAN
WHERE 
--ID_URUSAN  IN (1,10) 
--ID_URUSAN  IN (2) 
--ID_URUSAN  IN (3) 
--
ID_URUSAN  IN (108) 
ID_URUSAN  IN (14) 

SELECT * FROM TBLRUJURUSAN
WHERE 
--NAMA_URUSAN LIKE '%GADAIAN%'
NAMA_URUSAN LIKE '%PERAKUAN%'

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--PENGAMBILAN
-- 20201007 cyber

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(51, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(51, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(52, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(52, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(53, 158, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 51, NULL);

INSERT INTO TBLRUJSUBURUSANSTATUS
(ID_SUBURUSAN, ID_STATUS, AKTIF, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, LANGKAH, MODULE_ID)
VALUES(53, 270, NULL, 1, TIMESTAMP '2013-07-15 00:00:00.000000', 1, NULL, 50, NULL);


SELECT * FROM  TBLRUJSUBURUSANSTATUS
	WHERE ID_SUBURUSAN IN (
		SELECT ID_SUBURUSAN FROM TBLRUJSUBURUSAN
		WHERE ID_URUSAN = 17
	)

SELECT * FROM TBLRUJSUBURUSAN
WHERE ID_URUSAN = 17

SELECT * FROM TBLRUJURUSAN
WHERE 
NAMA_URUSAN LIKE '%PENGAMBILAN%'

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--PHP

SELECT * FROM TBLRUJSUBURUSAN
WHERE 
ID_URUSAN  IN (7,8,9)

SELECT * FROM TBLRUJURUSAN
WHERE 
--NAMA_URUSAN LIKE '%PENYEWAAN%'
--NAMA_URUSAN LIKE '%AKTA%'
--NAMA_URUSAN LIKE '%PELEPASAN%'
--NAMA_URUSAN LIKE '%TUKAR%'
--NAMA_URUSAN LIKE '%KUASA%'

+++++++++++++++++++++++++++++++++++++++++++++++++++++
--PPK

SELECT * FROM TBLRUJSUBURUSAN
WHERE ID_URUSAN  IN (382)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--GUNA ID 158 (TINDAKAN TELAH DIAMBIL)

-- 20201007 cyber
-- STATUS 270 (PERMOHONAN DIKEMBALIKAN)
INSERT INTO TBLRUJSTATUS
(ID_STATUS, KOD_STATUS, KETERANGAN, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI, ID_SEKSYEN)
VALUES(270, '270', 'PERMOHONAN DIKEMBALIKAN', NULL, NULL, NULL, NULL, 0);

SELECT * FROM TBLRUJSTATUS WHERE id_status=270

SELECT * FROM TBLRUJSTATUS
WHERE KETERANGAN LIKE '%TINDAKAN%'
ORDER BY ID_STATUS DESC

++++++++++++++++++++++++++++++++++++++++++++++++++++++++

SUBMODUL JRP

SELECT * FROM TBLRUJSUBURUSANSTATUS
WHERE ID_SUBURUSAN=9920122
ORDER BY LANGKAH

--9920122
SELECT * FROM TBLRUJSUBURUSAN
WHERE
--ID_URUSAN IN (1,10)
--ID_URUSAN IN(2)
--ID_URUSAN IN(3)
--ID_URUSAN IN(108)
ID_URUSAN IN (14)

