

--2017/04/25 Run Staging inviroment, db staging
--2017/04/21 Run POC inviroment, db ekptg   
ALTER TABLE
   USER_ROLE
MODIFY
   (
   ROLE_ID  VARCHAR(100)
   );
   
   
--2017/04/25 Run Staging inviroment, db staging   
--2017/04/21 Run POC inviroment, db ekptg   
ALTER TABLE
   USERS_ONLINE
ADD
   (
   ID_BANDAR  NUMBER
	,FLAG_AKTIF VARCHAR2(1)
   );
 
   
ALTER TABLE
   MODULE
ADD
   (
   ID_MASUK  NUMBER,
   ID_KEMASKINI NUMBER,
   TARIKH_MASUK  DATE,
   TARIKH_KEMASKINI DATE
   );
   
--2017/04/25 Run Staging inviroment, db staging   
--2017/04/21 Run POC inviroment, db ekptg   
ALTER TABLE
   USERS_KEMENTERIAN
ADD
(
   EMEL  VARCHAR(100)
   ,NO_KP_BARU  VARCHAR(12)
   ,FLAG_AKTIF VARCHAR2(1)

);
   
--CODING DELETE DUPLICATE DATA UNTUK USERS_INTERNAL & USERS_INTEGRASI
DELETE FROM USERS_INTERNAL WHERE ROWID IN
                           (SELECT 
                           --USERS_INTERNAL.USER_ID,
                           --COUNT(USERS_INTERNAL.USER_ID) AS CNT,
                           MIN(USERS_INTERNAL.ROWID) AS ID
                           FROM USERS_INTERNAL, USERS_INTEGRASI 
                           WHERE USERS_INTERNAL.USER_ID = USERS_INTEGRASI.USER_ID
                           GROUP BY USERS_INTERNAL.USER_ID
                           HAVING COUNT(USERS_INTERNAL.USER_ID) > 1)
                           
                           
ALTER TABLE
   TBLINTRUJPEJABAT
ADD
(
   POSKOD  VARCHAR(5),
   ID_BANDAR  NUMBER
);


ALTER TABLE 
	MODULE 
ADD 
	(
MODULE_VERSION VARCHAR2(20)
	);
	
	
ALTER TABLE
   PAGE_CSS
ADD
   (
   CONTENT BLOB,
   NAMA_DOC VARCHAR(100),
   JENIS_MIME VARCHAR(100)   
   );
   
--2017/04/25 Run POC inviroment, db ekptg   
ALTER TABLE 
	USERS_INTERNAL 
ADD 
	(
   JAWATAN  VARCHAR(100)
	,FLAG_AKTIF VARCHAR2(1)
	);
    
--2017/04/25 Run Staging inviroment, db staging   
--2017/04/25 Run POC inviroment, db ekptg   
ALTER TABLE USERS_INTERNAL
 ADD (WAKTU_KERJA  VARCHAR2(10 BYTE));
     
ALTER TABLE 
	USERS_KEMENTERIAN
ADD 
	(
FLAG_AKTIF VARCHAR2(1)
	); 
    
--2017/04/25 Run Staging inviroment, db staging   
--2017/04/21 Run POC inviroment, db ekptg    
ALTER TABLE 
	USERS_INTEGRASI
ADD 
	(
	 JAWATAN  VARCHAR(100)
	 ,FLAG_AKTIF VARCHAR2(1)
	); 
   
	
	


--SEQ BARU PERMOHONAN ID PENGGUNA
CREATE SEQUENCE PERMOHONANIDPENGGUNA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


--TABLE BARU PERMOHONAN ID PENGGUNA

DROP TABLE PERMOHONANIDPENGGUNA CASCADE CONSTRAINTS;

CREATE TABLE PERMOHONANIDPENGGUNA
(
  USER_ID              NUMBER(38),--SEQ
  NOKP           VARCHAR2(12 BYTE),
  USER_NAME            VARCHAR2(200 BYTE),
  TARIKH_PENDAFTARAN      DATE,
  TARIKH_KEPUTUSAN      DATE,
  ID_PENYEMAK      NUMBER,
  ID_TABLEUSERS      NUMBER,
  ID_PEJABATJKPTG      NUMBER,
  ID_JAWATAN      NUMBER,
  ID_SEKSYEN      NUMBER,
  ID_NEGERI      NUMBER,
  NO_HP            VARCHAR2(30 BYTE),
  EMEL            VARCHAR2(200 BYTE),
  CATATAN            VARCHAR2(4000 BYTE),
  PEGAWAIPENYELIA    VARCHAR2(200 BYTE),
  CONTENT BLOB,
  NAMA_DOC VARCHAR(100),
  JENIS_MIME VARCHAR(100),
  FLAG_STATUS     NUMBER -- 1-PERMOHONAN BARU 2-DITOLAK 3-DITERIMA
  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER PERMOHONANIDPENGGUNA_BI    
before insert on     PERMOHONANIDPENGGUNA    for each row
begin    if :new.USER_ID    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || PERMOHONANIDPENGGUNA_SEQ.NEXTVAL into :new.USER_ID   from dual; end if;    end;
/

	

INSERT INTO ROLE (NAME, DESCRIPTION, THEME)
   VALUES ('root', 'ROOT', 'eTapp_Admin.css');
	
 --FLAG_AKTIF UNTUK TABLE TBLRUJPEJABAT
 ALTER TABLE 
	TBLRUJPEJABAT 
ADD 
	(
FLAG_AKTIF VARCHAR2(1)
	);
    
--2017/04/25 Run Staging inviroment, db staging   
--2017/04/21 Run POC inviroment, db ekptg   
ALTER TABLE
   USERS
ADD
   ( 
   LAST_CHANGEPASSWORD DATE
   );	
   
 ALTER TABLE
   ROLE
ADD
   (   
   ROLE_DETAILS VARCHAR2(4000)
   );
   
   
 
   
  CREATE SEQUENCE TBLSEJARAHPENGGUNAUTAMA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLSEJARAHPENGGUNAUTAMA
( 
  ID_SEJARAHPENGGUNAUTAMA NUMBER(20) NOT NULL,
  JENIS_AKTIVITI VARCHAR2(10) NOT NULL, --INSERT,UPDATE,DELETE
  USER_ID NUMBER NOT NULL,
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLSEJARAHPENGGUNAUTAMA PRIMARY KEY (ID_SEJARAHPENGGUNAUTAMA)
);

CREATE OR REPLACE TRIGGER TBLSEJARAHPENGGUNAUTAMA_BI    
before insert on     TBLSEJARAHPENGGUNAUTAMA    for each row
begin    if :new.ID_SEJARAHPENGGUNAUTAMA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLSEJARAHPENGGUNAUTAMA_SEQ.NEXTVAL into :new.ID_SEJARAHPENGGUNAUTAMA   from dual; end if;    end;
/


CREATE SEQUENCE TBLSEJARAHPENGGUNASUB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLSEJARAHPENGGUNASUB
( 
  ID_SEJARAHPENGGUNASUB NUMBER(20) NOT NULL,
  ID_SEJARAHPENGGUNAUTAMA NUMBER(20) NOT NULL,
  REKOD_SEBELUM VARCHAR2(4000),
  REKOD_SELEPAS VARCHAR2(4000),
  REKOD_LABEL VARCHAR2(500),
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLSEJARAHPENGGUNASUB PRIMARY KEY (ID_SEJARAHPENGGUNASUB)
);

CREATE OR REPLACE TRIGGER TBLSEJARAHPENGGUNASUB_BI    
before insert on     TBLSEJARAHPENGGUNASUB    for each row
begin    if :new.ID_SEJARAHPENGGUNASUB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLSEJARAHPENGGUNASUB_SEQ.NEXTVAL into :new.ID_SEJARAHPENGGUNASUB  from dual; end if;    end;
/
   
--diba tambah 16/2/17
ALTER TABLE 
TBLRUJJENISPEJABAT
ADD  
(
NAMA_LAIN_JENIS_PEJABAT VARCHAR2(30),
PENERANGAN_LANJUT VARCHAR2(30)
);   

ALTER TABLE 
TBLRUJPEJABATJKPTG
ADD  
(
FLAG_AKTIF VARCHAR2(1)
);   

--20/2/17
ALTER TABLE 
TBLRUJSEKSYEN
 ADD (
 FLAG_AKTIF  NUMBER,
 CATATAN VARCHAR2(4000 BYTE)
 );
 
 
 --tambah table klasifikasi 1/3/17
 
 CREATE SEQUENCE TBLRUJGRED_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1;
  
  
  
CREATE SEQUENCE TBLRUJKLASIFIKASI_SEQ
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1;
  
  
 ALTER TABLE TBLRUJGRED
 DROP PRIMARY KEY CASCADE;

DROP TABLE TBLRUJGRED CASCADE CONSTRAINTS;

CREATE TABLE TBLRUJGRED
(
  ID_GRED           NUMBER(38)                  NOT NULL,
  NAMA_GRED         VARCHAR2(50 BYTE),
  KETERANGAN        VARCHAR2(200 BYTE),
  ID_KEMASKINI      NUMBER,
  ID_MASUK          NUMBER,
  TARIKH_KEMASKINI  DATE,
  TARIKH_MASUK      DATE,
  FLAG_STATUS       NUMBER,
  ID_KLASIFIKASI    NUMBER(38)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLRUJGRED_PK ON TBLRUJGRED
(ID_GRED)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLRUJGRED ADD (
  CONSTRAINT TBLRUJGRED_PK
 PRIMARY KEY
 (ID_GRED)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
ALTER TABLE TBLRUJKLASIFIKASI
 DROP PRIMARY KEY CASCADE;

DROP TABLE TBLRUJKLASIFIKASI CASCADE CONSTRAINTS;

CREATE TABLE TBLRUJKLASIFIKASI
(
  ID_KLASIFIKASI    NUMBER(38)                  NOT NULL,
  NAMA_KLASIFIKASI  VARCHAR2(200 BYTE),
  KETERANGAN        VARCHAR2(200 BYTE),
  ID_KEMASKINI      NUMBER,
  ID_MASUK          NUMBER,
  TARIKH_KEMASKINI  DATE,
  TARIKH_MASUK      DATE,
  FLAG_STATUS       VARCHAR2(1 BYTE),
  ID_GRED           NUMBER(38)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLRUJKLASIFIKASI_PK ON TBLRUJKLASIFIKASI
(ID_KLASIFIKASI)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLRUJKLASIFIKASI ADD (
  CONSTRAINT TBLRUJKLASIFIKASI_PK
 PRIMARY KEY
 (ID_KLASIFIKASI)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


ALTER TABLE
  TBLRUJKLASIFIKASI
ADD
   (
   NAMA_LAIN_KLASIFIKASI  VARCHAR2(20)
   );
   
   
      ALTER TABLE TBLRUJKLASIFIKASI
DROP COLUMN ID_GRED;


   
ALTER TABLE TBLRUJKHIDMAT
 DROP PRIMARY KEY CASCADE;

DROP TABLE TBLRUJKHIDMAT CASCADE CONSTRAINTS;

CREATE TABLE TBLRUJKHIDMAT
(
  ID_KHIDMAT         NUMBER(38)   NOT NULL,
  NAMA_KHIDMAT VARCHAR2(100),
  NAMA_LAIN_KHIDMAT  VARCHAR2(50 BYTE),
  KETERANGAN         VARCHAR2(200 BYTE),
  KETERANGAN_KHIDMAT VARCHAR2(100),
  FLAG_STATUS        VARCHAR2(1 BYTE),
  SKOP_GRED          VARCHAR2(100 BYTE),
  CATATAN            VARCHAR2(200 BYTE),
  SUMBER_MAKLUMAT    VARCHAR2(100 BYTE),
  ID_MASUK           NUMBER,
  ID_KEMASKINI       NUMBER,
  TARIKH_MASUK       DATE,
  TARIKH_KEMASKINI   DATE
 
  ALTER TABLE TBLRUJKHIDMAT
RENAME COLUMN SKOP_GRED TO SKOP_GRED1;

ALTER TABLE TBLRUJKHIDMAT
 ADD (SKOP_GRED2  VARCHAR2(100 BYTE));
 
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX TBLRUJKHIDMAT_PK ON TBLRUJKHIDMAT
(ID_KHIDMAT)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLRUJKHIDMAT ADD (
  CONSTRAINT TBLRUJKHIDMAT_PK
 PRIMARY KEY
 (ID_KHIDMAT)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


DROP SEQUENCE TBLRUJKHIDMAT;

CREATE SEQUENCE TBLRUJKHIDMAT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
			   

			  


                         
   ALTER TABLE
   TBLRUJGRED
DROP
   (
   ID_JAWATAN 
   );
   
   ALTER TABLE 
TBLRUJGRED
ADD  
(
ID_JAWATAN NUMBER(10)

); 

  
 --alter TBLMEMO for pengumuman
UPDATE TBLMEMO 
SET FLAG_ROLE_INTERNAL = 2
WHERE FLAG_ROLE_ONLINE = 1;

ALTER TABLE TBLMEMO
RENAME COLUMN FLAG_ROLE_INTERNAL TO FLAG_ROLE;

ALTER TABLE TBLMEMO DROP COLUMN FLAG_ROLE_ONLINE;

ALTER TABLE TBLMEMO RENAME COLUMN FLAG_ROLE TO FLAG_ROLE_INTERNAL;

--2017/04/27 Run Staging inviroment, db staging - buang field FLAG_ROLE_ONLINE
--2017/05/19 Run POC inviroment, db ekptg(ekptgc) - buang field FLAG_ROLE_ONLINE
ALTER TABLE TBLMEMO
 ADD (
 	FLAG_ROLE_HQ  VARCHAR2(1 BYTE),
 	FLAG_ROLE_NEG  VARCHAR2(1 BYTE),
 	FLAG_ROLE_KJP  VARCHAR2(1 BYTE),
 	FLAG_ROLE_INTEG  VARCHAR2(1 BYTE),
 	FLAG_ROLE_ONLINE  VARCHAR2(1 BYTE)
 	);

 
 ALTER TABLE TBLRUJKEMENTERIAN
 ADD (FLAG_AKTIF  NUMBER);
 
 ALTER TABLE TBLRUJAGENSI
 ADD (FLAG_AKTIF  NUMBER);
 
 
 
--2017/04/21 Run Staging inviroment, db staging
CREATE TABLE TBLRUJGREDJAWATAN
(
  ID_GREDJAWATAN  NUMBER,
  ID_GRED         NUMBER,
  ID_JAWATAN      NUMBER,
  ID_MASUK   	  NUMBER,
  TARIKH_MASUK		DATE,
  ID_KEMASKINI  	NUMBER,
  TARIKH_KEMASKINI  DATE
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE SEQUENCE TBLRUJGREDJAWATAN_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
NOCACHE 
NOCYCLE 
ORDER ;

--2017/04/21 Run Staging inviroment, db staging
ALTER TABLE
   TBLRUJJAWATAN
ADD
   (
    KOD_SKIM  VARCHAR2(100)
   ,ID_KUMPULAN_PERKHIDMATAN  NUMBER
   ,KETERANGAN_TUGASAN  VARCHAR2(200)
   ,SUMBER_MAKLUMAT  VARCHAR2(200)
   ,ID_KLASIFIKASI  VARCHAR2(20)
   ,ID_KHIDMAT NUMBER
   );
			     

--28/4/2017   
ALTER TABLE TBLRUJGREDJAWATAN
 ADD (ID_MASUK  NUMBER);

ALTER TABLE TBLRUJGREDJAWATAN
 ADD (TARIKH_MASUK  DATE);
 
 ALTER TABLE INTEGRASI
ADD (NAMA_LAIN_PEMILIK VARCHAR2(30 BYTE));

ALTER TABLE INTEGRASI
ADD (KATEG_PEMILIK NUMBER);

ALTER TABLE INTEGRASI
 ADD (ID_PEG_1  NUMBER);

ALTER TABLE INTEGRASI
 ADD (ID_PEG_2  NUMBER);
 
 
 
  Insert into TBLINTRUJJENISPEJABAT
   (ID_JENISPEJABAT, ID_SIMPAN, ID_KEMASKINI, TARIKH_SIMPAN, TARIKH_KEMASKINI, 
    KOD_PEJABAT, NAMA_PEJABAT, FLAG_AKTIF)
 Values
   (16113, NULL, NULL, NULL, NULL, 
    '03', 'LHDN', 1);
    
-- ADD BY AIN ON 16052017
ALTER TABLE USERS_INTERNAL
 ADD (NO_TEL  VARCHAR2(12 BYTE));

ALTER TABLE USERS_INTERNAL
 ADD (NO_TEL_PEJABAT  VARCHAR2(12 BYTE));

ALTER TABLE USERS_INTERNAL
 ADD (NO_FAKS  VARCHAR2(12 BYTE)); 
 
 
 -- ADD TABLE INTEGRASI
 CREATE TABLE TBLRUJINTEGRASI
(
  ID_INTEGRASI      NUMBER,
  ID_JENISINTEG     NUMBER,
  ID_KATEGORI       NUMBER,
  NAMA              VARCHAR2(100 BYTE),
  NAMA_LAIN         VARCHAR2(100 BYTE),
  PENERANGAN        VARCHAR2(500 BYTE),
  STATUS            NUMBER,
  NAMA_PEMILIK      VARCHAR2(30 BYTE),
  ALAMAT1           VARCHAR2(100 BYTE),
  ALAMAT2           VARCHAR2(100 BYTE),
  ALAMAT3           VARCHAR2(100 BYTE),
  POSKOD            NUMBER,
  ID_NEGERI         NUMBER,
  NO_TEL            VARCHAR2(50 BYTE),
  EMEL              VARCHAR2(50 BYTE),
  CATATAN           VARCHAR2(500 BYTE),
  FLAG_AKTIF        NUMBER,
  TARIKH_MASUK      DATE,
  ID_MASUK          NUMBER,
  TARIKH_KEMASKINI  DATE,
  ID_KEMASKINI      NUMBER,
  KOD_AGENSI 	VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE TBLRUJINTEGRASI_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
NOCACHE 
NOCYCLE 
ORDER ;


 ALTER TABLE TBLRUJINTEGRASI
ADD (NAMA_LAIN_PEMILIK VARCHAR2(30 BYTE));

ALTER TABLE TBLRUJINTEGRASI
ADD (KATEG_PEMILIK NUMBER);

ALTER TABLE TBLRUJINTEGRASI
 ADD (ID_PEG_1  NUMBER);

ALTER TABLE TBLRUJINTEGRASI
 ADD (ID_PEG_2  NUMBER);
 
 ALTER TABLE TBLRUJINTEGRASI
ADD (NO_FAKS VARCHAR2(50 BYTE));


--5/7/17
--insert role baru untuk integrasi eHutang
INSERT INTO ROLE (NAME, DESCRIPTION, ROLE_DETAILS, THEME)  
VALUES ('(INTEGRASI)UsersAgensi', 'PENGGUNA INTEGRASI BAGI AGENSI', 'AGENSI YANG TERLIBAT DENGAN E-HUTANG', 'Integrasi.css') ;


--20/7
INSERT INTO TBLRUJJENISPEJABAT (ID_JENISPEJABAT ,KOD_JENIS_PEJABAT , KETERANGAN, NAMA_LAIN_JENIS_PEJABAT ,PENERANGAN_LANJUT ) 
 VALUES ('1617162','91','institusi kewangan kerajaan','ikk','untuk e-Hutang');
 
 
 --31/7
 
ALTER TABLE PERMOHONANIDPENGGUNA
 ADD (NO_OFFICE  VARCHAR2(30 BYTE));
 
 
 
 --15/8 untuk mobile app
  ALTER TABLE
   USERS
ADD
   (
   mobileapp_token VARCHAR2(4000)
   );
   
 
   
  ---15/8 (deeba)  
 
 
 ALTER TABLE PERMOHONANIDPENGGUNA
ADD (ID_GRED VARCHAR2(30 BYTE));

 ALTER TABLE TBLRUJPEJABAT
ADD (FLAG_INT VARCHAR2(1 BYTE));

 ALTER TABLE TBLRUJPEJABATJKPTG
ADD (FLAG_INT VARCHAR2(1 BYTE));


 UPDATE USERS_INTEGRASI SET ID_JENISPEJABAT = 3 WHERE ID_JENISPEJABAT = 16111;
 
 
 --untuk integrasi dalaman
 
 INSERT INTO ROLE (NAME, DESCRIPTION, ROLE_DETAILS, THEME)  
 VALUES ('(INTEGRASI)UsersMACGDI', 'PENGGUNA INTEGRASI BAGI MACGDI', '', 'Integrasi.css') ;
 
  INSERT INTO ROLE (NAME, DESCRIPTION, ROLE_DETAILS, THEME)  
 VALUES ('(INTEGRASI)UsersPNMB', 'PENGGUNA INTEGRASI BAGI PNMB', '', 'Integrasi.css') ;
 
 --ADD PEJABAT FOR INTEGRASI
 
INSERT INTO TBLRUJPEJABAT (ID_DAERAH, ID_SEKSYEN, ID_NEGERI, ID_BANDAR, NAMA_PEJABAT, ALAMAT1, ALAMAT2, ALAMAT3, FLAG_AKTIF, NO_FAX, NO_TEL, POSKOD, FLAG_INT,  ID_JENISPEJABAT)  
VALUES ('121', '11', '14', '422', 'PENCETAKAN NASIONAL MALAYSIA BERHAD', 'JALAN CHAN SOW LIN', '', '', '1', '', '0392366888', '50554', '1', '7') ;


 ALTER TABLE TBLRUJINTEGRASI
ADD (ID_JENISPEJABAT VARCHAR2(30 BYTE));


INSERT INTO TBLRUJINTEGRASI (NAMA, NAMA_LAIN, ALAMAT1, ALAMAT2, ALAMAT3, POSKOD, ID_NEGERI, FLAG_AKTIF, ID_JENISINTEG, ID_KATEGORI, ID_JENISPEJABAT, NO_TEL, NO_FAKS, ID_MASUK, TARIKH_MASUK) 
VALUES ('PENCETAKAN NASIONAL MALAYSIA BERHAD', 'PNMB', 'JALAN CHAN SOW LIN', '', '', '50554', '14', '1', '1', '1', '7', '0392366888', '', '161723928',  SYSDATE ) ;

INSERT INTO TBLRUJJENISPEJABAT (KOD_JENIS_PEJABAT, KETERANGAN, NAMA_LAIN_JENIS_PEJABAT, PENERANGAN_LANJUT, ID_JENISPEJABAT) 
VALUES ('92', 'MACGDI', 'GEOSPATIAL', '', '1617203') ;


INSERT INTO TBLRUJPEJABAT (ID_DAERAH, ID_SEKSYEN, ID_NEGERI, ID_BANDAR, NAMA_PEJABAT, ALAMAT1, ALAMAT2, ALAMAT3, FLAG_AKTIF, NO_FAX, NO_TEL, POSKOD, FLAG_INT, ID_JENISPEJABAT)  
VALUES ('123', '161325', '16', '424', 'PUSAT INFRASTRUKTUR DATA GEOSPATIAL NEGARA', 'LEVEL 7 & 8, WISMA SUMBER ASLI', 'NO. 25, PERSIARAN PERDANA', 'PRESINT 4', '1', '', '0380008000', '62574', '1',  '1617203'); 


INSERT INTO TBLRUJINTEGRASI (NAMA, NAMA_LAIN, ALAMAT1, ALAMAT2, ALAMAT3, POSKOD, ID_NEGERI, FLAG_AKTIF, ID_JENISINTEG, ID_KATEGORI, ID_JENISPEJABAT, NO_TEL, NO_FAKS, ID_MASUK, TARIKH_MASUK)  
VALUES ('PUSAT INFRASTRUKTUR DATA GEOSPATIAL NEGARA', '', 'LEVEL 7 & 8, WISMA SUMBER ASLI', 'NO. 25, PERSIARAN PERDANA', 'PRESINT 4', '62574', '16', '1', '1', '1', '1617203', '0380008000', '', '161723928',  SYSDATE ) ;

--LHDN
INSERT INTO TBLRUJJENISPEJABAT (KOD_JENIS_PEJABAT, KETERANGAN, NAMA_LAIN_JENIS_PEJABAT, PENERANGAN_LANJUT, ID_JENISPEJABAT) 
VALUES ('93', 'LEMBAGA HASIL DALAM NEGERI', 'LHDN', '', '1617204') ;

INSERT INTO TBLRUJPEJABAT (ID_DAERAH, ID_SEKSYEN, ID_NEGERI, ID_BANDAR, NAMA_PEJABAT, ALAMAT1, ALAMAT2, ALAMAT3, FLAG_AKTIF, NO_FAX, NO_TEL, POSKOD, FLAG_INT, ID_PEJABAT, ID_JENISPEJABAT) 
VALUES ('81', '2', '10', '295', 'LEMBAGA HASIL DALAM NEGERI', 'MENARA HASIL,', 'PERSIARAN RIMBA PERMAI', 'CYBER 8', '1', '', '0383138888', '63000', '1', '1617783', '1617204') ;

INSERT INTO TBLRUJINTEGRASI (NAMA, NAMA_LAIN, ALAMAT1, ALAMAT2, ALAMAT3, POSKOD, ID_NEGERI, FLAG_AKTIF, ID_JENISINTEG, ID_KATEGORI, ID_JENISPEJABAT, NO_TEL, NO_FAKS, ID_INTEGRASI, ID_MASUK, TARIKH_MASUK) 
VALUES ('LEMBAGA HASIL DALAM NEGERI', 'LHDN', 'MENARA HASIL,', 'PERSIARAN RIMBA PERMAI', 'CYBER 8', '63000', '10', '1', '1', '1', '1617204', '0383138888', '', '161732', '161723928',  SYSDATE ) ;


--17/8

 ALTER TABLE PERMOHONANIDPENGGUNA
ADD (ID_KHIDMAT VARCHAR2(30 BYTE));

 ALTER TABLE PERMOHONANIDPENGGUNA
ADD (ID_KLASIFIKASI VARCHAR2(30 BYTE));


--21/8
INSERT INTO TBLRUJJENISPEJABAT (KOD_JENIS_PEJABAT, KETERANGAN, NAMA_LAIN_JENIS_PEJABAT, PENERANGAN_LANJUT, ID_JENISPEJABAT) 
VALUES ('93', 'KETUA PENGARAH INSOLVENSI', '', '', '141782') ;

---TBLRUJ SUB BAHAGIAN
CREATE TABLE TBLRUJSUBBAHAGIAN
(
  ID_SUBBAHAGIAN    NUMBER,
  ID_BAHAGIAN       NUMBER,
  NAMA_SUB_BAHAGIAN VARCHAR2(100 BYTE),
  NAMA_LAIN_SUB
         VARCHAR2(100 BYTE),
  ALAMAT_1
        VARCHAR2(500 BYTE),
  ALAMAT_2
      VARCHAR2(500 BYTE),
  ALAMAT_3
           VARCHAR2(500 BYTE),
  POSKOD            NUMBER,
  ID_NEGERI         NUMBER,
  NO_TEL            VARCHAR2(50 BYTE),
   NO_FAKS
            VARCHAR2(50 BYTE),
   EMEL VARCHAR2(50 BYTE)

)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE TBLRUJSUBBAHAGIAN_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
NOCACHE 
NOCYCLE 
ORDER ;

CREATE OR REPLACE TRIGGER TBLRUJSUBBAHAGIAN_BI    
before insert on     TBLRUJSUBBAHAGIAN    for each row
begin    if :new.ID_SUBBAHAGIAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJSUBBAHAGIAN_SEQ.NEXTVAL into :new.ID_SUBBAHAGIAN            from dual;    end if;    end;


DROP TABLE TBLRUJSUBBAHAGIAN CASCADE CONSTRAINTS;

--ADD COLUMN 14/9

ALTER TABLE TBLRUJSEKSYEN
ADD (
ALAMAT_1
        VARCHAR2(500 BYTE),
  ALAMAT_2
      VARCHAR2(500 BYTE),
  ALAMAT_3
           VARCHAR2(500 BYTE),
  POSKOD            NUMBER,
  ID_NEGERI         NUMBER,
  NO_TEL            VARCHAR2(50 BYTE),
   NO_FAKS
            VARCHAR2(50 BYTE),
   EMEL VARCHAR2(50 BYTE));

   
CREATE TABLE TBLRUJSUBUNIT
(
  ID_SUBUNIT    NUMBER,
  ID_BAHAGIAN       NUMBER,
  NAMA_SUBUNIT VARCHAR2(100 BYTE)

)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE TBLRUJSUBUNIT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
NOCACHE 
NOCYCLE 
ORDER ;

CREATE OR REPLACE TRIGGER "EKPTGHQ".TBLRUJSUBUNIT_BI    before insert on     TBLRUJSUBUNIT    for each row
begin    if :new.ID_SUBUNIT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJSUBUNIT_SEQ.NEXTVAL into :new.ID_SUBUNIT            from dual;    end if;    end;
/









--RAZMAN ADD 2 FIELD PASSWORD GEN
ALTER TABLE
   USERS
ADD
   (
   USER_PASSWORD_GEN_2  VARCHAR(100),
   USER_PASSWORD_GEN_3  VARCHAR(100)
   );


--EDIT TABLE 3/10
ALTER TABLE PERMOHONANIDPENGGUNA
ADD  (CATATAN_PEMOHON VARCHAR2(100)
);


---6/10 TBLRUJMODUL BARU
CREATE TABLE TBLRUJMODUL
(
  ID_MODUL          VARCHAR2(100),
  KOD_MODUL         VARCHAR2(100),
  NAMA_MODUL        VARCHAR2(100),
  ID_MASUK          VARCHAR2(100),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      VARCHAR2(100),
  TARIKH_KEMASKINI  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE TBLRUJMODUL_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--TRIGGER BARU
CREATE OR REPLACE TRIGGER TBLRUJMODUL_BI    
before insert on     TBLRUJMODUL    for each row
begin    if :new.ID_MODUL    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJMODUL_SEQ.NEXTVAL into :new.ID_MODUL   from dual; end if;    end;
/


CREATE TABLE TBLRUJDOKUMENADMIN
(
  ID_DOKUMENADMIN   VARCHAR2(100 BYTE)          NOT NULL,
  ID_REF            VARCHAR2(100 BYTE),
  FLAG_ADMIN        VARCHAR2(30 BYTE),
  ID_MASUK          VARCHAR2(100 BYTE),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      VARCHAR2(100 BYTE),
  TARIKH_KEMASKINI  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE TBLRUJDOKUMENADMIN ADD (
  CONSTRAINT TBLRUJDOKUMENADMIN_PK
 PRIMARY KEY
 (ID_DOKUMENADMIN));
 
 
 CREATE SEQUENCE TBLRUJDOKUMENADMIN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
  
  CREATE OR REPLACE TRIGGER TBLRUJDOKUMENADMIN_BI    
before insert on     TBLRUJDOKUMENADMIN    for each row
begin    if :new.ID_DOKUMENADMIN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJDOKUMENADMIN_SEQ.NEXTVAL into :new.ID_DOKUMENADMIN   from dual; end if;    end;
/



---3/11 TBLRUJMODULBAHAGIAN BARU
CREATE TABLE TBLRUJMODULBAHAGIAN
(
  ID_MODULBAHAGIAN          VARCHAR2(100),
  ID_MODUL         VARCHAR2(100),
  ID_BAHAGIAN        VARCHAR2(100),
  ID_MASUK          VARCHAR2(100),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      VARCHAR2(100),
  TARIKH_KEMASKINI  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;

CREATE SEQUENCE TBLRUJMODULBAHAGIAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--TRIGGER BARU TBLRUJMODULBAHAGIAN
CREATE OR REPLACE TRIGGER TBLRUJMODULBAHAGIAN_BI    
before insert on     TBLRUJMODULBAHAGIAN    for each row
begin    if :new.ID_MODULBAHAGIAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJMODULBAHAGIAN_SEQ.NEXTVAL into :new.ID_MODULBAHAGIAN   from dual; end if;    end;
/

//06112017
ALTER TABLE
   PAGE_CSS
ADD
(
    MODUL_ID  VARCHAR(100)
);

--aishah tambah coloum email untuk pejabat jkptg
ALTER TABLE TBLRUJPEJABATJKPTG
ADD (EMEL VARCHAR2(50 BYTE));

COMMENT ON COLUMN 
TBLRUJPEJABATJKPTG.EMEL IS 
'alamat email jkptg';


--tmbh column emel untuk pjbt urusan
ALTER TABLE TBLRUJPEJABAT
ADD (EMEL VARCHAR2(30 BYTE));


ALTER TABLE TBLRUJDOKUMENADMIN
ADD (
KETERANGAN VARCHAR2(100 BYTE), 
NAMA_DOKUMEN VARCHAR2(50 BYTE), 
 JENIS_DOKUMEN VARCHAR2(50 BYTE), 
 DOKUMEN BLOB
);

-------insert mof
INSERT INTO TBLRUJINTEGRASI (NAMA, NAMA_LAIN, ALAMAT1, ALAMAT2, ALAMAT3, POSKOD, ID_NEGERI, FLAG_AKTIF, ID_JENISINTEG, 
ID_KATEGORI, ID_JENISPEJABAT, NO_TEL, NO_FAKS, ID_INTEGRASI, ID_MASUK, TARIKH_MASUK)  
VALUES ('FLI', '', 'KEMENTERIAN KEWANGAN MALAYSIA', 'ARAS 6, PERBENDAHARAAN 2, NO 7, PERSIARAAN PERDANA', 'PRESINT 2', 
'62592', '16', 'Y', '1', '1', '1618222', '0345678901', '', '161834', '161723928',  SYSDATE ) ;


ALTER TABLE 
    USERS_INTERNAL 
ADD 
    (
   FLAG_JAWATAN  VARCHAR(1), 
   TARIKH_MULA_TEMPOH DATE,
   TARIKH_TAMAT_TEMPOH DATE
    );
