
-- 2020/07/14 EKPTGHUAT
--2020/05/30
--SELECT * FROM TBLRUJJENISDOKUMEN

CREATE OR REPLACE TRIGGER TBLSEMAKANJENISDOKUMEN_BI    
before insert on     TBLSEMAKANJENISDOKUMEN    for each row
begin    if :new.ID_SEMAKANJENISDOKUMEN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLSEMAKANJENISDOKUMEN_SEQ.NEXTVAL into :new.ID_SEMAKANJENISDOKUMEN        from dual;    end if;    end;

CREATE SEQUENCE TBLSEMAKANJENISDOKUMEN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
 
ALTER TABLE TBLSEMAKANJENISDOKUMEN ADD (
  CONSTRAINT TBLSEMAKANJENISDOKUMEN_PK
 PRIMARY KEY
 (ID_SEMAKANJENISDOKUMEN));

CREATE TABLE TBLSEMAKANJENISDOKUMEN 
   (	"ID_SEMAKANJENISDOKUMEN" NUMBER CONSTRAINT "TBLSEMAKANJENISDOKUMEN_C01" NOT NULL ENABLE, 
	"ID_SEMAKAN" NUMBER CONSTRAINT "TBLSEMAKANJENISDOKUMEN_C02" NOT NULL ENABLE, 
	"ID_JENISDOKUMEN" NUMBER CONSTRAINT "TBLSEMAKANJENISDOKUMEN_C03" NOT NULL ENABLE, 
	"ID_MASUK" NUMBER, 
	"TARIKH_MASUK" DATE, 
	"ID_KEMASKINI" NUMBER, 
	"TARIKH_KEMASKINI" DATE
)
TABLESPACE RUJ01
--TABLESPACE RUJ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;	
 
  
--2020/05/21
INSERT INTO TBLRUJJENISTANAH
(ID_JENISTANAH, KOD_JENIS_TANAH, KETERANGAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(7, 'HP', 'HAKMILIK PETAK', NULL, NULL, NULL, NULL);


06022020--------------------------------------------------------------------------------

DROP TRIGGER RUJENISDOKUMEN_BI;

CREATE OR REPLACE TRIGGER RUJENISDOKUMEN_BI    
before insert on     TBLRUJJENISDOKUMEN    for each row
begin    if :new.ID_JENISDOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || RUJENISDOKUMEN_SEQ.NEXTVAL into :new.ID_JENISDOKUMEN          from dual;    end if;    end;
/

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--06/02/2020, semasa (2) 
DROP SEQUENCE RUJENISDOKUMEN_SEQ;


CREATE SEQUENCE RUJENISDOKUMEN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
 INSERT INTO TBLRUJJENISDOKUMEN
(ID_JENISDOKUMEN, KOD_JENIS_DOKUMEN, KETERANGAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, ID_LAPORAN)
VALUES(99202, 'img', 'GAMBAR', NULL, NULL, NULL, NULL, 0, NULL);

INSERT INTO TBLRUJJENISDOKUMEN
(ID_JENISDOKUMEN, KOD_JENIS_DOKUMEN, KETERANGAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, ID_LAPORAN)
VALUES(99201, 'pdf', 'DOKUMEN PDF', NULL, NULL, NULL, NULL, 0, NULL);

