06022020--------------------------------------------------------------------------------

DROP TRIGGER RUJENISDOKUMEN_BI;

CREATE OR REPLACE TRIGGER RUJENISDOKUMEN_BI    
before insert on     TBLRUJJENISDOKUMEN    for each row
begin    if :new.ID_JENISDOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || RUJENISDOKUMEN_SEQ.NEXTVAL into :new.ID_JENISDOKUMEN          from dual;    end if;    end;
/

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--06/02/2020, semasa (2) 
DROP SEQUENCE RUJENISDOKUMEN_SEQ;


CREATE SEQUENCE RUJENISDOKUMEN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
 INSERT INTO TBLRUJJENISDOKUMEN
(ID_JENISDOKUMEN, KOD_JENIS_DOKUMEN, KETERANGAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, ID_LAPORAN)
VALUES(99202, 'img', 'GAMBAR', NULL, NULL, NULL, NULL, 0, NULL);

INSERT INTO TBLRUJJENISDOKUMEN
(ID_JENISDOKUMEN, KOD_JENIS_DOKUMEN, KETERANGAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, ID_LAPORAN)
VALUES(99201, 'pdf', 'DOKUMEN PDF', NULL, NULL, NULL, NULL, 0, NULL);
