ALTER TABLE EKPTGWP.TBLPPKHUTANG
 DROP PRIMARY KEY CASCADE;
DROP TABLE EKPTGWP.TBLPPKHUTANG CASCADE CONSTRAINTS;

CREATE TABLE EKPTGWP.TBLPPKHUTANG
(
  ID_HUTANG           NUMBER CONSTRAINT TBLPPKHUTANG_C01 NOT NULL,
  NAMA                VARCHAR2(200 BYTE) CONSTRAINT TBLPPKHUTANG_C02 NOT NULL,
  NO_PENGENALAN_BARU  VARCHAR2(12 BYTE),
  ALAMAT_1            VARCHAR2(200 BYTE),
  ALAMAT_2            VARCHAR2(200 BYTE),
  ALAMAT_3            VARCHAR2(200 BYTE),
  POSKOD              VARCHAR2(5 BYTE),
  ID_BANDAR           NUMBER,
  ID_NEGERI           NUMBER,
  NO_TELEFON          VARCHAR2(12 BYTE),
  EMEL                VARCHAR2(200 BYTE),
  CATATAN             VARCHAR2(500 BYTE),
  ID_MASUK            NUMBER,
  TARIKH_MASUK        DATE,
  ID_KEMASKINI        NUMBER,
  TARIKH_KEMASKINI    DATE,
  ID_PEJABAT          NUMBER
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          169M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGWP.TBLPPKHUTANG_PK ON EKPTGWP.TBLPPKHUTANG
(ID_HUTANG)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER EKPTGWP.TBLPPKHUTANG_BI    
before insert on     TBLPPKHUTANG    for each row
begin    if :new.ID_HUTANG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKHUTANG_SEQ.NEXTVAL into :new.ID_HUTANG            from dual;    end if;    end;
/


ALTER TABLE EKPTGWP.TBLPPKHUTANG ADD (
  CONSTRAINT TBLPPKHUTANG_PK
 PRIMARY KEY
 (ID_HUTANG)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          16M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EKPTGWP.TBLPPKHUTANG TO EKPTGSYNC;






ALTER TABLE TBLPPKHUTANG
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPPKHUTANG CASCADE CONSTRAINTS;

CREATE TABLE TBLPPKHUTANG
(
  ID_HUTANG           NUMBER CONSTRAINT TBLPPKHUTANG_C01 NOT NULL,
  NAMA                VARCHAR2(200 BYTE) CONSTRAINT TBLPPKHUTANG_C02 NOT NULL,
  NO_PENGENALAN_BARU  VARCHAR2(12 BYTE),
  ALAMAT_1            VARCHAR2(200 BYTE),
  ALAMAT_2            VARCHAR2(200 BYTE),
  ALAMAT_3            VARCHAR2(200 BYTE),
  POSKOD              VARCHAR2(5 BYTE),
  ID_BANDAR           NUMBER,
  ID_NEGERI           NUMBER,
  NO_TELEFON          VARCHAR2(12 BYTE),
  EMEL                VARCHAR2(200 BYTE),
  CATATAN             VARCHAR2(500 BYTE),
  ID_MASUK            NUMBER,
  TARIKH_MASUK        DATE,
  ID_KEMASKINI        NUMBER,
  TARIKH_KEMASKINI    DATE
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          169M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLPPKHUTANG_PK ON TBLPPKHUTANG
(ID_HUTANG)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TBLPPKHUTANG_BI    
before insert on     TBLPPKHUTANG    for each row
begin    if :new.ID_HUTANG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKHUTANG_SEQ.NEXTVAL into :new.ID_HUTANG            from dual;    end if;    end;
/


ALTER TABLE TBLPPKHUTANG ADD (
  CONSTRAINT TBLPPKHUTANG_PK
 PRIMARY KEY
 (ID_HUTANG)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          16M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKHUTANG TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKHUTANG TO PPTMHQ;

ALTER TABLE TBLPPKSENARAIHUTANG
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPPKSENARAIHUTANG CASCADE CONSTRAINTS;

CREATE TABLE TBLPPKSENARAIHUTANG
(
  ID_SENARAIHUTANG       NUMBER CONSTRAINT TBLPPKSENARAIHUTANG_C01 NOT NULL,
  ID_HUTANG              NUMBER                 NOT NULL,
  NAMA                   VARCHAR2(200 BYTE),
  NO_PENGENALAN          VARCHAR2(12 BYTE),
  ALAMAT_1               VARCHAR2(100 BYTE),
  ALAMAT_2               VARCHAR2(100 BYTE),
  ALAMAT_3               VARCHAR2(100 BYTE),
  POSKOD                 VARCHAR2(5 BYTE),
  ID_BANDAR              NUMBER,
  ID_NEGERI              NUMBER,
  NO_TELEFON             VARCHAR2(12 BYTE),
  EMEL                   VARCHAR2(200 BYTE),
  JENIS_HUTANG           VARCHAR2(100 BYTE),
  NO_AKAUN               VARCHAR2(50 BYTE),
  BUTIRAN_HUTANG         VARCHAR2(500 BYTE),
  NILAI_HUTANG           NUMBER(11,2),
  BAKI_HUTANG            NUMBER(11,2),
  STATUS_HUTANG          VARCHAR2(2 BYTE),
  TARIKH_SELESAI_HUTANG  DATE,
  CATATAN                VARCHAR2(500 BYTE),
  ID_MASUK               NUMBER,
  TARIKH_MASUK           DATE,
  ID_KEMASKINI           NUMBER,
  TARIKH_KEMASKINI       DATE
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TBLPPKSENARAIHUTANG.STATUS_HUTANG IS 'Y=SELESAI; T=BELUM SELESAI';


CREATE UNIQUE INDEX TBLPPKSENARAIHUTANG_PK ON TBLPPKSENARAIHUTANG
(ID_SENARAIHUTANG)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TBLPPKSENARAIHUTANG_BI    
before insert on     TBLPPKSENARAIHUTANG    for each row
begin    if :new.ID_SENARAIHUTANG     is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKSENARAIHUTANG_SEQ.NEXTVAL into :new.ID_SENARAIHUTANG           from dual;    end if;    end;
/


ALTER TABLE TBLPPKSENARAIHUTANG ADD (
  CONSTRAINT TBLPPKSENARAIHUTANG_PK
 PRIMARY KEY
 (ID_SENARAIHUTANG)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKSENARAIHUTANG TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKSENARAIHUTANG TO PPTMHQ;


ALTER TABLE TBLPPKDOKUMENSENARAIHUTANG
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPPKDOKUMENSENARAIHUTANG CASCADE CONSTRAINTS;

CREATE TABLE TBLPPKDOKUMENSENARAIHUTANG
(
  ID_DOKUMEN        NUMBER                      NOT NULL,
  ID_SENARAIHUTANG  NUMBER,
  NAMA_DOKUMEN      VARCHAR2(200 BYTE),
  CATATAN           VARCHAR2(500 BYTE),
  NAMA_FAIL         VARCHAR2(200 BYTE),
  CONTENT           BLOB,
  JENIS_MIME        VARCHAR2(100 BYTE),
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  PPK01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE PPK01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLPPKDOKUMENSENARAIHUTANG_PK ON TBLPPKDOKUMENSENARAIHUTANG
(ID_DOKUMEN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TBLPPKDOKUMENSENARAIHUTANG_BI    
before insert on     TBLPPKDOKUMENSENARAIHUTANG    for each row
begin    if :new.ID_DOKUMEN     is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKDOKUMENSENARAIHUTANG_SEQ.NEXTVAL into :new.ID_DOKUMEN           from dual;    end if;    end;
/


ALTER TABLE TBLPPKDOKUMENSENARAIHUTANG ADD (
  CONSTRAINT TBLPPKDOKUMENSENARAIHUTANG_PK
 PRIMARY KEY
 (ID_DOKUMEN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKDOKUMENSENARAIHUTANG TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPPKDOKUMENSENARAIHUTANG TO PPTMHQ;


DROP SEQUENCE TBLPPKHUTANG_SEQ;

CREATE SEQUENCE TBLPPKHUTANG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
DROP SEQUENCE TBLPPKSENARAIHUTANG_SEQ;

CREATE SEQUENCE TBLPPKSENARAIHUTANG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
DROP SEQUENCE TBLPPKDOKUMENSENARAIHUTANG_SEQ;

CREATE SEQUENCE TBLPPKDOKUMENSENARAIHUTANG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP SEQUENCE TBLRUJJANTINA_SEQ;

CREATE SEQUENCE TBLRUJJANTINA_SEQ
  START WITH 4
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
  ALTER TABLE TBLRUJJANTINA
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLRUJJANTINA CASCADE CONSTRAINTS;

CREATE TABLE TBLRUJJANTINA
(
  ID_JANTINA          NUMBER CONSTRAINT TBLRUJJANTINA_C01 NOT NULL,
  KOD_JANTINA         VARCHAR2(3 BYTE),
  KETERANGAN        VARCHAR2(15 BYTE),
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE
)
TABLESPACE RUJ01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLRUJJANTINA_PK ON TBLRUJJANTINA
(ID_JANTINA)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TBLRUJJANTINA_BI    
before insert on     TBLRUJJANTINA    for each row
begin    if :new.ID_JANTINA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJJANTINA_SEQ.NEXTVAL into :new.ID_JANTINA            from dual;    end if;    end;
/


ALTER TABLE TBLRUJJANTINA ADD (
  CONSTRAINT TBLRUJJANTINA_PK
 PRIMARY KEY
 (ID_JANTINA)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLRUJJANTINA TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLRUJJANTINA TO PPTMHQ;


Insert into TBLRUJJANTINA
   (ID_JANTINA, KOD_JANTINA, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (1, '01', 'LELAKI', NULL, NULL, 
    NULL, NULL);
Insert into TBLRUJJANTINA
   (ID_JANTINA, KOD_JANTINA, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (2, '02', 'PEREMPUAN', NULL, NULL, 
    NULL, NULL);
Insert into TBLRUJJANTINA
   (ID_JANTINA, KOD_JANTINA, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (0, '99', 'TIADA MAKLUMAT', NULL, NULL, 
    NULL, NULL);
COMMIT;
