
CREATE SEQUENCE EP_PENAMBAHBAIKAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE EP_PENAMBAHBAIKAN
( 
  ID_PENAMBAHBAIKAN NUMBER(20) NOT NULL,
  ID_SUBMODUL NUMBER(20) NOT NULL,
  ID_PIC NUMBER(20) NOT NULL,
  PENAMBAHBAIKAN VARCHAR2(4000) NOT NULL,
  CATATAN VARCHAR2(4000),
  FLAG_TAHAP_KESUKARAN NUMBER(1)  DEFAULT 0,
  FS_LOCAL NUMBER(1)  DEFAULT 0,
  FS_STG NUMBER(1) DEFAULT 0,
  FS_DEV NUMBER(1) DEFAULT 0,
  F_KIV NUMBER(1) DEFAULT 0,
  TARIKH_MULA      DATE,
  TARIKH_TARGET_SIAP     DATE,
  TARIKH_ACTUAL_SIAP     DATE,
  TURUTAN          NUMBER DEFAULT 1,
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE DEFAULT SYSDATE,
  CONSTRAINT EP_PENAMBAHBAIKAN PRIMARY KEY (ID_PENAMBAHBAIKAN)
);

CREATE OR REPLACE TRIGGER EP_PENAMBAHBAIKAN_BI    
before insert on     EP_PENAMBAHBAIKAN    for each row
begin    if :new.ID_PENAMBAHBAIKAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || EP_PENAMBAHBAIKAN_SEQ.NEXTVAL into :new.ID_PENAMBAHBAIKAN   from dual; end if;    end;
/


CREATE SEQUENCE EP_MAINMODUL_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE EP_MAINMODUL
( 
  ID_MAINMODUL NUMBER(20) NOT NULL,
  MAINMODUL VARCHAR2(4000) NOT NULL,
  ID_PROJEK NUMBER(20) NOT NULL,
  ID_MASUK          NUMBER,
  TURUTAN          NUMBER NOT NULL DEFAULT 1,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE DEFAULT SYSDATE,
  CONSTRAINT EP_MAINMODUL PRIMARY KEY (ID_MAINMODUL)
);

CREATE OR REPLACE TRIGGER EP_MAINMODUL_BI    
before insert on     EP_MAINMODUL    for each row
begin    if :new.ID_MAINMODUL    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || EP_MAINMODUL_SEQ.NEXTVAL into :new.ID_MAINMODUL   from dual; end if;    end;
/




CREATE SEQUENCE EP_SUBMODUL_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE EP_SUBMODUL
( 
  ID_SUBMODUL NUMBER(20) NOT NULL,
  ID_MAINMODUL NUMBER(20) NOT NULL,
  SUBMODUL VARCHAR2(4000) NOT NULL,
  TURUTAN          NUMBER NOT NULL DEFAULT 1,
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE DEFAULT SYSDATE,
  CONSTRAINT EP_SUBMODUL PRIMARY KEY (ID_SUBMODUL)
);

CREATE OR REPLACE TRIGGER EP_SUBMODUL_BI    
before insert on     EP_SUBMODUL    for each row
begin    if :new.ID_SUBMODUL    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || EP_SUBMODUL_SEQ.NEXTVAL into :new.ID_SUBMODUL   from dual; end if;    end;
/




CREATE SEQUENCE EP_PIC_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE EP_PIC
( 
  ID_PIC NUMBER(20) NOT NULL,
  PIC VARCHAR2(4000) NOT NULL,  
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE DEFAULT SYSDATE,
  CONSTRAINT EP_PIC PRIMARY KEY (ID_PIC)
);

CREATE OR REPLACE TRIGGER EP_PIC_BI    
before insert on     EP_PIC    for each row
begin    if :new.ID_PIC    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || EP_PIC_SEQ.NEXTVAL into :new.ID_PIC   from dual; end if;    end;
/



CREATE SEQUENCE EP_PROJEK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE EP_PROJEK
( 
  ID_PROJEK NUMBER(20) NOT NULL,
  PROJEK VARCHAR2(4000) NOT NULL,  
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE DEFAULT SYSDATE,
  CONSTRAINT EP_PROJEK PRIMARY KEY (ID_PROJEK)
);

CREATE OR REPLACE TRIGGER EP_PROJEK_BI    
before insert on     EP_PROJEK    for each row
begin    if :new.ID_PROJEK    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || EP_PROJEK_SEQ.NEXTVAL into :new.ID_PROJEK   from dual; end if;    end;
/
