
CREATE OR REPLACE FUNCTION GETUPI(KOD_NEGERI VARCHAR2,KOD_DAERAH VARCHAR2,KOD_MUKIM VARCHAR2,SEKSYEN VARCHAR2,STATUS VARCHAR2,NO_LOT VARCHAR2,NO_HAKMILIK VARCHAR2,JENIS VARCHAR2)
    RETURN VARCHAR2 AS LOT_UPI VARCHAR2(46):='';
    BEGIN
          LOT_UPI := KOD_NEGERI||KOD_DAERAH||KOD_MUKIM||SEKSYEN||
          --      ||
                CASE 
                   WHEN STATUS ='Y' OR NO_HAKMILIK IS NULL
                       THEN
                           GETLOTUPI(NO_LOT)
                   ELSE
                      JENIS||GETHAKMILIKUPI(NO_HAKMILIK) 
               END 
               ;                           
      RETURN LOT_UPI;
    END;
/

CREATE OR REPLACE FUNCTION GETLOTUPI(NO_LOT VARCHAR)
    RETURN VARCHAR2 AS
    LOT_UPI VARCHAR2(7):='';
        BEGIN
          LOT_UPI :=
                CASE WHEN NO_LOT LIKE '%BLK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'BLK'),10),'')),7,'0') 
                    WHEN NO_LOT LIKE '%SEK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'SEK'),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%SEC%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'SEC'),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%BLOCK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'BLOCK'),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%(%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'('),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%,%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,','),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%&%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'&'),10),'')),7,'0')
                    WHEN NO_LOT LIKE '%''%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,''''),10),'')),7,'0')
                    WHEN NO_LOT LIKE 'PTD%' THEN LPAD(REPLACE(NO_LOT,'PTD',''),7,'0')
                ELSE 
                    LPAD(TRIM(NO_LOT),7,'0') 
                END;
        RETURN LOT_UPI;
    END;
/


CREATE OR REPLACE FUNCTION GETHAKMILIKUPI(NO_LOT VARCHAR)
    RETURN VARCHAR2 AS
    LOT_UPI VARCHAR2(8):='';
        BEGIN
          LOT_UPI :=
                CASE WHEN NO_LOT LIKE '%BLK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'BLK'),10),'')),8,'0') 
                    WHEN NO_LOT LIKE '%SEK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'SEK'),10),'')),8,'0')
                    WHEN NO_LOT LIKE '%SEC%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'SEC'),10),'')),8,'0')
                    WHEN NO_LOT LIKE '%BLOCK%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'BLOCK'),10),'')),8,'0')
                    WHEN NO_LOT LIKE '%(%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'('),10),'')),8,'0')
                    WHEN NO_LOT LIKE '%,%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,','),10),'')),8,'0')
                    WHEN NO_LOT LIKE '%&%' THEN LPAD(TRIM(REPLACE(NO_LOT,SUBSTR(NO_LOT,INSTR(NO_LOT,'&'),10),'')),8,'0')
                    WHEN NO_LOT LIKE 'PTD%' THEN LPAD(REPLACE(NO_LOT,'PTD',''),8,'0')
                ELSE 
                    LPAD(TRIM(NO_LOT),8,'0') 
                END;
        RETURN LOT_UPI;
    END;
/


CREATE OR REPLACE FUNCTION GETGISTATUSREKOD(STATUS_JENISHAKMILIK VARCHAR,NO_WARTA VARCHAR)
    RETURN VARCHAR AS
    GISTATUS VARCHAR(2):='4';
        BEGIN
          GISTATUS :=
            CASE
                WHEN NO_WARTA IS NOT NULL THEN '6' 
                ELSE 
                    CASE 
                        WHEN STATUS_JENISHAKMILIK='Y'
                            THEN '5'
                        ELSE '4'
                    END   
            END;   
        RETURN GISTATUS;
    END;
/
