
====================================================================================================
===== 2017/05/09, Script add column bagi tujuan maklumat pajakan
ALTER TABLE TBLHTPPAJAKAN
 ADD (TARIKH_PATUT_BAYAR  DATE);

ALTER TABLE TBLHTPPAJAKAN
 ADD (CATATAN  VARCHAR2(1500));

ALTER TABLE TBLHTPPAJAKAN
 ADD (FLAG_AKTIF  VARCHAR2(2));
 
====================================================================================================
===== 2017/04/19, Script add column bagi tujuan fungsi pemantauan
ALTER TABLE EKPTGHQ.TBLRUJSUBURUSANSTATUSFAIL
 ADD (URL_CATATAN  VARCHAR2(1500));
 
====================================================================================================
===== 2017/04/18, Script Laporan Pemantauan
SELECT 
F.NO_FAIL,F.TAJUK_FAIL
--LP.*
--,TO_CHAR(P.TARIKH_TERIMA,'DD/MM/YYYY') TARIKH_TERIMA_PERMOHONAN
,TO_CHAR(PP.TARIKH_SURAT_RUJUKAN_LAIN,'DD/MM/YYYY') TARIKH_TERIMA_PERMOHONAN
,TO_CHAR(LP.TARIKH_JAWAB_PERMOHONAN,'DD/MM/YYYY') TARIKH_JAWAB_PERMOHONAN
,TO_CHAR(LP.KJPTARIKH_HANTAR,'DD/MM/YYYY') STATUS_KJP
,TO_CHAR(LP.JPPHTARIKH_HANTAR,'DD/MM/YYYY') ULASAN_JPPH
,TO_CHAR(LP.TARIKH_JKPTGN,'DD/MM/YYYY') TARIKH_HANTAR_JKPTGN
,TO_CHAR(LP.TARIKH_HANTAR_KSU,'DD/MM/YYYY') TARIKH_HANTAR_NRE
,TO_CHAR(LP.TARIKH_TERIMA_KSU,'DD/MM/YYYY') TARIKH_TERIMA_NRE
,TO_CHAR(LP.TARIKH_KEPUTUSAN,'DD/MM/YYYY') TARIKH_KEPUTUSAN_MJM
,TO_CHAR(LP.TARIKH_HANTAR_PEMOHON,'DD/MM/YYYY') TARIKH_HANTAR_PEMOHON
,TO_CHAR(LP.PERTARIKH_HANTAR_PEMOHON,'DD/MM/YYYY') PERTARIKH_HANTAR_PEMOHON
,TO_CHAR(LP.PERTARIKH_HANTAR_PKP,'DD/MM/YYYY') PERTARIKH_HANTAR_PKP
,TO_CHAR(LP.TARIKH_TANDATANGAN,'DD/MM/YYYY') PERTARIKH_TANDATANGAN
,LP.TEMPOH_PAJAKAN
,LTRIM(TO_CHAR(NVL(LP.KADAR_PAJAKAN,0),'99,999,990.00')) KADAR_PAJAKAN
,TO_CHAR(LP.BORTARIKH_TANDATANGAN_PTP,'DD/MM/YYYY') TARIKH_TANDATANGAN15A
,TO_CHAR(LP.BORTARIKH_DAFTAR,'DD/MM/YYYY') TARIKH_DAFTAR
,TO_CHAR(LP.BORTARIKH_TERIMAHAKMILIK,'DD/MM/YYYY') TARIKH_TERIMA_HAKMILIK
--,TO_CHAR(LP.TARIKH_TANDATANGAN,'DD/MM/YYYY') PERTARIKH_TANDATANGAN
,RS.KETERANGAN STATUS_SEMASA
,MT.NO_HAKMILIK, MT.NO_WARTA, MT.NO_LOT,MT.LUAS_LOT,MT.LUAS_ASAL, MT.NAMA_NEGERI, MT.NAMA_DAERAH, MT.NAMA_MUKIM 
--,(select sum(jumlah_bayaran) from tblhtpbayaran where id_permohonan=P.ID_PERMOHONAN ) Bayaran
FROM TBLPFDFAIL F
,TBLPERMOHONAN P
,TBLHTPPERMOHONAN PP
,TBLHTPLPRPAJAKANAKT LP
,(                
    SELECT HTPU.ID_PERMOHONAN,N.ID_NEGERI, D.ID_DAERAH, M.ID_MUKIM, N.NAMA_NEGERI, D.NAMA_DAERAH, M.NAMA_MUKIM
        ,RTRIM(XMLAGG(XMLELEMENT(E,HTPU.NO_WARTA || ',')).EXTRACT('//text()'),',') NO_WARTA
        ,RTRIM(XMLAGG(XMLELEMENT(E,RH.KOD_JENIS_HAKMILIK||HTPU.NO_HAKMILIK || ',')).EXTRACT('//text()'),',') NO_HAKMILIK
        ,RTRIM(XMLAGG(XMLELEMENT(E,RL.KETERANGAN||HTPU.NO_LOT || ',')).EXTRACT('//text()'),',') NO_LOT
,RTRIM(XMLAGG(XMLELEMENT(E,HTPU.LUAS_BERSAMAAN  || ',')).EXTRACT('//text()'),',') LUAS_LOT
        ,RTRIM(XMLAGG(XMLELEMENT(E,H.LUAS_BERSAMAAN  || ',')).EXTRACT('//text()'),',') LUAS_ASAL
    FROM TBLHTPHAKMILIKURUSAN HTPU,TBLRUJJENISHAKMILIK RH, TBLRUJLOT RL,TBLRUJNEGERI N, TBLRUJDAERAH D, TBLRUJMUKIM M
    ,TBLHTPHAKMILIK H
    WHERE RH.ID_JENISHAKMILIK(+) = HTPU.ID_JENISHAKMILIK
    AND RL.ID_LOT = HTPU.ID_LOT    
    AND HTPU.ID_NEGERI = N.ID_NEGERI
    AND HTPU.ID_DAERAH = D.ID_DAERAH
    AND HTPU.ID_MUKIM = M.ID_MUKIM
    AND HTPU.PEGANGAN_HAKMILIK = H.PEGANGAN_HAKMILIK
    GROUP BY HTPU.ID_PERMOHONAN,N.NAMA_NEGERI, D.NAMA_DAERAH, M.NAMA_MUKIM, N.ID_NEGERI, D.ID_DAERAH, M.ID_MUKIM
    --ORDER BY HTPU.NO_HAKMILIK DESC                      
) MT
,TBLRUJSTATUS RS
WHERE P.ID_FAIL = F.ID_FAIL 
AND P.ID_PERMOHONAN = PP.ID_PERMOHONAN
AND P.ID_PERMOHONAN = LP.ID_PERMOHONAN
AND P.ID_PERMOHONAN = MT.ID_PERMOHONAN
AND F.ID_STATUS = RS.ID_STATUS
AND F.ID_SUBURUSAN=7
--ORDER BY

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPBORANG_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPBORANG_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPBORANGPAJAKAN FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set BORTARIKH_TERIMA = :new.TARIKH_TERIMA 
      ,BORTARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTARPEMOHON
      ,BORTARIKH_TANDATANGAN_PTP = :new.TARIKH_TANDATANGANPTP
      ,BORTARIKH_DAFTAR = :new.TARIKH_DAFTAR
      ,BORTARIKH_TERIMAHAKMILIK = :new.TARIKH_TERIMAHAKMILIK
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set BORTARIKH_TERIMA = :new.TARIKH_TERIMA 
      ,BORTARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTARPEMOHON
      ,BORTARIKH_TANDATANGAN_PTP = :new.TARIKH_TANDATANGANPTP
      ,BORTARIKH_DAFTAR = :new.TARIKH_DAFTAR
      ,BORTARIKH_TERIMAHAKMILIK = :new.TARIKH_TERIMAHAKMILIK
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;

END;

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPDERAF_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPDERAF_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPDERAFPERJANJIAN FOR EACH ROW
BEGIN
  -- Deraf Perjanjian kepada PKP
  IF :new.JENIS_DOKUMEN ='P' OR :old.JENIS_DOKUMEN ='P' THEN
      CASE
        WHEN INSERTING THEN
          update TBLHTPLPRPAJAKANAKT 
          set PERTARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTAR_DERAF
          ,PERTARIKH_TERIMA_PEMOHON = :new.TARIKH_TERIMA
          ,PERTARIKH_HANTAR_PKP = :new.TARIKH_HANTARPTP
          ,PERTARIKH_TERIMA_PKP = :new.TARIKH_TERIMAPTP
          ,PERULASAN_PKP = :new.ULASAN_SEKSYEN 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
        WHEN UPDATING THEN
          update TBLHTPLPRPAJAKANAKT 
          set PERTARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTAR_DERAF
          ,PERTARIKH_TERIMA_PEMOHON = :new.TARIKH_TERIMA
          ,PERTARIKH_HANTAR_PKP = :new.TARIKH_HANTARPTP
          ,PERTARIKH_TERIMA_PKP = :new.TARIKH_TERIMAPTP
          ,PERULASAN_PKP = :new.ULASAN_SEKSYEN 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
      END CASE;
      
  END IF;

END;

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPPAJAKAN_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPPAJAKAN_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPPAJAKAN FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TEMPOH_PAJAKAN = :new.TEMPOH_PAJAKAN 
      ,TARIKH_MULA_PAJAKAN = :new.TARIKH_MULA_PAJAKAN
      ,TARIKH_TAMATPAJAKAN = :new.TARIKH_TAMATPAJAKAN
      ,KADAR_PAJAKAN = :new.KADAR_PAJAKAN
      ,TARIKH_TANDATANGAN = :new.TARIKH_TANDATANGAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TEMPOH_PAJAKAN = :new.TEMPOH_PAJAKAN 
      ,TARIKH_MULA_PAJAKAN = :new.TARIKH_MULA_PAJAKAN
      ,TARIKH_TAMATPAJAKAN = :new.TARIKH_TAMATPAJAKAN
      ,KADAR_PAJAKAN = :new.KADAR_PAJAKAN
      ,TARIKH_TANDATANGAN = :new.TARIKH_TANDATANGAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;

END;
/

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPJM_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPJM_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPJEMAAHMENTERI FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TARIKH_HANTAR_KSU = :new.TARIKH_HANTAR_KSU 
      ,TARIKH_TERIMA_KSU = :new.TARIKH_TERIMA
      ,TARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTAR_PEMOHON
      ,TARIKH_MEMORANDUM = :new.TARIKH_MEMORANDUM
      ,TARIKH_KEPUTUSAN = :new.TARIKH_KEPUTUSAN
      ,TARIKH_HANTAR_DASAR = :new.TARIKH_HANTAR_DASAR
      ,NO_MEMORANDUM = :new.NO_MEMORANDUM
      ,TARIKH_MSYRT_JEMAAH = :new.TARIKH_MSYRT_JEMAAH
      ,TARIKH_KUASA_PBDN = :new.TARIKH_KUASA_PBDN  
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TARIKH_HANTAR_KSU = :new.TARIKH_HANTAR_KSU 
      ,TARIKH_TERIMA_KSU = :new.TARIKH_TERIMA
      ,TARIKH_HANTAR_PEMOHON = :new.TARIKH_HANTAR_PEMOHON
      ,TARIKH_MEMORANDUM = :new.TARIKH_MEMORANDUM
      ,TARIKH_KEPUTUSAN = :new.TARIKH_KEPUTUSAN
      ,TARIKH_HANTAR_DASAR = :new.TARIKH_HANTAR_DASAR
      ,NO_MEMORANDUM = :new.NO_MEMORANDUM
      ,TARIKH_MSYRT_JEMAAH = :new.TARIKH_MSYRT_JEMAAH
      ,TARIKH_KUASA_PBDN = :new.TARIKH_KUASA_PBDN  
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;

END;

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPULASANKJP_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPULASANKJP_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPULASANKJP FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set KJPTARIKH_HANTAR = :new.TARIKH_HANTAR 
      ,KJPTARIKH_TERIMA = :new.TARIKH_TERIMA
      ,KJPTARIKH_SURAT_KEPUTUSAN = :new.TARIKH_SURAT_KEPUTUSAN
      ,ULASAN=:new.ULASAN
      ,STATUS_KEPUTUSAN=:new.STATUS_KEPUTUSAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set KJPTARIKH_HANTAR = :new.TARIKH_HANTAR 
      ,KJPTARIKH_TERIMA = :new.TARIKH_TERIMA
      ,KJPTARIKH_SURAT_KEPUTUSAN = :new.TARIKH_SURAT_KEPUTUSAN
      ,ULASAN=:new.ULASAN
      ,STATUS_KEPUTUSAN=:new.STATUS_KEPUTUSAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;
 
END;

====================================================================================================
--desc tblhtpulasanteknikal
DROP TRIGGER EKPTGHQ.TRI_TBLHTPULASANTEK_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPULASANTEK_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPULASANTEKNIKAL FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set JPPHTARIKH_HANTAR = :new.TARIKH_HANTAR 
      ,JPPHTARIKH_TERIMA = :new.TARIKH_TERIMA
      ,JPPHULASAN = :new.ULASAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set JPPHTARIKH_HANTAR = :new.TARIKH_HANTAR 
      ,JPPHTARIKH_TERIMA = :new.TARIKH_TERIMA
      ,JPPHULASAN = :new.ULASAN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;
 
END;

====================================================================================================
DROP TRIGGER TRI_TBLHTPSUSULAN_INSERT;

CREATE OR REPLACE TRIGGER TRI_TBLHTPSUSULAN_INSERT AFTER INSERT OR UPDATE OR DELETE ON TBLHTPSUSULAN FOR EACH ROW
BEGIN
  IF :new.sumber IN ('PAJAKAN_SURAT_MOHON') OR :old.sumber IN ('PAJAKAN_SURAT_MOHON') THEN
      CASE
        WHEN INSERTING THEN
          update TBLHTPLPRPAJAKANAKT 
          set TARIKH_JAWAB_PERMOHONAN = :new.TARIKH 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
        WHEN UPDATING THEN
          update TBLHTPLPRPAJAKANAKT 
          set TARIKH_JAWAB_PERMOHONAN = :new.TARIKH 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
      END CASE;
  ELSIF :new.sumber IN ('PAJAKAN_SURAT_JKPTGN') OR :old.sumber IN ('PAJAKAN_SURAT_JKPTGN')  THEN
      CASE
        WHEN INSERTING THEN
          update TBLHTPLPRPAJAKANAKT 
          set TARIKH_JKPTGN = :new.TARIKH 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
        WHEN UPDATING THEN
          update TBLHTPLPRPAJAKANAKT 
          set TARIKH_JKPTGN = :new.TARIKH 
          where ID_PERMOHONAN = :new.ID_PERMOHONAN;
      END CASE;
  END IF;
END;

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLHTPPERMOHONAN_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLHTPPERMOHONAN_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLHTPPERMOHONAN FOR EACH ROW
--DECLARE
BEGIN
  CASE
    WHEN INSERTING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TRI_TINDAKAN = 'UPDATE' 
      ,TARIKH_SURAT=:new.TARIKH_SURAT_RUJUKAN_LAIN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TRI_TINDAKAN = 'UPDATE' 
      ,TARIKH_SURAT=:new.TARIKH_SURAT_RUJUKAN_LAIN
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN DELETING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TRI_TINDAKAN = 'DELETE' 
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;
 
END;

====================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLPERMOHONAN_INSERT;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLPERMOHONAN_INSERT AFTER INSERT OR UPDATE OR DELETE ON EKPTGHQ.TBLPERMOHONAN FOR EACH ROW
--DECLARE
BEGIN
  CASE
    WHEN INSERTING THEN
      insert into TBLHTPLPRPAJAKANAKT
        (ID_PERMOHONAN,TARIKH_TERIMA,TRI_TINDAKAN)
      values
        (:new.ID_PERMOHONAN,:new.TARIKH_TERIMA,'INSERT');
    WHEN UPDATING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TRI_TINDAKAN = 'UPDATE' 
      ,TARIKH_TERIMA=:new.TARIKH_TERIMA
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
    WHEN DELETING THEN
      update TBLHTPLPRPAJAKANAKT 
      set TRI_TINDAKAN = 'DELETE' 
      where ID_PERMOHONAN = :new.ID_PERMOHONAN;
  END CASE;
 
END;

  ==================================================================================================
DROP TRIGGER EKPTGHQ.TRI_TBLPERMOHONAN_UPDATE;

CREATE OR REPLACE TRIGGER EKPTGHQ.TRI_TBLPERMOHONAN_UPDATE before update ON EKPTGHQ.TBLPERMOHONAN for each row
begin
  insert into TBLHTPLPRPAJAKANAKT
    (ID_PERMOHONAN,TARIKH_TERIMA,TRI_TINDAKAN)
  values
    (:new.ID_PERMOHONAN,:new.TARIKH_TERIMA,'INSERT');
end;
  
  ==================================================================================================
ALTER TABLE EKPTGHQ.TBLHTPLPRPAJAKANAKT
 DROP PRIMARY KEY CASCADE;
DROP TABLE EKPTGHQ.TBLHTPLPRPAJAKANAKT CASCADE CONSTRAINTS;

CREATE TABLE TBLHTPLPRPAJAKANAKT
(
  ID_LPRPAJAKANAKT           NUMBER CONSTRAINT LPRPAJAKANAKT_C01 NOT NULL,
  ID_PERMOHONAN              NUMBER,
  ID_AGENSI                  NUMBER,
  ID_KEMENTERIAN             NUMBER,
  NO_RUJUKAN_FAIL            VARCHAR2(50 BYTE),
  NO_RUJUKAN_KJP             VARCHAR2(50 BYTE),
  ID_MASUK                   NUMBER,
  TARIKH_MASUK               DATE,
  ID_KEMASKINI               NUMBER,
  TARIKH_KEMASKINI           DATE,
  TARIKH_HANTAR_KSU          DATE,
  TARIKH_TERIMA_KSU          DATE,
  TARIKH_TERIMA              DATE,
  TARIKH_HANTAR_PEMOHON      DATE,
  TARIKH_MEMORANDUM          DATE,
  TARIKH_KEPUTUSAN           DATE,
  TARIKH_HANTAR_DASAR        DATE,
  NO_MEMORANDUM              VARCHAR2(30 BYTE),
  TARIKH_MSYRT_JEMAAH        DATE,
  TARIKH_KUASA_PBDN          DATE,
  JPPHTARIKH_HANTAR          DATE,
  JPPHTARIKH_TERIMA          DATE,
  JPPHULASAN                 VARCHAR2(1500 BYTE),
  TEKTARIKH_HANTAR           DATE,
  TEKTARIKH_TERIMA           DATE,
  TEKTARIKH_KEPUTUSAN        DATE,
  PERTARIKH_TERIMA_PEMOHON   DATE,
  PERTARIKH_HANTAR_PKP       DATE,
  PERTARIKH_TERIMA_PKP       DATE,
  TARIKH_TERIMA_PERJANJIAN   DATE,
  PERTARIKH_HANTAR_PEMOHON   DATE,
  TARIKH_TANDATANGAN         DATE,
  BORTARIKH_TERIMA           DATE,
  BORTARIKH_HANTAR_PEMOHON   DATE,
  BORTARIKH_TANDATANGAN_PTP  DATE,
  BORTARIKH_DAFTAR           DATE,
  TARIKH_MULA_PAJAKAN        DATE,
  TARIKH_TAMATPAJAKAN        DATE,
  TEMPOH_PAJAKAN             VARCHAR2(10 BYTE),
  KADAR_PAJAKAN              NUMBER(26,10),
  TRI_TINDAKAN               VARCHAR2(10 BYTE),
  TARIKH_SURAT               DATE,
  KJPTARIKH_HANTAR           DATE,
  KJPTARIKH_TERIMA           DATE,
  KJPTARIKH_SURAT_KEPUTUSAN  DATE,
  ULASAN                     VARCHAR2(1500 BYTE),
  STATUS_KEPUTUSAN           VARCHAR2(2 BYTE),
  TARIKH_JAWAB_PERMOHONAN    DATE,
  TARIKH_JKPTGN              DATE,
  PERULASAN_PKP              VARCHAR2(1500 BYTE),
  BORTARIKH_TERIMAHAKMILIK   DATE

)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX LPRPAJAKANAKT_INDX1 ON TBLHTPLPRPAJAKANAKT
(ID_PERMOHONAN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LPRPAJAKANAKT_PK ON TBLHTPLPRPAJAKANAKT
(ID_LPRPAJAKANAKT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE TBLHTPLPRPAJAKANAKT ADD (
  CONSTRAINT LPRPAJAKANAKT_PK
 PRIMARY KEY
 (ID_LPRPAJAKANAKT)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
  ==================================================================================================
CREATE OR REPLACE TRIGGER TBLHTPLPRPAJAKANAKT_BI    
before insert on     TBLHTPLPRPAJAKANAKT    for each row
begin    if :new.ID_LPRPAJAKANAKT   is null    then select TBLHTPLPRPAJAKANAKT_SEQ.NEXTVAL into :new.ID_LPRPAJAKANAKT            from dual;    end if;    end;
              
  ==================================================================================================
DROP SEQUENCE TBLHTPLPRPAJAKANAKT_SEQ;

CREATE SEQUENCE TBLHTPLPRPAJAKANAKT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;