

====================================================

CREATE OR REPLACE TRIGGER TBLHTPHAKMILIKADUAN_BI 
   BEFORE INSERT 
   ON TBLHTPHAKMILIKADUAN 
   FOR EACH ROW
BEGIN 
   IF :NEW.ID_HAKMILIKADUAN IS NULL 
   THEN 
      SELECT    (SELECT kod_negeri 
                   FROM tbllookupstate) 
             || TO_CHAR (SYSDATE, 'YY') 
             || TBLHTPHAKMILIKADUAN_SEQ.NEXTVAL 
        INTO :NEW.ID_HAKMILIKADUAN 
        FROM DUAL; 
   END IF; 
END;

CREATE SEQUENCE TBLHTPHAKMILIKADUAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;

ALTER TABLE TBLHTPHAKMILIKADUAN ADD (
  CONSTRAINT TBLHTPHAKMILIKADUAN_PK
 PRIMARY KEY
 (ID_HAKMILIKADUAN));

CREATE TABLE TBLHTPHAKMILIKADUAN
(
  ID_HAKMILIKADUAN  NUMBER                     NOT NULL,
  ID_ADUAN      NUMBER                     NOT NULL,
  ID_LUAS            NUMBER,
  NO_HAKMILIK        VARCHAR2(50 BYTE),
  NO_WARTA           VARCHAR2(10 BYTE),
  TARIKH_WARTA       DATE,
  NO_LOT             VARCHAR2(20 BYTE),
  LUAS               VARCHAR2(40 BYTE),
  NO_SYIT            VARCHAR2(50 BYTE),
  NO_PELAN           VARCHAR2(50 BYTE),
  SYARAT             VARCHAR2(1000 BYTE),
  SEKATAN            VARCHAR2(1000 BYTE),
  CUKAI              NUMBER(11,2),
  FLAG_PELAN         VARCHAR2(1 BYTE),
  ULASAN             VARCHAR2(1500 BYTE),
  ID_SUBKATEGORI     NUMBER,
  LOKASI             VARCHAR2(60 BYTE),
  CUKAI_TERKINI      NUMBER(26,10),
  STATUS_RIZAB       VARCHAR2(50 BYTE),
  NO_BANGUNAN        VARCHAR2(5 BYTE),
  NO_TINGKAT         VARCHAR2(5 BYTE),
  NO_PETAK           VARCHAR2(5 BYTE),
  STATUS_TANAH       VARCHAR2(2 BYTE),
  TARIKH_MULA        DATE,
  TARIKH_LUPUT       DATE,
  LUAS_BERSAMAAN     NUMBER(11,5),
  ID_KATEGORI        NUMBER,
  ID_DAERAH          NUMBER                     NOT NULL,
  ID_NEGERI          NUMBER                     NOT NULL,
  ID_MUKIM           VARCHAR2(20 BYTE)          NOT NULL,
  ID_LOT             NUMBER,
  ID_JENISHAKMILIK   NUMBER,
  ID_JENISRIZAB      NUMBER,
  NO_RIZAB           VARCHAR2(10 BYTE),
  TARIKH_RIZAB       DATE,
  NO_PU              VARCHAR2(20 BYTE),
  ID_LUAS_BERSAMAAN  NUMBER                     DEFAULT 2,
  ID_MASUK           NUMBER,
  TARIKH_MASUK       DATE,
  ID_KEMASKINI       NUMBER,
  TARIKH_KEMASKINI   DATE
 )
TABLESPACE HTP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

====================================================

INSERT INTO USER_MODULE_TEMPLATE
(TAB_ID, USER_LOGIN, MODULE_ID, "SEQUENCE", MODULE_CUSTOM_TITLE, COLUMN_NUMBER)
VALUES('1594262361517', '(HTP)HQPengguna', 'ekptg.view.htp.online.aduan.AduanTanah', 1, 'Agihan Aduan', 0);

INSERT INTO USER_MODULE_TEMPLATE
(TAB_ID, USER_LOGIN, MODULE_ID, "SEQUENCE", MODULE_CUSTOM_TITLE, COLUMN_NUMBER)
VALUES('1594262361517', '(HTP)AdminHTP', 'ekptg.view.htp.online.aduan.AduanTanah', 1, 'Agihan Aduan', 0);


SELECT * FROM USER_MODULE_TEMPLATE
WHERE 
--USER_LOGIN LIKE '%htp-online-user%'
MODULE_ID LIKE '%AduanTanah%'


INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.PengurusanAduanTanah', '(HTP)HQPegawai');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.PengurusanAduanTanah', '(HTP)HQPegawai1');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.PengurusanAduanTanah', '(HTP)HQPegawaiPerolehan');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.PengurusanAduanTanah', '(HTP)HQPengarah');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.PengurusanAduanTanah', '(HTP)HQPengguna');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', '(HTP)HQPegawai');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', '(HTP)HQPegawai1');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', '(HTP)HQPegawaiPerolehan');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', '(HTP)HQPengarah');
INSERT INTO ROLE_MODULE
(MODULE_ID, USER_ROLE)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', '(HTP)HQPengguna');

SELECT * FROM ROLE_MODULE
WHERE MODULE_ID LIKE '%AduanTanah%'

INSERT INTO MODULE
(MODULE_ID, MODULE_TITLE, MODULE_CLASS, MODULE_GROUP, MODULE_DESCRIPTION, MODULE_VERSION, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES('ekptg.view.htp.online.aduan.AduanTanah', 'Pengurusan Aduan Manual', 'ekptg.view.htp.online.aduan.AduanTanah', 'EKPTG - HTP', NULL, '1.0', 1, 1, TIMESTAMP '2020-04-27 00:00:00.000000', TIMESTAMP '2020-04-27 00:00:00.000000');

SELECT * FROM MODULE
WHERE MODULE_ID LIKE '%AduanTanah%'