-- ros 1/11/2020
====================================================================================================
ALTER TABLE TBLHTPHAKMILIKURUSAN ADD ID_KEMENTERIAN NUMBER;
ALTER TABLE TBLHTPHAKMILIKURUSAN ADD ID_AGENSI NUMBER;
ALTER TABLE TBLHTPULASANKJP ADD ID_AGENSI NUMBER;
ALTER TABLE TBLHTPULASANKJP ADD NO_HAKMILIK VARCHAR2(100);


-- 2020/10/21 local-mac

--200 LAPORAN
INSERT INTO TBLRUJSUBURUSAN
(ID_SUBURUSAN,ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB, FLAG_AKTIF)
VALUES(90201,200, '01', 'LAPORAN TANAH', NULL, NULL, NULL, NULL, 3, NULL, '1');

--
SELECT * FROM TBLRUJSUBURUSAN WHERE ID_URUSAN=200

CREATE OR REPLACE TRIGGER TBLLAPORANTANAH_BI    
before insert on     TBLLAPORANTANAH    for each row
begin    if :new.ID_LAPORANTANAH    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLLAPORANTANAH_SEQ.NEXTVAL into :new.ID_LAPORANTANAH            from dual;    end if;    end;

CREATE SEQUENCE TBLLAPORANTANAH_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  ORDER;

ALTER TABLE TBLLAPORANTANAH ADD (
  CONSTRAINT TBLAPORANTANAH_PK
 PRIMARY KEY
 (ID_LAPORANTANAH));

--NAMA_JAWATAN_PELAPOR
--"ID_PERMOHONAN" NUMBER CONSTRAINT "TBLAPORANTANAH_C02" NOT NULL ENABLE, 

CREATE TABLE "TBLLAPORANTANAH" 
   (	"ID_LAPORANTANAH" NUMBER CONSTRAINT "TBLAPORANTANAH_C01" NOT NULL ENABLE, 
	"ID_PERMOHONAN" NUMBER , 
	"TARIKH_LAWATAN" DATE, 
	"JALAN_HUBUNGAN" VARCHAR2(1000), 
	"KAWASAN_BERHAMPIRAN" VARCHAR2(1000), 
	"KEADAAN_RUPABUMI" VARCHAR2(1000), 
	"KEADAAN_TANAH" VARCHAR2(1000), 
	"KEMUDAHAN_ASAS" VARCHAR2(1000), 
	"SEMP_UTARA" VARCHAR2(1000), 
	"SEMP_BARAT" VARCHAR2(1000), 
	"SEMP_TIMUR" VARCHAR2(1000), 
	"SEMP_SELATAN" VARCHAR2(1000), 
	"ULASAN" VARCHAR2(1500), 
	"FLAG_KEMUDAHANASAS_AIR" VARCHAR2(1), 
	"FLAG_KEMUDAHANASAS_ELEKTRIK" VARCHAR2(1), 
	"FLAG_KEMUDAHANASAS_TEL" VARCHAR2(1), 
	"FLAG_JENISTANAH" VARCHAR2(2), 
	"ID_HAKMILIK" NUMBER, 
	"TUJUAN_LAPORAN" VARCHAR2(1000), 
	"LAPORAN_ATASTANAH" VARCHAR2(1000), 
	"JARAK_DARIBANDAR" VARCHAR2(100), 
	"FLAG_LAWATAN" VARCHAR2(1), 
	"NAMA_PELAPOR" VARCHAR2(100), 
	"ID_JAWATANPELAPOR" NUMBER, 
	"ID_NEGERIPELAPOR" NUMBER, 
	"TUJUAN_LAWATAN" VARCHAR2(1000), 
	"PERKEMBANGAN_TAPAK" VARCHAR2(1000), 
	"JARAK_DRBANDAR" VARCHAR2(100), 
	"PEMBANGUNAN_SEKITAR" VARCHAR2(500), 
	"LATARBELAKANG_TAPAK" VARCHAR2(500), 
	"LAPORAN" VARCHAR2(1500), 
	"FLAG_LAPORAN" VARCHAR2(1), 
	"CATATAN" VARCHAR2(1500), 
	"ID_TANAH" NUMBER, 
	"KOS_OPERASI" NUMBER(11,2), 
	"MASA_OPERASI_DARI" VARCHAR2(5), 
	"MASA_OPERASI_HINGGA" VARCHAR2(5), 
	"WAKTU_OPERASI_DARI" VARCHAR2(10), 
	"WAKTU_OPERASI_HINGGA" VARCHAR2(10), 
	"TARIKH_AKHIR_OPERASI" DATE, 
	"TARIKH_MULA_OPERASI" DATE, 
	"NAMA_JAWATAN_PELAPOR" VARCHAR2(100), 
	"TARIKH_TERIMA_FAIL" DATE, 
	"TARIKH_LAPORAN" DATE, 
	"LOKASI" VARCHAR2(1000), 
	"NAMA_PENYEMAK" VARCHAR2(100), 
	"NAMA_JAWATAN_PENYEMAK" VARCHAR2(100), 
	"ID_NEGERIPENYEMAK" NUMBER, 
	"LAPORAN_SELEPASOPERASI" VARCHAR2(1500), 
	"LAPORAN_SEMASAOPERASI" VARCHAR2(3000), 
	"NAMA_PENCEROBOH" VARCHAR2(80),
		"ID_MASUK" NUMBER, 
	"TARIKH_MASUK" DATE, 
	"ID_KEMASKINI" NUMBER, 
	"TARIKH_KEMASKINI" DATE 
   ) 
   --TABLESPACE RUJ01
   TABLESPACE RUJ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
                        BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-- 2020/10/11 local
====================================================================================================
UPDATE TBLRUJURUSAN
SET NAMA_URUSAN='PEMBERIMILIKAN TANAH'
WHERE ID_URUSAN=1

UPDATE tblrujsuburusan
SET NAMA_SUBURUSAN='PEMBERIMILIKAN TANAH'
WHERE ID_SUBURUSAN=42

--2020/10/01
====================================================================================================
ALTER TABLE TBLONLINEEADUAN ADD NO_FAIL VARCHAR2(100);
ALTER TABLE TBLHTPHAKMILIKADUAN ADD ID_SEKSYEN NUMBER;

--2020/09/30
ALTER TABLE TBLHTPHAKMILIK ADD CATATAN_PELEPASAN VARCHAR2(250);
====================================================================================================

--2020/09/21
====================================================================================================
ALTER TABLE TBLHTPMEMOMENTERI ADD NAMA_PEMOHON VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD MAKLUMAT_TANAH VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD ASAS_PERTIMBANGAN VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD KADAR_PAJAKAN VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD KESIMPULAN VARCHAR2(100);

--2020/09/17
====================================================================================================

ALTER TABLE TBLHTPDOKUMEN MODIFY JENIS_DOKUMEN NUMBER DEFAULT 0;


--2020/09/12
====================================================================================================

ALTER TABLE TBLHTPHAKMILIKURUSAN ADD ID_SEKSYEN NUMBER DEFAULT 0;


--2020/08/28
====================================================================================================
ALTER TABLE TBLHTPFAILLAIN ADD FLAG_AKTIF VARCHAR(1) DEFAULT 'Y';


SELECT * FROM TBLHTPFAILLAIN

--2020/08/26
====================================================================================================

SELECT * FROM TBLPHPLAPORANTANAH
WHERE ID_LAPORANTANAH=992011801

CREATE OR REPLACE VIEW V_LAPORAN_TANAH
(ID_LOT,KOD_LOT,NO_LOT,ID_JENISHAKMILIK,KOD_JENIS_HAKMILIK,NO_HAKMILIK,ID_NEGERI,NAMA_NEGERI,ID_DAERAH,NAMA_DAERAH,ID_MUKIM,NAMA_MUKIM,NO_FAIL,TAJUK_FAIL,NAMA_URUSAN,ID_LAPORAN,MODUL)
AS
(
--PHP
SELECT MT.ID_LOT,RL.KETERANGAN AS KOD_LOT,MT.NO_LOT
,MT.ID_JENISHAKMILIK,RJH.KOD_JENIS_HAKMILIK,NVl(MT.NO_HAKMILIK,'TIADA') NO_HAKMILIK
,MT.ID_NEGERI,RN.NAMA_NEGERI,MT.ID_DAERAH,RD.NAMA_DAERAH,MT.ID_MUKIM,RM.NAMA_MUKIM
,NVL(F.NO_FAIL,'TIADA') NO_FAIL,NVL(F.TAJUK_FAIL,'TIADA') TAJUK_FAIL
--,P.ID_PERMOHONAN
,RU.NAMA_URUSAN,LT.ID_LAPORANTANAH ID_LAPORAN,'PHP' MODUL
--LT.*
FROM
TBLPHPLAPORANTANAH LT
, TBLPERMOHONAN P
, TBLPHPHAKMILIKPERMOHONAN HP
--
,TBLPHPHAKMILIK MT
,TBLRUJLOT RL
,TBLRUJJENISHAKMILIK RJH
, TBLRUJMUKIM RM, TBLRUJDAERAH RD, TBLRUJNEGERI RN
--FAIL
,TBLPFDFAIL F,TBLRUJURUSAN RU
WHERE
LT.ID_PERMOHONAN = P.ID_PERMOHONAN
AND P.ID_PERMOHONAN = HP.ID_PERMOHONAN
--AND HP.ID_HAKMILIKPERMOHONAN = MT.ID_HAKMILIKPERMOHONAN
AND HP.ID_HAKMILIKPERMOHONAN = MT.ID_HAKMILIKPERMOHONAN(+)
--TANAH
AND MT.ID_LOT= RL.ID_LOT
AND MT.ID_JENISHAKMILIK = RJH.ID_JENISHAKMILIK(+)
AND MT.ID_NEGERI = RN.ID_NEGERI
AND MT.ID_DAERAH = RD.ID_DAERAH
AND MT.ID_MUKIM = RM.ID_MUKIM
AND F.ID_FAIL = P.ID_FAIL
AND F.ID_URUSAN = RU.ID_URUSAN
)


SELECT * FROM TBLPERMOHONAN
WHERE ID_PERMOHONAN=9920153466

SELECT * FROM TBLPFDFAIL
WHERE ID_FAIL=9920661094

--2020/06/04
====================================================================================================

-- LIVE 9920122 (2020/06/04)
UPDATE TBLRUJSUBURUSAN
SET ID_URUSAN=14, KOD_SUBURUSAN='01', NAMA_SUBURUSAN='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', ID_MASUK=NULL, TARIKH_MASUK=NULL, ID_KEMASKINI=NULL, TARIKH_KEMASKINI=NULL, ID_SEKSYEN=3, KOD_SUBURUSAN_ARKIB=NULL, FLAG_AKTIF='1'
WHERE ID_SUBURUSAN=9920122;

INSERT INTO TBLRUJSUBURUSAN
(ID_SUBURUSAN,ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB, FLAG_AKTIF)
VALUES(9920122,14, '01', 'PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', NULL, NULL, NULL, NULL, 3, NULL, '1');

SELECT * FROM TBLRUJSUBURUSAN
WHERE NAMA_SUBURUSAN ='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT'


SELECT * FROM TBLPPKP