--2020/06/04
====================================================================================================

-- LIVE 9920122 (2020/06/04)
UPDATE TBLRUJSUBURUSAN
SET ID_URUSAN=14, KOD_SUBURUSAN='01', NAMA_SUBURUSAN='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', ID_MASUK=NULL, TARIKH_MASUK=NULL, ID_KEMASKINI=NULL, TARIKH_KEMASKINI=NULL, ID_SEKSYEN=3, KOD_SUBURUSAN_ARKIB=NULL, FLAG_AKTIF='1'
WHERE ID_SUBURUSAN=9920122;

INSERT INTO TBLRUJSUBURUSAN
(ID_SUBURUSAN,ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB, FLAG_AKTIF)
VALUES(9920122,14, '01', 'PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', NULL, NULL, NULL, NULL, 3, NULL, '1');

SELECT * FROM TBLRUJSUBURUSAN
WHERE NAMA_SUBURUSAN ='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT'
