--2020/10/01
====================================================================================================
ALTER TABLE TBLONLINEEADUAN ADD NO_FAIL VARCHAR2(100);
ALTER TABLE TBLHTPHAKMILIKADUAN ADD ID_SEKSYEN NUMBER;

--2020/09/21
====================================================================================================
ALTER TABLE TBLHTPMEMOMENTERI ADD NAMA_PEMOHON VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD MAKLUMAT_TANAH VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD ASAS_PERTIMBANGAN VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD KADAR_PAJAKAN VARCHAR2(100);
ALTER TABLE TBLHTPMEMOMENTERI ADD KESIMPULAN VARCHAR2(100);

--2020/09/17
====================================================================================================

ALTER TABLE TBLHTPDOKUMEN MODIFY JENIS_DOKUMEN NUMBER DEFAULT 0;


--2020/09/12
====================================================================================================

ALTER TABLE TBLHTPHAKMILIKURUSAN ADD ID_SEKSYEN NUMBER DEFAULT 0;


--2020/08/28
====================================================================================================
ALTER TABLE TBLHTPFAILLAIN ADD FLAG_AKTIF VARCHAR(1) DEFAULT 'Y';


SELECT * FROM TBLHTPFAILLAIN

--2020/08/26
====================================================================================================

SELECT * FROM TBLPHPLAPORANTANAH
WHERE ID_LAPORANTANAH=992011801

CREATE OR REPLACE VIEW V_LAPORAN_TANAH
(ID_LOT,KOD_LOT,NO_LOT,ID_JENISHAKMILIK,KOD_JENIS_HAKMILIK,NO_HAKMILIK,ID_NEGERI,NAMA_NEGERI,ID_DAERAH,NAMA_DAERAH,ID_MUKIM,NAMA_MUKIM,NO_FAIL,TAJUK_FAIL,NAMA_URUSAN,ID_LAPORAN,MODUL)
AS
(
--PHP
SELECT MT.ID_LOT,RL.KETERANGAN AS KOD_LOT,MT.NO_LOT
,MT.ID_JENISHAKMILIK,RJH.KOD_JENIS_HAKMILIK,NVl(MT.NO_HAKMILIK,'TIADA') NO_HAKMILIK
,MT.ID_NEGERI,RN.NAMA_NEGERI,MT.ID_DAERAH,RD.NAMA_DAERAH,MT.ID_MUKIM,RM.NAMA_MUKIM
,NVL(F.NO_FAIL,'TIADA') NO_FAIL,NVL(F.TAJUK_FAIL,'TIADA') TAJUK_FAIL
--,P.ID_PERMOHONAN
,RU.NAMA_URUSAN,LT.ID_LAPORANTANAH ID_LAPORAN,'PHP' MODUL
--LT.*
FROM
TBLPHPLAPORANTANAH LT
, TBLPERMOHONAN P
, TBLPHPHAKMILIKPERMOHONAN HP
--
,TBLPHPHAKMILIK MT
,TBLRUJLOT RL
,TBLRUJJENISHAKMILIK RJH
, TBLRUJMUKIM RM, TBLRUJDAERAH RD, TBLRUJNEGERI RN
--FAIL
,TBLPFDFAIL F,TBLRUJURUSAN RU
WHERE
LT.ID_PERMOHONAN = P.ID_PERMOHONAN
AND P.ID_PERMOHONAN = HP.ID_PERMOHONAN
--AND HP.ID_HAKMILIKPERMOHONAN = MT.ID_HAKMILIKPERMOHONAN
AND HP.ID_HAKMILIKPERMOHONAN = MT.ID_HAKMILIKPERMOHONAN(+)
--TANAH
AND MT.ID_LOT= RL.ID_LOT
AND MT.ID_JENISHAKMILIK = RJH.ID_JENISHAKMILIK(+)
AND MT.ID_NEGERI = RN.ID_NEGERI
AND MT.ID_DAERAH = RD.ID_DAERAH
AND MT.ID_MUKIM = RM.ID_MUKIM
AND F.ID_FAIL = P.ID_FAIL
AND F.ID_URUSAN = RU.ID_URUSAN
)


SELECT * FROM TBLPERMOHONAN
WHERE ID_PERMOHONAN=9920153466

SELECT * FROM TBLPFDFAIL
WHERE ID_FAIL=9920661094

--2020/06/04
====================================================================================================

-- LIVE 9920122 (2020/06/04)
UPDATE TBLRUJSUBURUSAN
SET ID_URUSAN=14, KOD_SUBURUSAN='01', NAMA_SUBURUSAN='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', ID_MASUK=NULL, TARIKH_MASUK=NULL, ID_KEMASKINI=NULL, TARIKH_KEMASKINI=NULL, ID_SEKSYEN=3, KOD_SUBURUSAN_ARKIB=NULL, FLAG_AKTIF='1'
WHERE ID_SUBURUSAN=9920122;

INSERT INTO TBLRUJSUBURUSAN
(ID_SUBURUSAN,ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB, FLAG_AKTIF)
VALUES(9920122,14, '01', 'PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT', NULL, NULL, NULL, NULL, 3, NULL, '1');

SELECT * FROM TBLRUJSUBURUSAN
WHERE NAMA_SUBURUSAN ='PERMOHONAN PERAKUAN JAWATANKUASA RUANG PEJABAT'


SELECT * FROM TBLPPKP