
--2020/08/12 LOCAL,UAT

ALTER TABLE TBLINTLOG ADD NO_TRANSAKSI VARCHAR2(30);

CREATE TRIGGER TBLINTLOG_BI    
before insert on     TBLINTLOG    for each row
begin    if :new.ID_LOG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTLOG_SEQ.NEXTVAL into :new.ID_LOG                from dual;    end if;    end; 

CREATE SEQUENCE TBLINTLOG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
 
SELECT * FROM TBLINTMTLOG
  

--TABLESPACE "PFD01" 
CREATE TABLE TBLINTLOG (
	ID_LOG NUMBER CONSTRAINT "TBLINTLOG_C01" NOT NULL ENABLE, 
	JENIS_TRANSAKSI VARCHAR2(10), 
	FLAG_INTEGRASI VARCHAR2(1), 
	TARIKH_TRANSAKSI DATE, 
	FLAG_TRANSAKSI VARCHAR2(1), 
	CATATAN VARCHAR2(500), 
	ID_MASUK           NUMBER,
  	TARIKH_MASUK       DATE,
  	ID_KEMASKINI       NUMBER,
  	TARIKH_KEMASKINI   DATE,
	CONSTRAINT TBLINTLOG_PK PRIMARY KEY (ID_LOG)
 )
--TABLESPACE INT01 --LOCAL
TABLESPACE USERS --UAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN "TBLINTLOG"."JENIS_TRANSAKSI" IS 'J=JPPH B; D=REGISTER';
 
COMMENT ON COLUMN "TBLINTLOG"."FLAG_INTEGRASI" IS 'I=IN; O=OUT';
 
COMMENT ON COLUMN "TBLINTLOG"."FLAG_TRANSAKSI" IS 'Y=SUCCESS; T=FAILED';


-- 2020/03/30 change INT_WS_CONFIG (TBLINTWSCONFIG)

-- 2020/04/13 (ekptghqfat)
INSERT INTO TBLINTWSCONFIG
(KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES('MT', 'MyeTaPPApplication', 'etpapi01', 'etpapi01', 'http://sit-ws.kehakiman.gov.my/sit/etapp?wsdl', 'ETP', NULL, NULL, 'Y', NULL, NULL, NULL, NULL);

-- 2020/04/13 (ekptghqfat)
INSERT INTO TBLINTWSCONFIG
(KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES('MTREG', 'MyeTaPPApplication', 'etpapi01', 'etpapi01', 'http://sit-ws.kehakiman.gov.my/sit/etappCivilRegisterCase?wsdl', 'ETP', NULL, NULL, 'Y', NULL, NULL, NULL, NULL);


-- 2020/04/13 (ekptghqfat)
CREATE OR REPLACE TRIGGER TBLINTWSCONFIG_BI    
before insert on     TBLINTWSCONFIG    for each row
begin    if :new.ID_CONFIG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTWSCONFIG_SEQ.NEXTVAL into :new.ID_CONFIG   from dual; end if;    end;
/

-- 2020/04/13 (ekptghqfat)
CREATE SEQUENCE TBLINTWSCONFIG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
-- 2020/04/13 (ekptghqfat)
--ALTER TABLE TBLINTWSCONFIG ADD WS_SOURCE VARCHAR2(20);
--DROP TABLE TBLINTWSCONFIG;
CREATE TABLE TBLINTWSCONFIG(
  ID_CONFIG NUMBER(38),
  KOD VARCHAR2(100 BYTE),
  KETERANGAN VARCHAR2(250 BYTE),
  WS_USERNAME VARCHAR2(20 BYTE),
  WS_PASSWORD VARCHAR2(20 BYTE),
  WS_URL VARCHAR2(100 BYTE),
  WS_SOURCE VARCHAR2(20 BYTE),
  ID_AGENSIID VARCHAR2(100 BYTE),
  CATATAN VARCHAR2(250 BYTE),
  FLAG_AKTIF VARCHAR(1 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLINTWSCONFIG_PK PRIMARY KEY (ID_CONFIG)
);

