
CREATE SEQUENCE TBLPPKBORANGPNB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLPPKBORANGPNB
(
  ID_BORANGPNB         NUMBER,
  ID_FAIL           NUMBER,
  ID_PERBICARAAN           NUMBER,
  ID_NEGERIUNIT           NUMBER,
  ID_UNIT           NUMBER,
  NO_PNB       VARCHAR2(100 BYTE),
  NAMA_BORANG       VARCHAR2(100 BYTE),
  CONTENT           BLOB,
  FLAG_HANTARPNB       VARCHAR2(1 BYTE),
  ID_HANTARPNB          NUMBER,
  TARIKH_HANTARPNB      DATE,
  FLAG_DOWNLOAD       VARCHAR2(1 BYTE),
  ID_DOWNLOAD          NUMBER,
  TARIKH_DOWNLOAD      DATE
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  ETAPP01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE ETAPP01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE TBLPPKBORANGPNB ADD (
  PRIMARY KEY
 (ID_BORANGPNB));
 
 
CREATE OR REPLACE TRIGGER TBLPPKBORANGPNB_BI    
before insert on     TBLPPKBORANGPNB    for each row
begin    if :new.ID_BORANGPNB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKBORANGPNB_SEQ.NEXTVAL into :new.ID_BORANGPNB   from dual; end if;    end;
/



CREATE SEQUENCE TBLPPKBORANGPNBOB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


CREATE TABLE TBLPPKBORANGPNBOB
(
  ID_BORANGPNBOB         NUMBER,
  ID_BORANGPNB NUMBER,
  ID_PK           NUMBER,
  TABLENAME       VARCHAR2(200 BYTE),
  FLAG_HANTAROB       VARCHAR2(1 BYTE),
  ID_HANTAROB          NUMBER,
  TARIKH_HANTAROB      DATE,
  FLAG_RETURN       VARCHAR2(1 BYTE),
  ID_RETURN          NUMBER,
  TARIKH_RETURN      DATE,
  CATATAN_RETURN       VARCHAR2(4000 BYTE),
  NAMA       VARCHAR2(1000 BYTE),
  TARAF       VARCHAR2(1000 BYTE),
  ALAMAT_1       VARCHAR2(1000 BYTE),
  ALAMAT_2       VARCHAR2(1000 BYTE),
  ALAMAT_3       VARCHAR2(1000 BYTE),
  POSKOD       VARCHAR2(10 BYTE),
  NEGERI       VARCHAR2(1000 BYTE),
  BANDAR       VARCHAR2(1000 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE TBLPPKBORANGPNBOB ADD (
  PRIMARY KEY
 (ID_BORANGPNBOB));
 
 CREATE OR REPLACE TRIGGER TBLPPKBORANGPNBOB_BI    
before insert on     TBLPPKBORANGPNBOB    for each row
begin    if :new.ID_BORANGPNBOB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKBORANGPNBOB_SEQ.NEXTVAL into :new.ID_BORANGPNB   from dual; end if;    end;
/


CREATE TABLE TBLRUJSEQESNOPNB
(
  TAHUN       VARCHAR2(4 BYTE),
  ID_NEGERI   VARCHAR2(20 BYTE),
  KOD_MODUL   VARCHAR2(20 BYTE),
  NO_TURUTAN  NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



INSERT INTO ROLE (
   NAME, DESCRIPTION, THEME, 
   ROLE_DETAILS) 
VALUES ('user_pnb','Pengguna PNB','Integrasi.css','KETERANGAN PERANAN');



ALTER TABLE TBLPPKBORANGPNB
ADD (
	JENIS_BORANG VARCHAR2(100 BYTE)
);



	
INSERT INTO ROLE (NAME, DESCRIPTION, THEME)
VALUES ('user_pnb', 'Pengguna PNB', 'Integrasi.css');

Insert into TBLINTRUJJENISPEJABAT
   (ID_JENISPEJABAT, ID_SIMPAN, ID_KEMASKINI, TARIKH_SIMPAN, TARIKH_KEMASKINI, 
    KOD_PEJABAT, NAMA_PEJABAT, FLAG_AKTIF)
 Values
   (16112, NULL, NULL, NULL, NULL, 
    '02', 'Pencetakan Nasional Berhad', 1);
    
    
    Insert into TBLINTRUJJENISPEJABAT
   (ID_JENISPEJABAT, ID_SIMPAN, ID_KEMASKINI, TARIKH_SIMPAN, TARIKH_KEMASKINI, 
    KOD_PEJABAT, NAMA_PEJABAT, FLAG_AKTIF)
 Values
   (16113, NULL, NULL, NULL, NULL, 
    '03', 'LHDN', 1);

ALTER TABLE TBLPPKBORANGPNB
ADD (
	COUNT_PAGES NUMBER
);


   
   ALTER TABLE
   TBLPPKBORANGPNBOB
   ADD
   (
   NOSURAT_HANTAROB VARCHAR2(100 BYTE)
   );
	

