-- Mula v6.5

--2020/07/14
 INFO [14/Jul/2020 06:33:46] (SkrinPopupCarianHakmilik.java:991) LIST HAKMILIK : 
 
 SELECT * FROM (  
 	SELECT  ROW_NUMBER () OVER (ORDER BY MK.NAMA_MUKIM ASC, LPAD (M.NO_LOT, 20) ASC, LPAD (M.NO_PT, 20) ASC, LPAD (M.NO_SUBJAKET, 20) ASC) AS RN, UI.ID_JAWATAN,  M.FLAG_SEGERA_SEBAHAGIAN, M.FLAG_PEMBATALAN_KESELURUHAN,M.FLAG_PENARIKAN_KESELURUHAN,P.NO_RUJUKAN_PTG, P.ID_STATUS, F.NO_FAIL, M.CATATAN, P.ID_PERMOHONAN, LS.KETERANGAN AS UNIT1, LT.KETERANGAN AS UNIT2, M.ID_HAKMILIK, M.ID_NEGERI, M.TARIKH_MASUK AS TARIKH_MASUK,  '' AS NAMA_PEGAWAI, '' AS ID_BORANGE,  '' AS FLAG_ONLINE,'' AS STATUS_BANTAHAN_AP,'' AS KETERANGAN,  ''  AS ID_SIASATAN, '' AS ID_BORANGL, '' AS TARIKH_BORANGL, '' AS JENIS_PILIH,  '' AS TEMPOH,  N.NAMA_NEGERI,   NVL(TEMP_COUNTPB.TOTALPB,0) AS TOTALPB, M.ID_JENISHAKMILIK, M.ID_DAERAH, M.ID_MUKIM, MK.NAMA_MUKIM, M.ID_UNITLUASLOT, M.LUAS_AMBIL,    M.NO_HAKMILIK, M.NO_LOT, M.LUAS_LOT, M.NO_PT, M.TARIKH_DAFTAR, M.TARIKH_LUPUT, M.TEMPOH_LUPUT, JH.KOD_JENIS_HAKMILIK,  M.LOKASI,M.SYARAT_NYATA,M.SYARAT_KHAS,  M.SEKATAN_HAK,M.SEKATAN_KEPENTINGAN,M.NO_SYIT, JH.KETERANGAN AS JENIS_HAKMILIK, M.ID_KATEGORITANAH,  M.FLAG_AMBIL_SEGERA,D.NAMA_DAERAH,M.FLAG_BORANGL, M.STATUS_BORANGL,   M.TARIKH_TERIMA_HM, JH.STATUS_HAKMILIK,  M.FLAG_JENIS_RIZAB, M.NAMA_LAIN_RIZAB, M.NO_WARTA_RIZAB, M.TARIKH_WARTA_RIZAB, M.NO_SUBJAKET,   M.ID_PEGAWAI, M.ID_UNITLUASAMBIL_CONVERT, M.ID_UNITLUASLOT_CONVERT,  CASE  WHEN M.NO_LOT IS NOT NULL AND M.NO_PT IS NULL THEN M.NO_LOT  WHEN M.NO_LOT IS NULL AND   M.NO_PT IS NULL THEN LT.KETERANGAN || M.NO_PT  WHEN M.NO_LOT IS NULL AND M.NO_PT IS NOT NULL THEN  LT.KETERANGAN || M.NO_PT    WHEN M.NO_LOT IS NOT NULL AND M.NO_PT IS NOT NULL THEN LT.KETERANGAN || M.NO_PT || CHR(32) || CHR(40) || M.NO_LOT || CHR(41)  ELSE 'TIADA'  END AS NO_LOTPT, M.SEKSYEN    
 	FROM TBLPFDFAIL F, TBLPPTPERMOHONAN P, TBLRUJLOT LT
 	,(	SELECT PHM.ID_HAKMILIK, COUNT(HPB.ID_PIHAKBERKEPENTINGAN) AS TOTALPB  
 		FROM TBLPPTHAKMILIK PHM,  TBLPPTHAKMILIKPB HPB, TBLPPTPIHAKBERKEPENTINGAN PPB  
 		WHERE PHM.ID_HAKMILIK = HPB.ID_HAKMILIK 
 		AND HPB.ID_PIHAKBERKEPENTINGAN = PPB.ID_PIHAKBERKEPENTINGAN  
 		AND HPB.ID_JENISPB NOT IN (40, 41, 42)  
 		AND PHM.ID_PERMOHONAN = '412213'  GROUP BY PHM.ID_HAKMILIK
 	) TEMP_COUNTPB
 	, TBLRUJLUAS LS, TBLRUJMUKIM MK, TBLRUJDAERAH D, TBLRUJNEGERI N, TBLPPTHAKMILIK M, TBLRUJJENISHAKMILIK JH
 	, USERS U, USERS_INTERNAL UI   
 	WHERE M.ID_PERMOHONAN = P.ID_PERMOHONAN   
 	AND M.ID_NEGERI = N.ID_NEGERI   AND P.ID_FAIL = F.ID_FAIL   AND M.ID_DAERAH = D.ID_DAERAH  
	AND TEMP_COUNTPB.ID_HAKMILIK(+) = M.ID_HAKMILIK  AND LS.ID_LUAS(+) = M.ID_UNITLUASLOT    AND M.ID_JENISHAKMILIK = JH.ID_JENISHAKMILIK(+)  
 	AND M.ID_LOT = LT.ID_LOT(+)   AND M.ID_MUKIM = MK.ID_MUKIM(+)  AND NVL(M.FLAG_PEMBATALAN_KESELURUHAN,0) <> 'Y'    
 	AND NVL(M.FLAG_PENARIKAN_KESELURUHAN,0) <> 'Y'  AND P.ID_MASUK = U.USER_ID AND U.USER_ID = UI.USER_ID(+)  
 	AND P.ID_PERMOHONAN = '412213' 
 	)    
WHERE UPPER(NO_LOTPT) LIKE '%%'    
ORDER BY NAMA_MUKIM ASC, TARIKH_MASUK ASC, LPAD(NO_LOT,20) ASC, LPAD(NO_PT,20) ASC, LPAD(NO_LOTPT,20) ASC, LPAD(NO_SUBJAKET,20) ASC

SELECT M.NO_HAKMILIK 
,P.ID_MASUK
FROM TBLRUJMUKIM MK, TBLRUJDAERAH D, TBLRUJNEGERI N, TBLPPTHAKMILIK M
, TBLRUJJENISHAKMILIK JH,TBLRUJLUAS LS,TBLRUJLOT LT
,TBLPFDFAIL F, TBLPPTPERMOHONAN P
WHERE M.ID_NEGERI = N.ID_NEGERI AND  M.ID_DAERAH = D.ID_DAERAH AND M.ID_MUKIM = MK.ID_MUKIM
AND M.ID_JENISHAKMILIK = JH.ID_JENISHAKMILIK 
AND LS.ID_LUAS(+) = M.ID_UNITLUASLOT
AND M.ID_LOT = LT.ID_LOT(+)
AND M.ID_PERMOHONAN = P.ID_PERMOHONAN AND P.ID_FAIL = F.ID_FAIL
AND M.NO_HAKMILIK LIKE '%0091%'


SELECT * FROM USERS
WHERE USER_ID=16101379

--2020/07/13



 INFO [14/Jul/2020 06:29:36] (FrmPopupCapaianHakmilikeTanahData.java:246) sql=
 
 INSERT INTO TBLPPTHAKMILIK (ID_HAKMILIK, ID_PERMOHONAN, NO_HAKMILIK, NO_PT, ID_KATEGORITANAH, ID_JENISHAKMILIK, ID_NEGERI, ID_DAERAH, ID_MUKIM, ID_UNITLUASLOT, LUAS_LOT, CATATAN, SYARAT_NYATA, SEKATAN_KEPENTINGAN, PGNHM, ID_MASUK, TARIKH_MASUK)  
 VALUES (992069692, '412213', '00000091', '0000023', '1', '4', '4', '37', '135', '2', '0.9688', '', '-', '-', '040206GM00000091', '16101308',  SYSDATE ) 

SELECT * FROM TBLINTMAKLUMATANAH WHERE NO_RESIT = '202111601250030' AND ID_HAKMILIK = '040206GM00000091' AND ID_PERMOHONAN = '412213'

SELECT * FROM TBLPPTHAKMILIK
WHERE ID_HAKMILIK =992069692

SELECT * FROM TBLINTMAKLUMATANAH

--2020/04/27 - uat
-- 2020/04/22 local

--2020/05/28 LOCAL (ekptghq), UAT
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

INSERT INTO TBLINTWSCONFIG
(ID_CONFIG, KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES(3, 'E-TANAH', 'MyEtappPengambilanPort', 'myetapp', 'etanah123', 'http://kjsb.zapto.org:6009/etanahwsa/MyEtappPengambilanService?wsdl', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL);

SELECT * FROM TBLINTWSCONFIG

-- 2020/07/15
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

SELECT * FROM TBLINTMAKLUMATANAHOB

ALTER TABLE TBLINTMAKLUMATANAHOB ADD JENIS_PB VARCHAR2(5);
ALTER TABLE TBLINTMAKLUMATANAHOB ADD BA VARCHAR2(15);
ALTER TABLE TBLINTMAKLUMATANAHOB ADD BB VARCHAR2(15);


CREATE OR REPLACE TRIGGER INTMAKLUMATANAHOB_BI    
before insert on     TBLINTMAKLUMATANAHOB    for each row
begin    if :new.ID_MAKLUMATANAHOB   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMAKLUMATANAHOB_SEQ.NEXTVAL into :new.ID_MAKLUMATANAHOB          from dual;    end if;    end;

CREATE SEQUENCE TBLINTMAKLUMATANAHOB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

ALTER TABLE TBLINTMAKLUMATANAHOB ADD (
  CONSTRAINT INTMAKLUMATANAHOB_PK
 PRIMARY KEY
 (ID_MAKLUMATANAHOB));

CREATE TABLE TBLINTMAKLUMATANAHOB
(
  ID_MAKLUMATANAHOB             NUMBER                 NOT NULL,
  ID_HAKMILIK            VARCHAR2(30 BYTE)     NOT NULL,
  NAMA_OB                    VARCHAR2(100 BYTE),
  JENIS_KP                   VARCHAR2(5 BYTE),
  NO_KP_BARU                 VARCHAR2(12 BYTE),
  NO_KP_LAMA                 VARCHAR2(10 BYTE),
  NO_KP_LAIN                 VARCHAR2(30 BYTE),
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE INT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

--EKPTGHQUAT,MAC
ALTER TABLE TBLINTMAKLUMATANAH ADD BA_SIMATI VARCHAR2(15);
ALTER TABLE TBLINTMAKLUMATANAH ADD BB_SIMATI VARCHAR2(15);


-- 2020/07/13 uat (insert)
CREATE OR REPLACE TRIGGER INTMAKLUMATANAH_BI    
before insert on     TBLINTMAKLUMATANAH    for each row
begin    if :new.ID_MAKLUMATANAH    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTMAKLUMATANAH_SEQ.NEXTVAL into :new.ID_MAKLUMATANAH            from dual;    end if;    end;

-- 2020/07/13 uat (insert)
CREATE SEQUENCE INTMAKLUMATANAH_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE UNIQUE INDEX TBLINTMAKLUMATANAH_PK ON TBLINTMAKLUMATANAH
(ID_MAKLUMATANAH)
LOGGING
NOPARALLEL;

-- 2020/07/13 uat (insert)
ALTER TABLE TBLINTMAKLUMATANAH ADD (
  CONSTRAINT INTMAKLUMATANAH_PK
 PRIMARY KEY
 (ID_MAKLUMATANAH));

-- 2020/07/13 uat (insert)
CREATE TABLE TBLINTMAKLUMATANAH
(
  ID_MAKLUMATANAH             NUMBER                 NOT NULL,
  ID_PERMOHONAN    VARCHAR2(100 BYTE)     NOT NULL,
  ID_HAKMILIK            VARCHAR2(100 BYTE)     NOT NULL,
  ID_JENISHM             VARCHAR2(100 BYTE),
  ID_JENISPB             VARCHAR2(100 BYTE)     DEFAULT 1,
  ID_KATEGORI            VARCHAR2(100 BYTE),
  ID_DAERAH              VARCHAR2(100 BYTE),
  ID_LUAS                VARCHAR2(100 BYTE),
  ID_MUKIM               VARCHAR2(100 BYTE),
  ID_NEGERI              VARCHAR2(100 BYTE),
  CATATAN                VARCHAR2(1000 BYTE),
  NO_HAKMILIK            VARCHAR2(100 BYTE),
  NO_PT                  VARCHAR2(100 BYTE),
  NO_RESIT               VARCHAR2(100 BYTE)     NOT NULL,
  LUAS                   VARCHAR2(100 BYTE),
  LUAS_HMP               VARCHAR2(100 BYTE),
  JENIS_HTA              VARCHAR2(100 BYTE)     DEFAULT 'Y',
  JENIS_TANAH              VARCHAR2(100 BYTE),
  STATUS_PEMILIKAN       VARCHAR2(100 BYTE),
  GADAIAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_GADAIAN  VARCHAR2(100 BYTE),
  KAVEAT                 VARCHAR2(100 BYTE),
  NO_PERSERAHAN_KAVEAT   VARCHAR2(100 BYTE),
  PAJAKAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_PAJAKAN  VARCHAR2(100 BYTE),
  SYARAT_NYATA           VARCHAR2(1000 BYTE),
  SEKATAN                VARCHAR2(1000 BYTE),
  FLAG_AKTIF             VARCHAR2(1 BYTE)       DEFAULT 'Y',
  FLAG_DAFTAR            VARCHAR2(100 BYTE)     DEFAULT 1,
  FLAG_TERIMA            VARCHAR2(1 BYTE)       DEFAULT 'T',
  TARIKH_TERIMA          DATE,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE RUJ01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

SELECT * FROM INT_PPKHTA