-- 2020/03/30 change INT_WS_CONFIG (TBLINTWSCONFIG)

INSERT INTO TBLINTWSCONFIG
(ID_CONFIG, KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES(1, 'MT', 'MyeTaPPApplication', 'etpapi01', 'etpapi01', 'http://sit-ws.kehakiman.gov.my/sit/etapp?wsdl', 'ETP', NULL, NULL, 'Y', NULL, NULL, NULL, NULL);

INSERT INTO TBLINTWSCONFIG
(ID_CONFIG, KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES(2, 'MTREG', 'MyeTaPPApplication', 'etpapi01', 'etpapi01', 'http://sit-ws.kehakiman.gov.my/sit/etappCivilRegisterCase?wsdl', 'ETP', NULL, NULL, 'Y', NULL, NULL, NULL, NULL);


CREATE OR REPLACE TRIGGER TBLINTWSCONFIG_BI    
before insert on     TBLINTWSCONFIG    for each row
begin    if :new.ID_CONFIG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTWSCONFIG_SEQ.NEXTVAL into :new.ID_CONFIG   from dual; end if;    end;
/

CREATE SEQUENCE TBLINTWSCONFIG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLINTWSCONFIG;
CREATE TABLE TBLINTWSCONFIG(
  ID_CONFIG NUMBER(38),
  KOD VARCHAR2(100 BYTE),
  KETERANGAN VARCHAR2(250 BYTE),
  WS_USERNAME VARCHAR2(20 BYTE),
  WS_PASSWORD VARCHAR2(20 BYTE),
  WS_URL VARCHAR2(100 BYTE),
  ID_AGENSIID VARCHAR2(100 BYTE),
  CATATAN VARCHAR2(250 BYTE),
  FLAG_AKTIF VARCHAR(1 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLINTWSCONFIG_PK PRIMARY KEY (ID_CONFIG)
);

--ID (ID_CONFIG
,KOD,KETERANGAN,WS_USERNAME,WS_PASSWORD,WS_URL,ID_AGENSI
--ID_NEGERI
CATATAN,FLAG_AKTIF
ID_MASUK,TARIKH_MASUK,ID_KEMASKINI,TARIKH_KEMASKINI

select * FROM TBLINTWSCONFIG
