
--2020/10/16 - mac, uat(76) 

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'R', CAT_LUAS = 'Relong,Jemba,Kaki Persegi'
WHERE ID_JENISDOKUMEN=8;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'D', CAT_LUAS = 'Ekar, Depa'
WHERE ID_JENISDOKUMEN=7;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'P', CAT_LUAS = 'Ekar'
WHERE ID_JENISDOKUMEN=6;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'K', CAT_LUAS = 'Kaki Persegi'
WHERE ID_JENISDOKUMEN=5;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'E', CAT_LUAS = 'Ekar, Rode, Pole'
WHERE ID_JENISDOKUMEN=4;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'M', CAT_LUAS = 'Meter Persegi'
WHERE ID_JENISDOKUMEN=3;

UPDATE TBLINTRUJMAPPING
SET KOD_LUAS = 'H', CAT_LUAS = 'Hektar'
WHERE ID_JENISDOKUMEN=2;

--SELECT rowid,d.* FROM TBLINTRUJENISDOKUMEN d
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992001, 1, 'A', 'Pemberitahu Bahawa Tanah Mungkin Diambil', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992002, 2, 'B', 'Kuasa Masuk Dan Mengukur', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992003, 3, 'C', 'Akta Pengambilan Tanah, 1960', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992004, 4, 'D', 'Perisytiharaan Pengambilan Yang Dicadangkan', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992005, 5, 'K', 'Pemberitahu Bahawa Tanah Telah Diambil Milik', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992006, 6, 'I', 'Gambar Hakmilik', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992007, 7, 'SPU', 'Sijil Pengecualian Ukur', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992008, 8, 'MMKNe', 'Kertas Majlis Mesyuarat Kerajaan Negeri (MyeTaPP)', NULL, NULL, NULL, NULL);
INSERT INTO TBLINTRUJENISDOKUMEN
(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(992009, 9, 'SII', 'Surat Iringan ', NULL, NULL, NULL, NULL);
--INSERT INTO TBLINTRUJENISDOKUMEN
--(ID_INTJENISDOKUMEN, ID_JENISDOKUMEN, KOD_DOKUMENETANAH, CAT_DOKUMENETANAH, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
--VALUES(992002, 2, 'B', 'Kuasa Masuk Dan Mengukur', NULL, NULL, NULL, NULL);

--20201020 uat-76
ALTER TABLE TBLINTRUJMAPPING MODIFY  
KOD_DOKUMENETANAH VARCHAR2(15 BYTE)

ALTER TABLE TBLINTRUJMAPPING ADD  
CAT_LUAS VARCHAR2(15 BYTE)

ALTER TABLE TBLINTRUJMAPPING ADD  
KOD_LUAS VARCHAR2(2 BYTE)

ALTER TABLE TBLINTRUJMAPPING ADD (
  PRIMARY KEY
 (ID_INTJENISDOKUMEN));

--ALTER TABLE TBLINTRUJENISDOKUMEN RENAME TO TBLINTRUJMAPPING;

CREATE TABLE TBLINTRUJMAPPING
(
  ID_INTJENISDOKUMEN   NUMBER                      NOT NULL,
  ID_JENISDOKUMEN   NUMBER                      NOT NULL,
  KOD_DOKUMENETANAH VARCHAR2(15 BYTE)          ,
  CAT_DOKUMENETANAH          VARCHAR2(15 BYTE),
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE
)
-- 76
--TABLESPACE RUJ01 
--TABLESPACE RUJ
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

SELECT * FROM TBLINTRUJMAPPING

-- Mula v6.5
--2020/04/27 - uat
-- 2020/04/22 local



6+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


CREATE OR REPLACE TRIGGER TBLINTANAHPPT_BI    
before insert on     TBLINTANAHPPT    for each row
begin    if :new.ID_ETANAHPPT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTANAHPPT_SEQ.NEXTVAL into :new.ID_ETANAHPPT                from dual;    end if;    end;

--DROP SEQUENCE TBLINTANAHPPT_SEQ;
CREATE SEQUENCE TBLINTANAHPPT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
 ============================================================================

--ALTER TABLE TBLINTANAHPPT  DROP PRIMARY KEY CASCADE;
--DROP TABLE TBLINTANAHPPT CASCADE CONSTRAINTS;

CREATE TABLE TBLINTANAHPPT(
ID_ETANAHPPT  NUMBER CONSTRAINT TBLINTANAHPPT_C01 NOT NULL,
NO_PERMOHONAN       VARCHAR2(50 BYTE),
TARIKH_HANTAR DATE,
TARIKH_TERIMA DATE,
TARIKH_ENDORSAN DATE,
TARIKH_KEPUTUSAN DATE,
FLAG_URUSAN           VARCHAR2(2 BYTE),
KEPUTUSAN          VARCHAR2(20 BYTE),
CATATAN        VARCHAR2(500 BYTE),
TARIKH_MASUK DATE,
ID_MASUK NUMBER(16,0),
TARIKH_KEMASKINI DATE,
ID_KEMASKINI NUMBER(16,0),
CONSTRAINT TBLINTANAHPPT_PK PRIMARY KEY (ID_ETANAHPPT)
)
TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

5+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


CREATE OR REPLACE TRIGGER TBLINTANAHDOKUMENEND_BI    
before insert on     TBLINTANAHDOKUMENEND    for each row
begin    if :new.ID_DOKUMENENDORSAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTANAHDOKUMENEND_SEQ.NEXTVAL into :new.ID_DOKUMENENDORSAN                from dual;    end if;    end;
/

--DROP SEQUENCE TBLINTANAHDOKUMENEND_SEQ;
CREATE SEQUENCE TBLINTANAHDOKUMENEND_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
 ============================================================================

--ALTER TABLE TBLINTANAHDOKUMENEND  DROP PRIMARY KEY CASCADE;
--DROP TABLE TBLINTANAHDOKUMENEND CASCADE CONSTRAINTS;

CREATE TABLE TBLINTANAHDOKUMENEND(
  ID_DOKUMENENDORSAN  NUMBER CONSTRAINT TBLINTANAHDOKUMENEND_C01 NOT NULL,
  ID_PERMOHONAN       VARCHAR2(50 BYTE),
  FLAG_DOKUMEN        VARCHAR2(1 BYTE),
  NAMA_DOKUMEN        VARCHAR2(1000 BYTE),
  CONTENT             BLOB,
  JENIS_MIME          VARCHAR2(100 BYTE),
  	TARIKH_MASUK DATE,
  	ID_MASUK NUMBER(16,0),
 	TARIKH_KEMASKINI DATE,
  	ID_KEMASKINI NUMBER(16,0),
	CONSTRAINT TBLINTANAHDOKUMENEND_PK PRIMARY KEY (ID_DOKUMENENDORSAN)
)
TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN TBLINTANAHDOKUMENEND.FLAG_DOKUMEN IS '1=Borang D; 2=Warta Kerajaan Persekutuan; 3=Surat Iringan Borang D; 4=Jadual Bearing Distance & Coordinate; 5=Pelan Pengambilan Digital; 6=Surat Maklum; 7=Borang K; 8=Surat Iringan Borang K; 9=Borang D; 10=Warta Borang D; 11=Surat Iringan Batalkan Endorsan Borang D; 12=Warta Tarik Balik; 13=Surat Iringan Tarik Balik;';


 
4+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

SELECT * FROM TBLINTANAHDOKUMEN
 
  CREATE OR REPLACE TRIGGER TBLINTANAHDOKUMEN_BI    
before insert on     TBLINTANAHDOKUMEN   for each row
begin    if :new.ID_TANAHDOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTANAHDOKUMEN_SEQ.NEXTVAL into :new.ID_TANAHDOKUMEN          from dual;    end if;    end;
/

 ============================================================================
 
CREATE SEQUENCE TBLINTANAHDOKUMEN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  ============================================================================

  CREATE TABLE TBLINTANAHDOKUMEN (
    ID_TANAHDOKUMEN NUMBER NOT NULL ENABLE, 
	ID_RUJUKAN NUMBER, 
	ID_DOKUMEN NUMBER, 
  	TARIKH_MASUK DATE,
  	ID_MASUK NUMBER(16,0),
  	TARIKH_KEMASKINI DATE,
  	ID_KEMASKINI NUMBER(16,0),
	CONSTRAINT INTANAHDOKUMEN_PK PRIMARY KEY (ID_TANAHDOKUMEN)
 )TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


3+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CREATE OR REPLACE TRIGGER INTANAHPERMOHONANMILIKEND_BI    
before insert on     TBLINTANAHPERMOHONANMILIKEND    for each row
begin    if :new.ID_HAKMILIKENDORSAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTANAHPERMOHONANMILIKEND_SEQ.NEXTVAL into :new.ID_HAKMILIKENDORSAN                from dual;    end if;    end;
/

============================================================================
--DROP SEQUENCE INTANAHPERMOHONANMILIKEND_SEQ;

CREATE SEQUENCE INTANAHPERMOHONANMILIKEND_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

 ============================================================================

--ALTER TABLE TBLINTANAHPERMOHONANMILIKEND PRIMARY KEY CASCADE;
--DROP TABLE TBLINTANAHPERMOHONANMILIKEND CASCADE CONSTRAINTS;

CREATE TABLE TBLINTANAHPERMOHONANMILIKEND(
  ID_HAKMILIKENDORSAN    NUMBER CONSTRAINT INTANAHPERMOHONANMILIKEND_C01 NOT NULL,
  ID_PERMOHONAN          NUMBER,
  ID_HAKMILIK            NUMBER,
  ID_HAKMILIK_SAMBUNGAN  NUMBER,
	NO_PERMOHONAN          VARCHAR2(20 BYTE),
  KOD_NEGERI             VARCHAR2(50 BYTE),
  KOD_DAERAH             VARCHAR2(50 BYTE),
  KOD_MUKIM              VARCHAR2(50 BYTE),
  KOD_HAKMILIK           VARCHAR2(50 BYTE),
  NO_HAKMILIK            VARCHAR2(50 BYTE),
  KOD_LOT                VARCHAR2(50 BYTE),
  NO_LOT                 VARCHAR2(50 BYTE),
  NO_SEKSYEN             VARCHAR2(50 BYTE),
  KOD_LUAS_SAMBUNGAN     VARCHAR2(50 BYTE),
  LUAS_SAMBUNGAN         VARCHAR2(50 BYTE),
  NO_PERSERAHAN          VARCHAR2(50 BYTE),
  TARIKH_ENDORSAN        VARCHAR2(10 BYTE),
  MASA_ENDORSAN          VARCHAR2(10 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLINTANAHPERMOHONANMILIKEND PRIMARY KEY (ID_HAKMILIKENDORSAN)	
)
TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


2+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


CREATE OR REPLACE TRIGGER TBLINTANAHPERMOHONANMILIK_BI    
before insert on     TBLINTANAHPERMOHONANMILIK    for each row
begin    if :new.ID_PERMOHONANMILIK    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTANAHPERMOHONANMILIK_SEQ.NEXTVAL into :new.ID_PERMOHONANMILIK                from dual;    end if;    end;
/

============================================================================

--DROP SEQUENCE TBLINTANAHPERMOHONANMILIK_SEQ;
CREATE SEQUENCE TBLINTANAHPERMOHONANMILIK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
============================================================================

--ALTER TABLE TBLINTANAHPERMOHONANMILIK DROP PRIMARY KEY CASCADE;
--DROP TABLE TBLINTANAHPERMOHONANMILIK CASCADE CONSTRAINTS;
CREATE TABLE TBLINTANAHPERMOHONANMILIK(
  ID_PERMOHONANMILIK  NUMBER CONSTRAINT INTANAHPERMOHONANMILIK_C01 NOT NULL,
  ID_PERMOHONAN          NUMBER,
  ID_HAKMILIK            NUMBER,
  NO_PERMOHONAN          VARCHAR2(20 BYTE),
  KOD_NEGERI             VARCHAR2(50 BYTE),
  KOD_DAERAH             VARCHAR2(50 BYTE),
  KOD_MUKIM              VARCHAR2(50 BYTE),
  KOD_HAKMILIK           VARCHAR2(50 BYTE),
  NO_HAKMILIK            VARCHAR2(50 BYTE),
  KOD_LOT                VARCHAR2(50 BYTE),
  NO_LOT                 VARCHAR2(50 BYTE),
  NO_SEKSYEN             VARCHAR2(50 BYTE),
  KOD_LUAS_ASAL          VARCHAR2(50 BYTE),
  LUAS_ASAL              VARCHAR2(50 BYTE),
  KOD_LUAS_AMBIL         VARCHAR2(50 BYTE),
  LUAS_AMBIL             VARCHAR2(50 BYTE),
  NO_WARTA               VARCHAR2(50 BYTE),
  TARIKH_WARTA           DATE,
  TARIKH_BORANGK         DATE,
  STATUS_AMBIL           VARCHAR2(50 BYTE),
  NO_SUBJAKET            VARCHAR2(50 BYTE),
  SEBAB_PENARIKANBALIK   VARCHAR2(50 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLINTANAHPERMOHONANMILIK PRIMARY KEY (ID_PERMOHONANMILIK)	
)
TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


1+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


CREATE OR REPLACE TRIGGER INTANAHPERMOHONAN_BI    
before insert on     TBLINTANAHPERMOHONAN    for each row
begin    if :new.ID_PERMOHONANINT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTANAHPERMOHONAN_SEQ.NEXTVAL into :new.ID_PERMOHONANINT                from dual;    end if;    end;


--DROP SEQUENCE INTANAHPERMOHONAN_SEQ;
CREATE SEQUENCE INTANAHPERMOHONAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

-- X Run
ALTER TABLE INT_PPTPERMOHONAN
 ADD (NO_WARTA  VARCHAR2(200 BYTE));

ALTER TABLE INT_PPTPERMOHONAN
 ADD (TARIKH_WARTA  DATE);

  	COMMENT ON COLUMN TBLINTANAHPERMOHONAN.FLAG_URUSAN IS 
  	'A = MMK (SEK4); B = BORANG B/ WARTA;
	 C = MMK (SEK8); D = BORANG D/WARTA;
	 K = BORANG K; PD=PENARIKANBALIK BORANG D/WARTA;
	 S = SIJIL PEMBEBASAN UKUR, PU = PERMOHONAN UKUR;'

  	COMMENT ON COLUMN TBLINTANAHPERMOHONAN.NO_PERMOHONAN IS 'Rujukan ID_PERMOHONAN eTANAH';

--ALTER TABLE INT_PPTPERMOHONAN DROP PRIMARY KEY CASCADE;
--DROP TABLE TBLINTANAHPERMOHONAN CASCADE CONSTRAINTS;

	CREATE TABLE TBLINTANAHPERMOHONAN(
	  	ID_PERMOHONANINT         NUMBER CONSTRAINT INTANAH_PERMOHONAN_C01 NOT NULL,
	  	ID_PERMOHONAN         NUMBER ,
	  	NO_FAIL               VARCHAR2(50 BYTE),
	  	NO_JILID              VARCHAR2(50 BYTE),
	  	NAMA_KEMENTERIAN      VARCHAR2(500 BYTE),
	  	NAMA_PROJEK           VARCHAR2(4000 BYTE),
	  	TARIKH_HANTAR         DATE,
	  	TARIKH_TERIMA         DATE,
	  	FLAG_ENDORSAN         VARCHAR2(1 BYTE)        DEFAULT 'T',
	  	FLAG_HANTAR           VARCHAR2(1 BYTE)        DEFAULT 'T',
	  	FLAG_URUSAN           VARCHAR2(2 BYTE),
	  	FLAG_AKTIF            VARCHAR2(1 BYTE)        DEFAULT 'Y',
	  	FLAG_TRANSAKSI        VARCHAR2(1 BYTE)        DEFAULT 'Y',
	  	NO_PERMOHONAN         VARCHAR2(50 BYTE),
	 	KETERANGAN_TRANSAKSI  VARCHAR2(500 BYTE),
	  	ID_MASUK  NUMBER,
	  	ID_KEMASKINI NUMBER,
	  	TARIKH_MASUK  DATE,
	  	TARIKH_KEMASKINI DATE,
	  	CONSTRAINT TBLINTANAHPERMOHONAN PRIMARY KEY (ID_PERMOHONANINT)	
  	)
TABLESPACE ETAPP
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1K
            NEXT             1K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING


-- Tamat v6.5
-- Mula v6

DROP SEQUENCE INT_PPKRUJURUSAN_SEQ;

CREATE SEQUENCE INT_PPKRUJURUSAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

ALTER TABLE INT_PPKRUJURUSAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPKRUJURUSAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPKRUJURUSAN
(
  ID_URUSAN          NUMBER CONSTRAINT INT_PPKRUJURUSAN_C01 NOT NULL,
  KOD        VARCHAR2(3 BYTE),
  KETERANGAN        VARCHAR2(200 BYTE),
  KATEGORI_URUSAN        VARCHAR2(3 BYTE),
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE
)
TABLESPACE RUJ01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INT_PPKRUJURUSAN_PK ON INT_PPKRUJURUSAN
(ID_URUSAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPKRUJURUSAN_BI    
before insert on     INT_PPKRUJURUSAN    for each row
begin    if :new.ID_URUSAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPKRUJURUSAN_SEQ.NEXTVAL into :new.ID_URUSAN            from dual;    end if;    end;
/


ALTER TABLE INT_PPKRUJURUSAN ADD (
  CONSTRAINT INT_PPKRUJURUSAN_PK
 PRIMARY KEY
 (ID_URUSAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPKRUJURUSAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPKRUJURUSAN TO PPTMHQ;

ALTER TABLE INT_PPKRUJURUSAN
 ADD CONSTRAINT INT_PPKRUJURUSAN_PK
 PRIMARY KEY
 (ID_URUSAN);
 
UPDATE INT_PPKRUJURUSAN SET KETERANGAN = UPPER(KETERANGAN);
COMMIT;

ALTER TABLE int_ppkhakmilikperintah
 ADD (tarikh_hantar  DATE);
 
ALTER TABLE int_ppkhakmilikperintah
 ADD (flag_hantar  VARCHAR2(1 BYTE)                 DEFAULT 'T');
 
ALTER  TABLE int_ppkperintah DROP COLUMN tarikh_hantar;
ALTER TABLE int_ppkperintah DROP COLUMN flag_hantar;

ALTER TABLE int_ppkhta
MODIFY(gadaian VARCHAR2(4000 BYTE));


ALTER TABLE int_ppkhta
MODIFY(no_perserahan_gadaian VARCHAR2(4000 BYTE));


ALTER TABLE int_ppkhta
MODIFY(kaveat VARCHAR2(4000 BYTE));


ALTER TABLE int_ppkhta
MODIFY(no_perserahan_kaveat VARCHAR2(4000 BYTE));


ALTER TABLE int_ppkhta
MODIFY(pajakan VARCHAR2(4000 BYTE));


ALTER TABLE int_ppkhta
MODIFY(no_perserahan_pajakan VARCHAR2(4000 BYTE));


ALTER TABLE EKPTGHQTEST.INT_PPKPERINTAH
ADD (JENIS_PENGENALAN_PEMOHON VARCHAR2(50 BYTE));

DROP SEQUENCE INT_PPTDOKUMENENDORSAN_SEQ;

CREATE SEQUENCE INT_PPTDOKUMENENDORSAN_SEQ
  START WITH 5
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE INT_PPTDOKUMENENDORSAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPTDOKUMENENDORSAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPTDOKUMENENDORSAN
(
  ID_DOKUMENENDORSAN  NUMBER CONSTRAINT INT_PPTDOKUMENENDORSAN_C01 NOT NULL,
  ID_PERMOHONAN       VARCHAR2(50 BYTE),
  FLAG_DOKUMEN        VARCHAR2(1 BYTE),
  NAMA_DOKUMEN        VARCHAR2(1000 BYTE),
  CONTENT             BLOB,
  JENIS_MIME          VARCHAR2(100 BYTE)
)
TABLESPACE PFD01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          193M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  PFD01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE PFD01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INT_PPTDOKUMENENDORSAN.FLAG_DOKUMEN IS '1=Borang D; 2=Warta Kerajaan Persekutuan; 3=Surat Iringan Borang D; 4=Jadual Bearing Distance & Coordinate; 5=Pelan Pengambilan Digital; 6=Surat Maklum; 7=Borang K; 8=Surat Iringan Borang K; 9=Borang D; 10=Warta Borang D; 11=Surat Iringan Batalkan Endorsan Borang D; 12=Warta Tarik Balik; 13=Surat Iringan Tarik Balik;';


CREATE UNIQUE INDEX INT_PPTDOKUMENENDORSAN_PK ON INT_PPTDOKUMENENDORSAN
(ID_DOKUMENENDORSAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPTDOKUMENENDORSAN_BI    
before insert on     INT_PPTDOKUMENENDORSAN    for each row
begin    if :new.ID_DOKUMENENDORSAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPTDOKUMENENDORSAN_SEQ.NEXTVAL into :new.ID_DOKUMENENDORSAN                from dual;    end if;    end;
/


ALTER TABLE INT_PPTDOKUMENENDORSAN ADD (
  CONSTRAINT INT_PPTDOKUMENENDORSAN_PK
 PRIMARY KEY
 (ID_DOKUMENENDORSAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          32M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTDOKUMENENDORSAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTDOKUMENENDORSAN TO PPTMHQ;

DROP SEQUENCE INT_PPTDOKUMENPERMOHONAN_SEQ;

CREATE SEQUENCE INT_PPTDOKUMENPERMOHONAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE INT_PPTDOKUMENPERMOHONAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPTDOKUMENPERMOHONAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPTDOKUMENPERMOHONAN
(
  ID_DOKUMENPERMOHONAN  NUMBER CONSTRAINT INT_PPTDOKUMENPERMOHONAN_C01 NOT NULL,
  ID_PERMOHONAN         VARCHAR2(50 BYTE),
  FLAG_DOKUMEN          VARCHAR2(1 BYTE),
  NAMA_DOKUMEN          VARCHAR2(1000 BYTE),
  CONTENT               BLOB,
  JENIS_MIME            VARCHAR2(100 BYTE),
  KOD_DOKUMEN           VARCHAR2(4000 BYTE)
)
TABLESPACE PFD01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          193M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  PFD01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE PFD01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INT_PPTDOKUMENPERMOHONAN.FLAG_DOKUMEN IS '1=Borang D; 2=Warta Kerajaan Persekutuan; 3=Surat Iringan Borang D; 4=Jadual Bearing Distance & Coordinate; 5=Pelan Pengambilan Digital; 6=Surat Maklum; 7=Borang K; 8=Surat Iringan Borang K; 9=Borang D; 10=Warta Borang D; 11=Surat Iringan Batalkan Endorsan Borang D; 12=Warta Tarik Balik; 13=Surat Iringan Tarik Balik;';


CREATE UNIQUE INDEX INT_PPTDOKUMENPERMOHONAN_PK ON INT_PPTDOKUMENPERMOHONAN
(ID_DOKUMENPERMOHONAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPTDOKUMENPERMOHONAN_BI    
before insert on     INT_PPTDOKUMENPERMOHONAN    for each row
begin    if :new.ID_DOKUMENPERMOHONAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPTDOKUMENPERMOHONAN_SEQ.NEXTVAL into :new.ID_DOKUMENPERMOHONAN                from dual;    end if;    end;
/


ALTER TABLE INT_PPTDOKUMENPERMOHONAN ADD (
  CONSTRAINT INT_PPTDOKUMENPERMOHONAN_PK
 PRIMARY KEY
 (ID_DOKUMENPERMOHONAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          32M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTDOKUMENPERMOHONAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTDOKUMENPERMOHONAN TO PPTMHQ;

DROP SEQUENCE INT_PPTHAKMILIKENDORSAN_SEQ;

CREATE SEQUENCE INT_PPTHAKMILIKENDORSAN_SEQ
  START WITH 15
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE INT_PPTHAKMILIKENDORSAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPTHAKMILIKENDORSAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPTHAKMILIKENDORSAN
(
  ID_HAKMILIKENDORSAN    NUMBER CONSTRAINT INT_PPTHAKMILIKENDORSAN_C01 NOT NULL,
  ID_PERMOHONAN          VARCHAR2(50 BYTE),
  ID_HAKMILIK            VARCHAR2(50 BYTE),
  ID_HAKMILIK_SAMBUNGAN  VARCHAR2(50 BYTE),
  KOD_NEGERI             VARCHAR2(50 BYTE),
  KOD_DAERAH             VARCHAR2(50 BYTE),
  KOD_MUKIM              VARCHAR2(50 BYTE),
  KOD_HAKMILIK           VARCHAR2(50 BYTE),
  NO_HAKMILIK            VARCHAR2(50 BYTE),
  KOD_LOT                VARCHAR2(50 BYTE),
  NO_LOT                 VARCHAR2(50 BYTE),
  NO_SEKSYEN             VARCHAR2(50 BYTE),
  KOD_LUAS_SAMBUNGAN     VARCHAR2(50 BYTE),
  LUAS_SAMBUNGAN         VARCHAR2(50 BYTE),
  NO_PERSERAHAN          VARCHAR2(50 BYTE),
  TARIKH_ENDORSAN        VARCHAR2(10 BYTE),
  MASA_ENDORSAN          VARCHAR2(10 BYTE)
)
TABLESPACE PFD01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          193M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INT_PPTHAKMILIKENDORSAN_PK ON INT_PPTHAKMILIKENDORSAN
(ID_HAKMILIKENDORSAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPTHAKMILIKENDORSAN_BI    
before insert on     INT_PPTHAKMILIKENDORSAN    for each row
begin    if :new.ID_HAKMILIKENDORSAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPTHAKMILIKENDORSAN_SEQ.NEXTVAL into :new.ID_HAKMILIKENDORSAN                from dual;    end if;    end;
/


ALTER TABLE INT_PPTHAKMILIKENDORSAN ADD (
  CONSTRAINT INT_PPTHAKMILIKENDORSAN_PK
 PRIMARY KEY
 (ID_HAKMILIKENDORSAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          32M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTHAKMILIKENDORSAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTHAKMILIKENDORSAN TO PPTMHQ;

DROP SEQUENCE INT_PPTHAKMILIKPERMOHONAN_SEQ;

CREATE SEQUENCE INT_PPTHAKMILIKPERMOHONAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


ALTER TABLE INT_PPTHAKMILIKPERMOHONAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPTHAKMILIKPERMOHONAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPTHAKMILIKPERMOHONAN
(
  ID_HAKMILIKPERMOHONAN  NUMBER CONSTRAINT INT_PPTHAKMILIKPERMOHONAN_C01 NOT NULL,
  ID_PERMOHONAN          VARCHAR2(50 BYTE),
  ID_HAKMILIK            VARCHAR2(50 BYTE),
  KOD_NEGERI             VARCHAR2(50 BYTE),
  KOD_DAERAH             VARCHAR2(50 BYTE),
  KOD_MUKIM              VARCHAR2(50 BYTE),
  KOD_HAKMILIK           VARCHAR2(50 BYTE),
  NO_HAKMILIK            VARCHAR2(50 BYTE),
  KOD_LOT                VARCHAR2(50 BYTE),
  NO_LOT                 VARCHAR2(50 BYTE),
  NO_SEKSYEN             VARCHAR2(50 BYTE),
  KOD_LUAS_ASAL          VARCHAR2(50 BYTE),
  LUAS_ASAL              VARCHAR2(50 BYTE),
  KOD_LUAS_AMBIL         VARCHAR2(50 BYTE),
  LUAS_AMBIL             VARCHAR2(50 BYTE),
  NO_WARTA               VARCHAR2(50 BYTE),
  TARIKH_WARTA           DATE,
  TARIKH_BORANGK         DATE,
  STATUS_AMBIL           VARCHAR2(50 BYTE),
  NO_SUBJAKET            VARCHAR2(50 BYTE),
  SEBAB_PENARIKANBALIK   VARCHAR2(50 BYTE)
)
TABLESPACE PFD01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          193M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INT_PPTHAKMILIKPERMOHONAN_PK ON INT_PPTHAKMILIKPERMOHONAN
(ID_HAKMILIKPERMOHONAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPTHAKMILIKPERMOHONAN_BI    
before insert on     INT_PPTHAKMILIKPERMOHONAN    for each row
begin    if :new.ID_HAKMILIKPERMOHONAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPTHAKMILIKPERMOHONAN_SEQ.NEXTVAL into :new.ID_HAKMILIKPERMOHONAN                from dual;    end if;    end;
/


ALTER TABLE INT_PPTHAKMILIKPERMOHONAN ADD (
  CONSTRAINT INT_PPTHAKMILIKPERMOHONAN_PK
 PRIMARY KEY
 (ID_HAKMILIKPERMOHONAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          32M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTHAKMILIKPERMOHONAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTHAKMILIKPERMOHONAN TO PPTMHQ;

DROP SEQUENCE INT_PPTPERMOHONAN_SEQ;

CREATE SEQUENCE INT_PPTPERMOHONAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE INT_PPTPERMOHONAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE INT_PPTPERMOHONAN CASCADE CONSTRAINTS;

CREATE TABLE INT_PPTPERMOHONAN
(
  ID_PERMOHONAN         NUMBER CONSTRAINT INT_PPTPERMOHONAN_C01 NOT NULL,
  NO_FAIL               VARCHAR2(100 BYTE),
  NO_JILID              VARCHAR2(100 BYTE),
  NAMA_KEMENTERIAN      VARCHAR2(500 BYTE),
  NAMA_PROJEK           VARCHAR2(4000 BYTE),
  TARIKH_HANTAR         DATE,
  TARIKH_TERIMA         DATE,
  FLAG_ENDORSAN         VARCHAR2(1 BYTE)        DEFAULT 'T',
  FLAG_HANTAR           VARCHAR2(1 BYTE)        DEFAULT 'T',
  FLAG_URUSAN           VARCHAR2(5 BYTE),
  FLAG_AKTIF            VARCHAR2(1 BYTE)        DEFAULT 'Y',
  FLAG_TRANSAKSI        VARCHAR2(1 BYTE)        DEFAULT 'Y',
  KETERANGAN_TRANSAKSI  VARCHAR2(500 BYTE)
)
TABLESPACE PFD01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          193M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN INT_PPTPERMOHONAN.FLAG_URUSAN IS 'D=BORANG D/WARTA; K=BORANG K; PD=PENARIKANBALIK BORANG D/WARTA;';


CREATE UNIQUE INDEX INT_PPTPERMOHONAN_PK ON INT_PPTPERMOHONAN
(ID_PERMOHONAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER INT_PPTPERMOHONAN_BI    
before insert on     INT_PPTPERMOHONAN    for each row
begin    if :new.ID_PERMOHONAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INT_PPTPERMOHONAN_SEQ.NEXTVAL into :new.ID_PERMOHONAN                from dual;    end if;    end;
/


ALTER TABLE INT_PPTPERMOHONAN ADD (
  CONSTRAINT INT_PPTPERMOHONAN_PK
 PRIMARY KEY
 (ID_PERMOHONAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          32M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTPERMOHONAN TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON INT_PPTPERMOHONAN TO PPTMHQ;

ALTER TABLE INT_PPTPERMOHONAN
 ADD (NO_WARTA  VARCHAR2(200 BYTE));

ALTER TABLE INT_PPTPERMOHONAN
 ADD (TARIKH_WARTA  DATE);
 
