-- Mula 18/03/3020

 CREATE OR REPLACE TRIGGER TBLINTMTPENDAFTARANDOK_BI    
before insert on     TBLINTMTPENDAFTARANDOK   for each row
begin    if :new.ID_PENDAFTARANDOK   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMTPENDAFTARANDOK_SEQ.NEXTVAL into :new.ID_PENDAFTARANDOK          from dual;    end if;    end;
/

-- 
CREATE SEQUENCE TBLINTMTPENDAFTARANDOK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
 
  CREATE TABLE TBLINTMTPENDAFTARANDOK (
    ID_PENDAFTARANDOK NUMBER NOT NULL ENABLE, 
	ID_RUJUKAN NUMBER, 
	ID_DOKUMEN NUMBER, 
  	TARIKH_MASUK DATE,
  	ID_MASUK NUMBER(16,0),
  	TARIKH_KEMASKINI DATE,
  	ID_KEMASKINI NUMBER(16,0),
	CONSTRAINT INTMTPENDAFTARANDOK_PK PRIMARY KEY (ID_PENDAFTARANDOK)
 );

 CREATE OR REPLACE TRIGGER TBLINTMTLOCATIONMAP_BI    
before insert on     TBLINTMTLOCATIONMAP   for each row
begin    if :new.ID_LOCATIONMAP   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMTLOCATIONMAP_SEQ.NEXTVAL into :new.ID_LOCATIONMAP          from dual;    end if;    end;
/

-- 
CREATE SEQUENCE TBLINTMTLOCATIONMAP_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
 
  CREATE TABLE TBLINTMTLOCATIONMAP (
    ID_LOCATIONMAP NUMBER NOT NULL ENABLE, 
	ID_LOCATION NUMBER, 
	ID_PEJABAT NUMBER, 
  	TARIKH_MASUK DATE,
  	ID_MASUK NUMBER(16,0),
  	TARIKH_KEMASKINI DATE,
  	ID_KEMASKINI NUMBER(16,0),
	CONSTRAINT INTMTLOCATIONMAP_PK PRIMARY KEY (ID_LOCATIONMAP)
 );

 CREATE OR REPLACE TRIGGER TBLINTMTLOCATION_BI    
before insert on     TBLINTMTLOCATION   for each row
begin    if :new.ID_LOCATION   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMTLOCATION_SEQ.NEXTVAL into :new.ID_LOCATION          from dual;    end if;    end;
/

-- 
CREATE SEQUENCE TBLINTMTLOCATION_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

  CREATE TABLE TBLINTMTLOCATION (
    ID_LOCATION NUMBER NOT NULL ENABLE, 
	LOCATION NUMBER, 
	NAME VARCHAR2(50), 
	CODE VARCHAR2(5), 
	FLAG_AKTIF VARCHAR2(1) DEFAULT 'Y', 
  	TARIKH_MASUK DATE,
  	ID_MASUK NUMBER(16,0),
  	TARIKH_KEMASKINI DATE,
  	ID_KEMASKINI NUMBER(16,0),
	CONSTRAINT INTMTLOCATION_PK PRIMARY KEY (ID_LOCATION)
 );
-- Tamat 18/03/3020

-- 2020/04/13 (ekptghqfat)
-- 06/03/3020, run on ekptghqtest 
 CREATE OR REPLACE TRIGGER TBLINTMTPENDAFTARAN_BI    
before insert on     TBLINTMTPENDAFTARAN    for each row
begin    if :new.ID_PENDAFTARAN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMTPENDAFTARAN_SEQ.NEXTVAL into :new.ID_PENDAFTARAN          from dual;    end if;    end;
/
-- 06/03/3020
CREATE SEQUENCE TBLINTMTPENDAFTARAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

 -- 18/04/2020
 ALTER TABLE TBLINTMTPENDAFTARAN MODIFY JENIS_TRANSAKSI VARCHAR2(10);
ALTER TABLE TBLINTMTPENDAFTARAN ADD ID_RUJUKAN NUMBER;
referenceNo
 ALTER TABLE TBLINTMTPENDAFTARAN RENAME COLUMN KODPEJABAT TO KOD_MT;
ALTER TABLE TBLINTMTPENDAFTARAN MODIFY KOD_MT VARCHAR2(2);

-- 06/03/3020
  CREATE TABLE TBLINTMTPENDAFTARAN (
    ID_PENDAFTARAN NUMBER NOT NULL ENABLE, 
	ID_FAIL NUMBER, 
	NO_FAIL VARCHAR2(50), 
	NOKP_BARU VARCHAR2(15), 
	NOKP_LAMA VARCHAR2(50), 
	NOKP_LAIN VARCHAR2(50), 
	TARIKH_DAFTARKES DATE, 
	NO_KES VARCHAR2(200), 
	KODPEJABAT VARCHAR2(10), 
	JENIS_TRANSAKSI VARCHAR2(1), 
	CATATAN VARCHAR2(250), 
	TARIKH_HANTAR DATE, 
	FLAG_AKTIF VARCHAR2(1) DEFAULT 'Y', 
	ID_TRANSAKSI VARCHAR2(100), 
	ID_PENDAFTARANSTR VARCHAR2(20), 
  TARIKH_MASUK DATE,
  ID_MASUK NUMBER(16,0),
  TARIKH_KEMASKINI DATE,
  ID_KEMASKINI NUMBER(16,0),
CONSTRAINT INTMTPENDAFTARAN_PK PRIMARY KEY (ID_PENDAFTARAN)
 );
 
