
-- 2020/04/13 (ekptghqfat)
-- 06/03/3020, run on ekptghqtest 
 CREATE OR REPLACE TRIGGER TBLINTMTPENDAFTARAN_BI    
before insert on     TBLINTMTPENDAFTARAN    for each row
begin    if :new.ID_PENDAFTARAN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMTPENDAFTARAN_SEQ.NEXTVAL into :new.ID_PENDAFTARAN          from dual;    end if;    end;
/
-- 06/03/3020
CREATE SEQUENCE TBLINTMTPENDAFTARAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

-- 06/03/3020
  CREATE TABLE TBLINTMTPENDAFTARAN (
    ID_PENDAFTARAN NUMBER NOT NULL ENABLE, 
	ID_FAIL NUMBER, 
	NO_FAIL VARCHAR2(50), 
	NOKP_BARU VARCHAR2(15), 
	NOKP_LAMA VARCHAR2(50), 
	NOKP_LAIN VARCHAR2(50), 
	TARIKH_DAFTARKES DATE, 
	NO_KES VARCHAR2(200), 
	KODPEJABAT VARCHAR2(10), 
	JENIS_TRANSAKSI VARCHAR2(1), 
	CATATAN VARCHAR2(250), 
	TARIKH_HANTAR DATE, 
	FLAG_AKTIF VARCHAR2(1) DEFAULT 'Y', 
	ID_TRANSAKSI VARCHAR2(100), 
	ID_PENDAFTARANSTR VARCHAR2(20), 
  TARIKH_MASUK DATE,
  ID_MASUK NUMBER(16,0),
  TARIKH_KEMASKINI DATE,
  ID_KEMASKINI NUMBER(16,0),
CONSTRAINT INTMTPENDAFTARAN_PK PRIMARY KEY (ID_PENDAFTARAN)
 );
 
