ALTER TABLE TBLINTMACGDIHISTORY
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLINTMACGDIHISTORY CASCADE CONSTRAINTS;

CREATE TABLE TBLINTMACGDIHISTORY
(
  ID                 NUMBER,
  NAMA_LAPORAN       VARCHAR2(100 BYTE),
  USER_LOGIN         VARCHAR2(16 BYTE),
  TARIKH_CETAK       DATE,
  ID_SENARAILAPORAN  NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLINTMACGDIHISTORY_PK ON TBLINTMACGDIHISTORY
(ID)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLINTMACGDIHISTORY ADD (
  CONSTRAINT TBLINTMACGDIHISTORY_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;

DROP SEQUENCE TBLINTMACGDIHISTORY_SEQ;

CREATE SEQUENCE TBLINTMACGDIHISTORY_SEQ
  START WITH 357
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
ALTER TABLE TBLINTMACGDILAPORAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLINTMACGDILAPORAN CASCADE CONSTRAINTS;

CREATE TABLE TBLINTMACGDILAPORAN
(
  ID            NUMBER,
  NAMA_LAPORAN  VARCHAR2(100 BYTE),
  URUSAN        VARCHAR2(100 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLINTMACGDILAPORAN_PK ON TBLINTMACGDILAPORAN
(ID)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLINTMACGDILAPORAN ADD (
  CONSTRAINT TBLINTMACGDILAPORAN_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;
Insert into TBLINTMACGDILAPORAN
   (ID, NAMA_LAPORAN, URUSAN)
 Values
   (5, 'SENARAI KESELURUHAN PELESEN', 'APB');
Insert into TBLINTMACGDILAPORAN
   (ID, NAMA_LAPORAN, URUSAN)
 Values
   (1, 'Ringkasan Tanah Milik Persekutuan Mengikut Kementerian', 'HTP');
Insert into TBLINTMACGDILAPORAN
   (ID, NAMA_LAPORAN, URUSAN)
 Values
   (2, 'Ringkasan Tanah Milik Persekutuan Mengikut Negeri', 'HTP');
Insert into TBLINTMACGDILAPORAN
   (ID, NAMA_LAPORAN, URUSAN)
 Values
   (3, 'Ringkasan Tanah Rizab Persekutuan Mengikut Negeri', 'HTP');
Insert into TBLINTMACGDILAPORAN
   (ID, NAMA_LAPORAN, URUSAN)
 Values
   (4, 'Ringkasan Tanah Rizab Persekutuan Mengikut Kementerian', 'HTP');
COMMIT;
