---19112020
CREATE OR REPLACE TRIGGER "TBLINTANAHPERMOHONAN_BI" 
before insert on     TBLINTANAHPERMOHONAN   for each row
begin    if :new.ID_ETANAHPPT   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTETANAHPPT_SEQ.NEXTVAL into :new.ID_ETANAHPPT  
from dual;    end if;    end;

ALTER TABLE TBLINTRUJMAPPING ADD KOD_LAIN VARCHAR(2);

--2020/04/27 - uat
-- 2020/04/22 local

--2020/05/28 LOCAL (ekptghq), UAT
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

INSERT INTO TBLINTWSCONFIG
(ID_CONFIG, KOD, KETERANGAN, WS_USERNAME, WS_PASSWORD, WS_URL, WS_SOURCE, ID_AGENSIID, CATATAN, FLAG_AKTIF, ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI)
VALUES(3, 'E-TANAH', 'MyEtappPengambilanPort', 'myetapp', 'etanah123', 'http://kjsb.zapto.org:6009/etanahwsa/MyEtappPengambilanService?wsdl', NULL, NULL, NULL, 'Y', NULL, NULL, NULL, NULL);

SELECT * FROM TBLINTWSCONFIG

-- 2020/07/15
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

SELECT * FROM TBLINTMAKLUMATANAHOB

ALTER TABLE TBLINTMAKLUMATANAHOB ADD JENIS_PB VARCHAR2(5);
ALTER TABLE TBLINTMAKLUMATANAHOB ADD BA VARCHAR2(15);
ALTER TABLE TBLINTMAKLUMATANAHOB ADD BB VARCHAR2(15);


CREATE OR REPLACE TRIGGER INTMAKLUMATANAHOB_BI    
before insert on     TBLINTMAKLUMATANAHOB    for each row
begin    if :new.ID_MAKLUMATANAHOB   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLINTMAKLUMATANAHOB_SEQ.NEXTVAL into :new.ID_MAKLUMATANAHOB          from dual;    end if;    end;

CREATE SEQUENCE TBLINTMAKLUMATANAHOB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

ALTER TABLE TBLINTMAKLUMATANAHOB ADD (
  CONSTRAINT INTMAKLUMATANAHOB_PK
 PRIMARY KEY
 (ID_MAKLUMATANAHOB));

CREATE TABLE TBLINTMAKLUMATANAHOB
(
  ID_MAKLUMATANAHOB             NUMBER                 NOT NULL,
  ID_HAKMILIK            VARCHAR2(30 BYTE)     NOT NULL,
  NAMA_OB                    VARCHAR2(100 BYTE),
  JENIS_KP                   VARCHAR2(5 BYTE),
  NO_KP_BARU                 VARCHAR2(12 BYTE),
  NO_KP_LAMA                 VARCHAR2(10 BYTE),
  NO_KP_LAIN                 VARCHAR2(30 BYTE),
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE INT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

--EKPTGHQUAT,MAC
ALTER TABLE TBLINTMAKLUMATANAH ADD BA_SIMATI VARCHAR2(15);
ALTER TABLE TBLINTMAKLUMATANAH ADD BB_SIMATI VARCHAR2(15);


-- 2020/07/13 uat (insert)
CREATE OR REPLACE TRIGGER INTMAKLUMATANAH_BI    
before insert on     TBLINTMAKLUMATANAH    for each row
begin    if :new.ID_MAKLUMATANAH    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTMAKLUMATANAH_SEQ.NEXTVAL into :new.ID_MAKLUMATANAH            from dual;    end if;    end;

-- 2020/07/13 uat (insert)
CREATE SEQUENCE INTMAKLUMATANAH_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE UNIQUE INDEX TBLINTMAKLUMATANAH_PK ON TBLINTMAKLUMATANAH
(ID_MAKLUMATANAH)
LOGGING
NOPARALLEL;

-- 2020/07/13 uat (insert)
ALTER TABLE TBLINTMAKLUMATANAH ADD (
  CONSTRAINT INTMAKLUMATANAH_PK
 PRIMARY KEY
 (ID_MAKLUMATANAH));

-- 2020/07/13 uat (insert)
CREATE TABLE TBLINTMAKLUMATANAH
(
  ID_MAKLUMATANAH             NUMBER                 NOT NULL,
  ID_PERMOHONAN    VARCHAR2(100 BYTE)     NOT NULL,
  ID_HAKMILIK            VARCHAR2(100 BYTE)     NOT NULL,
  ID_JENISHM             VARCHAR2(100 BYTE),
  ID_JENISPB             VARCHAR2(100 BYTE)     DEFAULT 1,
  ID_KATEGORI            VARCHAR2(100 BYTE),
  ID_DAERAH              VARCHAR2(100 BYTE),
  ID_LUAS                VARCHAR2(100 BYTE),
  ID_MUKIM               VARCHAR2(100 BYTE),
  ID_NEGERI              VARCHAR2(100 BYTE),
  CATATAN                VARCHAR2(1000 BYTE),
  NO_HAKMILIK            VARCHAR2(100 BYTE),
  NO_PT                  VARCHAR2(100 BYTE),
  NO_RESIT               VARCHAR2(100 BYTE)     NOT NULL,
  LUAS                   VARCHAR2(100 BYTE),
  LUAS_HMP               VARCHAR2(100 BYTE),
  JENIS_HTA              VARCHAR2(100 BYTE)     DEFAULT 'Y',
  JENIS_TANAH              VARCHAR2(100 BYTE),
  STATUS_PEMILIKAN       VARCHAR2(100 BYTE),
  GADAIAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_GADAIAN  VARCHAR2(100 BYTE),
  KAVEAT                 VARCHAR2(100 BYTE),
  NO_PERSERAHAN_KAVEAT   VARCHAR2(100 BYTE),
  PAJAKAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_PAJAKAN  VARCHAR2(100 BYTE),
  SYARAT_NYATA           VARCHAR2(1000 BYTE),
  SEKATAN                VARCHAR2(1000 BYTE),
  FLAG_AKTIF             VARCHAR2(1 BYTE)       DEFAULT 'Y',
  FLAG_DAFTAR            VARCHAR2(100 BYTE)     DEFAULT 1,
  FLAG_TERIMA            VARCHAR2(1 BYTE)       DEFAULT 'T',
  TARIKH_TERIMA          DATE,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE RUJ01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

SELECT * FROM INT_PPKHTA