-- Mula v6.5
--2020/04/27 - uat
-- 2020/04/22 local

--2020/05/28 LOCAL ekptghq, UAT
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

CREATE OR REPLACE TRIGGER INTMAKLUMATANAH_BI    
before insert on     TBLINTMAKLUMATANAH    for each row
begin    if :new.ID_MAKLUMATANAH    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || INTMAKLUMATANAH_SEQ.NEXTVAL into :new.ID_MAKLUMATANAH            from dual;    end if;    end;

CREATE SEQUENCE INTMAKLUMATANAH_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE UNIQUE INDEX TBLINTMAKLUMATANAH_PK ON TBLINTMAKLUMATANAH
(ID_MAKLUMATANAH)
LOGGING
NOPARALLEL;

ALTER TABLE TBLINTMAKLUMATANAH ADD (
  CONSTRAINT INTMAKLUMATANAH_PK
 PRIMARY KEY
 (ID_MAKLUMATANAH));

CREATE TABLE TBLINTMAKLUMATANAH
(
  ID_MAKLUMATANAH             NUMBER                 NOT NULL,
  ID_PERMOHONAN    VARCHAR2(100 BYTE)     NOT NULL,
  ID_HAKMILIK            VARCHAR2(100 BYTE)     NOT NULL,
  ID_JENISHM             VARCHAR2(100 BYTE),
  ID_JENISPB             VARCHAR2(100 BYTE)     DEFAULT 1,
  ID_KATEGORI            VARCHAR2(100 BYTE),
  ID_DAERAH              VARCHAR2(100 BYTE),
  ID_LUAS                VARCHAR2(100 BYTE),
  ID_MUKIM               VARCHAR2(100 BYTE),
  ID_NEGERI              VARCHAR2(100 BYTE),
  CATATAN                VARCHAR2(1000 BYTE),
  NO_HAKMILIK            VARCHAR2(100 BYTE),
  NO_PT                  VARCHAR2(100 BYTE),
  NO_RESIT               VARCHAR2(100 BYTE)     NOT NULL,
  LUAS                   VARCHAR2(100 BYTE),
  LUAS_HMP               VARCHAR2(100 BYTE),
  JENIS_HTA              VARCHAR2(100 BYTE)     DEFAULT 'Y',
  JENIS_TANAH              VARCHAR2(100 BYTE),
  STATUS_PEMILIKAN       VARCHAR2(100 BYTE),
  GADAIAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_GADAIAN  VARCHAR2(100 BYTE),
  KAVEAT                 VARCHAR2(100 BYTE),
  NO_PERSERAHAN_KAVEAT   VARCHAR2(100 BYTE),
  PAJAKAN                VARCHAR2(100 BYTE),
  NO_PERSERAHAN_PAJAKAN  VARCHAR2(100 BYTE),
  SYARAT_NYATA           VARCHAR2(1000 BYTE),
  SEKATAN                VARCHAR2(1000 BYTE),
  FLAG_AKTIF             VARCHAR2(1 BYTE)       DEFAULT 'Y',
  FLAG_DAFTAR            VARCHAR2(100 BYTE)     DEFAULT 1,
  FLAG_TERIMA            VARCHAR2(1 BYTE)       DEFAULT 'T',
  TARIKH_TERIMA          DATE,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE INT01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;