====================================================================================================
===== 2017/05/05, Script update data aktif(1) atau tidak(0)
where id_suburusan=161064;update tblrujsuburusan
set flag_aktif='0'
where id_suburusan=161064;

====================================================================================================
===== 2017/05/05, Script add column bagi tujuan aktif atau tidak
--2017/ Run Staging inviroment, db staging
--2017/05/05 Run POC inviroment, db ekptg
ALTER TABLE TBLRUJSUBURUSAN
 ADD (FLAG_AKTIF  VARCHAR2(2)                       DEFAULT 1);


--aishahlatip 15052017
ALTER TABLE TBLRUJNEGERI
ADD (FLAG_CUTI NUMBER);

COMMENT ON COLUMN 
TBLRUJNEGERI.FLAG_CUTI IS 
'1:cuti jumaat sabtu 2:cuti sabtu ahad';

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 1
WHERE ID_NEGERI =1;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 1
WHERE ID_NEGERI =2;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 1
WHERE ID_NEGERI =3;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =4;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =5;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =6;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =7;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =8;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =9;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =10;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 1
WHERE ID_NEGERI =11;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =12;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =13;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =14;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =15;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =16;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =17;

UPDATE TBLRUJNEGERI
SET FLAG_CUTI = 2
WHERE ID_NEGERI =0;

--end aishahlatip add
 
