
/*open table baru pandangan undang-undang*/ 

CREATE SEQUENCE TBLPDTMESYUARATUTAMA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
/*ADD 01/03/2018 */  
ALTER TABLE TBLPDTMESYUARATUTAMA
ADD(ID_BAHAGIAN NUMBER);

--DROP TABLE TBLPDTMESYUARATUTAMA CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTMESYUARATUTAMA
(
  ID_MESYUARATUTAMA NUMBER(38),--SEQ
  TAJUK_MESYUARAT VARCHAR2(4000 BYTE),
  TAHUN NUMBER,
  BILANGAN NUMBER,
  FLAG_AKTIF VARCHAR2(1 BYTE), -- A:AKTIF T:TANGGUH
  ID_MESYUARATUTAMA_PREV NUMBER(38),--SEQ
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TBLPDTMESYUARATUTAMA ADD (
  CONSTRAINT TBLPDTMESYUARATUTAMA_PK
 PRIMARY KEY
 (ID_MESYUARATUTAMA));


--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTMESYUARATUTAMA_BI    
before insert on     TBLPDTMESYUARATUTAMA    for each row
begin    if :new.ID_MESYUARATUTAMA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTMESYUARATUTAMA_SEQ.NEXTVAL into :new.ID_MESYUARATUTAMA   from dual; end if;    end;
/


CREATE SEQUENCE TBLPDTMESYUARATCONTENT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLPDTMESYUARATCONTENT CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTMESYUARATCONTENT
(
  ID_MESYUARATCONTENT              NUMBER(38),--SEQ
  ID_MESYUARATUTAMA              NUMBER(38),--fk
  KETERANGAN           VARCHAR2(4000 BYTE),
  LAYER NUMBER,
  ID_REFER NUMBER(38),
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TBLPDTMESYUARATCONTENT ADD (
  CONSTRAINT TBLPDTMESYUARATCONTENT_PK
 PRIMARY KEY
 (ID_MESYUARATCONTENT));

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTMESYUARATCONTENT_BI    
before insert on     TBLPDTMESYUARATCONTENT    for each row
begin    if :new.ID_MESYUARATCONTENT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTMESYUARATCONTENT_SEQ.NEXTVAL into :new.ID_MESYUARATCONTENT   from dual; end if;    end;
/




CREATE SEQUENCE TBLPDTMESYUARATTINDAKAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


CREATE TABLE TBLPDTMESYUARATTINDAKAN
(
  ID_MESYUARATTINDAKAN              NUMBER(38),--SEQ
  ID_MESYUARATCONTENT              NUMBER(38),--fk
  ID_MESYUARATUTAMA              NUMBER(38),--fk
  BAHAGIAN           VARCHAR2(500 BYTE),
  EMEL           VARCHAR2(200 BYTE),
  CATATAN           VARCHAR2(4000 BYTE), 
  ID_STATUS NUMBER,--1 DALAM TINDAKAN, 2 MAKLUMAN, 3 SELESAI
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE, 
  COUNT_EMEL NUMBER,
  EMEL_ERROR VARCHAR2(4000 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TBLPDTMESYUARATTINDAKAN ADD (
  CONSTRAINT TBLPDTMESYUARATTINDAKAN_PK
 PRIMARY KEY
 (ID_MESYUARATTINDAKAN));

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTMESYUARATTINDAKAN_BI    
before insert on     TBLPDTMESYUARATTINDAKAN    for each row
begin    if :new.ID_MESYUARATTINDAKAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTMESYUARATTINDAKAN_SEQ.NEXTVAL into :new.ID_MESYUARATTINDAKAN   from dual; end if;    end;
/




CREATE SEQUENCE TBLPDTMESYUARATDOKUMEN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLPDTMESYUARATDOKUMEN CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTMESYUARATDOKUMEN
(
  ID_MESYUARATDOKUMEN              NUMBER(38),--SEQ
  ID_MESYUARATUTAMA              NUMBER(38),--fk
  CONTENT BLOB,
  NAMA_DOC VARCHAR(100),
  JENIS_MIME VARCHAR(100),  
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TBLPDTMESYUARATDOKUMEN ADD (
  CONSTRAINT TBLPDTMESYUARATDOKUMEN_PK
 PRIMARY KEY
 (ID_MESYUARATDOKUMEN));

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTMESYUARATDOKUMEN_BI    
before insert on     TBLPDTMESYUARATDOKUMEN    for each row
begin    if :new.ID_MESYUARATDOKUMEN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTMESYUARATDOKUMEN_SEQ.NEXTVAL into :new.ID_MESYUARATDOKUMEN   from dual; end if;    end;
/


/*new addition as 24/5/2017*/


ALTER TABLE TBLPDTMESYUARATUTAMA
   ADD
   (
   PIC  VARCHAR(500),
   EMEL_PIC  VARCHAR(100)
   );
   
   
ALTER TABLE
   TBLPDTMESYUARATUTAMA
MODIFY
   (
   EMEL_PIC varchar2(4000)
   );
   
ALTER TABLE
   TBLPDTMESYUARATTINDAKAN
MODIFY
   (
   EMEL varchar2(4000)
   );
   
ALTER TABLE TBLPDTMESYUARATUTAMA ADD (foo CLOB);
UPDATE TBLPDTMESYUARATUTAMA SET foo = EMEL_PIC;
ALTER TABLE TBLPDTMESYUARATUTAMA DROP COLUMN EMEL_PIC;
ALTER TABLE TBLPDTMESYUARATUTAMA RENAME COLUMN foo TO EMEL_PIC;

ALTER TABLE TBLPDTMESYUARATTINDAKAN ADD (foo CLOB);
UPDATE TBLPDTMESYUARATTINDAKAN SET foo = EMEL;
ALTER TABLE TBLPDTMESYUARATTINDAKAN DROP COLUMN EMEL;
ALTER TABLE TBLPDTMESYUARATTINDAKAN RENAME COLUMN foo TO EMEL;   
   



ALTER TABLE
   TBLPDTMESYUARATUTAMA
ADD
   (
   TEL_PIC varchar2(100)
   );
   
ALTER TABLE
   TBLPDTMESYUARATTINDAKAN
ADD
   (
   EMEL_CC CLOB
   )
   