
--2017/05/19 Run POC inviroment, db ekptg (ekptgc)  
DROP SEQUENCE TBLMINITTRANSAKSI_SEQ;

CREATE SEQUENCE TBLMINITTRANSAKSI_SEQ
  START WITH 14
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


DROP TABLE TBLMINITTRANSAKSI;

CREATE TABLE TBLMINITTRANSAKSI
(
  ID_MINITTRANSAKSI        NUMBER(38),
  MINIT_INSERT NUMBER(3),
  MINIT_UPDATE NUMBER(3),
  ID_TRANSAKSI        NUMBER(38),  
  ID_MASUK        NUMBER(38),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI       NUMBER(38),
  TARIKH_KEMASKINI      DATE
  )
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER TBLMINITTRANSAKSI_BI    
before insert on     TBLMINITTRANSAKSI    for each row
begin    if :new.ID_MINITTRANSAKSI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLMINITTRANSAKSI_SEQ.NEXTVAL into :new.ID_MINITTRANSAKSI   from dual; end if;    end;
/


DROP SEQUENCE TBLTRANSAKSI_SEQ;

CREATE SEQUENCE TBLTRANSAKSI_SEQ
  START WITH 18
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


DROP TABLE TBLTRANSAKSI;
  
CREATE TABLE TBLTRANSAKSI
(
  ID_TRANSAKSI        NUMBER(38),
  NAMA_AKTIVITI VARCHAR(1000),
  NAMA_TABLE VARCHAR(1000),
  QUERY_NOFAIL VARCHAR(4000),
  FIELD_CHECK VARCHAR(1000),
  ID_SEKSYEN        NUMBER(38),
  ID_MASUK        NUMBER(38),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI       NUMBER(38),
  TARIKH_KEMASKINI      DATE
  )
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER TBLTRANSAKSI_BI    
before insert on     TBLTRANSAKSI    for each row
begin    if :new.ID_TRANSAKSI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLTRANSAKSI_SEQ.NEXTVAL into :new.ID_TRANSAKSI   from dual; end if;    end;
/


CREATE SEQUENCE TBLLOGTRANSAKSI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLLOGTRANSAKSI;
CREATE TABLE TBLLOGTRANSAKSI
(
  ID_LOGTRANSAKSI        NUMBER(38),
  ID_TRANSAKSI NUMBER(38),
  VALUE_FIELD_CHECK VARCHAR(1000),
  TRANSAKSI_TYPE VARCHAR(1000),
  WAKTU_LOG DATE,
  ID_MASUK        NUMBER(38),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI       NUMBER(38),
  TARIKH_KEMASKINI      DATE
  )
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER TBLLOGTRANSAKSI_BI    
before insert on     TBLLOGTRANSAKSI    for each row
begin    if :new.ID_LOGTRANSAKSI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLLOGTRANSAKSI_SEQ.NEXTVAL into :new.ID_LOGTRANSAKSI   from dual; end if;    end;
/


CREATE SEQUENCE TBLPERMOHONANOT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLPERMOHONANOT;

CREATE TABLE TBLPERMOHONANOT
(
  ID_PERMOHONANOT        NUMBER(38),
  ID_PEMOHON NUMBER(38),
  ID_PELULUS NUMBER(38),
  TARIKH_MULA DATE,
  TARIKH_AKHIR DATE,
  TARIKH_MOHON DATE,
  TARIKH_LULUS DATE,
  CATATAN_PEMOHON VARCHAR(4000),
  CATATAN_PELULUS VARCHAR(4000),
  ID_STATUS NUMBER(38),
  NO_OT VARCHAR(100),
  FLAG_CUTI VARCHAR(1),
  ID_SEKSYEN NUMBER(38),
  ID_MASUK        NUMBER(38),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI       NUMBER(38),
  TARIKH_KEMASKINI      DATE
  )
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER TBLPERMOHONANOT_BI    
before insert on     TBLPERMOHONANOT    for each row
begin    if :new.ID_PERMOHONANOT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPERMOHONANOT_SEQ.NEXTVAL into :new.ID_PERMOHONANOT   from dual; end if;    end;
/


ALTER TABLE TBLMINITTRANSAKSI ADD (
  CONSTRAINT TBLMINITTRANSAKSI_PK
 PRIMARY KEY
 (ID_MINITTRANSAKSI)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


ALTER TABLE TBLLOGTRANSAKSI ADD (
  CONSTRAINT TBLLOGTRANSAKSI_PK
 PRIMARY KEY
 (ID_LOGTRANSAKSI)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
ALTER TABLE TBLTRANSAKSI ADD (
  CONSTRAINT TBLTRANSAKSI_PK
 PRIMARY KEY
 (ID_TRANSAKSI)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
ALTER TABLE TBLPERMOHONANOT ADD (
  CONSTRAINT TBLPERMOHONANOT_PK
 PRIMARY KEY
 (ID_PERMOHONANOT)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
                    

CREATE TABLE TBLRUJSEQESNOOT
(
  TAHUN       VARCHAR2(4 BYTE),
  ID_NEGERI   VARCHAR2(4 BYTE),
  KOD_MODUL   VARCHAR2(4 BYTE),
  NO_TURUTAN  NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


SET DEFINE OFF;
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16171, 'MAKLUMAT ASAS PERMOHONAN', 'TBLPPKPERMOHONAN', 'ID_PERMOHONAN', NULL, 
    NULL, 1, TO_DATE('03/29/2017 16:24:16', 'MM/DD/YYYY HH24:MI:SS'), 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16172, 'MAKLUMAT SENARAI SEMAK', 'TBLSEMAKANHANTAR', 'ID_PERMOHONAN', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16173, 'MAKLUMAT SIMATI', 'TBLPPKSIMATI', 'ID_SIMATI', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16174, 'MAKLUMAT PEMOHON', 'TBLPPKPEMOHON', 'ID_PEMOHON', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16175, 'MAKLUMAT PEGUAM', 'TBLPPKPEGUAM', 'ID_PEGUAM', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16176, 'MAKLUMAT WARIS, OB, SAKSI & PEMIUTANG', 'TBLPPKOB', 'ID_OB', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16177, 'MAKLUMAT HARTA TAK ALIH (ADA HAKMILIK & TIADA HAKMILIK)', 'TBLPPKHTA', 'ID_HTA', NULL, 
    NULL, 1, TO_DATE('03/29/2017 15:59:39', 'MM/DD/YYYY HH24:MI:SS'), 2, 'SELECT F.NO_FAIL,H.ID_HTA FROM TBLPPKHTA H, TBLPPKPERMOHONANSIMATI SM,TBLPPKPERMOHONAN P, TBLPFDFAIL F
WHERE H.ID_PERMOHONANSIMATI = SM.ID_PERMOHONANSIMATI AND SM.ID_PERMOHONAN = P.ID_PERMOHONAN 
AND P.ID_FAIL = F.ID_FAIL AND H.ID_HTA = ''999999'' AND ROWNUM < 1
');
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16178, 'MAKLUMAT KEPUTUSAN PERMOHONAN', 'TBLPPKKEPUTUSANPERMOHONAN', 'ID_KEPUTUSANPERMOHONAN', NULL, 
    NULL, 1, TO_DATE('03/29/2017 16:03:22', 'MM/DD/YYYY HH24:MI:SS'), 2, 'SELECT F.NO_FAIL FROM TBLPPKKEPUTUSANPERMOHONAN KP, TBLPPKPERMOHONAN P, TBLPFDFAIL F
WHERE KP.ID_PERMOHONAN = P.ID_PERMOHONAN AND P.ID_FAIL = F.ID_FAIL
AND KP.ID_KEPUTUSANPERMOHONAN = ''999999'' AND ROWNUM < 1');
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (16179, 'MAKLUMAT NOTIS PERBICARAAN', 'TBLPPKPERBICARAAN', 'ID_PERBICARAAN', NULL, 
    NULL, 1, TO_DATE('03/29/2017 16:05:08', 'MM/DD/YYYY HH24:MI:SS'), 2, 'SELECT F.NO_FAIL FROM TBLPPKKEPUTUSANPERMOHONAN KP, TBLPPKPERMOHONAN P, TBLPFDFAIL F, TBLPPKPERBICARAAN PBC
WHERE KP.ID_PERMOHONAN = P.ID_PERMOHONAN AND P.ID_FAIL = F.ID_FAIL 
AND PBC.ID_KEPUTUSANPERMOHONAN = KP.ID_KEPUTUSANPERMOHONAN
AND PBC.ID_PERBICARAAN = 11200 AND ROWNUM < 1');
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (161710, 'MAKLUMAT PENGHANTARAN NOTIS', 'TBLPPKNOTISOBMST', 'ID_NOTISOBMST', NULL, 
    NULL, 1, TO_DATE('03/27/2017 08:56:56', 'MM/DD/YYYY HH24:MI:SS'), 2, 'SELECT NO_FAIL FROM TBLPFDFAIL WHERE ID_FAIL = ''999999'' AND ROWNUM = 1');
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (161711, 'MAKLUMAT PERINTAH', 'TBLPPKPERINTAH', 'ID_PERINTAH', NULL, 
    NULL, NULL, NULL, 2, NULL);
Insert into TBLTRANSAKSI
   (ID_TRANSAKSI, NAMA_AKTIVITI, NAMA_TABLE, FIELD_CHECK, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, QUERY_NOFAIL)
 Values
   (161712, 'MAKLUMAT HARTA ALIH', 'TBLPPKHA', 'ID_HA', NULL, 
    NULL, 1, TO_DATE('03/29/2017 15:57:32', 'MM/DD/YYYY HH24:MI:SS'), 2, 'SELECT F.NO_FAIL FROM TBLPPKHA H, TBLPPKPERMOHONANSIMATI SM,TBLPPKPERMOHONAN P, TBLPFDFAIL F
WHERE H.ID_PERMOHONANSIMATI = SM.ID_PERMOHONANSIMATI AND SM.ID_PERMOHONAN = P.ID_PERMOHONAN 
AND P.ID_FAIL = F.ID_FAIL AND H.ID_HA = ''999999'' AND ROWNUM < 1');




SET DEFINE OFF;
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16174, 5, 2, 16177, 161723950, 
    TO_DATE('03/29/2017 19:42:18', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16176, 5, 2, 16179, 161723950, 
    TO_DATE('03/29/2017 19:43:16', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16179, 5, 2, 16174, 161723950, 
    TO_DATE('03/29/2017 19:44:01', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (161710, 5, 2, 16172, 161723950, 
    TO_DATE('03/29/2017 19:44:15', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (161713, 5, 2, 161711, 161723950, 
    TO_DATE('03/29/2017 19:45:06', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16171, 5, 2, 16171, NULL, 
    NULL, 161723950, TO_DATE('03/29/2017 19:42:41', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16173, 5, 2, 161712, 1, 
    TO_DATE('03/27/2017 09:25:32', 'MM/DD/YYYY HH24:MI:SS'), 161723950, TO_DATE('03/29/2017 19:42:55', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16175, 10, 2, 16178, 161723950, 
    TO_DATE('03/29/2017 19:42:30', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16177, 5, 2, 161710, 161723950, 
    TO_DATE('03/29/2017 19:43:28', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (16178, 5, 2, 16175, 161723950, 
    TO_DATE('03/29/2017 19:43:40', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (161711, 5, 2, 16173, 161723950, 
    TO_DATE('03/29/2017 19:44:29', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
Insert into TBLMINITTRANSAKSI
   (ID_MINITTRANSAKSI, MINIT_INSERT, MINIT_UPDATE, ID_TRANSAKSI, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (161712, 5, 2, 16176, 161723950, 
    TO_DATE('03/29/2017 19:44:54', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);



               
               