ALTER TABLE EKPTG.TBLPDTDOKUMEN
ADD (Tahun NUMBER(4));

//24/2/2017 

DROP TABLE EKPTG.TBLPDTRUJLAMPIRAN CASCADE CONSTRAINTS;

CREATE TABLE EKPTG.TBLPDTRUJLAMPIRAN
(
  ID_LAMPIRAN              NUMBER               NOT NULL,
  ID_DOKUMEN               NUMBER,
  CONTENT                  BLOB,
  NAMA_FAIL                VARCHAR2(100 BYTE),
  JENIS_MIME               VARCHAR2(100 BYTE),
  ID_PEKELILING            NUMBER,
  ID_MASUK                 NUMBER,
  TARIKH_MASUK             DATE,
  ID_KEMASKINI             NUMBER,
  TARIKH_KEMASKINI         DATE,
  ID_TBLPDTSENARAIDOKUMEN  NUMBER(16),
  ID_TBLPDTMESYUARAT       NUMBER(16),
  ID_JENISDOKUMEN          NUMBER(16)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  ETAPP01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE ETAPP01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EKPTG.TBLPDTRUJLAMPIRAN_INDX1 ON EKPTG.TBLPDTRUJLAMPIRAN
(ID_DOKUMEN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;





/*open table baru pandangan undang-undang*/ 

CREATE SEQUENCE TBLPDTPANDANGANUNDANGUTAMA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLPDTPANDANGANUNDANGUTAMA CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTPANDANGANUNDANGUTAMA
(
  ID_PANDANGANUNDANGUTAMA              NUMBER(38),--SEQ
  TAJUK           VARCHAR2(3800 BYTE),
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTPANDANGANUNDANGUTAMA_BI    
before insert on     TBLPDTPANDANGANUNDANGUTAMA    for each row
begin    if :new.ID_PANDANGANUNDANGUTAMA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTPANDANGANUNDANGUTAMA_SEQ.NEXTVAL into :new.ID_PANDANGANUNDANGUTAMA   from dual; end if;    end;
/


CREATE SEQUENCE TBLPDTPANDANGANUNDANG_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLPDTPANDANGANUNDANG CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTPANDANGANUNDANG
(
  ID_PANDANGANUNDANG              NUMBER(38),--SEQ
  ID_PANDANGANUNDANGUTAMA              NUMBER(38),--fk
  TAJUK           VARCHAR2(3800 BYTE),
  LAYER NUMBER,
  ID_REFER NUMBER(38),
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTPANDANGANUNDANG_BI    
before insert on     TBLPDTPANDANGANUNDANG    for each row
begin    if :new.ID_PANDANGANUNDANG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTPANDANGANUNDANG_SEQ.NEXTVAL into :new.ID_PANDANGANUNDANG   from dual; end if;    end;
/




CREATE SEQUENCE TBLPDTPANDANGANLAMPIRAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

--DROP TABLE TBLPDTPANDANGANLAMPIRAN CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTPANDANGANLAMPIRAN
(
  ID_PANDANGANLAMPIRAN              NUMBER(38),--SEQ
  ID_PANDANGANUNDANG              NUMBER(38),
  ID_PANDANGANUNDANGUTAMA              NUMBER(38),--fk
  CONTENT BLOB,
  NAMA_DOC VARCHAR(100),
  JENIS_MIME VARCHAR(100),  
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTPANDANGANLAMPIRAN_BI    
before insert on     TBLPDTPANDANGANLAMPIRAN    for each row
begin    if :new.ID_PANDANGANLAMPIRAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTPANDANGANLAMPIRAN_SEQ.NEXTVAL into :new.ID_PANDANGANLAMPIRAN   from dual; end if;    end;
/


ALTER TABLE
   TBLPDTPANDANGANLAMPIRAN
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- PANDANGANUNDANG/TANAHRIZAB
   );
   
   ALTER TABLE
   TBLPDTPANDANGANUNDANG
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- PANDANGANUNDANG/TANAHRIZAB
   );
   
   ALTER TABLE
   TBLPDTPANDANGANUNDANGUTAMA
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- PANDANGANUNDANG/TANAHRIZAB
   );

/*close table baru pandangan undang-undang*/ 
   
--  21/3/2017 
   ALTER TABLE TBLPDTPANDANGANUNDANGUTAMA
 ADD (ID_SEKSYEN  NUMBER);
 
 ALTER TABLE TBLPDTPANDANGANLAMPIRAN
 ADD (TARIKH_DAFTAR  DATE);

--9/1/2018
/*open table baru dokumen berkaitan tanah rizab melayu*/ 

CREATE SEQUENCE TBLPDTDOCTRMUTAMA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
--DROP TABLE TBLPDTDOCTRMUTAMA CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTDOCTRMUTAMA
(
  ID_DOCTRM NUMBER(38),--SEQ
  TAJUK VARCHAR2(3800 BYTE),
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTDOCTRMUTAMA_BI    
before insert on     TBLPDTDOCTRMUTAMA    for each row
begin    if :new.ID_DOCTRM    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTDOCTRMUTAMA_SEQ.NEXTVAL into :new.ID_DOCTRM   from dual; end if;    end;
/

CREATE SEQUENCE TBLPDTDOCTRM_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
--DROP TABLE TBLPDTDOCTRM CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTDOCTRM
(
  ID_DOCTRM NUMBER(38),--SEQ
  ID_DOCTRMUTAMA NUMBER(38),--fk
  TAJUK VARCHAR2(3800 BYTE),
  LAYER NUMBER,
  ID_REFER NUMBER(38),
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTDOCTRM_BI    
before insert on     TBLPDTDOCTRM    for each row
begin    if :new.ID_DOCTRM    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTDOCTRM_SEQ.NEXTVAL into :new.ID_DOCTRM   from dual; end if;    end;
/

CREATE SEQUENCE TBLPDTDOCTRMLAMPIRAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
--DROP TABLE TBLPDTDOCTRMLAMPIRAN CASCADE CONSTRAINTS;

CREATE TABLE TBLPDTDOCTRMLAMPIRAN
(
  ID_DOCTRMLAMPIRAN NUMBER(38),--SEQ
  ID_DOCTRM NUMBER(38),
  ID_DOCTRMUTAMA NUMBER(38),--fk
  CONTENT BLOB,
  NAMA_DOC VARCHAR(100),
  JENIS_MIME VARCHAR(100),  
  ID_MASUK NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK DATE,
  TARIKH_KEMASKINI DATE  
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--TRIGGER BARU PERMOHONAN ID PENGGUNA
CREATE OR REPLACE TRIGGER TBLPDTDOCTRMLAMPIRAN_BI    
before insert on     TBLPDTDOCTRMLAMPIRAN    for each row
begin    if :new.ID_DOCTRMLAMPIRAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTDOCTRMLAMPIRAN_SEQ.NEXTVAL into :new.ID_DOCTRMLAMPIRAN   from dual; end if;    end;
/

ALTER TABLE
   TBLPDTDOCTRMLAMPIRAN
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- TANAHRIZAB
   );
   
   ALTER TABLE
   TBLPDTDOCTRM
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- TANAHRIZAB
   );
   
   ALTER TABLE
   TBLPDTDOCTRMUTAMA
ADD
   (
   JENIS_AKTIVITI  VARCHAR(20) -- TANAHRIZAB
   );
   
   ALTER TABLE TBLPDTDOCTRMUTAMA
 ADD (ID_SEKSYEN  NUMBER);
 
 ALTER TABLE TBLPDTDOCTRMLAMPIRAN
 ADD (TARIKH_DAFTAR  DATE);
 
  ALTER TABLE TBLPDTDOCTRMUTAMA
 RENAME COLUMN ID_DOCTRM TO ID_DOCTRMUTAMA;

/*close table baru dokumen berkaitan tanah rizab melayu*/ 
 
/*Create table ruj skop/perkara 20.2.2018*/ 
 CREATE TABLE TBLRUJSKOP
(
  ID_SKOP          VARCHAR2(10 BYTE) CONSTRAINT TBLRUJSKOP NOT NULL,
  KOD_SKOP         VARCHAR2(2 BYTE),
  NAMA_SKOP        VARCHAR2(40 BYTE),
  ID_MASUK           VARCHAR2(10 BYTE),
  TARIKH_MASUK       DATE,
  ID_KEMASKINI      VARCHAR2(10 BYTE),
  TARIKH_KEMASKINI   DATE

);


CREATE SEQUENCE TBLRUJSKOP_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE OR REPLACE TRIGGER TBLRUJSKOP_BI    
before insert on     TBLRUJSKOP    for each row
begin    if :new.ID_SKOP    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLRUJSKOP_SEQ.NEXTVAL into :new.ID_SKOP            from dual;    end if;    end;
/
/*Create table ruj skop/perkara*/
