--25102019 ADD BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPKEHADIRANMESY
ADD EMAIL VARCHAR(200);
COMMIT;

--30102019 UPDATE BY AIN AT EKPTGHQTEST
UPDATE TBLRUJSTATUS
SET KETERANGAN = 'MAKLUMAT KELULUSAN KAJIAN'
WHERE ID_STATUS = 1610236;
COMMIT;

--30102019 UPDATE BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
  ADD (NO_FAIL_JMG VARCHAR(400),
      TARIKH_LULUS_JMG DATE,
      TARIKH_SURAT_JMG DATE,
      TARIKH_TERIMA_JMG DATE,
      KEPUTUSAN_JMG VARCHAR(1000),
      KUANTITI_PASIR NUMBER(26,10));
COMMIT;

--31102019 UPDATE BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
  ADD (ULASAN_PASIR VARCHAR(4000),
      ULASAN_HIDRAULIK VARCHAR(4000));
COMMIT;

--29012020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPRUJJENISTUJUAN ADD (
  FOREIGN KEY (ID_SUBURUSAN) 
 REFERENCES TBLRUJSUBURUSAN (ID_SUBURUSAN));
 
--30012020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPRUJJENISTUJUAN 
MODIFY(KETERANGAN VARCHAR2(500 BYTE));
COMMIT; 

ALTER TABLE TBLPHPRUJJENISTUJUAN 
MODIFY(KOD_JENISTUJUAN VARCHAR2(5 BYTE));
COMMIT; 

ALTER TABLE TBLPHPRUJJENISTUJUAN 
  ADD (CATATAN VARCHAR2(500 BYTE));
COMMIT; 
 
--05022020 UPDATE BY AIN AT EKPTGHQTEST--
KCREATE TABLE TBLPHPPERMOHONANTUJUAN
(
  ID_PHPPERMOHONANTUJUAN  NUMBER                NOT NULL,
  ID_PHPPERMOHONANSEWA    NUMBER,
  ID_JENISTUJUAN          NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)

ALTER TABLE TBLPHPPERMOHONANTUJUAN ADD (
  CONSTRAINT TBLPHPPERMOHONANTUJUAN_PK
 PRIMARY KEY
 (ID_PHPPERMOHONANTUJUAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
ALTER TABLE TBLPHPPERMOHONANTUJUAN ADD (
  FOREIGN KEY (ID_PHPPERMOHONANSEWA) 
 REFERENCES TBLPHPPERMOHONANSEWA (ID_PHPPERMOHONANSEWA),
  FOREIGN KEY (ID_JENISTUJUAN) 
 REFERENCES TBLPHPRUJJENISTUJUAN (ID_JENISTUJUAN));
 
--06022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPULASANTEKNIKAL
ADD JENIS_KADARSEWA VARCHAR2(2);
COMMIT;

--07022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE EKPTGHQTEST.TBLPHPLAPORANTANAH
ADD (CATATAN_PELAPOR VARCHAR2(100 BYTE));
COMMIT;
ALTER TABLE EKPTGHQTEST.TBLPHPLAPORANTANAH
ADD (CATATAN_PENYEMAK VARCHAR2(100 BYTE));
COMMIT;

--13022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPLOGTUGASAN RENAME COLUMN FLAG_MAKLUMAT_TAMBAHAN TO FLAG_PEMBETULAN;
COMMIT;

--26022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPPERJANJIAN
    ADD TEMPOH_DASAR VARCHAR(5);
    COMMIT;
    
--27022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPPERJANJIAN
    ADD JENIS_KADAR_SEWA VARCHAR2(1 BYTE);
    COMMIT;
    
--18032020 UPDATE BY AIN AT EKPTGHQ--
ALTER TABLE TBLPHPDOKUMEN
    ADD JENIS_IMEJ VARCHAR2(2 BYTE);
    COMMIT;
    
--30042020 UPDATE BY AIN AT EKPTGHQ LOCAL--  
ALTER TABLE TBLPHPPERMOHONANPELEPASAN
ADD FLAG_PERMOHONANDARI VARCHAR2(3);
COMMIT;

--19052020 UPDATE BY AIN AT EKPTGHQ LOCAL--  
ALTER TABLE TBLPHPPEMOHON
    MODIFY NO_PENGENALAN VARCHAR2(50);
    COMMIT;