--05/09/2020, ADD FIELD- EKPTGHQUAT--
ALTER TABLE TBLPHPPERMOHONANTUJUAN ADD TUJUAN_LAIN VARCHAR2(1000);

--01/09/2020, PLA V6 PP (en.Azhar)-- 
ALTER TABLE TBLPHPPERMOHONANSEWA MODIFY LUAS_ASAL NUMBER(15,5);

ALTER TABLE TBLPHPPERMOHONANSEWA MODIFY LUAS_MHN1 NUMBER(15,5);

ALTER TABLE TBLPHPPERMOHONANSEWA MODIFY LUAS_MHNBERSAMAAN NUMBER(15,5);

ALTER TABLE TBLPHPPERMOHONANSEWA MODIFY LUAS_MHN NUMBER(15,5);

ALTER TABLE TBLPHPPERMOHONANSEWA MODIFY LUAS_BAKI NUMBER(15,5);

--030820 MEMO
ALTER TABLE TBLPHPNOTISHASIL ADD FLAG_NOTIS VARCHAR2(4);

--SENARAI SEMAK
INSERT INTO TBLSEMAKANSENARAI
(ID_SEMAKANSENARAI, ID_SEMAKAN, ID_URUSAN, KOD_FORM, ATURAN, CATATAN, ID_SUBURUSAN, ID_KATEGORIPEMOHON, STATUS_DOKUMEN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(9920221, 191, 6, 'penawaran', 1, NULL, 32, NULL, NULL, NULL, TIMESTAMP '2020-07-16 00:00:00.000000', NULL, TIMESTAMP '2020-07-16 00:00:00.000000');
INSERT INTO TBLSEMAKANSENARAI
(ID_SEMAKANSENARAI, ID_SEMAKAN, ID_URUSAN, KOD_FORM, ATURAN, CATATAN, ID_SUBURUSAN, ID_KATEGORIPEMOHON, STATUS_DOKUMEN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(9920222, 192, 6, 'penawaran', 2, NULL, 32, NULL, NULL, NULL, TIMESTAMP '2020-07-16 00:00:00.000000', NULL, TIMESTAMP '2020-07-16 00:00:00.000000');

SELECT * FROM TBLSEMAKANSENARAI
WHERE KOD_FORM='penawaran'

INSERT INTO TBLSEMAKAN
(ID_SEMAKAN, ID_PARENT, KOD_SEMAK, PERIHAL, LAIN_LAIN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(191, NULL, 'L', 'Surat Permohonan Rasmi Daripada Kementerian', NULL, NULL, NULL, NULL, NULL);
INSERT INTO TBLSEMAKAN
(ID_SEMAKAN, ID_PARENT, KOD_SEMAK, PERIHAL, LAIN_LAIN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
VALUES(192, NULL, 'L', 'Pelan Pra-Hitungan (Jika Melibatkan Sebahagian Tanah)', NULL, NULL, NULL, NULL, NULL);

--25102019 ADD BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPKEHADIRANMESY
ADD EMAIL VARCHAR(200);
COMMIT;

--30102019 UPDATE BY AIN AT EKPTGHQTEST
UPDATE TBLRUJSTATUS
SET KETERANGAN = 'MAKLUMAT KELULUSAN KAJIAN'
WHERE ID_STATUS = 1610236;
COMMIT;

--30102019 UPDATE BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
  ADD (NO_FAIL_JMG VARCHAR(400),
      TARIKH_LULUS_JMG DATE,
      TARIKH_SURAT_JMG DATE,
      TARIKH_TERIMA_JMG DATE,
      KEPUTUSAN_JMG VARCHAR(1000),
      KUANTITI_PASIR NUMBER(26,10));
COMMIT;

--31102019 UPDATE BY AIN AT EKPTGHQTEST
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
  ADD (ULASAN_PASIR VARCHAR(4000),
      ULASAN_HIDRAULIK VARCHAR(4000));
COMMIT;

--29012020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPRUJJENISTUJUAN ADD (
  FOREIGN KEY (ID_SUBURUSAN)
 REFERENCES TBLRUJSUBURUSAN (ID_SUBURUSAN));

--30012020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPRUJJENISTUJUAN
MODIFY(KETERANGAN VARCHAR2(500 BYTE));
COMMIT;

ALTER TABLE TBLPHPRUJJENISTUJUAN
MODIFY(KOD_JENISTUJUAN VARCHAR2(5 BYTE));
COMMIT;

ALTER TABLE TBLPHPRUJJENISTUJUAN
  ADD (CATATAN VARCHAR2(500 BYTE));
COMMIT;

--05022020 UPDATE BY AIN AT EKPTGHQTEST--
CREATE TABLE TBLPHPPERMOHONANTUJUAN
(
  ID_PHPPERMOHONANTUJUAN  NUMBER                NOT NULL,
  ID_PHPPERMOHONANSEWA    NUMBER,
  ID_JENISTUJUAN          NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)

ALTER TABLE TBLPHPPERMOHONANTUJUAN ADD (
  CONSTRAINT TBLPHPPERMOHONANTUJUAN_PK
 PRIMARY KEY
 (ID_PHPPERMOHONANTUJUAN)
    USING INDEX
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TBLPHPPERMOHONANTUJUAN ADD (
  FOREIGN KEY (ID_PHPPERMOHONANSEWA)
 REFERENCES TBLPHPPERMOHONANSEWA (ID_PHPPERMOHONANSEWA),
  FOREIGN KEY (ID_JENISTUJUAN)
 REFERENCES TBLPHPRUJJENISTUJUAN (ID_JENISTUJUAN));

--06022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPULASANTEKNIKAL
ADD JENIS_KADARSEWA VARCHAR2(2);
COMMIT;

--07022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPLAPORANTANAH
ADD (CATATAN_PELAPOR VARCHAR2(100 BYTE));
COMMIT;
ALTER TABLE TBLPHPLAPORANTANAH
ADD (CATATAN_PENYEMAK VARCHAR2(100 BYTE));
COMMIT;

--13022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPLOGTUGASAN RENAME COLUMN FLAG_MAKLUMAT_TAMBAHAN TO FLAG_PEMBETULAN;
COMMIT;

--26022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPPERJANJIAN
    ADD TEMPOH_DASAR VARCHAR(5);
    COMMIT;

--27022020 UPDATE BY AIN AT EKPTGHQTEST--
ALTER TABLE TBLPHPPERJANJIAN
    ADD JENIS_KADAR_SEWA VARCHAR2(1 BYTE);
    COMMIT;

--18032020 UPDATE BY AIN AT EKPTGHQ--
ALTER TABLE TBLPHPDOKUMEN
    ADD JENIS_IMEJ VARCHAR2(2 BYTE);
    COMMIT;

--30042020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPPERMOHONANPELEPASAN
ADD FLAG_PERMOHONANDARI VARCHAR2(3);
COMMIT;

--19052020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPPEMOHON
    MODIFY NO_PENGENALAN VARCHAR2(50);
    COMMIT;

--28052020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPAKAUN
	ADD ID_KATEGORI_BAYARAN NUMBER;
    COMMIT;

--29052020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPRUJSENARAISEMAK
ADD (ID_URUSAN NUMBER);

ALTER TABLE TBLPHPRUJSENARAISEMAK
ADD CONSTRAINT ID_URUSAN
FOREIGN KEY
  (ID_URUSAN)
REFERENCES
  TBLRUJURUSAN
  (ID_URUSAN)
ENABLE
VALIDATE;
COMMIT;

--31052020 UPDATE BY AIN AT EKPTGHQ LOCAL--
UPDATE TBLRUJSTATUS
SET KETERANGAN = 'ULASAN MENTERI KATS'
WHERE ID_STATUS = '1610205';
COMMIT;

--03062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPRUJSENARAISEMAK
ADD (ID_SUBURUSAN NUMBER);

ALTER TABLE TBLPHPRUJSENARAISEMAK
ADD CONSTRAINT ID_SUBURUSAN
FOREIGN KEY
  (ID_SUBURUSAN)
REFERENCES
  TBLRUJSUBURUSAN
  (ID_SUBURUSAN)
ENABLE
VALIDATE;
COMMIT;

--10062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA
ADD (ID_JENISPERMOHONAN NUMBER);
COMMIT;

--10062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
SET DEFINE OFF;
Insert into TBLRUJKATEGORIPEMOHON
   (ID_KATEGORIPEMOHON, KOD_KATEGORIPEMOHON, KETERANGAN, ID_MASUK, TARIKH_MASUK,
    ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (10, '10', 'ORGANISASI', NULL, NULL,
    NULL, NULL);
COMMIT;

SET DEFINE OFF;
Insert into TBLRUJKATEGORIPEMOHON
   (ID_KATEGORIPEMOHON, KOD_KATEGORIPEMOHON, KETERANGAN, ID_MASUK, TARIKH_MASUK,
    ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (11, '11', 'BUKAN INDIVIDU', NULL, NULL,
    NULL, NULL);
COMMIT;

--10062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPPEMOHON
ADD (FLAG_INDIVIDU NUMBER)

COMMENT ON COLUMN
TBLPHPPEMOHON.FLAG_INDIVIDU IS
'1 = INDIVIDU; 2 = BUKAN INDIVIDU';
COMMIT;

--11062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA
ADD (ID_JENIS_LESEN NUMBER)

COMMENT ON COLUMN
TBLPHPPMOHONNJDUALPERTAMA.ID_JENIS_LESEN IS
'2=Borang 2;3=Borang 3;4=Borang 4';
COMMIT;

--12062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (NO_FAIL_JPS VARCHAR2(400 BYTE));
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (TARIKH_SURAT_JPS DATE);
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (TARIKH_TERIMA_JPS DATE);
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (KEPUTUSAN_JPS VARCHAR2(1000 BYTE));
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (TARIKH_LULUS_JPS DATE);
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (TEMPOH_AKHIR_LULUS_JPS NUMBER(2));
COMMIT;

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
ADD (TEMPOH_AKHIR_LULUS_JMG NUMBER(2));
COMMIT;
----------------------------------------

--26062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
SET DEFINE OFF;
Insert into ROLE
   (NAME, DESCRIPTION, THEME, ROLE_DETAILS)
 Values
   ('(PHP)UrusetiaMesyuarat', 'Urusetia Mesyuarat', 'eTapp_PHP.css', 'Urusetia Mesyuarat');
COMMIT;

--26062020 UPDATE BY AIN AT EKPTGHQ LOCAL--
SET DEFINE OFF;
Insert into MODULE
   (MODULE_ID, MODULE_TITLE, MODULE_CLASS, MODULE_GROUP, MODULE_DESCRIPTION,
    ID_MASUK, ID_KEMASKINI, TARIKH_MASUK, TARIKH_KEMASKINI, MODULE_VERSION)
 Values
   ('ekptg.view.php2.FrmPHPMesyuaratDashboard', 'Urusetia Dashboard', 'ekptg.view.php2.FrmPHPMesyuaratDashboard', 'EKPTG - PHP', NULL,
    10101144, NULL, TO_DATE('06/26/2020 11:59:36', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL);
COMMIT;

--data tblphprujsenaraisemak--
CREATE TABLE TBLPHPRUJSENARAISEMAK
(
  ID_RUJSENARAISEMAK  NUMBER(16),
  ID_KATEGORIPEMOHON  NUMBER(16),
  KOD_SENARAISEMAK    NUMBER(16),
  KETERANGAN          VARCHAR2(200 BYTE),
  ID_MASUK            NUMBER(16),
  TARIKH_MASUK        DATE,
  ID_KEMASKINI        NUMBER(16),
  TARIKH_KEMASKINI    DATE,
  FLAG_AKTIF          VARCHAR2(1 BYTE)          DEFAULT 'Y',
  ID_KATEGORI_SS      VARCHAR2(1 BYTE)          DEFAULT '1',
  ID_URUSAN           NUMBER,
  ID_SUBURUSAN        NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE INDEX TBLPHPRUJSENARAISEMAK_IDX1 ON TBLPHPRUJSENARAISEMAK
(ID_KATEGORIPEMOHON)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

ALTER TABLE TBLPHPRUJSENARAISEMAK ADD (
  CONSTRAINT TBLPHPRUJSENARAISEMAK_PK
 PRIMARY KEY
 (ID_RUJSENARAISEMAK)
    USING INDEX
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TBLPHPRUJSENARAISEMAK ADD (
  CONSTRAINT TBLPHPRUJSENARAISEMAK_FK1
 FOREIGN KEY (ID_KATEGORIPEMOHON)
 REFERENCES TBLRUJKATEGORIPEMOHON (ID_KATEGORIPEMOHON),
  CONSTRAINT ID_URUSAN
 FOREIGN KEY (ID_URUSAN)
 REFERENCES TBLRUJURUSAN (ID_URUSAN),
  CONSTRAINT ID_SUBURUSAN
 FOREIGN KEY (ID_SUBURUSAN)
 REFERENCES TBLRUJSUBURUSAN (ID_SUBURUSAN));

--05072020 UPDATE BY AIN AT EKPTGHQ LOCAL--
CREATE TABLE TBLPHPMESYUARATPERMOHONAN
(
  ID_MESYUARAT_PERMOHONAN  NUMBER(16)           NOT NULL,
  ID_PERMOHONAN            NUMBER(16),
  FLAG_SYOR                VARCHAR2(1 BYTE),
  ID_MASUK                 NUMBER(16),
  TARIKH_MASUK             DATE,
  ID_KEMASKINI             NUMBER(16),
  TARIKH_KEMASKINI         DATE,
  ID_MESYUARAT             NUMBER,
  CATATAN                  VARCHAR2(1000 BYTE),
  FLAG_JENIS_PERMOHONAN    VARCHAR2(2 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP SEQUENCE TBLPHPRUJMESYUARAT_SEQ;
CREATE SEQUENCE TBLPHPMESYUARATPERMOHONAN_SEQ
  START WITH 1000000
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER TBLPHPMESYUARATPERMOHONAN_BI
before insert on     TBLPHPMESYUARATPERMOHONAN    for each row
begin    if :new.ID_MESYUARAT_PERMOHONAN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPHPMESYUARATPERMOHONAN_SEQ.NEXTVAL into :new.ID_MESYUARAT_PERMOHONAN
from dual;    end if;    end;

INSERT INTO TBLPHPMESYUARATPERMOHONAN (
   ID_PERMOHONAN, FLAG_SYOR,
   ID_MESYUARAT, CATATAN)
SELECT ID_PERMOHONAN, FLAG_SYOR, ID_MESYUARAT, CATATAN FROM TBLPHPMESYUARAT;

ALTER TABLE TBLPHPMESYUARAT
RENAME COLUMN FLAG_SYOR TO STATUS_MESYUARAT;

ALTER TABLE TBLPHPMESYUARAT DROP COLUMN ID_PERMOHONAN;

COMMENT ON COLUMN TBLPHPMESYUARAT.STATUS_MESYUARAT IS '1 = BARU; 2= SELESAI; 3 = BATAL';

INSERT INTO TBLPHPMESYUARATPERMOHONAN (
   ID_PERMOHONAN, FLAG_SYOR,
   ID_MESYUARAT, CATATAN)
SELECT ID_PERMOHONAN, FLAG_SYOR, ID_MESYUARAT, CATATAN FROM TBLPHPMESYUARAT;

ALTER TABLE TBLPHPMESYUARAT
 ADD (ID_URUSAN  NUMBER);
COMMIT;

UPDATE TBLRUJSUBURUSAN
SET FLAG_AKTIF = 0
WHERE ID_SUBURUSAN IN (1613116, 1613119, 37, 26);
COMMIT;

UPDATE TBLRUJURUSAN
SET FLAG_AKTIF = 0
WHERE ID_SUBURUSAN IN (1613116, 1613119);
COMMIT;

SET DEFINE OFF;
Insert into TBLRUJSUBURUSAN
   (ID_SUBURUSAN, ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK,
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB,
    FLAG_AKTIF)
 Values
   (9920124, 7, '04', 'PAPAN IKLAN', 1,
    TO_DATE('07/10/2020 17:47:10', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 4, NULL,
    '1');
COMMIT;

SET DEFINE OFF;
Insert into TBLRUJSUBURUSAN
   (ID_SUBURUSAN, ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK,
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB,
    FLAG_AKTIF)
 Values
   (9920125, 12, '09', 'KELAPA', NULL,
    NULL, NULL, NULL, 4, NULL,
    '1');
Insert into TBLRUJSUBURUSAN
   (ID_SUBURUSAN, ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK,
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB,
    FLAG_AKTIF)
 Values
   (9920126, 12, '10', 'BUAH - BUAHAN', NULL,
    NULL, NULL, NULL, 4, NULL,
    '1');
Insert into TBLRUJSUBURUSAN
   (ID_SUBURUSAN, ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK,
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB,
    FLAG_AKTIF)
 Values
   (9920127, 12, '11', 'KOKO', NULL,
    NULL, NULL, NULL, 4, NULL,
    '1');
Insert into TBLRUJSUBURUSAN
   (ID_SUBURUSAN, ID_URUSAN, KOD_SUBURUSAN, NAMA_SUBURUSAN, ID_MASUK,
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_SEKSYEN, KOD_SUBURUSAN_ARKIB,
    FLAG_AKTIF)
 Values
   (9920128, 12, '12', 'KOPI', NULL,
    NULL, NULL, NULL, 4, NULL,
    '1');
COMMIT;

 --rozai add untuk apb--20/07/2020
 CREATE TABLE TBLINTPHPDOKUMENRUJUKAN
(
  ID                    NUMBER,
  NAMA_DOKUMEN_RUJUKAN  VARCHAR2(100 BYTE),
  URUSAN                VARCHAR2(100 BYTE)
)
TABLESPACE PHP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

SET DEFINE OFF;
Insert into TBLINTPHPDOKUMENRUJUKAN
   (ID, NAMA_DOKUMEN_RUJUKAN, URUSAN)
 Values
   (1, 'Senarai Rujukan SOP', 'APB');
Insert into TBLINTPHPDOKUMENRUJUKAN
   (ID, NAMA_DOKUMEN_RUJUKAN, URUSAN)
 Values
   (2, 'Pekeliling', 'APB');
Insert into TBLINTPHPDOKUMENRUJUKAN
   (ID, NAMA_DOKUMEN_RUJUKAN, URUSAN)
 Values
   (3, 'Warta', 'APB');
Insert into TBLINTPHPDOKUMENRUJUKAN
   (ID, NAMA_DOKUMEN_RUJUKAN, URUSAN)
 Values
   (4, 'Akta dan Lain-lain', 'APB');
COMMIT;

 ALTER TABLE TBLPHPDOKUMEN
 ADD (id_dokumen_rujukan  NUMBER);
 
--05082020 UPDATE BY AIN AT EKPTGHQ LOCAL--
UPDATE TBLRUJSTATUS
SET KETERANGAN = 'ULASAN MENTERI KeTSA'
WHERE ID_STATUS = 1610205;
COMMIT;

--CREATE BY YATI--
ALTER TABLE TBLPHPPERMOHONANSEWA 
ADD ID_PERMOHONANLAMA NUMBER;

ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA 
ADD ID_PERMOHONANLAMA NUMBER;
COMMIT;

-- Add by Ain for Ulasan MOF 09/09/2020 (EKPTGHQUAT) --
ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
ADD (NAMA_PEGAWAI VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
ADD (NO_TELEFON_PEGAWAI NUMBER);
COMMIT;

--10/9/2020--rozai add
ALTER TABLE TBLPHPMESYUARATPERMOHONAN 
ADD (FLAG_JENIS_PERMOHONAN VARCHAR2(2 BYTE));
COMMIT;

--Add by Ain for Modul Penguatkuasaan 13/09/2020--
ALTER TABLE TBLPHPPERMOHONANKUATKUASA
MODIFY(LAIN_JNS_CEROBOH VARCHAR2(1000 BYTE));

ALTER TABLE TBLPHPPERMOHONANKUATKUASA
MODIFY(LOKASI VARCHAR2(1000 BYTE));

ALTER TABLE TBLPHPPERMOHONANKUATKUASA
MODIFY(KETERANGAN_ADUAN VARCHAR2(1000 BYTE));

ALTER TABLE TBLPHPPERMOHONANKUATKUASA
MODIFY(AKTIVITI VARCHAR2(1000 BYTE));
COMMIT;

--15/9/2020--rozai add
ALTER TABLE TBLPHPMESYUARAT
ADD (ID_SUBURUSAN NUMBER);
COMMIT;

--22/9/2020--rozai add
ALTER TABLE TBLPHPMESYUARATPERMOHONAN
ADD (CATATAN_RINGKASAN_PERTIMBANGAN VARCHAR2(500 BYTE));