ALTER TABLE TBLPHPFAILAPBBERTINDIH
MODIFY(NAMA_SYARIKAT_TINDIH VARCHAR2(200 BYTE));

ALTER TABLE TBLPHPFAILAPBBERTINDIH
MODIFY(BERTINDIH_DENGAN_NOFAIL VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(NO_FAIL_JAS VARCHAR2(400 BYTE));

ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(NO_FAIL_PHN VARCHAR2(400 BYTE));

ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA
 ADD (TEMPOH_DILULUSKAN  NUMBER(2));
 
 ALTER TABLE TBLPHPPEMOHON
 ADD (CATATAN  VARCHAR2(1000 BYTE));

 ALTER TABLE TBLPHPHASIL
 ADD (CATATAN_TANAH  VARCHAR2(1000 BYTE));
    
CREATE OR REPLACE FORCE VIEW V_MAKLUMATTNH_DAN_LAPORANTNH (ID_MUKIM,
                                                           KOD_LOT,
                                                           NO_LOT,
                                                           ID_PERMOHONAN,
                                                           ID_FAIL,
                                                           NO_FAIL,
                                                           TAJUK_FAIL,
                                                           STATUS,
                                                           NAMA_URUSAN,
                                                           KOD_URUSAN,
                                                           MODULE_CLASS_DAFTARPMHNN,
                                                           KEPUTUSAN,
                                                           MODULE_CLASS_KEPUTUSAN,
                                                           TARIKH_KEPUTUSAN,
                                                           ID_LAPORANTANAH,
                                                           NAMA_PELAPOR
                                                          )
AS
   (SELECT C.ID_MUKIM, H.KETERANGAN AS KOD_LOT, C.NO_LOT, A.ID_PERMOHONAN,
           A.ID_FAIL, E.NO_FAIL, E.TAJUK_FAIL, F.KETERANGAN AS STATUS,
           G.NAMA_SUBURUSAN AS NAMA_URUSAN, G.ID_SUBURUSAN AS KOD_URUSAN,
           DECODE
              (G.ID_SUBURUSAN,
               '32', 'view.php2.FrmPNWMaklumatPermohonanView',
               '33', 'view.php2.FrmTKRMaklumatPermohonanView',
               '34', 'view.php2.FrmPLPMaklumatPermohonanView'
              ) MODULE_CLASS_DAFTARPMHNN,
           DECODE (I.KEPUTUSAN,
                   'L', 'LULUS',
                   'LB', 'LULUS BERSYARAT',
                   'T', 'TOLAK',
                   'Tiada Keputusan'
                  ) KEPUTUSAN,
           DECODE
               (G.ID_SUBURUSAN,
                '32', 'view.php2.FrmPNWKeputusanView',
                '33', 'view.php2.FrmTKRKeputusanView',
                '34', 'view.php2.FrmPLPKeputusanView'
               ) MODULE_CLASS_KEPUTUSAN,
           I.TARIKH_KEPUTUSAN, D.ID_LAPORANTANAH, D.NAMA_PELAPOR
      FROM TBLPERMOHONAN A,
           TBLPHPHAKMILIKPERMOHONAN B,
           TBLPHPHAKMILIK C,
           TBLPHPLAPORANTANAH D,
           TBLPFDFAIL E,
           TBLPHPPERMOHONANPELEPASAN I,
           TBLRUJSTATUS F,
           TBLRUJSUBURUSAN G,
           TBLRUJLOT H
     WHERE B.ID_HAKMILIKPERMOHONAN = C.ID_HAKMILIKPERMOHONAN
       AND A.ID_PERMOHONAN = B.ID_PERMOHONAN
       AND D.ID_PERMOHONAN = A.ID_PERMOHONAN
       AND I.ID_PERMOHONAN = A.ID_PERMOHONAN
       AND E.ID_FAIL = A.ID_FAIL
       AND F.ID_STATUS = A.ID_STATUS
       AND G.ID_SUBURUSAN = E.ID_SUBURUSAN
       AND C.ID_LOT = H.ID_LOT
       AND A.ID_PERMOHONAN = D.ID_PERMOHONAN);

-- ADD BY AIN ON 19042017       
ALTER TABLE TBLPHPPERMOHONANPELEPASAN
    ADD CATATAN_KEPUTUSAN VARCHAR2(2000);
 
-- ADD BY PEJE ON 19042017
UPDATE TBLRUJJENISBAYARAN SET KETERANGAN = 'FI PERMOHONAN' WHERE ID_JENISBAYARAN = 11;
UPDATE TBLRUJJENISBAYARAN SET KETERANGAN = 'BAYARAN ROYALTI PASIR' WHERE ID_JENISBAYARAN = 14;
UPDATE TBLRUJJENISBAYARAN SET KETERANGAN = 'FI LESEN' WHERE ID_JENISBAYARAN = 19;
COMMIT;

-- ADD BY PEJE ON 20042017 - UNUSE COLUMN
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN FLAG_LUAR_PERAIRAN;

-- ADD BY PEJE ON 20042017 - UPDATE NULL DATA DEFAULT TO 1
UPDATE TBLPHPPMOHONNJDUALPERTAMA SET FLAG_LUAR_PERAIRANNEGERI = 1 WHERE FLAG_LUAR_PERAIRANNEGERI IS NULL;
COMMIT;

ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(SYOR_JKPTG VARCHAR2(1000 BYTE));

ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (ULASAN_PTG  VARCHAR2(1000 BYTE));
 
-- ADD BY PEJE ON 21042017 - UNUSE TABLE AND COLUMN
DELETE TBLPHPKERTASKERJA CASCADE;
ALTER TABLE TBLPHPKERTASKERJAAPB DROP COLUMN ID_KERTASKERJA;

-- ADD BY PEJE ON 25042017 - UNUSE COLUMN
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN BIL_TITIK;
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN ID_UNITISIPADU;
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN ISIPADU;
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN ID_LUASDIPOHON;
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN MODAL_SEMASA;
ALTER TABLE TBLPHPPMOHONNJDUALPERTAMA DROP COLUMN MODAL_SEDIA;

-- ADD BY AIN ON 19042017
ALTER TABLE TBLPHPHAKMILIK
ADD NO_SYIT NUMBER;

-- ADD BY AIN ON 11052017
UPDATE USERS_INTERNAL SET FLAG_AKTIF = 'Y' 
WHERE FLAG_AKTIF IS NULL;
-- OR
UPDATE USERS_INTERNAL SET FLAG_AKTIF = '1' 
WHERE FLAG_AKTIF ='Y';

-- ADD BY AIN ON 15052017       
ALTER TABLE TBLPHPPERMOHONANPELEPASAN
    ADD KEPUTUSAN_PTD VARCHAR2(1000);
    
ALTER TABLE TBLPHPLAPORANTANAH
    ADD SEJARAH_TANAH VARCHAR2(1000);

ALTER TABLE TBLPHPLAPORANTANAH
    ADD ID_SEJARAH NUMBER(17);

-- ADD BY PEJE ON 30052017
ALTER TABLE TBLPHPFAILAPBBERTINDIH
MODIFY(BERTINDIH_DENGAN_NOFAIL VARCHAR2(200 BYTE));

ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(NOTA VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(PENGALAMAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JAWATANKUASA_KHAS VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(TUJUAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JABATAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(SYOR_PTP VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(PERAKUAN_PTP VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JAS VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_NAHRIM VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JAB_LAUT VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JPS VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JAB_GEOSAINS VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JAB_PERIKANAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_PUSAT_HIDROGRAFI VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_POLISMARIN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_KEM_KEBUDAYAAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(SYOR_JABATAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_KEPUTUSAN VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_JUPEM VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(SYOR_JKPTG VARCHAR2(4000 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(NAMA_MENTERI VARCHAR2(200 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(NAMA_KSU VARCHAR2(200 BYTE));


ALTER TABLE TBLPHPKERTASKERJAAPB
MODIFY(ULASAN_PTG VARCHAR2(4000 BYTE));

--ADD BY PEJE - 02062017 - BETULKAN DATA KOORDINAT
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (DU  VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (DT  VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (MU  VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (MT  VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (SU  VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
 ADD (ST  VARCHAR2(10));
 
UPDATE TBLPHPKOORDINATPERMOHONAN SET DU = LPAD(DARJAH_U, 3, 0);
UPDATE TBLPHPKOORDINATPERMOHONAN SET DT = LPAD(DARJAH_T, 3, 0);
UPDATE TBLPHPKOORDINATPERMOHONAN SET MU = LPAD(MINIT_U, 2, 0);
UPDATE TBLPHPKOORDINATPERMOHONAN SET MT = LPAD(MINIT_T, 2, 0);
UPDATE TBLPHPKOORDINATPERMOHONAN SET SU = SAAT_U;
UPDATE TBLPHPKOORDINATPERMOHONAN SET ST = SAAT_T;
UPDATE TBLPHPKOORDINATPERMOHONAN SET DARJAH_U = NULL;
UPDATE TBLPHPKOORDINATPERMOHONAN SET DARJAH_T = NULL;
UPDATE TBLPHPKOORDINATPERMOHONAN SET MINIT_U = NULL;
UPDATE TBLPHPKOORDINATPERMOHONAN SET MINIT_T = NULL;
UPDATE TBLPHPKOORDINATPERMOHONAN SET SAAT_U = NULL;
UPDATE TBLPHPKOORDINATPERMOHONAN SET SAAT_T = NULL;
COMMIT;

ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(DARJAH_U VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(DARJAH_T VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(MINIT_U VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(MINIT_T VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(SAAT_U VARCHAR2(10));
ALTER TABLE TBLPHPKOORDINATPERMOHONAN
MODIFY(SAAT_T VARCHAR2(10));

UPDATE TBLPHPKOORDINATPERMOHONAN SET DARJAH_U = DU;
UPDATE TBLPHPKOORDINATPERMOHONAN SET DARJAH_T = DT;
UPDATE TBLPHPKOORDINATPERMOHONAN SET MINIT_U = MU;
UPDATE TBLPHPKOORDINATPERMOHONAN SET MINIT_T = MT;
UPDATE TBLPHPKOORDINATPERMOHONAN SET SAAT_U = SU;
UPDATE TBLPHPKOORDINATPERMOHONAN SET SAAT_T = ST;
COMMIT;

ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN DU;
ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN DT;
ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN MU;
ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN MT;
ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN SU;
ALTER TABLE TBLPHPKOORDINATPERMOHONAN DROP COLUMN ST;

ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (FLAG_KERTAS  VARCHAR2(1 BYTE));
COMMENT ON COLUMN TBLPHPKERTASKERJAAPB.FLAG_KERTAS IS '1=KERTAS KERJA; 2=KERTAS RINGKASAN';
UPDATE TBLPHPKERTASKERJAAPB SET FLAG_KERTAS = 1 WHERE FLAG_KERTAS IS NULL;
COMMIT;

INSERT INTO TBLPHPKERTASKERJAAPB (
   NOTA, PENGALAMAN, 
   ULASAN_JAWATANKUASA_KHAS, TARIKH_HANTAR_KSU, FLAG_PERAKUAN_KSU, 
   TARIKH_PERAKUAN_KSU, ID_MASUK, TARIKH_MASUK, 
   ID_KEMASKINI, TARIKH_KEMASKINI, ID_PERMOHONAN, 
   TUJUAN, ULASAN_JABATAN, SYOR_PTP, 
   PERAKUAN_PTP, TARIKH_KEPUTUSAN, FLAG_KEPUTUSAN, 
   ULASAN_JAS, ULASAN_NAHRIM, ULASAN_JAB_LAUT, 
   ULASAN_JPS, ULASAN_JAB_GEOSAINS, ULASAN_JAB_PERIKANAN, 
   ULASAN_PUSAT_HIDROGRAFI, ULASAN_POLISMARIN, ULASAN_KEM_KEBUDAYAAN, 
   SYOR_JABATAN, ULASAN_KEPUTUSAN, ULASAN_JUPEM, 
   SYOR_JKPTG, NAMA_MENTERI, NAMA_KSU, 
   TARIKH_HANTAR_MENTERI, FLAG_KELULUSAN, ULASAN_PTG, 
   FLAG_KERTAS) 
SELECT T.NOTA, T.PENGALAMAN, 
   T.ULASAN_JAWATANKUASA_KHAS, T.TARIKH_HANTAR_KSU, T.FLAG_PERAKUAN_KSU, 
   T.TARIKH_PERAKUAN_KSU, T.ID_MASUK, T.TARIKH_MASUK, 
   T.ID_KEMASKINI, T.TARIKH_KEMASKINI, T.ID_PERMOHONAN, 
   T.TUJUAN, T.ULASAN_JABATAN, T.SYOR_PTP, 
   T.PERAKUAN_PTP, T.TARIKH_KEPUTUSAN, T.FLAG_KEPUTUSAN, 
   T.ULASAN_JAS, T.ULASAN_NAHRIM, T.ULASAN_JAB_LAUT, 
   T.ULASAN_JPS, T.ULASAN_JAB_GEOSAINS, T.ULASAN_JAB_PERIKANAN, 
   T.ULASAN_PUSAT_HIDROGRAFI, T.ULASAN_POLISMARIN, T.ULASAN_KEM_KEBUDAYAAN, 
   T.SYOR_JABATAN, T.ULASAN_KEPUTUSAN, T.ULASAN_JUPEM, 
   T.SYOR_JKPTG, T.NAMA_MENTERI, T.NAMA_KSU, 
   T.TARIKH_HANTAR_MENTERI, T.FLAG_KELULUSAN, T.ULASAN_PTG, 
   2 AS FLAG_KERTAS
FROM TBLPHPKERTASKERJAAPB T;
COMMIT;

--07062017 ADD BY PEJE
COMMENT ON COLUMN TBLPHPULASANTEKNIKAL.FLAG_STATUS IS '1=TELAH DIHANTAR; 2=DITERIMA; 3=TIADA JAWAPAN';

ALTER TABLE TBLPHPULASANTEKNIKAL
MODIFY(ULASAN VARCHAR2(4000 BYTE));
ALTER TABLE TBLPHPULASANTEKNIKAL
MODIFY(NO_RUJUKAN VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JUPEM  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JUPEM  DATE);
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JAS  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JAS  DATE);
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JAB_GEOSAINS  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JAB_GEOSAINS  DATE); 
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JAB_PERIKANAN  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JAB_PERIKANAN  DATE); 
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JAB_LAUT  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JAB_LAUT  DATE);
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_PUSAT_HIDROGRAFI  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_PUSAT_HIDROGRAFI  DATE);
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_JPS  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_JPS  DATE);
 
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NO_RUJUKAN_PTG  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_SURAT_PTG  DATE);

ALTER TABLE TBLPHPFAILAPBBERTINDIH
MODIFY(LAIN_LAIN VARCHAR2(4000 BYTE));

ALTER TABLE TBLPHPDOKUMEN
 ADD (ID_LAPORANPASIR  NUMBER);
 

--13062017 ADD BY PEJE
ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT1_TETAP VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT2_TETAP VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT3_TETAP VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT1_SURAT VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT2_SURAT VARCHAR2(100 BYTE));

ALTER TABLE TBLPHPPEMOHON
MODIFY(ALAMAT3_SURAT VARCHAR2(100 BYTE));

--17072017 add by peje
COMMENT ON COLUMN TBLPHPBAYARANPERLUDIBAYAR.FLAG_AKTIF IS 'Y=AKTIF; T=TIDAK AKTIF;';
COMMENT ON COLUMN TBLPHPBAYARANPERLUDIBAYAR.FLAG_LULUSDASAR IS 'Y=YA; T=TIDAK ;';
COMMENT ON COLUMN TBLPHPBAYARANPERLUDIBAYAR.FLAG_PERJANJIAN IS 'U = UTAMA; 1 = PENGURANGAN KADAR SEWA; 2 = PENAMBAHAN KADAR SEWA; 3 = PENGECUALIAN KADAR SEWA;';

UPDATE TBLPHPBAYARANPERLUDIBAYAR SET FLAG_AKTIF = 'T' WHERE FLAG_AKTIF IS NULL;
UPDATE TBLPHPBAYARANPERLUDIBAYAR SET STATUS = '1' WHERE STATUS IS NULL;
UPDATE TBLPHPBAYARANPERLUDIBAYAR SET FLAG_LULUSDASAR = 'T' WHERE FLAG_LULUSDASAR IS NULL;
UPDATE TBLPHPBAYARANPERLUDIBAYAR SET FLAG_PERJANJIAN = 'U' WHERE FLAG_PERJANJIAN IS NULL;
COMMIT;

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
 ADD (FLAG_CARA_CAJ  VARCHAR2(1 BYTE)               DEFAULT '1');
ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR DROP COLUMN PERJANJIAN_BERMUSIM;
COMMENT ON COLUMN TBLPHPBAYARANPERLUDIBAYAR.FLAG_CARA_CAJ IS '1=BULAN KE BULAN; 2= 3 BULAN SEKALI; 3= 6 BULAN SEKALI; 4 = SETAHUN SEKALI; 5 = CAJ PENUH(LUMPSUMP)';

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
RENAME COLUMN FLAG_CARA_CAJ TO FLAG_MOD_SEWA;

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
RENAME COLUMN FLAG_MOD_SEWA TO MOD_CAJ_SEWAAN;

COMMENT ON COLUMN TBLPHPBAYARANPERLUDIBAYAR.MOD_CAJ_SEWAAN IS '1 = BULAN KE BULAN; 3 = 3 BULAN SEKALI; 6= 6 BULAN SEKALI; 12 = SETAHUN SEKALI; 0 = CAJ PENUH(LUMPSUMP)';

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
MODIFY(MOD_CAJ_SEWAAN VARCHAR2(10 BYTE));

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
MODIFY(BAYARAN  DEFAULT '0');

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
MODIFY(DEPOSIT  DEFAULT '0');

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
MODIFY(FLAG_AKTIF  DEFAULT 'Y');

ALTER TABLE TBLPHPBAYARANPERLUDIBAYAR
MODIFY(TEMPOH  DEFAULT '0');

--01082017 add by ain
ALTER TABLE TBLPHPLAPORANTANAH
MODIFY(NAMA_PENCEROBOH VARCHAR2(1000 BYTE));

ALTER TABLE TBLPHPHASIL
MODIFY(TUJUAN VARCHAR2(4000 BYTE));

ALTER TABLE TBLPHPHASIL
MODIFY(MAKLUMAT_LOT VARCHAR2(4000 BYTE));

ALTER TABLE TBLPHPHASIL
MODIFY(CATATAN_TANAH VARCHAR2(4000 BYTE));

ALTER TABLE TBLPHPHASIL
 ADD (CATATAN_ABT  VARCHAR2(4000 BYTE));

--03082017 add by ain
ALTER TABLE TBLPHPLAPORANTANAH 
 ADD (NAMA_BANDAR  VARCHAR(1000));


ALTER TABLE TBLPHPNOTISHASIL
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPHPNOTISHASIL CASCADE CONSTRAINTS;

CREATE TABLE TBLPHPNOTISHASIL
(
  ID_NOTIS             NUMBER NOT NULL,
  ID_MASUK             NUMBER,
  TARIKH_MASUK         DATE,
  ID_KEMASKINI         NUMBER,
  TARIKH_KEMASKINI     DATE
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          136M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX TBLPHPNOTISHASIL_PK ON TBLPHPNOTISHASIL
(ID_NOTIS)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          24M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP SEQUENCE TBLPHPNOTISHASIL_SEQ;
CREATE SEQUENCE TBLPHPNOTISHASIL_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER TBLPHPNOTISHASIL_BI    
before insert on     TBLPHPNOTISHASIL    for each row
begin    if :new.ID_NOTIS    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPHPNOTISHASIL_SEQ.NEXTVAL into :new.ID_NOTIS                from dual;    end if;    end;
/

ALTER TABLE TBLPHPNOTISHASIL ADD (
  CONSTRAINT TBLPHPNOTISHASIL_PK
 PRIMARY KEY
 (ID_NOTIS)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          24M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPHPNOTISHASIL TO EKPTGSYNC;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON TBLPHPNOTISHASIL TO PPTMHQ;

ALTER TABLE TBLPHPNOTISHASIL
 ADD (ID_HASIL  NUMBER);
 ALTER TABLE TBLPHPNOTISHASIL
 ADD (TARIKH_NOTIS  DATE);
ALTER TABLE TBLPHPNOTISHASIL
 ADD (KADAR_SEWA  NUMBER(11,2));
ALTER TABLE TBLPHPNOTISHASIL
 ADD (BULAN_TUNGGAKAN  NUMBER);
ALTER TABLE TBLPHPNOTISHASIL
 ADD (JUMLAH_TUNGGAKAN  NUMBER(11,2));
 ALTER TABLE TBLPHPNOTISHASIL
 ADD (BIL_PERINGATAN  NUMBER);
 ALTER TABLE TBLPHPNOTISHASIL
 ADD (ID_JENIS_NOTIS  VARCHAR2(1 BYTE));
COMMENT ON COLUMN TBLPHPNOTISHASIL.ID_JENIS_NOTIS IS '1=NOTIS TUNTUTAN TUNGGAKAN; 2= NOTIS RAMPASAN DEPOSIT';

ALTER TABLE TBLPHPAKAUN
MODIFY(FLAG_DEPOSIT  DEFAULT 'T');
ALTER TABLE TBLPHPAKAUN
MODIFY(ID_MOD_BAYARAN  DEFAULT 'K');

--ADD BY AIN 16082017

Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (1, 1, 1, 'Salinan Kad Pengenalan', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (2, 1, 2, 'Salinan sijil carian rasmi daripada Pejabat Tanah Daerah/Pejabat Tanah Galian', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (3, 1, 3, 'Pelan Tanah/ Pelan Susunatur/ Pelan Perancangan Tapak yang ditandakan kawasan/ bahagian yang dipohon', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (4, 2, 4, 'Salinan sijil pendaftaran', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (5, 2, 5, 'Salinan borang 24 Akta Syarikat', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (6, 2, 6, 'Salinan borang 49 Akta Syarikat', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (7, 3, 7, 'Salinan artikel M.A.A', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (8, 2, 8, 'Salinan Undang-undang Tubuh/ Kecil', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (9, 2, 2, 'Salinan sijil carian rasmi daripada Pejabat Tanah Daerah/ Pejabat Tanah Galian', NULL, 
    NULL, NULL, NULL);
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, ID_MASUK, 
    TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (10, 2, 3, 'Pelan Tanah/ Pelan Susunatur/ Pelan Perancangan Tapak yang ditandakan kawasan/ bahagian yang dipohon', NULL, 
    NULL, NULL, NULL);
COMMIT;

--------------------------------DAH RUN DI POC 16082017-------------------------------------------------

--ADD BY AIN 16082017
COMMENT ON COLUMN TBLPHPDOKUMEN.FLAG_DOKUMEN IS 'I=IMEJAN; P=PELAN;L=LAMPIRAN';

--------------------------------DAH RUN DI POC 17082017-------------------------------------------------

--ADD BY AIN 21082017
ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
    ADD KEPUTUSAN_KEWANGAN VARCHAR2(2);
    
--------------------------------DAH RUN DI POC 21082017-------------------------------------------------

ALTER TABLE TBLPHPNOTISHASIL
 ADD (TARIKH_AKHIR_NOTIS  DATE);
 
insert into tblrujjenisbayaran
    (id_jenisbayaran, kod_jenis_bayaran, keterangan, amaun, id_seksyen, id_masuk, tarikh_masuk, id_kemaskini, tarikh_kemaskini, id_db, kod_hasil)
values
    (37, 'LL', 'BAYARAN LAIN-LAIN', 1, 4, 1, NULL, 1, NULL, 1, NULL);
COMMIT;

--------------------------------DAH RUN DI POC 22082017-------------------------------------------------

ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_KERTAS  DATE);
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (NAMA_PTP  VARCHAR2(200 BYTE));
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (TARIKH_MESYUARAT  DATE);
ALTER TABLE TBLPHPKERTASKERJAAPB
 ADD (BIL_MESYUARAT  VARCHAR2(100 BYTE));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
RENAME COLUMN FLAG_LANJUT_TEMPOH TO FLAG_AKTIF;
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(FLAG_AKTIF  DEFAULT 'Y');
UPDATE TBLPHPBYRNSYRTKLLSNLESENAPB SET FLAG_AKTIF = 'Y';
COMMIT;
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
 ADD (TEMPOH_KELULUSAN_DASAR  NUMBER(2));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(ULASAN_EIA VARCHAR2(4000 BYTE));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(ULASAN_HIDROGRAFI VARCHAR2(4000 BYTE));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(MAKLUMAT_TAMBAHAN VARCHAR2(4000 BYTE));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB
MODIFY(SYARAT_LULUS_LAMPIRAN VARCHAR2(4000 BYTE));
ALTER TABLE TBLPHPBYRNSYRTKLLSNLESENAPB DROP COLUMN KADAR_FEE_LESEN;

--------------------------------DAH RUN DI POC 29082017------------------------------------------------

ALTER TABLE TBLPHPAKAUN
MODIFY(DEBIT  DEFAULT 0);
ALTER TABLE TBLPHPAKAUN
MODIFY(KREDIT  DEFAULT 0);
UPDATE TBLPHPAKAUN SET DEBIT = 0 WHERE DEBIT IS NULL;
UPDATE TBLPHPAKAUN SET KREDIT = 0 WHERE KREDIT IS NULL;
COMMIT;

UPDATE TBLPHPBAYARANPERLUDIBAYAR SET STATUS = 2 WHERE STATUS = 1 AND SYSDATE > TARIKH_TAMAT;
COMMIT;

--ADD BY AIN 14092017
ALTER TABLE TBLPHPLAPORANTANAH
   MODIFY SEJARAH_TANAH VARCHAR2(4000);

--ADD BY AIN 20092017
ALTER TABLE TBLPHPPERMOHONANPELEPASAN
    MODIFY FLAG_JENIS_PROJEK VARCHAR2(5);
    
--------------------------------DAH RUN DI POC 20092017------------------------------------------------

--ADD BY AIN 20092017
ALTER TABLE TBLPHPULASANTEKNIKAL
    ADD FLAG_KEPUTUSAN_PEMOHON VARCHAR2(2);
ALTER TABLE TBLPHPULASANTEKNIKAL
    ADD ULASAN_PEMOHON VARCHAR2(4000);

--ADD BY AIN 21092017    
ALTER TABLE TBLPHPULASANTEKNIKAL
    MODIFY FLAG_KEPUTUSAN_PEMOHON VARCHAR2(10);
    
ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
    MODIFY KEPUTUSAN_KEWANGAN VARCHAR2(10);

ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
    ADD FLAG_KEPUTUSAN_PEMOHON VARCHAR2(10);
ALTER TABLE TBLPHPKERTASKERJAPELEPASAN
    ADD ULASAN_PEMOHON VARCHAR2(4000);    

--ADD BY AIN 24092017
UPDATE TBLRUJSTATUS SET KETERANGAN = 'KERTAS CADANGAN' WHERE ID_STATUS = 1610202;
UPDATE TBLRUJSTATUS SET KETERANGAN = 'ULASAN MENTERI KEWANGAN' WHERE ID_STATUS = 1610203;
UPDATE TBLRUJSTATUS SET KETERANGAN = 'KERTAS PERTIMBANGAN' WHERE ID_STATUS = 1610204;
UPDATE TBLRUJSTATUS SET KETERANGAN = 'ULASAN MENTERI NRE' WHERE ID_STATUS = 1610205;
COMMIT;

ALTER TABLE TBLPHPRUJSENARAISEMAK
 ADD (FLAG_AKTIF  VARCHAR2(1 BYTE)                  DEFAULT 'Y');
ALTER TABLE TBLPHPRUJSENARAISEMAK
 ADD (ID_KATEGORI_SS  VARCHAR2(1 BYTE)              DEFAULT '1');
COMMENT ON COLUMN TBLPHPRUJSENARAISEMAK.ID_KATEGORI_SS IS '1 = MAKLUMAT INDIVIDU / SYARIKAT; 2 = MAKLUMAT TANAH';

DELETE FROM TBLPHPRUJSENARAISEMAK;
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (1, 1, 1, 'Salinan Kad Pengenalan', 'Y', 
    '1');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (2, 1, 2, 'Salinan sijil carian rasmi daripada Pejabat Tanah Daerah/Pejabat Tanah Galian', 'Y', 
    '2');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (3, 1, 3, 'Pelan Tanah/ Pelan Susunatur/ Pelan Perancangan Tapak yang ditandakan kawasan/ bahagian yang dipohon', 'Y', 
    '2');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (4, 2, 1, 'Salinan sijil pendaftaran', 'Y', 
    '1');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (5, 2, 2, 'Salinan borang 24 Akta Syarikat', 'Y', 
    '1');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (6, 2, 3, 'Salinan borang 49 Akta Syarikat', 'Y', 
    '1');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (7, 2, 4, 'Salinan Undang-undang Tubuh / Kecil', 'Y', 
    '1');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (8, 2, 5, 'Salinan sijil carian rasmi daripada Pejabat Tanah Daerah/ Pejabat Tanah Galian', 'Y', 
    '2');
Insert into TBLPHPRUJSENARAISEMAK
   (ID_RUJSENARAISEMAK, ID_KATEGORIPEMOHON, KOD_SENARAISEMAK, KETERANGAN, FLAG_AKTIF, 
    ID_KATEGORI_SS)
 Values
   (9, 2, 6, 'Pelan Tanah/ Pelan Susunatur/ Pelan Perancangan Tapak yang ditandakan kawasan/ bahagian yang dipohon', 'Y', 
    '2');
COMMIT;

DELETE FROM TBLRUJKEMENTERIAN;
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (2, '02', 'KEMENTERIAN TENAGA, TEKNOLOGI HIJAU DAN AIR', 'Blok E4/5, Parcel E', 'Pusat Pentadbiran Kerajaan Persekutuan', 
    NULL, '62668', 16, 'KETUA SETIAUSAHA,', 'KEMENTERIAN TENAGA, AIR DAN KOMUNIKASI', 
    '147', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (3, '03', 'KEMENTERIAN DALAM NEGERI', 'Bahagian Kewangan, Bekalan dan Pembangunan', 'Aras 3, Blok D1, Parcel D', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62546', 16, 'KETUA SETIAUSAHA,', 'KEMENTERIAN KESELAMATAN DALAM NEGERI', 
    '131', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (4, '04', 'KEMENTERIAN KERJA RAYA', 'Bahagian Pembangunan dan Penswastaan', 'Tingkat 4, Blok A, Kompleks Kerja Raya', 
    'Jalan Sultan Salahuddin', '50580', 14, 'KETUA SETIAUSAHA,', 'KEMENTERIAN KERJARAYA', 
    '105', 'testingetapp@gmail.com', NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (5, '05', 'KEMENTERIAN KESIHATAN', 'Blok E1, E6, E7 & E10', 'Kompleks E', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62590', 16, 'KETUA SETIAUSAHA,', NULL, 
    '123', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (6, '06', 'KEMENTERIAN PERTANIAN DAN INDUSTRI ASAS TANI', 'Wisma Tani', 'No. 28, Persiaran Perdana', 
    'Presint 4', '62624', 16, 'KETUA SETIAUSAHA,', NULL, 
    '134', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (7, '07', 'KEMENTERIAN PERTAHANAN', 'Wisma Pertahanan', 'Jalan Padang Tembak', 
    NULL, '50634', 14, 'KETUA SETIAUSAHA,', NULL, 
    '117', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (8, '08', 'KEMENTERIAN PENGANGKUTAN MALAYSIA', 'Blok D5, Kompleks D', 'Pusat Pentadbiran Kerajaan Persekutuan', 
    NULL, '62616', 16, 'KETUA SETIAUSAHA,', NULL, 
    '104', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (9, '09', 'KEMENTERIAN PEMBANGUNAN WANITA, KELUARGA DAN MASYARAKAT', 'Aras 2, Blok E', 'Kompleks Pejabat Kerajaan Bukit Perdana', 
    'Jalan Dato Onn', '50515', 14, 'KETUA SETIAUSAHA,', NULL, 
    '143', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (10, '10', 'KEMENTERIAN UNDANG-UNDANG / KEHAKIMAN', NULL, NULL, 
    NULL, NULL, 14, 'KETUA SETIAUSAHA,', NULL, 
    '128', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (11, '11', 'KEMENTERIAN SAINS, TEKNOLOGI DAN INOVASI', 'Bahagian Pengurusan', 'Blok C5, Parcel C', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62662', 16, 'KETUA SETIAUSAHA,', NULL, 
    '139', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (12, '12', 'JABATAN PERDANA MENTERI', 'Blok B8', 'Kompleks Jabatan Perdana Menteri', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62502', 16, 'KETUA SETIAUSAHA,', NULL, 
    '101', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (13, '13', 'KEMENTERIAN KEWANGAN', 'Kompleks Kementerian Kewangan', 'Aras 2 (Utara)', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62592', 16, 'KETUA SETIAUSAHA PERBENDAHARAAN,', NULL, 
    '103', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (14, '14', 'KEMENTERIAN PEMBANGUNAN USAHAWAN DAN KOPERASI', 'Aras 14, Blok Menara', 'Lot 2G6, Presint 2', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62100', 16, 'KETUA SETIAUSAHA,', NULL, 
    '142', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (15, '15', 'KEMENTERIAN PERUSAHAAN, PERLADANGAN DAN KOMODITI', 'Aras 6- 13, Lot 2G4, Presint 2', 'Pusat Pentadbiran Kerajaan Persekutuan', 
    NULL, '62654', 16, 'KETUA SETIAUSAHA,', NULL, 
    '132', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (16, '16', 'KEMENTERIAN BELIA DAN SUKAN', 'BAHAGIAN PEMBANGUNAN KEMENTERIAN BELIA DAN SUKAN MALAYSIA', 'ARAS 8, MENARA KBS', 
    'NO. 27, PERSIARAN PERDANA, PRESINT 4', '62570', 16, 'KETUA SETIAUSAHA,', NULL, 
    '121', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (17, '17', 'KEMENTERIAN LUAR NEGERI', 'Wisma Putra, No.1, Jalan Wisma Putra, Precint 2', 'Pusat Pentadbiran Kerajaan Persekutuan', 
    NULL, '65202', 16, 'KETUA SETIAUSAHA,', NULL, 
    '119', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (18, '18', 'KEMENTERIAN SUMBER ASLI DAN ALAM SEKITAR', 'Aras 15, Wisma Sumber Asli', 'No. 25 Persiaran Perdana, Presint 4', 
    NULL, '62574', 16, 'KETUA SETIAUSAHA,', NULL, 
    '141', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (19, '19', 'KEMENTERIAN PERUMAHAN DAN KERAJAAN TEMPATAN', 'Bahagian Pembangunan', 'No. 51, Persiaran Perdana, Presint 4', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62100', 16, 'KETUA SETIAUSAHA,', NULL, 
    '116', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (20, '20', 'KEMENTERIAN SUMBER MANUSIA', 'Bahagian Perancangan dan Penyelidikan Dasar', 'Aras 7, Blok D3, Parcel D', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62502', 16, 'KETUA SETIAUSAHA,', NULL, 
    '114', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (21, '21', 'KEMENTERIAN PENERANGAN KOMUNIKASI DAN KEBUDAYAAN', 'Aras 1, Blok A, Kompleks Sultan Abdul Samad', 'Jalan Raja', 
    NULL, '50610', 14, 'KETUA SETIAUSAHA,', 'KEMENTERIAN PENERANGAN', 
    '145', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (22, '22', 'KEMENTERIAN PERDAGANGAN ANTARABANGSA DAN INDUSTRI', 'Bahagian Pentadbiran', 'Blok 10, MITI', 
    'Kompleks Pejabat Kerajaan, Jalan Duta', '50622', 14, 'KETUA SETIAUSAHA,', NULL, 
    '108', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (23, '23', 'KEMENTERIAN KEMAJUAN LUAR BANDAR DAN WILAYAH', 'Bahagian Kemajuan Tanah dan Wilayah', 'Aras 25, No. 47, Persiaran Perdana, Presint 4', 
    NULL, '62100', 16, 'KETUA SETIAUSAHA,', NULL, 
    '140', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (24, '24', 'KEMENTERIAN PERPADUAN, KEBUDAYAAN, KESENIAN DAN WARISAN', 'Tingkat 26, 27, 30, 34 & 35', 'Menara Th Perdana', 
    '100 1 Maju Junction,  Jalan Sultan Ismail', '50250', 14, 'KETUA SETIAUSAHA,', 'KEMENTERIAN KEBUDAYAAN, KESENIAN DAN WARISAN', 
    '137', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (25, '25', 'KEMENTERIAN PERDAGANGAN DALAM NEGERI, KOPERASI DAN KEPENGGUNAAN', 'Lot 2G3, Precint 2', 'Pusat Pentadbiran Kerajaan Persekutuan', 
    NULL, '62623', 16, 'KETUA SETIAUSAHA,', 'KEMENTERIAN PERDAGANGAN DALAM NEGERI DAN HAL EHWAL PENGGUNA', 
    '144', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (26, '26', 'JABATAN YANG TIADA BERKEMENTERIAN', NULL, NULL, 
    NULL, NULL, 14, 'KETUA SETIAUSAHA,', NULL, 
    '129', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (27, '27', 'KEMENTERIAN PEMBANGUNAN WANITA DAN HAL EHWAL PENGGUNA', NULL, NULL, 
    NULL, NULL, 16, 'KETUA SETIAUSAHA,', NULL, 
    NULL, NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (28, '28', 'KEMENTERIAN PENGAJIAN TINGGI', 'Bahagian Pembangunan', 'Aras 10, Menara 2', 
    'Jalan P5/6, Presint 5', '62200', 16, 'KETUA SETIAUSAHA,', NULL, 
    '136', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (29, '29', 'KEMENTERIAN DALAM NEGERI', 'Bahagian Pembangunan', 'Aras 3, Blok Dl, Parcel D', 
    'Pusat Pentadbiran Kerajaan Persekutuan', '62592', 16, 'KETUA SETIAUSAHA,', 'KEMENTERIAN HAL EHWAL DALAM NEGERI', 
    '130', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (30, '30', 'KEMENTERIAN PELANCONGAN DAN KEBUDAYAAN MALAYSIA', 'No. 2, Menara 1', 'Jalan P5/6', 
    'Presint 5', '62200', 16, 'KETUA SETIAUSAHA,', NULL, 
    '138', NULL, NULL);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (31, '31', 'KEMENTERIAN WILAYAH PERSEKUTUAN DAN KESEJAHTERAAN BANDAR', 'ARAS 6, BLOK 2', 'PRESINT 2', 
    'PUSAT PENTADBIRAN KERAJAAN PERSEKUTUAN', '62100', 16, 'KETUA SETIAUSAHA,', 'KEMENTERIAN WILAYAH PERSEKUTUAN', 
    '127', NULL, 1);
Insert into TBLRUJKEMENTERIAN
   (ID_KEMENTERIAN, KOD_KEMENTERIAN, NAMA_KEMENTERIAN, ALAMAT1, ALAMAT2, 
    ALAMAT3, POSKOD, ID_NEGERI, JAWATAN, NAMA_KEMENTERIAN_LAMA, 
    KOD_DDSA, EMEL, FLAG_AKTIF)
 Values
   (1, '01', 'KEMENTERIAN PELAJARAN MALAYSIA', 'ARAS 1, 3 & 6, BLOK E2, PARCEL E', 'PUSAT PENTADBIRAN KERAJAAN PERSEKUTUAN', 
    NULL, '62604', 16, 'KETUA SETIAUSAHA,', NULL, 
    '135', NULL, 1);
COMMIT;
DELETE FROM TBLRUJAGENSI WHERE ID_KEMENTERIAN NOT IN(SELECT ID_KEMENTERIAN FROM TBLRUJKEMENTERIAN);
COMMIT;

--------------------------------DAH RUN DI POC 25092017------------------------------------------------

--ADD BY AIN 29092017
ALTER TABLE TBLPHPLAPORANTANAH
ADD ID_JAWATANPENYEMAK NUMBER;
COMMIT;

ALTER TABLE TBLPHPHASIL
 ADD (NILAI_TUNGGAKAN  NUMBER(11,2) DEFAULT 0);

COMMENT ON TABLE EKPTG.TBLPHPAKAUN IS '1 - CAJ, 2 = BAYARAN, 3 = PELARASAN';

--------------------------------DAH RUN DI POC 02102017------------------------------------------------

alter table TBLPHPLAPORANTANAH
 modify WAKTU_OPERASI_DARI varchar2(20);
alter table TBLPHPLAPORANTANAH
 modify WAKTU_OPERASI_HINGGA varchar2(20);
commit;

--------------------------------DAH RUN DI POC 08102017------------------------------------------------

UPDATE TBLPHPBAYARANPERLUDIBAYAR SET STATUS = 2 WHERE TARIKH_TAMAT < SYSDATE AND STATUS NOT IN(2,3);
COMMIT;