/*remove contraint*/
ALTER TABLE TBLESADUAN
	DROP CONSTRAINT TBLESADUAN_FK3;
	
	
	
CREATE OR REPLACE TRIGGER TBLESNOTIFIKASI_BI    
before insert on     TBLESNOTIFIKASI    for each row
begin    if :new.ID_ESNOTIFIKASI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLESNOTIFIKASI_SEQ.NEXTVAL into 

:new.ID_ESNOTIFIKASI            from dual;    end if;    end;
/


CREATE OR REPLACE TRIGGER TBLESCOMMENT_BI    
before insert on     TBLESCOMMENT    for each row
begin    if :new.ID_ESCOMMENT  is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLESCOMMENT_SEQ.NEXTVAL into 

:new.ID_ESCOMMENT         from dual;    end if;    end;
/

---- TBLRUJTAHAPKESUKARAN

INSERT INTO TBLRUJTAHAPKESUKARAN (ID_TBLRUJTAHAPKESUKARAN, KOD_TAHAP, PERIHAL , JANGKAMASA_DARI ,JANGKAMASA_HINGGA ,ID_MASUK , TARIKH_MASUK) 
VALUES ('1','1','MINOR','1','3','1', SYSDATE);

INSERT INTO TBLRUJTAHAPKESUKARAN (ID_TBLRUJTAHAPKESUKARAN, KOD_TAHAP, PERIHAL , JANGKAMASA_DARI ,JANGKAMASA_HINGGA ,ID_MASUK , TARIKH_MASUK) 
VALUES ('2','2','MODERATE','4','7','1', SYSDATE);

INSERT INTO TBLRUJTAHAPKESUKARAN (ID_TBLRUJTAHAPKESUKARAN, KOD_TAHAP, PERIHAL , JANGKAMASA_DARI ,JANGKAMASA_HINGGA ,ID_MASUK , TARIKH_MASUK) 
VALUES ('3','3','MAJOR','8','12','1', SYSDATE);



INSERT INTO TBLRUJJENISADUAN (ID_JENISADUAN, KOD_JENIS_ADUAN, JENIS_ADUAN) VALUES ('16104','04','PUJIAN');