


CREATE SEQUENCE TBLPPKHISTORYJANANOTA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLPPKHISTORYJANANOTA;
CREATE TABLE TBLPPKHISTORYJANANOTA
(
  ID_HISTORYJANANOTA NUMBER(38),
  ID_PERBICARAAN NUMBER(38),
  ID_FAIL NUMBER(38),
  ID_PERINTAH NUMBER(38),
  NOTA CLOB,  
  NO_PINDAAN VARCHAR2(100 BYTE),
  NAMA_PEGAWAI VARCHAR2(500 BYTE),
  BIL_BICARA VARCHAR2(5 BYTE),
  WAKTU_BICARA VARCHAR2(500 BYTE),
  NO_PINDAAN VARCHAR2(100 BYTE),
  NO_FAIL VARCHAR2(200 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLPPKHISTORYJANANOTA PRIMARY KEY (ID_HISTORYJANANOTA)
);

CREATE OR REPLACE TRIGGER TBLPPKHISTORYJANANOTA_BI    
before insert on     TBLPPKHISTORYJANANOTA    for each row
begin    if :new.ID_HISTORYJANANOTA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKHISTORYJANANOTA_SEQ.NEXTVAL into :new.ID_HISTORYJANANOTA   from dual; end if;    end;
/

CREATE INDEX TBLPPKHISTORYJANANOTA_IDX1 ON TBLPPKHISTORYJANANOTA
(ID_PERBICARAAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKHISTORYJANANOTA_IDX2 ON TBLPPKHISTORYJANANOTA
(ID_PERINTAH)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKHISTORYJANANOTA_IDX3 ON TBLPPKHISTORYJANANOTA
(ID_FAIL)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--------------------------------------15/10/2020----------------------------------
-------TBLPPKBITIDAKHADIR

ALTER TABLE EKPTGHQLIVE.TBLPPKBITIDAKHADIR
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQLIVE.TBLPPKBITIDAKHADIR CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQLIVE.TBLPPKBITIDAKHADIR
(
  ID_BITIDAKHADIR   NUMBER                      NOT NULL,
  ID_PERBICARAAN    NUMBER,
  NAMA              VARCHAR2(500 BYTE),
  UMUR              NUMBER,
  STATUS            VARCHAR2(500 BYTE),
  PENGENALAN        VARCHAR2(100 BYTE),
  HUBUNGAN          VARCHAR2(500 BYTE),
  CATATAN           VARCHAR2(4000 BYTE),
  ID_MASUK          NUMBER,
  ID_KEMASKINI      NUMBER,
  TARIKH_MASUK      DATE,
  TARIKH_KEMASKINI  DATE,
  JENIS_TIDAKHADIR  VARCHAR2(10 BYTE),
  ID_TIDAKHADIR     VARCHAR2(10 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGHQLIVE.TBLPPKBITIDAKHADIR_PK ON EKPTGHQLIVE.TBLPPKBITIDAKHADIR
(ID_BITIDAKHADIR)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EKPTGHQLIVE.TBLPPKBITIDAKHADIR ADD (
  CONSTRAINT TBLPPKBITIDAKHADIR_PK
 PRIMARY KEY
 (ID_BITIDAKHADIR)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));



















--OPEN ALTER CATATAN PERINTAH
--takperlu
/*
ALTER TABLE TBLPPKPERINTAH
ADD CATATAN_BLOB CLOB

UPDATE TBLPPKPERINTAH P  SET P.CATATAN_BLOB = TO_CLOB(P.CATATAN)

ALTER TABLE
   TBLPPKPERINTAH
DROP COLUMN
   CATATAN;
   
ALTER TABLE
   TBLPPKPERINTAH
RENAME COLUMN
   CATATAN_BLOB 
TO
   CATATAN;
*/   
 --OPEN ALTER CATATAN PERINTAH  
   


--OPEN INDEX PERINTAH

CREATE INDEX TBLPPKPERBICARAAN_IDX5 ON TBLPPKPERBICARAAN
(TARIKH_BICARA)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKPERINTAHHTAOBDTL_IDX2 ON TBLPPKPERINTAHHTAOBDTL
(ID_OB)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE INDEX TBLPPKPERINTAHHTAOBDTL_IDX3 ON TBLPPKPERINTAHHTAOBDTL
(ID_PA1)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKPERINTAHHTAOBDTL_IDX4 ON TBLPPKPERINTAHHTAOBDTL
(ID_PA2)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKPERINTAHHTAOBDTL_IDX5 ON TBLPPKPERINTAHHTAOBDTL
(ID_PA3)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKPERINTAHHTAOBDTL_IDX6 ON TBLPPKPERINTAHHTAOBDTL
(ID_PA4)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

--CLOSE INDEX PERINTAH


ALTER TABLE
  TBLPPKPERINTAH
ADD
(
   ID_INTROPERINTAH  NUMBER,
   CATATAN_PERINTAH_BI  CLOB,   
   CATATAN_KEPUTUSAN_PERBICARAAN  CLOB,
   INTROFIELD1 VARCHAR2(4000 BYTE),
   INTROFIELD2 VARCHAR2(4000 BYTE),
   INTROFIELD3 VARCHAR2(4000 BYTE)
)

ALTER TABLE
  TBLPPKPERBICARAAN
ADD
(
   FLAG_BANTAHAN VARCHAR2(1 BYTE)
)


ALTER TABLE
  TBLPPKPERBICARAAN
ADD
(
   KETERANGAN_BANTAHAN VARCHAR2(4000 BYTE)
)


CREATE SEQUENCE TBLPPKRUJINTROPERINTAH_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLPPKRUJINTROPERINTAH;
CREATE TABLE TBLPPKRUJINTROPERINTAH
(
  ID_INTROPERINTAH NUMBER(38),
  INTRO VARCHAR2(4000 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  SEKSYEN NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLPPKRUJINTROPERINTAH PRIMARY KEY (ID_INTROPERINTAH)
);


CREATE OR REPLACE TRIGGER TBLPPKRUJINTROPERINTAH_BI    
before insert on     TBLPPKRUJINTROPERINTAH    for each row
begin    if :new.ID_INTROPERINTAH    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKRUJINTROPERINTAH_SEQ.NEXTVAL into :new.ID_INTROPERINTAH   from dual; end if;    end;
/











CREATE SEQUENCE TBLPPKBIKEHADIRAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLPPKBIKEHADIRAN;
CREATE TABLE TBLPPKBIKEHADIRAN
(
  ID_BIKEHADIRAN NUMBER(38),
  ID_PERBICARAAN NUMBER(38),
  NAMA VARCHAR2(500 BYTE),
  UMUR NUMBER,
  STATUS VARCHAR2(500 BYTE),
  PENGENALAN VARCHAR2(100 BYTE),
  HUBUNGAN VARCHAR2(500 BYTE),
  CATATAN VARCHAR2(4000 BYTE),
  JENIS_HADIR VARCHAR2(10 BYTE), --OB: ORANG KEPENTINGAN, T--TURUT HADIR
  ID_HADIR VARCHAR2(100 BYTE),
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  NOTA_PEGAWAI CLOB,
  KETERANGAN CLOB,
  CONSTRAINT TBLPPKBIKEHADIRAN PRIMARY KEY (ID_BIKEHADIRAN)
);

CREATE OR REPLACE TRIGGER TBLPPKBIKEHADIRAN_BI    
before insert on     TBLPPKBIKEHADIRAN    for each row
begin    if :new.ID_BIKEHADIRAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKBIKEHADIRAN_SEQ.NEXTVAL into :new.ID_BIKEHADIRAN   from dual; end if;    end;
/







  
CREATE SEQUENCE TBLPPKSEJARAHBIMAIN_SEQ
START WITH 1
MAXVALUE 999999999
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;


DROP TABLE TBLPPKSEJARAHBIMAIN;

CREATE TABLE TBLPPKSEJARAHBIMAIN
( 
  ID_SEJARAHBIMAIN NUMBER(20) NOT NULL,
  JENIS_AKTIVITI VARCHAR2(10) NOT NULL, --INSERT,UPDATE,DELETE
  NAMA_TABLE VARCHAR2(500) NOT NULL,
  NAMA_FIELD_PK VARCHAR2(500) NOT NULL,
  SKRIN_NAME VARCHAR2(500),
  VALUE_FIELD_PK VARCHAR2(500),
  ID_PERMOHONANSIMATI NUMBER(38),
  ID_PERBICARAAN NUMBER(38),
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLPPKSEJARAHBIMAIN PRIMARY KEY (ID_SEJARAHBIMAIN)
);


CREATE OR REPLACE TRIGGER TBLPPKSEJARAHBIMAIN_BI    
before insert on     TBLPPKSEJARAHBIMAIN    for each row
begin    if :new.ID_SEJARAHBIMAIN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKSEJARAHBIMAIN_SEQ.NEXTVAL into :new.ID_SEJARAHBIMAIN   from dual; end if;    end;
/


CREATE SEQUENCE TBLPPKSEJARAHBISUB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
DROP TABLE TBLPPKSEJARAHBISUB;

CREATE TABLE TBLPPKSEJARAHBISUB
(
  ID_SEJARAHBISUB     NUMBER(20),
  ID_SEJARAHBIMAIN    NUMBER(20),
  REKOD_LABEL         VARCHAR2(200 BYTE),
  NAMA_FIELD          VARCHAR2(200 BYTE),
  VALUE_SEBELUM       VARCHAR2(4000 BYTE),
  KETERANGAN_SEBELUM  VARCHAR2(4000 BYTE),
  VALUE_SELEPAS       VARCHAR2(4000 BYTE),
  KETERANGAN_SELEPAS  VARCHAR2(4000 BYTE),
  ID_MASUK            NUMBER,
  TARIKH_MASUK        DATE                      DEFAULT SYSDATE,
  TURUTAN             NUMBER(26,10),
  CONSTRAINT TBLPPKSEJARAHBISUB PRIMARY KEY (ID_SEJARAHBISUB)
)

CREATE OR REPLACE TRIGGER TBLPPKSEJARAHBISUB_BI    
before insert on     TBLPPKSEJARAHBISUB    for each row
begin    if :new.ID_SEJARAHBISUB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKSEJARAHBISUB_SEQ.NEXTVAL into :new.ID_SEJARAHBISUB  from dual; end if;    end;
/








CREATE INDEX TBLPPKSEJARAHBIMAIN_IDX2 ON TBLPPKSEJARAHBIMAIN
(ID_PERMOHONANSIMATI)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE INDEX TBLPPKSEJARAHBIMAIN_IDX4 ON TBLPPKSEJARAHBIMAIN
(VALUE_FIELD_PK)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKSEJARAHBIMAIN_IDX5 ON TBLPPKSEJARAHBIMAIN
(NAMA_FIELD_PK)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKSEJARAHBIMAIN_IDX6 ON TBLPPKSEJARAHBIMAIN
(NAMA_TABLE)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKSEJARAHBISUB_IDX2 ON TBLPPKSEJARAHBISUB
(ID_SEJARAHBIMAIN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



CREATE INDEX TBLPPKBAYARAN_IDX2 ON TBLPPKBAYARAN
(ID_PERMOHONAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;













CREATE SEQUENCE TBLPPKTUKARPEGAWAI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
DROP TABLE TBLPPKTUKARPEGAWAI;
CREATE TABLE TBLPPKTUKARPEGAWAI
(
  ID_TUKARPEGAWAI NUMBER(38),
  NO_TUKARPEGAWAI VARCHAR2(100 BYTE),
  ID_PEMOHON NUMBER(38),
  ID_PELULUS NUMBER(38),
  ID_PERBICARAAN NUMBER(38),
  ID_PEMOHONTUKARPEGAWAI NUMBER(38),
  ID_PEGAWAIASAL NUMBER(38),
  ID_PEGAWAIBARU NUMBER(38),
  ID_FAIL NUMBER(38),
  ID_NEGERIPEGAWAIBARU NUMBER(38),
  ID_NEGERIPEGAWAIASAL NUMBER(38),
  USER_ID_PEGAWAIBARU NUMBER(38),
  USER_ID_PEGAWAIASAL NUMBER(38),
  CATATAN_PEMOHON VARCHAR2(4000 BYTE),
  CATATAN_PELULUS VARCHAR2(4000 BYTE),
  STATUS_TUKARPEGAWAI NUMBER(38),
  TARIKH_MOHON DATE,
  TARIKH_KEPUTUSAN DATE,
  ID_MASUK  NUMBER,
  ID_KEMASKINI NUMBER,
  TARIKH_MASUK  DATE,
  TARIKH_KEMASKINI DATE,
  CONSTRAINT TBLPPKTUKARPEGAWAI PRIMARY KEY (ID_TUKARPEGAWAI)
);

CREATE OR REPLACE TRIGGER TBLPPKTUKARPEGAWAI_BI    
before insert on     TBLPPKTUKARPEGAWAI    for each row
begin    if :new.ID_TUKARPEGAWAI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKTUKARPEGAWAI_SEQ.NEXTVAL into :new.ID_TUKARPEGAWAI   from dual; end if;    end;
/



CREATE INDEX TBLPPKTUKARPEGAWAI_IDX2 ON TBLPPKTUKARPEGAWAI
(ID_PERBICARAAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKTUKARPEGAWAI_IDX3 ON TBLPPKTUKARPEGAWAI
(ID_PEMOHONTUKARPEGAWAI )
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKTUKARPEGAWAI_IDX4 ON TBLPPKTUKARPEGAWAI
(ID_PEGAWAIASAL)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKTUKARPEGAWAI_IDX5 ON TBLPPKTUKARPEGAWAI
(ID_PEGAWAIBARU)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKTUKARPEGAWAI_IDX6 ON TBLPPKTUKARPEGAWAI
(ID_NEGERIPEGAWAIBARU)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX TBLPPKTUKARPEGAWAI_IDX7 ON TBLPPKTUKARPEGAWAI
(USER_ID_PEGAWAIBARU)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKTUKARPEGAWAI_IDX8 ON TBLPPKTUKARPEGAWAI
(USER_ID_PEGAWAIASAL)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKTUKARPEGAWAI_IDX9 ON TBLPPKTUKARPEGAWAI
(ID_FAIL)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;




CREATE TABLE TBLRUJSEQNOTUKARPEGAWAI
(
  TAHUN       VARCHAR2(4 BYTE),
  ID_NEGERI   VARCHAR2(20 BYTE),
  KOD_MODUL   VARCHAR2(20 BYTE),
  NO_TURUTAN  NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;





CREATE INDEX TBLPPKPENJAGA_IDX1 ON TBLPPKPENJAGA
(ID_OBMINOR)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE INDEX TBLPPKPENJAGA_IDX2 ON TBLPPKPENJAGA
(ID_OB)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          160M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;



