ALTER TABLE EKPTGWP.TBLPPKRAYUAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE EKPTGWP.TBLPPKRAYUAN CASCADE CONSTRAINTS;

CREATE TABLE EKPTGWP.TBLPPKRAYUAN
(
  ID_RAYUAN                 NUMBER CONSTRAINT TBLPPKRAYUAN_C02 NOT NULL,
  ID_PERMOHONAN             NUMBER CONSTRAINT TBLPPKRAYUAN_C01 NOT NULL,
  TARIKH_MOHON              DATE,
  MAKLUMAT_PERAYU           VARCHAR2(2000 BYTE),
  PERKARA_RAYU              CLOB,
  ID_NEGERI                 NUMBER,
  ID_DAERAH                 NUMBER,
  ID_UNITPSK                NUMBER,
  ID_NEGERIUNITPSK          NUMBER,
  ID_JENISPERINTAH          NUMBER,
  ID_KEPUTUSANMAHKAMAH      NUMBER,
  ID_MAHKAMAH               NUMBER,
  ID_KEPUTUSANPEGAWAI       NUMBER,
  CATATAN                   VARCHAR2(2000 BYTE),
  CATATAN_PEGAWAI           VARCHAR2(2000 BYTE),
  ID_MASUK                  NUMBER,
  TARIKH_MASUK              DATE,
  ID_KEMASKINI              NUMBER,
  TARIKH_KEMASKINI          DATE,
  ID_DB                     NUMBER,
  ALASAN_RAYUAN             VARCHAR2(4000 CHAR),
  ASAS_KEPUTUSAN            VARCHAR2(4000 CHAR),
  NOTA_BICARA               VARCHAR2(4000 CHAR),
  ID_PERINTAH               NUMBER,
  PERKARA_RAYU_MEMORANDUM   VARCHAR2(4000 CHAR),
  ALASAN_RAYUAN_MEMORANDUM  VARCHAR2(4000 CHAR),
  JENIS_MIME                VARCHAR2(100 BYTE),
  CONTENT                   BLOB,
  BORANG_A                  VARCHAR2(100 BYTE),
  BORANG_P                  VARCHAR2(100 BYTE),
  BORANG_DDA                VARCHAR2(100 BYTE),
  SA                        VARCHAR2(100 BYTE),
  LAMPIRAN1                 VARCHAR2(50 CHAR),
  FLAMPIRAN1                VARCHAR2(20 BYTE),
  QLAMPIRAN1                VARCHAR2(20 BYTE),
  JUMLAH_BAYARAN            VARCHAR2(20 BYTE),
  F2LAMPIRAN1               VARCHAR2(20 BYTE),
  LAMPIRAN2                 VARCHAR2(50 BYTE),
  FLAMPIRAN2                VARCHAR2(20 BYTE),
  F2LAMPIRAN2               VARCHAR2(20 BYTE),
  QLAMPIRAN2                VARCHAR2(20 BYTE),
  LAMPIRAN3                 VARCHAR2(50 BYTE),
  FLAMPIRAN3                VARCHAR2(20 BYTE),
  F2LAMPIRAN3               VARCHAR2(20 BYTE),
  QLAMPIRAN3                VARCHAR2(20 BYTE),
  LAMPIRAN4                 VARCHAR2(50 BYTE),
  FLAMPIRAN4                VARCHAR2(20 BYTE),
  F2LAMPIRAN4               VARCHAR2(20 BYTE),
  QLAMPIRAN4                VARCHAR2(20 BYTE),
  LAMPIRAN5                 VARCHAR2(50 BYTE),
  FLAMPIRAN5                VARCHAR2(20 BYTE),
  F2LAMPIRAN5               VARCHAR2(20 BYTE),
  QLAMPIRAN5                VARCHAR2(20 BYTE),
  LAMPIRAN6                 VARCHAR2(50 BYTE),
  FLAMPIRAN6                VARCHAR2(20 BYTE),
  F2LAMPIRAN6               VARCHAR2(20 BYTE),
  QLAMPIRAN6                VARCHAR2(20 BYTE),
  LAMPIRAN7                 VARCHAR2(50 BYTE),
  FLAMPIRAN7                VARCHAR2(20 BYTE),
  F2LAMPIRAN7               VARCHAR2(20 BYTE),
  QLAMPIRAN7                VARCHAR2(20 BYTE),
  LAMPIRAN8                 VARCHAR2(50 BYTE),
  FLAMPIRAN8                VARCHAR2(20 BYTE),
  F2LAMPIRAN8               VARCHAR2(20 BYTE),
  QLAMPIRAN8                VARCHAR2(20 BYTE)
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (PERKARA_RAYU) STORE AS 
      ( TABLESPACE  PPK01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        INDEX       (
          TABLESPACE PPK01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (CONTENT) STORE AS 
      ( TABLESPACE  PPK01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE PPK01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN EKPTGWP.TBLPPKRAYUAN.ID_KEPUTUSANMAHKAMAH IS 'RUJUK ID_STATUS DALAM TBLRUJSTATUS';

COMMENT ON COLUMN EKPTGWP.TBLPPKRAYUAN.ID_MAHKAMAH IS 'RUJUK ID_PEJABAT DALAM TBLRUJPEJABAT';

COMMENT ON COLUMN EKPTGWP.TBLPPKRAYUAN.ID_KEPUTUSANPEGAWAI IS 'RUJUK ID_STATUS DALAM TBLRUJSTATUS';


CREATE UNIQUE INDEX EKPTGWP.TBLPPKRAYUAN_PK ON EKPTGWP.TBLPPKRAYUAN
(ID_RAYUAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX EKPTGWP.TBLPPKRAYUAN_INDX1 ON EKPTGWP.TBLPPKRAYUAN
(ID_UNITPSK)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX EKPTGWP.TBLPPKRAYUAN_INDX2 ON EKPTGWP.TBLPPKRAYUAN
(ID_JENISPERINTAH)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX EKPTGWP.TBLPPKRAYUAN_INDX3 ON EKPTGWP.TBLPPKRAYUAN
(ID_PERMOHONAN)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER EKPTGWP.TBLPPKRAYUAN_BI    
before insert on     TBLPPKRAYUAN    for each row
begin    if :new.ID_RAYUAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKRAYUAN_SEQ.NEXTVAL into :new.ID_RAYUAN            from dual;    end if;    end;
/


ALTER TABLE EKPTGWP.TBLPPKRAYUAN ADD (
  CONSTRAINT TBLPPKRAYUAN_PK
 PRIMARY KEY
 (ID_RAYUAN)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE EKPTGWP.TBLPPKRAYUAN ADD (
  CONSTRAINT TBLPPKRAYUAN_FK3 
 FOREIGN KEY (ID_JENISPERINTAH) 
 REFERENCES EKPTGWP.TBLPPKRUJJENISPERINTAH (ID_JENISPERINTAH),
  CONSTRAINT TBLPPKRAYUAN_FK2 
 FOREIGN KEY (ID_UNITPSK) 
 REFERENCES EKPTGWP.TBLPPKRUJUNIT (ID_UNITPSK),
  CONSTRAINT TBLPPKRAYUAN_FK1 
 FOREIGN KEY (ID_PERMOHONAN) 
 REFERENCES EKPTGWP.TBLPPKPERMOHONAN (ID_PERMOHONAN));

ALTER TABLE EKPTGWP.TBLPPKPERAYU ADD (
  CONSTRAINT TBLPPKPERAYU_FK1 
 FOREIGN KEY (ID_RAYUAN) 
 REFERENCES EKPTGWP.TBLPPKRAYUAN (ID_RAYUAN));

ALTER TABLE EKPTGWP.TBLPPKSERAHANRAYUAN ADD (
  CONSTRAINT TBLPPKSERAHANRAYUAN_FK1 
 FOREIGN KEY (ID_RAYUAN) 
 REFERENCES EKPTGWP.TBLPPKRAYUAN (ID_RAYUAN));
SET DEFINE OFF;
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (14102, 1610548424, TO_DATE('04/27/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'zxc', 
    NULL, NULL, NULL, NULL, NULL, 
    167, 193, 164, NULL, NULL, 
    14101126, TO_DATE('04/27/2010 17:24:37', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('04/27/2010 17:32:45', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'rty', 'qwe', 'asd', 1610280674, 'zxc', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (14101, 431511, TO_DATE('04/27/2010 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'aaa', 
    NULL, NULL, NULL, NULL, NULL, 
    166, 142, 164, NULL, NULL, 
    14101126, TO_DATE('04/27/2010 16:43:33', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('04/27/2010 16:54:38', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'bbb', 'asd', 'zxc', 207788, 'aaa', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (16173, 1610548423, TO_DATE('01/27/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'rayuan', 
    NULL, NULL, NULL, NULL, NULL, 
    180, 142, 164, NULL, 'DSDF', 
    14101126, TO_DATE('03/09/2017 09:36:57', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('03/09/2017 09:40:58', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'diterima', 'Ditolak', 'sdf', 1610280672, 'rayuan', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (16174, 1610548419, TO_DATE('01/27/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'test', 
    NULL, NULL, NULL, NULL, NULL, 
    166, 142, 164, NULL, NULL, 
    14101126, TO_DATE('03/09/2017 09:46:08', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('04/05/2017 11:23:12', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'dfdsf', 'testing 123', 'test', 1610280667, 'test', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (161710, 1610548409, TO_DATE('03/16/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'PERINTAH PEMBAHAGIAN MENGIKUT FARAID', 
    NULL, NULL, NULL, NULL, NULL, 
    166, 142, 164, NULL, NULL, 
    14101126, TO_DATE('03/20/2017 14:57:01', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('03/20/2017 15:18:33', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    'ALASAN RAYUAN', 'ATAS PERSETUJUAN WARIS', 'TAK PERLU', 1610280676, 'PERINTAH PEMBAHAGIAN MENGIKUT FARAID', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (161714, 1610548404, TO_DATE('03/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'perkara yang dirayu di dalam permohonan rayuan', 
    NULL, NULL, NULL, NULL, NULL, 
    166, 142, 164, NULL, NULL, 
    14101126, TO_DATE('03/21/2017 14:37:09', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('03/23/2017 08:56:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, 'asas-asas keputusan', 'tak perlu ada', 1610280663, 'perkara yang dirayu di dalam keputusan permohonan', 
    'alasan rayuan di dalam keputusan permohonan', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (161715, 1610548402, TO_DATE('03/22/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'perkara yang dirayu di dalam permohonan rayuan', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    14101126, TO_DATE('03/22/2017 19:59:09', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('03/22/2017 20:00:25', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, 'asas-asas keputusan di dalam permohonan rayuan', 'maklumat nota bicara di dalam permohonan rayuan', 1610280648, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGWP.TBLPPKRAYUAN
   (ID_RAYUAN, ID_PERMOHONAN, TARIKH_MOHON, MAKLUMAT_PERAYU, PERKARA_RAYU, 
    ID_NEGERI, ID_DAERAH, ID_UNITPSK, ID_NEGERIUNITPSK, ID_JENISPERINTAH, 
    ID_KEPUTUSANMAHKAMAH, ID_MAHKAMAH, ID_KEPUTUSANPEGAWAI, CATATAN, CATATAN_PEGAWAI, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB, 
    ALASAN_RAYUAN, ASAS_KEPUTUSAN, NOTA_BICARA, ID_PERINTAH, PERKARA_RAYU_MEMORANDUM, 
    ALASAN_RAYUAN_MEMORANDUM, JENIS_MIME, CONTENT, BORANG_A, BORANG_P, 
    BORANG_DDA, SA, LAMPIRAN1, FLAMPIRAN1, QLAMPIRAN1, 
    JUMLAH_BAYARAN, F2LAMPIRAN1, LAMPIRAN2, FLAMPIRAN2, F2LAMPIRAN2, 
    QLAMPIRAN2, LAMPIRAN3, FLAMPIRAN3, F2LAMPIRAN3, QLAMPIRAN3, 
    LAMPIRAN4, FLAMPIRAN4, F2LAMPIRAN4, QLAMPIRAN4, LAMPIRAN5, 
    FLAMPIRAN5, F2LAMPIRAN5, QLAMPIRAN5, LAMPIRAN6, FLAMPIRAN6, 
    F2LAMPIRAN6, QLAMPIRAN6, LAMPIRAN7, FLAMPIRAN7, F2LAMPIRAN7, 
    QLAMPIRAN7, LAMPIRAN8, FLAMPIRAN8, F2LAMPIRAN8, QLAMPIRAN8)
 Values
   (161716, 1610548391, TO_DATE('03/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Perkara yang dirayu di dalam maklumat rayuan <font color="blue">14/03/2017</font>', 
    NULL, NULL, NULL, NULL, NULL, 
    166, 142, 164, 'CATATAN', NULL, 
    14101126, TO_DATE('04/05/2017 11:25:16', 'MM/DD/YYYY HH24:MI:SS'), 14101126, TO_DATE('04/13/2017 09:57:45', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, 'asas-asas keputusan', 'nota bicara', 1610280630, 'perkara yang dirayu', 
    'alasan rayuan', 'image/png', '‰PNG
