
--new role untuk modul aduan

Insert into ROLE
   (NAME, DESCRIPTION, THEME, ROLE_DETAILS)
 Values
   ('helpdesk', 'Help Desk PPK', 'eTapp_Aduan.css', 'PENDAFTAR ADUAN DARI HELPDESK');
   
UPDATE ROLE SET DESCRIPTION = 'PENYEMAK & PENGAGIH ADUAN' WHERE NAME = 'user_unit_intergriti'

Insert into TBLRUJKATEGORIADUANPUBLIC
   (ID_KATEGORIADUANPUBLIC, KATEGORIADUAN, KATEGORIADUAN_ENG, ID_MASUK, ID_KEMASKINI, 
    TARIKH_MASUK, TARIKH_KEMASKINI)
 Values
   (99180, 'PENGURUSAN PEMBAHAGIAN PUSAKA', 'PENGURUSAN PEMBAHAGIAN PUSAKA', NULL, NULL, 
    NULL, NULL);
    
Insert into TBLRUJKATEGORIPERTANYAAN
   (ID_KATEGORIPERTANYAAN, KATEGORIPERTANYAAN, KATEGORIPERTANYAAN_ENG, ID_MASUK, ID_KEMASKINI, 
    TARIKH_MASUK, TARIKH_KEMASKINI)
 Values
   (16173, 'PENGURUSAN PEMBAHAGIAN PUSAKA', 'PENGURUSAN PEMBAHAGIAN PUSAKA', NULL, NULL, 
    NULL, NULL);
    
ALTER TABLE
  TBLADUANPUBLIC
ADD
(
   ID_HELPDESK  NUMBER,
   ID_UNIT  NUMBER,
   NO_FAIL  VARCHAR(100),
   FLAG_HELPDESK  VARCHAR(1)
);

UPDATE TBLRUJSTATUSADUANPUBLIC SET KETERANGAN = 'DALAM SEMAKAN / AGIHAN', KETERANGAN_ENG = 'DALAM SEMAKAN / AGIHAN' WHERE  ID_STATUS = '16122';

UPDATE TBLRUJSTATUSADUANPUBLIC SET KETERANGAN = 'HANTAR KE BAHAGIAN / UNIT', KETERANGAN_ENG = 'HANTAR KE BAHAGIAN / UNIT' WHERE  ID_STATUS = '16126';

UPDATE TBLRUJSTATUSADUANPUBLIC SET KETERANGAN = 'DALAM TINDAKAN BAHAGIAN / UNIT', KETERANGAN_ENG = 'DALAM TINDAKAN BAHAGIAN / UNIT' WHERE  ID_STATUS = '16127';

UPDATE TBLRUJKATEGORITINDAKAN SET KATEGORITINDAKAN = 'PENYEMAK & PENGAGIH', KATEGORITINDAKAN_ENG = 'PENYEMAK & PENGAGIH' WHERE  ID_KATEGORITINDAKAN = '16176';

UPDATE TBLRUJKATEGORITINDAKAN SET KATEGORITINDAKAN = 'BPP HQ', KATEGORITINDAKAN_ENG = 'BPP HQ' WHERE  ID_KATEGORITINDAKAN = '16171';

UPDATE TBLRUJKATEGORITINDAKAN SET KATEGORITINDAKAN = 'BPP Negeri', KATEGORITINDAKAN_ENG = 'BPP Negeri' WHERE  ID_KATEGORITINDAKAN = '16172';


UPDATE TBLRUJJAWATAN SET SHORTNAME_JAWATAN = 'PT' WHERE ID_JAWATAN = '24';
   
UPDATE TBLRUJJAWATAN SET SHORTNAME_JAWATAN = 'PN' WHERE ID_JAWATAN = '26';
   
UPDATE TBLRUJJAWATAN SET SHORTNAME_JAWATAN = 'PPTM' WHERE ID_JAWATAN = '18';