

--------------------------------------10/6/2020----------------------------------
----------------------TBLRUJPEJABAT - Majlis Agama Islam

SET DEFINE OFF;
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (4, 38, 2, 61, '01', 'Majlis Agama Islam Melaka', 'Pusat Islam Melaka', 'Bukit Palah', '75400', '06-2836867', '06-2834022', 'Pengerusi', 1, TO_DATE('12/04/2009 16:13:04', 'MM/DD/YYYY HH24:MI:SS'), 108);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, TARIKH_KEMASKINI, ID_BANDAR)
 Values
   (2, 16, 2, 61, '01', 'Majlis Agama Islam Kedah', 'Bangunan Wan Mat Saman', 'Jalan Raja', '05767', '04-7333288', '04-7338333', 'Setiausaha', 1, TO_DATE('12/04/2009 16:16:28', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/21/2017 15:51:53', 'MM/DD/YYYY HH24:MI:SS'), 47);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (8, 64, 2, 61, '01', 'Majlis Agama Islam Perak', 'Tingkat 5, Kompleks Islam Darul Ridzuan', 'Jalan Panglima Bukit Gantang Wahab', '30000', '05-2558148', '05-2555512', 'Yang Dipertua', 1, TO_DATE('12/04/2009 16:22:54', 'MM/DD/YYYY HH24:MI:SS'), 226);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (5, 44, 2, 61, '01', 'Majlis Agama Islam Negeri Sembilan Darul Khusus', 'Karung Berkunci no. 3', '30000', '06-7620642', '06-7620648', 'Setiausaha', 1, TO_DATE('12/04/2009 16:35:03', 'MM/DD/YYYY HH24:MI:SS'), 136);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (10, 37, 2, 61, '01', 'Majlis Agama Islam Selangor', 'Tingkat 9, Menara Utara', 'Bangunan Sultan Idris Shah', '43000', '03-55143400', '03-55124042', 'Setiausaha', 1, TO_DATE('12/04/2009 16:42:59', 'MM/DD/YYYY HH24:MI:SS'), 321);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (7, 61, 2, 61, '01', 'Majlis Agama Islam Pulau Pinang dan Seberang Perai', 'Leboh Pantai', '10300', '04-2612500', '04-2633133', 'Yang Dipertua', 1, TO_DATE('12/04/2009 16:47:24', 'MM/DD/YYYY HH24:MI:SS'), 199);
Insert into TBLRUJPEJABAT
   ( ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (1, 2, 2, 61, '01', 'Majlis Agama Islam Johor', 'Aras 5, Kompleks Islam Johor K/B 725', '80990', '07-2243522', '07-2239062', 'Ketua Pegawai Kerja', 1, TO_DATE('12/04/2009 16:50:32', 'MM/DD/YYYY HH24:MI:SS'), 14);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, ID_BANDAR)
 Values
   (3, 29, 2, 61, '01', 'Majlis Agama Islam dan Adat Istiadat Melayu Kelantan', 'Balai Islam', 'Jalan Sultan Yahya Petra, Lundang', '01000', '09-7481512', '09-7444393', 'Yang Dipertua', 1, TO_DATE('12/04/2009 16:56:41', 'MM/DD/YYYY HH24:MI:SS'), 87);
Insert into TBLRUJPEJABAT
   (ID_NEGERI, ID_DAERAH, ID_SEKSYEN, ID_JENISPEJABAT, KOD_PEJABAT, NAMA_PEJABAT, ALAMAT1, ALAMAT2, ALAMAT3, POSKOD, NO_TEL, NO_FAX, JAWATAN, ID_MASUK, TARIKH_MASUK, TARIKH_KEMASKINI, ID_BANDAR)
 Values
   (14, 121, 2, 61, '01', 'Majlis Agama Islam Wilayah Persekutuan', 'UNIT PENGURUSAN ZAKAT FITRAH DAN SUMBER AM', 'Bahagian Baitulmal , Majlis Agama Islam Wilayah Persekutuan', 'aras 19 bangunan perkim, no 150 jalan sultan azlan shah', '51200', '03-40479444', '03-40440818', 'Yang Dipertua', 1, TO_DATE('12/04/2009 16:59:11', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/17/2018 12:41:45', 'MM/DD/YYYY HH24:MI:SS'), 422);
COMMIT;

--------------------------------20200206------------------------------------------------

28042020--------------------------------------------------------------------------------
--ALTER TABLE TBLPPKDOKUMENSIMATI RENAME COLUMN ID_RUJUKAN TO NO_RUJUKAN;

15042020--------------------------------------------------------------------------------
--ALTER TABLE TBLPPKDOKUMENSIMATI ADD (NO_RUJUKAN VARCHAR2(30));

06022020--------------------------------------------------------------------------------

--DROP TRIGGER PPKDOKUMENSIMATI_BI;
-- 2020/04/13 (ekptghqfat)

CREATE OR REPLACE TRIGGER PPKDOKUMENSIMATI_BI    
before insert on     TBLPPKDOKUMENSIMATI    for each row
begin    if :new.ID_DOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || PPKDOKUMENSIMATI_SEQ.NEXTVAL into :new.ID_DOKUMEN          from dual;    end if;    end;
/

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--06/02/2020 
--DROP SEQUENCE PPKDOKUMENSIMATI_SEQ;

-- 2020/04/13 (ekptghqfat)
CREATE SEQUENCE PPKDOKUMENSIMATI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
-- 2020/04/13 (ekptghqfat)
ALTER TABLE TBLPPKDOKUMENSIMATI ADD CONSTRAINT PPKDOKUMENSIMATI_PK PRIMARY KEY (ID_DOKUMEN) ENABLE;

CREATE TABLE TBLPPKDOKUMENSIMATI (
	ID_DOKUMEN NUMBER(16,0),
	ID_SIMATI NUMBER(16,0),
	ID_JENISDOKUMEN NUMBER(16,0),
	NO_RUJUKAN VARCHAR2(30),
	NAMA_DOKUMEN VARCHAR2(200),
	FORMAT VARCHAR2(100),
	SAIZ NUMBER(16,0),
	KANDUNGAN BLOB,
	TARIKH_MASUK DATE,
	ID_MASUK NUMBER(16,0),
	TARIKH_KEMASKINI DATE,
	ID_KEMASKINI NUMBER(16,0)
);

SELECT * FROM TBLPPKDOKUMENSIMATI



--------------------------------------15/10/2020----------------------------------
-------TBLPPKLOGTUGASAN

ALTER TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN
(
  ID_TUGASAN          NUMBER                    NOT NULL,
  ID_PEGAWAI          NUMBER,
  ID_NEGERI           NUMBER,
  TARIKH_DITUGASKAN   DATE,
  ID_FAIL             NUMBER,
  FLAG_AKTIF          VARCHAR2(1 BYTE),
  ROLE                VARCHAR2(100 BYTE),
  CATATAN             VARCHAR2(4000 BYTE),
  ID_PEGAWAI_SEBELUM  NUMBER,
  ID_NEGERI_SEBELUM   NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGHQLIVE.TBLPPKLOGTUGASAN_PK ON EKPTGHQLIVE.TBLPPKLOGTUGASAN
(ID_TUGASAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN ADD (
  CONSTRAINT TBLPPKLOGTUGASAN_PK
 PRIMARY KEY
 (ID_TUGASAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--------------------------------------16/10/2020----------------------------------
-------TBLPPKPERUBAHANAKTA

ALTER TABLE EKPTGHQUAT.TBLPPKPERUBAHANAKTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQUAT.TBLPPKPERUBAHANAKTA CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQUAT.TBLPPKPERUBAHANAKTA
(
  ID_PERUBAHAN                  NUMBER,
  FLAG_EMAIL_PEMOHON            VARCHAR2(2 BYTE),
  FLAG_NOTELEFONBIMBIT_PEMOHON  VARCHAR2(2 BYTE),
  FLAG_EMAIL_WARIS              VARCHAR2(2 BYTE),
  FLAG_DENDA                    VARCHAR2(2 BYTE),
  FLAG_5JUTA                    VARCHAR2(2 BYTE),
  FLAG_PENGECUALIAN             VARCHAR2(2 BYTE),
  AKSES_SKRIN_KEPBICARA         VARCHAR2(2 BYTE),
  FLAG_KEMASKINIPERINTAH_PT     VARCHAR2(2 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EKPTGHQUAT.TBLPPKPERUBAHANAKTA_INDEX ON EKPTGHQUAT.TBLPPKPERUBAHANAKTA
(FLAG_EMAIL_PEMOHON)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EKPTGHQUAT.TBLPPKPERUBAHANAKTA_PK ON EKPTGHQUAT.TBLPPKPERUBAHANAKTA
(ID_PERUBAHAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EKPTGHQUAT.TBLPPKPERUBAHANAKTA ADD (
  CONSTRAINT TBLPPKPERUBAHANAKTA_PK
 PRIMARY KEY
 (ID_PERUBAHAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;
Insert into EKPTGHQUAT.TBLPPKPERUBAHANAKTA
   (ID_PERUBAHAN, FLAG_EMAIL_PEMOHON, FLAG_NOTELEFONBIMBIT_PEMOHON, FLAG_EMAIL_WARIS, FLAG_DENDA, 
    FLAG_5JUTA, FLAG_PENGECUALIAN, AKSES_SKRIN_KEPBICARA, FLAG_KEMASKINIPERINTAH_PT)
 Values
   (1, 'F', 'F', 'F', 'F', 
    'T', 'F', 'T', 'T');
COMMIT;

--------------------------------------16/10/2020----------------------------------
-------TBLPPKPRAPERBICARAAN

ALTER TABLE EKPTGHQUAT.TBLPPKPRAPERBICARAAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQUAT.TBLPPKPRAPERBICARAAN CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQUAT.TBLPPKPRAPERBICARAAN
(
  ID_NOTISPRAPERBICARAAN    NUMBER              NOT NULL,
  ID_PRAPERBICARAAN         NUMBER              NOT NULL,
  ID_MASUK                  NUMBER,
  TARIKH_MASUK              DATE,
  ID_KEMASKINI              NUMBER,
  TARIKH_KEMASKINI          DATE,
  KEPUTUSAN_PRAPERBICARAAN  VARCHAR2(10 BYTE),
  CATATAN_KEPUTUSAN         VARCHAR2(100 BYTE),
  TARIKH_INKUIRI            DATE,
  SEBAB_INKUIRI             VARCHAR2(10 BYTE),
  CATATAN_SEBABINKUIRI      VARCHAR2(100 BYTE),
  CATATAN_NOTIS             VARCHAR2(100 BYTE),
  ID_PERMOHONAN             NUMBER(20),
  ALAMAT_BICARA1            VARCHAR2(100 BYTE),
  ALAMAT_BICARA2            VARCHAR2(100 BYTE),
  ALAMAT_BICARA3            VARCHAR2(100 BYTE),
  POSKOD_BICARA             NUMBER,
  IDNEGERI_BICARA           NUMBER,
  MASA_BICARA               VARCHAR2(4 BYTE),
  JENIS_MASA_BICARA         VARCHAR2(1 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGHQUAT.TBLPPKPRAPERBICARAAN_PK ON EKPTGHQUAT.TBLPPKPRAPERBICARAAN
(ID_NOTISPRAPERBICARAAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EKPTGHQUAT.TBLPPKPRAPERBICARAAN ADD (
  CONSTRAINT TBLPPKPRAPERBICARAAN_PK
 PRIMARY KEY
 (ID_NOTISPRAPERBICARAAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (992013, 992013, 10101144, TO_DATE('06/19/2020 18:42:21', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('06/19/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '1', 
    NULL, 'CATATAN8', 99191236213, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (992014, 992014, 10101144, TO_DATE('06/22/2020 19:26:50', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('06/25/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    NULL, 'KEMUKAKAN SIJIL MATI DARI MAHKAMAH', 99191234004, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (992020, 992020, 10101144, TO_DATE('06/23/2020 15:30:57', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('06/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '1', 
    NULL, 'CATATAN', 99191201835, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (992027, 992027, 10101144, TO_DATE('07/20/2020 14:18:49', 'MM/DD/YYYY HH24:MI:SS'), 10101144, 
    TO_DATE('07/20/2020 17:48:49', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, TO_DATE('07/23/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '3', 
    NULL, 'DIMINTA MEMBAWA SIJIL KEMATIAN YANG TERKINI DISEBABKAN NAMA SIMATI BERBEZA DENGAN BUKTI KEMATIAN.', 99191187687, 'ALAMAT', 'ALAMAT1', 
    'ALAMAT2', 61000, 10, '0400', '3');
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (992022, 992022, 10101144, TO_DATE('06/24/2020 16:36:15', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('06/29/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    NULL, 'SILA BAWA SIJIL KEMATIAN ORIGINAL', 99201238553, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (99201, 99201, 7101146, TO_DATE('07/21/2020 16:29:11', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('07/23/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '2', 
    NULL, 'SILA BAWA SIJIL KEMATIAN YANG ASAL PADA HARI PERBICARAAN.', 99201267366, 'ALAMAT1', 'ALAMAT2', 
    'ALAMAT3', 68100, 10, '0400', '3');
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (99203, 99203, 10101144, TO_DATE('10/12/2020 12:02:23', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    NULL, NULL, NULL, TO_DATE('10/15/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '1', 
    NULL, 'MEMBERI KETERANGAN BERHUBUNG PERLANTIKAN SAHABAT DAN PENJAGA', 99201259697, 'ALAMAT1', 'ALAMAT2', 
    'ALAMAT3', 68100, 10, '1200', '2');
Insert into EKPTGHQUAT.TBLPPKPRAPERBICARAAN
   (ID_NOTISPRAPERBICARAAN, ID_PRAPERBICARAAN, ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, 
    TARIKH_KEMASKINI, KEPUTUSAN_PRAPERBICARAAN, CATATAN_KEPUTUSAN, TARIKH_INKUIRI, SEBAB_INKUIRI, 
    CATATAN_SEBABINKUIRI, CATATAN_NOTIS, ID_PERMOHONAN, ALAMAT_BICARA1, ALAMAT_BICARA2, 
    ALAMAT_BICARA3, POSKOD_BICARA, IDNEGERI_BICARA, MASA_BICARA, JENIS_MASA_BICARA)
 Values
   (99202, 99202, 10101144, TO_DATE('10/12/2020 11:53:50', 'MM/DD/YYYY HH24:MI:SS'), 16125884, 
    TO_DATE('10/13/2020 08:49:12', 'MM/DD/YYYY HH24:MI:SS'), '1', 'SUMMARY DISTRIBUTION', TO_DATE('10/15/2020 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '1', 
    NULL, 'MEMBERI KETERANGAN BERHUBUNG PERLANTIKAN SAHABAT DAN PENJAGA', 99201259697, 'ALAMAT1', 'ALAMAT2', 
    'ALAMAT3', 68100, 10, '1200', '2');
COMMIT;




--------------------------------------16/10/2020----------------------------------
-------TBLPPKRUJTARAFKPTG
ALTER TABLE EKPTGHQUAT.TBLPPKRUJTARAFKPTG
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQUAT.TBLPPKRUJTARAFKPTG CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQUAT.TBLPPKRUJTARAFKPTG
(
  ID_TARAFKPTG      NUMBER CONSTRAINT TBLPPKRUJTARAFKPTG_C01 NOT NULL,
  KOD               VARCHAR2(2 BYTE),
  KETERANGAN        VARCHAR2(250 BYTE),
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE,
  ID_DB             NUMBER
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGHQUAT.TBLREFPPKTARAFKPTG_PK ON EKPTGHQUAT.TBLPPKRUJTARAFKPTG
(KOD)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EKPTGHQUAT.TBLRUJPPKTARAFKPTG_PK ON EKPTGHQUAT.TBLPPKRUJTARAFKPTG
(ID_TARAFKPTG)
LOGGING
TABLESPACE IDX01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER EKPTGHQUAT."TBLPPKRUJTARAFKPTG_BI" 
before insert on     TBLPPKRUJTARAFKPTG    for each row
begin    if :new.ID_TARAFKPTG    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPKRUJTARAFKPTG_SEQ.NEXTVAL into :new.ID_TARAFKPTG            from dual;    end if;    end;
/


ALTER TABLE EKPTGHQUAT.TBLPPKRUJTARAFKPTG ADD (
  CONSTRAINT TBLRUJPPKTARAFKPTG_PK
 PRIMARY KEY
 (ID_TARAFKPTG)
    USING INDEX 
    TABLESPACE IDX01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EKPTGHQUAT.TBLPPKRUJTARAFKPTG TO EKPTGSYNC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON EKPTGHQUAT.TBLPPKRUJTARAFKPTG TO PPTMHQ;


SET DEFINE OFF;
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (22, '21', 'PENTADBIR TANAH', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (21, '20', 'LAIN-LAIN AGENSI', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (16, '16', 'KETUA PENGARAH INSOLVENSI', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (17, '17', 'KERAJAAN NEGERI / WILAYAH PERSEKUTUAN', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (18, '18', 'KUMPULAN WANG DISATUKAN PERBENDAHARAAN MALAYSIA', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (19, '15', 'PENYEWA', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (1, '01', 'WARIS-WARIS SIMATI', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (2, '02', 'PEMIUTANG DAN PENGKAVEAT', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (3, '03', 'PEMBELI DIBAWAH SURAT PERJANJIAN JUAL BELI YANG SAH', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (4, '04', 'PEMEGANG GADAIAN ATAU PEMEGANG PAJAKAN TANAH SIMATI', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (5, '05', 'PENGHULU ATAU PEGAWAI PETEMPATAN YANG DIARAHKAN OLEH PENTADBIR TANAH', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (6, '06', 'AMANAH RAYA BERHAD', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (7, '07', 'PENJAGA', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (8, '08', 'BAITULMAL', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (9, '09', 'PENERIMA HIBAH', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (10, '10', 'PEMEGANG AMANAH', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (11, '11', 'PENERIMA HARTA SEPENCARIAN', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (12, '12', 'PEMEGANG SURAT KUASA ', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (13, '13', 'LAIN-LAIN ORANG KEPENTINGAN', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (14, '14', 'SAKSI YANG HADIR', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (0, '00', 'TIADA MAKLUMAT', NULL, NULL, 
    NULL, NULL, NULL);
Insert into EKPTGHQUAT.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (20, '19', 'MAJLIS AGAMA ISLAM NEGERI ', NULL, NULL, 
    NULL, NULL, NULL);
COMMIT;

