
--------------------------------09062020 (arief)------------------------------------------------
------------------update TBLRUJSTATUS 09062020 (arief)-------------------------
Insert into EKPTGHQLIVE.TBLRUJSTATUS
   (ID_STATUS, KOD_STATUS, KETERANGAN, ID_MASUK, ID_KEMASKINI, 
    TARIKH_MASUK, TARIKH_KEMASKINI, ID_SEKSYEN)
 Values
   (115, '115', 'SUMMARY DISTRIBUTION', NULL, NULL, 
    NULL, NULL, 3);

------------------update TBLPPKRUJTARAFKPTG 09062020 (arief)-------------------
Insert into EKPTGHQLIVE.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (20, '19', 'MAJLIS AGAMA ISLAM', NULL, NULL, 
    NULL, NULL, NULL);

Insert into EKPTGHQLIVE.TBLPPKRUJTARAFKPTG
   (ID_TARAFKPTG, KOD, KETERANGAN, ID_MASUK, TARIKH_MASUK, 
    ID_KEMASKINI, TARIKH_KEMASKINI, ID_DB)
 Values
   (21, '20', 'LAIN-LAIN AGENSI', NULL, NULL, 
    NULL, NULL, NULL);
    
    
---------------------TBLPPKPERUBAHANAKTA 09062020 (arief)-----------------------------

ALTER TABLE EKPTGHQLIVE.TBLPPKPERUBAHANAKTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQLIVE.TBLPPKPERUBAHANAKTA CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQLIVE.TBLPPKPERUBAHANAKTA
(
  ID_PERUBAHAN                  NUMBER,
  FLAG_EMAIL_PEMOHON            VARCHAR2(2 BYTE),
  FLAG_NOTELEFONBIMBIT_PEMOHON  VARCHAR2(2 BYTE),
  FLAG_EMAIL_WARIS              VARCHAR2(2 BYTE),
  FLAG_5JUTA                    VARCHAR2(2 BYTE),
  ID_MASUK                      NUMBER,
  TARIKH_MASUK                  DATE,
  ID_KEMASKINI                  NUMBER,
  TARIKH_KEMASKINI              DATE
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX EKPTGHQLIVE.TBLPPKPERUBAHANAKTA_INDEX ON EKPTGHQLIVE.TBLPPKPERUBAHANAKTA
(FLAG_EMAIL_PEMOHON)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX EKPTGHQLIVE.TBLPPKPERUBAHANAKTA_PK ON EKPTGHQLIVE.TBLPPKPERUBAHANAKTA
(ID_PERUBAHAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

---------------------TBLPPKPERUBAHANAKTA 09062020 (arief)------------------------------
ALTER TABLE EKPTGHQLIVE.TBLPPKPERUBAHANAKTA ADD (
  CONSTRAINT TBLPPKPERUBAHANAKTA_PK
 PRIMARY KEY
 (ID_PERUBAHAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;
Insert into EKPTGHQLIVE.TBLPPKPERUBAHANAKTA
   (ID_PERUBAHAN, FLAG_EMAIL_PEMOHON, FLAG_NOTELEFONBIMBIT_PEMOHON, FLAG_EMAIL_WARIS, FLAG_5JUTA, 
    ID_MASUK, TARIKH_MASUK, ID_KEMASKINI, TARIKH_KEMASKINI)
 Values
   (1, 'F', 'F', 'F', 'F', 
    NULL, NULL, NULL, NULL);
COMMIT;

ALTER TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN
 DROP PRIMARY KEY CASCADE;

DROP TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN CASCADE CONSTRAINTS;

CREATE TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN
(
  ID_TUGASAN          NUMBER                    NOT NULL,
  ID_PEGAWAI          NUMBER,
  ID_NEGERI           NUMBER,
  TARIKH_DITUGASKAN   DATE,
  ID_FAIL             NUMBER,
  FLAG_AKTIF          VARCHAR2(1 BYTE),
  ROLE                VARCHAR2(100 BYTE),
  CATATAN             VARCHAR2(4000 BYTE),
  ID_PEGAWAI_SEBELUM  NUMBER,
  ID_NEGERI_SEBELUM   NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EKPTGHQLIVE.TBLPPKLOGTUGASAN_PK ON EKPTGHQLIVE.TBLPPKLOGTUGASAN
(ID_TUGASAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE EKPTGHQLIVE.TBLPPKLOGTUGASAN ADD (
  CONSTRAINT TBLPPKLOGTUGASAN_PK
 PRIMARY KEY
 (ID_TUGASAN)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

    
    
--------------------------------20200206------------------------------------------------

28042020--------------------------------------------------------------------------------
--ALTER TABLE TBLPPKDOKUMENSIMATI RENAME COLUMN ID_RUJUKAN TO NO_RUJUKAN;

15042020--------------------------------------------------------------------------------
--ALTER TABLE TBLPPKDOKUMENSIMATI ADD (NO_RUJUKAN VARCHAR2(30));

06022020--------------------------------------------------------------------------------

--DROP TRIGGER PPKDOKUMENSIMATI_BI;
-- 2020/04/13 (ekptghqfat)

CREATE OR REPLACE TRIGGER PPKDOKUMENSIMATI_BI    
before insert on     TBLPPKDOKUMENSIMATI    for each row
begin    if :new.ID_DOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || PPKDOKUMENSIMATI_SEQ.NEXTVAL into :new.ID_DOKUMEN          from dual;    end if;    end;
/

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--06/02/2020 
--DROP SEQUENCE PPKDOKUMENSIMATI_SEQ;

-- 2020/04/13 (ekptghqfat)
CREATE SEQUENCE PPKDOKUMENSIMATI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
-- 2020/04/13 (ekptghqfat)
ALTER TABLE TBLPPKDOKUMENSIMATI ADD CONSTRAINT PPKDOKUMENSIMATI_PK PRIMARY KEY (ID_DOKUMEN) ENABLE;

CREATE TABLE TBLPPKDOKUMENSIMATI (
	ID_DOKUMEN NUMBER(16,0),
	ID_SIMATI NUMBER(16,0),
	ID_JENISDOKUMEN NUMBER(16,0),
	NO_RUJUKAN VARCHAR2(30),
	NAMA_DOKUMEN VARCHAR2(200),
	FORMAT VARCHAR2(100),
	SAIZ NUMBER(16,0),
	KANDUNGAN BLOB,
	TARIKH_MASUK DATE,
	ID_MASUK NUMBER(16,0),
	TARIKH_KEMASKINI DATE,
	ID_KEMASKINI NUMBER(16,0)
);

SELECT * FROM TBLPPKDOKUMENSIMATI
