--aishahlatip 07/05/2018
ALTER TABLE EKPTGHQLIVE.TBLPPKPERINTAHHTAOBMST
MODIFY(CATATAN VARCHAR2(4000 BYTE));



--Mohamad Rosli 0/05/2018
DROP VIEW VPPK_DAERAHJAGAAN;

CREATE OR REPLACE FORCE VIEW VPPK_DAERAHJAGAAN (id_daerah,
                                            id_user)
AS
    SELECT DISTINCT u.id_daerahurus id_daerah,ur.user_id id_user
    FROM tblrujpejabaturusan u,users_internal ur
    WHERE u.id_pejabatjkptg = ur.id_pejabatjkptg
    --AND ur.user_id = 161725699
    --
    UNION
    --
    SELECT DISTINCT rpu.id_daerahurus id_daerah,pbu.id_pemohon id_user
    FROM tblpermohonanbantuunit pbu,tblrujpejabaturusan rpu
    WHERE pbu.id_status = 2
    AND TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY') >=
        TO_DATE(TO_CHAR(pbu.tarikh_mula,'DD/MM/YYYY'),'DD/MM/YYYY')
    AND TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY') <=
        TO_DATE(TO_CHAR(pbu.tarikh_akhir,'DD/MM/YYYY'),'DD/MM/YYYY')
    AND pbu.id_unit = rpu.id_pejabatjkptg
    --AND pbu.id_pemohon = 161725699
;




--RAZMAN 09/04/2018
ALTER TABLE
  TBLPPKPERINTAH
ADD
(
   FLAG_BANTAHAN VARCHAR2(1 BYTE),
   ID_INTROPERINTAH  NUMBER,
   CATATAN_PERINTAH_BI  CLOB,   
   CATATAN_KEPUTUSAN_PERBICARAAN  CLOB,
   INTROFIELD1 VARCHAR2(4000 BYTE),
   INTROFIELD2 VARCHAR2(4000 BYTE),
   INTROFIELD3 VARCHAR2(4000 BYTE)
)



--RAZMAN 20/03/2017
ALTER TABLE
   TBLPPKKEPUTUSANPERMOHONAN
ADD
(
FLAG_SEBABPINDAHMAHKAMAH VARCHAR2(1)
);

comment on column TBLPPKKEPUTUSANPERMOHONAN.FLAG_SEBABPINDAHMAHKAMAH
  is '1-HARTA LEBIH 2 JUTA, 2-WASIAT ';
 


--aishahlatip22022018
ALTER TABLE TBLPPKHA
MODIFY(NAMA_SAHAM VARCHAR2(100 BYTE));

--aishahlatip14022018
ALTER TABLE TBLPPKHTA
MODIFY(NAMA_PEMAJU VARCHAR2(150 BYTE));


--AISHAHLATIP06112017

ALTER TABLE TBLRUJSEQESNOPINDAAN
ADD (NAMA_BORANG VARCHAR2(50 BYTE));

COMMENT ON COLUMN 
TBLRUJSEQESNOPINDAAN.NAMA_BORANG IS 
'NAMA BORANG UNTUK JANA NO PINDAAN';


--AISHAHLATIP02102017

ALTER TABLE TBLPPKDOKUMEN
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPPKDOKUMEN CASCADE CONSTRAINTS;

CREATE TABLE TBLPPKDOKUMEN
(
  ID_DOKUMEN        NUMBER(16),
  NAMA_DOKUMEN      VARCHAR2(200 BYTE),
  FORMAT            VARCHAR2(100 BYTE),
  SAIZ              NUMBER(16),
  KANDUNGAN         BLOB,
  TARIKH_MASUK      DATE,
  ID_MASUK          NUMBER(16),
  TARIKH_KEMASKINI  DATE,
  ID_KEMASKINI      NUMBER(16)
)
TABLESPACE EKPTGDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (KANDUNGAN) STORE AS 
      ( TABLESPACE  EKPTGDATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE EKPTGDATA
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLPPKDOKUMEN_PK ON TBLPPKDOKUMEN
(ID_DOKUMEN)
LOGGING
TABLESPACE EKPTGDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER TBLPPKDOKUMEN_BI    
before insert on     TBLPPKDOKUMEN    for each row
begin    if :new.ID_DOKUMEN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPHPRUJDOKUMEN_SEQ.NEXTVAL into :new.ID_DOKUMEN           from dual;    end if;    end;
/


ALTER TABLE TBLPPKDOKUMEN ADD (
  CONSTRAINT TBLPPKDOKUMEN_PK
 PRIMARY KEY
 (ID_DOKUMEN)
    USING INDEX 
    TABLESPACE EKPTGDATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TBLPPKUPLOADNOTABICARA ADD (
  CONSTRAINT TBLPPKUPLOADNOTABICARA_FK1 
 FOREIGN KEY (ID_DOKUMEN) 
 REFERENCES TBLPPKDOKUMEN (ID_DOKUMEN));

ALTER TABLE TBLPPKUPLOADPELAN ADD (
  CONSTRAINT TBLPPKUPLOADPELAN_FK1 
 FOREIGN KEY (ID_DOKUMEN) 
 REFERENCES TBLPPKDOKUMEN (ID_DOKUMEN));



--aishahlatip 18092017 ( Telah run di poc)
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI JOHOR' where ID_PEJABATJKPTG=82; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI KEDAH' where ID_PEJABATJKPTG=86; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI KELANTAN' where ID_PEJABATJKPTG=88; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI MELAKA' where ID_PEJABATJKPTG=90; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI SEMBILAN' where ID_PEJABATJKPTG=92; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI PAHANG' where ID_PEJABATJKPTG=93; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI PULAU PINANG' where ID_PEJABATJKPTG=95; 
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI PERAK' where ID_PEJABATJKPTG=96;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI PERLIS' where ID_PEJABATJKPTG=97;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI SELANGOR (P)' where ID_PEJABATJKPTG=98;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI TERENGGANU' where ID_PEJABATJKPTG=99;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI SABAH' where ID_PEJABATJKPTG=1611140;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI SARAWAK' where ID_PEJABATJKPTG=1611141;
 update  tblrujpejabatjkptg  set NAMA_PEJABAT = 'UNIT PEMBAHAGIAN NEGERI WILAYAH PERSEKUTUTAN KUALA LUMPUR' where ID_PEJABATJKPTG=100;

--17/09/2017 ( Telah run di poc)
 create table tblppkrujjenistanah as select * from tblrujjenistanah
 

--AISHAH 15092017( Telah run di poc)
ALTER TABLE TBLPERMOHONANBANTUUNIT
ADD (PERMOHONAN_NEGERI VARCHAR2(1 BYTE));

--aishah 13092017
Insert into TBLSEMAKANSENARAI
   (ID_SEMAKANSENARAI, ID_SEMAKAN, ID_URUSAN, KOD_FORM, ATURAN)
 Values
   (16171000000, 9, 382, 'frmPPKSenarai', 25);

--aishah 30082017
ALTER TABLE TBLPPKSIMATI
ADD (TARIKH_SURAT_AKUAN DATE);


--aishah 08062017
ALTER TABLE TBLRUJSEQESNOPINDAAN
ADD (SEKSYEN VARCHAR2(2 BYTE))

COMMENT ON COLUMN 
TBLRUJSEQESNOPINDAAN.SEKSYEN IS 
'Sekyen 8 atau Seksyen 17';


--aishah 29/05/2017

ALTER TABLE TBLPPKBORANG_HISTORY
ADD (FLAG_KEB_KEMASKINI VARCHAR2(1 BYTE));

COMMENT ON COLUMN 
TBLPPKBORANG_HISTORY.FLAG_KEB_KEMASKINI IS 
'Flag menyatakan sama ada fail ini berstatus keb kemaskini';

CREATE TABLE TBLRUJSEQESNOPINDAAN
(
  TAHUN       VARCHAR2(4),
  ID_DAERAH   VARCHAR2(20),
  KOD_MODUL   VARCHAR2(20),
  NO_TURUTAN  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;




--aishah

ALTER TABLE TBLPPKPERMOHONAN
ADD (TUJUAN_PINDAAN VARCHAR2(4000 BYTE))

COMMENT ON COLUMN 
TBLPPKPERMOHONAN.TUJUAN_PINDAAN IS 
'Catatan Tujuan Pindaan';

--en nizam
ALTER TABLE TBLPPKPERMOHONAN
ADD (FLAG_PRINT_NILAIAN_HARTA VARCHAR2(1 BYTE));

-- 2017/05/24 (Staging-ekptgwp2016)
-- 2017/05/25 (POC-ekptg@ekptgc|)
CREATE OR REPLACE FUNCTION GETBUKTIMATI(ID_BUKTIMATI NUMBER,NO_SIJIL_MATI VARCHAR)
    RETURN VARCHAR2 AS
    BUKTI VARCHAR2(100):='';
        BEGIN
          BUKTI :=
                CASE 
                    WHEN ID_BUKTIMATI = 1 THEN ', No. Sijil Mati: '|| NO_SIJIL_MATI
                    WHEN ID_BUKTIMATI = 2 THEN ', Surat Sumpah Kematian: '|| NO_SIJIL_MATI
                    WHEN ID_BUKTIMATI = 3 THEN ', Anggapan Kematian dari Mahkamah Tinggi: '|| NO_SIJIL_MATI
                    WHEN ID_BUKTIMATI = 4 THEN ', No. Permit Kubur: '|| NO_SIJIL_MATI
                    ELSE ''
                END  
                ;
        --    
        RETURN BUKTI;
    END;
/
CREATE OR REPLACE FUNCTION GETALAMATBICARAGABUNG(ALAMAT_BICARA1 VARCHAR,ALAMAT_BICARA2 VARCHAR,ALAMAT_BICARA3 VARCHAR,TEMPAT_BICARA VARCHAR,POSKOD VARCHAR,BANDAR VARCHAR,NAMA_NEGERI VARCHAR)
    RETURN VARCHAR2 AS
    ALAMAT VARCHAR2(250):='';
        BEGIN
          ALAMAT :=
                CASE
                    WHEN ALAMAT_BICARA1 IS NULL THEN REPLACE(REPLACE(UPPER(trim(TEMPAT_BICARA)),','),'&','&#38;')
                    WHEN ALAMAT_BICARA2 IS NULL AND ALAMAT_BICARA3 IS NULL THEN REPLACE(REPLACE(UPPER(trim(TEMPAT_BICARA)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA1)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(POSKOD)),','),'&','&#38;') || ' ' || REPLACE(REPLACE(UPPER(trim(BANDAR)),','),'&','&#38;') ||', '|| REPLACE(REPLACE(UPPER(trim(NAMA_NEGERI)),','),'&','&#38;')
                    WHEN ALAMAT_BICARA2 IS NULL THEN REPLACE(REPLACE(UPPER(trim(TEMPAT_BICARA)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA1)),','),'&','&#38;') ||', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA3)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(POSKOD)),','),'&','&#38;') || ' ' ||REPLACE(REPLACE(UPPER(trim(BANDAR)),','),'&','&#38;') ||', '|| REPLACE(REPLACE(UPPER(trim(NAMA_NEGERI)),','),'&','&#38;')
                    WHEN ALAMAT_BICARA3 IS NULL THEN REPLACE(REPLACE(UPPER(trim(TEMPAT_BICARA)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA1)),','),'&','&#38;') ||', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA2)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(POSKOD)),','),'&','&#38;') || ' ' ||REPLACE(REPLACE(UPPER(trim(BANDAR)),','),'&','&#38;') ||', '|| REPLACE(REPLACE(UPPER(trim(NAMA_NEGERI)),','),'&','&#38;')
                    WHEN ALAMAT_BICARA3 IS NOT NULL THEN REPLACE(REPLACE(UPPER(trim(TEMPAT_BICARA)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA1)),','),'&','&#38;')||', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA2)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(ALAMAT_BICARA3)),','),'&','&#38;') || ', ' || REPLACE(REPLACE(UPPER(trim(POSKOD)),','),'&','&#38;') || ' ' || REPLACE(REPLACE(UPPER(trim(BANDAR)),','),'&','&#38;') ||', '|| REPLACE(REPLACE(UPPER(trim(NAMA_NEGERI)),','),'&','&#38;')
                    ELSE 'TIADA'                     
                END
                ;
        --    
        RETURN ALAMAT;
    END;
/
CREATE OR REPLACE FUNCTION GETNAMAHARI(TARIKH_ DATE)
    RETURN VARCHAR2 AS
    TARIKH VARCHAR2(15):='';
        BEGIN
          TARIKH :=  
                CASE
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='SUNDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='AHAD' THEN 'Ahad'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='MONDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='ISNIN' THEN 'Isnin'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='TUESDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='SELASA' THEN 'Selasa'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='WEDNESDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='RABU' THEN 'Rabu'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='THURSDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='KHAMIS' THEN 'Khamis'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='FRIDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='JUMAAT' THEN 'Jumaat'
                    WHEN TO_CHAR(TARIKH_, 'FMDAY')='SATURDAY' or UPPER(TO_CHAR(TARIKH_, 'FMDAY'))='SABTU' THEN 'Sabtu'
                END
                ;
        --    
        RETURN TARIKH;
    END;
/

CREATE OR REPLACE FUNCTION GETNAMASIMATI(NAMA_SIMATI VARCHAR,NAMA_LAIN VARCHAR)
    RETURN VARCHAR2 AS
    NAMA VARCHAR2(200):='';
        BEGIN
          NAMA :=  
                CASE
                  WHEN NAMA_SIMATI IS NOT NULL AND NAMA_LAIN IS NULL THEN REPLACE(REPLACE(NAMA_SIMATI,'&','&#38;'),'@','&#64;')
                  WHEN NAMA_SIMATI IS NOT NULL AND NAMA_LAIN IS NOT NULL THEN REPLACE(REPLACE(NAMA_SIMATI,'&','&#38;'),'@','&#64;') || ' @ '|| REPLACE(NAMA_LAIN,'&','&#38;')
                  WHEN NAMA_SIMATI IS NULL AND NAMA_LAIN IS NOT NULL THEN REPLACE(REPLACE(NAMA_SIMATI,'&','&#38;'),'@','&#64;')
                END
                ;
        --    
        RETURN NAMA;
    END;
/




ALTER TABLE TBLPPKHANTARPERINTAH
MODIFY(NAMA_PENYERAH VARCHAR2(100 BYTE));

COMMENT ON COLUMN 
TBLPPKPERMOHONAN.FLAG_HANTAR_LPERINTAH IS 
'FLAG MENYATAKAN LAPORAN PERINTAH TELAH DIHANTAR'; 

COMMENT ON COLUMN 
TBLPPKPERMOHONAN.FLAG_EDIT_PERINTAH IS 
'FLAG PEMBETULAN PERINTAH SELEPAS MENDAPAT KEBENARAN KEMASKINI FAIL.1=ada kemaskini dibuat';

--2017/04/21 Run Staging inviroment, db staging
--Aishah, Salnizam
ALTER TABLE TBLPPKPERMOHONAN
ADD (
	TARIKH_EDIT_PERINTAH DATE
	,FLAG_EDIT_PERINTAH NUMBER
	,FLAG_HANTAR_LPERINTAH NUMBER
	)

--2017/04/25 Run Staging inviroment, db staging
	ALTER TABLE TBLPPKPERMOHONAN
ADD (
	TARIKH_MOHON_BICARA_SEMULA DATE
)

COMMENT ON COLUMN 
EKPTGHQ1.TBLPPKPERMOHONAN.TARIKH_EDIT_PERINTAH IS 
'TARIKH KEMASKINI PERINTAH (PEMBETULAN/PINDAAN)';

--tblppkhantarperintah

--2017/04/21 Run Staging inviroment, db staging
ALTER TABLE TBLPPKHANTARPERINTAH
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLPPKHANTARPERINTAH CASCADE CONSTRAINTS;

CREATE TABLE TBLPPKHANTARPERINTAH
(
  ID_PENGHANTARAN      NUMBER                   NOT NULL,
  JENIS_PENGHANTARAN   VARCHAR2(100 BYTE),
  TARIKH_SERAHAN       DATE,
  NAMA_PENERIMA        VARCHAR2(100 BYTE),
  NO_KP_PENERIMA       VARCHAR2(100 BYTE),
  CATATAN              VARCHAR2(4000 BYTE),
  NO_FAIL              VARCHAR2(100 BYTE),
  ID_PERINTAH          NUMBER,
  ID_PENGHANTAR_NOTIS  VARCHAR2(100 BYTE)
)
TABLESPACE PPK01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX TBLPPKHANTARPERINTAH_PK ON TBLPPKHANTARPERINTAH
(ID_PENGHANTARAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLPPKHANTARPERINTAH ADD (
  CONSTRAINT TBLPPKLAPORANHANTARPERINTAH_PK
 PRIMARY KEY
 (ID_PENGHANTARAN));


SET DEFINE OFF;
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161733, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'Pos-Dikembalikan', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161735, 'Pos-Diterima', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161745, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161747, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161751, 'Pos-Dikembalikan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161757, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161767, 'Pos-Dikembalikan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617109, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing1234567890', 'JKPTG/PK/14/00/0809/2015', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617113, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing1234567890', 'JKPTG/PK/14/00/0809/2015', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617117, 'Pos-Diterima', TO_DATE('03/20/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    NULL, 'JKPTG/PK/14/00/0580/2016', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161773, 'Serahan_Tangan', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Test', '780919015719', 
    'testing123', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161775, 'Serahan_Tangan', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161777, 'Serahan Tangan', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161743, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161753, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161779, 'Pos-Diterima', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161785, 'Pos-Diterima', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161787, 'Pos-Diterima', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161789, 'Serahan Tangan', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161791, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '345435', 
    'Testing123', 'JKPTG/PK/14/00/0578/2016', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161795, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'PTG/WP15/168/2004', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161797, 'Serahan Tangan', TO_DATE('01/11/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Abu', '79012129212', 
    'asdsadasdasd', 'PTG/WP15/183/93', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617103, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '345435', 
    'Testing123', 'JKPTG/PK/14/00/0578/2016', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617105, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '345435', 
    'Testing123', 'JKPTG/PK/14/00/0578/2016', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617107, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'PTG/WP15/168/2004', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161721, 'Pos-Diterima', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161717, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161719, 'Pos-Dikembalikan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161727, 'Pos-Diterima', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161729, 'Pos-Dikembalikan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161731, 'Serahan_Tangan', TO_DATE('01/11/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Abu', '79012129212', 
    'asdsadasdasd', 'PTG/WP15/183/93', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161771, 'Serahan_Tangan', TO_DATE('01/11/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Abu', '79012129212', 
    'asdsadasdasd', 'PTG/WP15/183/93', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161781, 'Pos Diterima', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161783, 'Pos Diterima', TO_DATE('03/10/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Testing', '780919015719', 
    'testing1235', 'JKPTG/PK/14/00/0525/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161799, 'Serahan Tangan', TO_DATE('01/05/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing', 'PTG/WP15/24/87', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617101, 'Serahan Tangan', TO_DATE('01/05/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing', 'PTG/WP15/24/87', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617115, 'Serahan Tangan', TO_DATE('03/14/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0574/2016', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617119, 'Serahan Tangan', TO_DATE('03/22/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    NULL, 'JKPTG/PK/14/00/0577/2016', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161737, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161739, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161741, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (16171, 'Pos-Diterima', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161725, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161749, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161755, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161759, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'test', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161793, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '345435', 
    'Testing123', 'JKPTG/PK/14/00/0578/2016', NULL, '12');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (1617111, 'Pos-Diterima', TO_DATE('03/13/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing1234567890', 'JKPTG/PK/14/00/0809/2015', NULL, '17');
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161761, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161763, 'Serahan_Tangan', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161765, 'Pos-Diterima', TO_DATE('01/07/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'testing123', 'PTG/WP15/168/2004', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161769, 'Pos-Diterima', TO_DATE('01/11/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Abu', '79012129212', 
    'asdsadasdasd', 'PTG/WP15/183/93', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161715, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
Insert into TBLPPKHANTARPERINTAH
   (ID_PENGHANTARAN, JENIS_PENGHANTARAN, TARIKH_SERAHAN, NAMA_PENERIMA, NO_KP_PENERIMA, 
    CATATAN, NO_FAIL, ID_PERINTAH, ID_PENGHANTAR_NOTIS)
 Values
   (161723, 'Serahan_Tangan', TO_DATE('01/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Salnizam', '780919015719', 
    'dfsfsfdsf', 'JKPTG/PK/14/00/0543/2015', NULL, NULL);
COMMIT;




--aishah 26/04/2017
CREATE TABLE TBLPPKKIV_HIST
(
  ID_KIVHISTORY   NUMBER,
  ID_PERINTAH     NUMBER,
  ID_PERBICARAAN  NUMBER,
  CHECK_KIV       NUMBER,
  DATE_KIV        DATE,
  CATATAN_KIV     VARCHAR2(4000),
  ID_MASUK		  NUMBER,
  TARIKH_MASUK	  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE SEQUENCE TBLPPKKIV_HIST_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
NOCACHE 
NOCYCLE 
NOORDER ;

-- aishah 5/5/2017
ALTER TABLE TBLPPKRUJUNIT
ADD (USER_ID NUMBER);


 --aishah 24/7/2017
INSERT INTO TBLPPKRUJPENGHANTARNOTIS
(ID_PENGHANTARNOTIS    ,
  KOD_PENGHANTAR_NOTIS  ,
  ID_PEJABATJKPTG       ,
  NAMA   ,
  NO_KP_BARU,
  NO_KP_LAMA  ,
  ID_MASUK   ,
  TARIKH_MASUK ) VALUES
  (99999, 9999, 99999, 'Lain-lain','' ,'','1',sysdate) ;
 
--aishah 24/7/2017
  ALTER TABLE TBLPPKNOTISOBMST
ADD (NAMA_PENGHANTAR_LAIN VARCHAR2(200 BYTE));

