--2017/05/03 Run Staging inviroment, db staging
--2017/05/03 Run POC inviroment, db ekptg (ekptghq)

CREATE SEQUENCE TBLPERMOHONANBANTUUNIT_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

DROP TABLE TBLPERMOHONANBANTUUNIT;

CREATE TABLE TBLPERMOHONANBANTUUNIT
(
  ID_PERMOHONANBANTUUNIT        NUMBER(38),
  ID_PEMOHON NUMBER(38),
  ID_PELULUS NUMBER(38),
  TARIKH_MULA DATE,
  TARIKH_AKHIR DATE,
  TARIKH_MOHON DATE,
  TARIKH_LULUS DATE,
  CATATAN_PEMOHON VARCHAR(4000),
  CATATAN_PELULUS VARCHAR(4000),
  ID_STATUS NUMBER(38),
  NO_BANTUUNIT VARCHAR(100),
  ID_UNIT NUMBER,
  ID_NEGERI NUMBER,
  ID_MASUK        NUMBER(38),
  TARIKH_MASUK      DATE,
  ID_KEMASKINI       NUMBER(38),
  TARIKH_KEMASKINI      DATE
  )
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE OR REPLACE TRIGGER TBLPERMOHONANBANTUUNIT_BI    
before insert on     TBLPERMOHONANBANTUUNIT    for each row
begin    if :new.ID_PERMOHONANBANTUUNIT    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPERMOHONANBANTUUNIT_SEQ.NEXTVAL into :new.ID_PERMOHONANBANTUUNIT   from dual; end if;    end;
/

ALTER TABLE TBLPERMOHONANBANTUUNIT ADD (
  CONSTRAINT TBLPERMOHONANBANTUUNIT_PK
 PRIMARY KEY
 (ID_PERMOHONANBANTUUNIT)
    USING INDEX 
    TABLESPACE ETAPP01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
               

CREATE TABLE TBLRUJSEQESNOBU
(
  TAHUN       VARCHAR2(4 BYTE),
  ID_NEGERI   VARCHAR2(20 BYTE),
  KOD_MODUL   VARCHAR2(20 BYTE),
  NO_TURUTAN  NUMBER
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

