
20200609 UAT--------------------------------------------------------------------------------

ALTER TABLE TBLPPTTANAHUMUM ADD KETERANGAN_KEROSAKAN VARCHAR(400);

SELECT * FROM TBLPPTTANAHUMUM

28042020--------------------------------------------------------------------------------
--2020/04/29 Run Staging
ALTER TABLE TBLRUJJENISPB ADD FLAG_AKTIF VARCHAR(2) DEFAULT 'Y';

UPDATE TBLRUJJENISPB 
SET FLAG_AKTIF='Y'

26/04/2020 Dari Rozi --------------------------------------------------------------------------------
BLPPTHAKMILIKSTRATA 
TBLRUJJENISHAKMILIK (LIST > Tambah TT - STRATA)

PPT 41
DATABASE : tblpptpermohonan
TAMBAH COLUMN 
TARIKH_PENDUDUKAN_MULA (DATE) 
TARIKH_PENDUDUKAN_AKHIR (DATE) 
TEMPOH_PENDUDUKAN (VARCHAR 5)

ALTER TABLE TBLPPTPERMOHONAN ADD TEMPOH_PENDUDUKAN VARCHAR(5);


--02/03/2020
02032020--------------------------------------------------------------------------------

--DROP TRIGGER PPTDOKUMENHAKMILIK_BI;

CREATE OR REPLACE TRIGGER PPTDOKUMENHAKMILIK_BI    
before insert on     TBLPPTDOKUMENHAKMILIK    for each row
begin    if :new.ID_DOKUMEN   is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || PPTDOKUMENHAKMILIK_SEQ.NEXTVAL into :new.ID_DOKUMEN          from dual;    end if;    end;
/

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

--02/03/2020 
--DROP SEQUENCE PPTDOKUMENHAKMILIK_SEQ;

CREATE SEQUENCE PPTDOKUMENHAKMILIK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
CREATE TABLE TBLPPTDOKUMENHAKMILIK (
	ID_DOKUMEN NUMBER(16,0),
	ID_RUJUKAN NUMBER(16,0),
	ID_PERMOHONAN NUMBER(16,0),
	ID_JENISDOKUMEN NUMBER(16,0),
	NAMA_DOKUMEN VARCHAR2(200),
	FORMAT VARCHAR2(100),
	SAIZ NUMBER(16,0),
	KANDUNGAN BLOB,
	TARIKH_DOKUMEN DATE,
	TARIKH_MASUK DATE,
	ID_MASUK NUMBER(16,0),
	TARIKH_KEMASKINI DATE,
	ID_KEMASKINI NUMBER(16,0)
);

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

ALTER TABLE TBLPPTPERMOHONAN
MODIFY(NO_RUJUKAN_PTD VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTPERMOHONAN
MODIFY(NO_RUJUKAN_UPT VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTPERMOHONAN
MODIFY(NO_RUJUKAN_PTG VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTPERMOHONAN
ADD(TARIKH_LENGKAP DATE);

ALTER TABLE TBLPPTWARTA
MODIFY(NO_WARTA VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTHAKMILIKPB
ADD(CATATAN2 VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTTANAHUMUM
ADD(NILAI_TANAH VARCHAR2(4000 BYTE));

ALTER TABLE TBLPPTBANGUNAN
ADD(ID_KATEGORI_TANAH NUMBER);

ALTER TABLE TBLPPTBANGUNAN
ADD(LAIN_JENIS_BANGUNAN VARCHAR2(100 BYTE));

ALTER TABLE TBLPPTENDOSANBORANGD
ADD(CATATAN VARCHAR2(200 BYTE));

ALTER TABLE TBLPPTENDOSANBORANGD
ADD(ID_WARTA NUMBER);

ALTER TABLE TBLPPTENDOSANBORANGD
ADD(TARIKH_BORANGD DATE);

ALTER TABLE TBLPPTPERMOHONAN
ADD(TARIKH_PERMOHONAN_KJP DATE);


CREATE SEQUENCE TBLRUJJENISBANGUNAN_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

ALTER TABLE TBLRUJJENISBANGUNAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE TBLRUJJENISBANGUNAN CASCADE CONSTRAINTS;

CREATE TABLE TBLRUJJENISBANGUNAN
(
  ID_JENIS_BANGUNAN  NUMBER                     NOT NULL,
  NAMA_BANGUNAN      VARCHAR2(100 BYTE),
  KETERANGAN         VARCHAR2(400 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLRUJJENISBANGUNAN_PK ON TBLRUJJENISBANGUNAN
(ID_JENIS_BANGUNAN)
LOGGING
TABLESPACE ETAPP01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE TBLRUJJENISBANGUNAN ADD (
  CONSTRAINT TBLRUJJENISBANGUNAN_PK
 PRIMARY KEY
 (ID_JENIS_BANGUNAN)
    USING INDEX 
    TABLESPACE EKPTG
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));


SET DEFINE OFF;
Insert into TBLRUJJENISBANGUNAN
   (ID_JENIS_BANGUNAN, NAMA_BANGUNAN, KETERANGAN)
 Values
   (2, 'Separuh kekal', 'Bangunan separuh konkrit dan separuh papan');
Insert into TBLRUJJENISBANGUNAN
   (ID_JENIS_BANGUNAN, NAMA_BANGUNAN, KETERANGAN)
 Values
   (3, 'Sementara kekal', 'Binaan bangunan dan papan dan kayu');
Insert into TBLRUJJENISBANGUNAN
   (ID_JENIS_BANGUNAN, NAMA_BANGUNAN, KETERANGAN)
 Values
   (1, 'Kekal', 'Bangunan konkrit dan mendapat kelulusan CF');
Insert into TBLRUJJENISBANGUNAN
   (ID_JENIS_BANGUNAN, NAMA_BANGUNAN, KETERANGAN)
 Values
   (4, 'Lain-lain', 'Lain-lain');


// TBLPPTSENARAISEMAK

ALTER TABLE TBLPPTSENARAISEMAK
ADD(SEMAK8 VARCHAR2(1 BYTE));

COMMENT ON COLUMN TBLPPTSENARAISEMAK.SEMAK8 IS 'Y=YA; T=TIDAK';


//TBLPPTIMEJBORANG

DROP TABLE TBLPPTIMEJBORANG CASCADE CONSTRAINTS;

CREATE TABLE TBLPPTIMEJBORANG
(
  ID_PPTIMEJBORANG  NUMBER(16),
  ID_JENISDOKUMEN   NUMBER(16),
  IMEJ              BLOB,
  ID_MASUK          NUMBER,
  TARIKH_MASUK      DATE,
  ID_KEMASKINI      NUMBER,
  TARIKH_KEMASKINI  DATE,
  JENIS_MIME        VARCHAR2(100 BYTE)
)
TABLESPACE EKPTG
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (IMEJ) STORE AS 
      ( TABLESPACE  EKPTG 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE EKPTG
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


//15.5.2017

ALTER TABLE TBLPPTPERMINTAANUKUR
ADD (NO_HAKMILIK_SAMBUNG VARCHAR2(50 BYTE));

ALTER TABLE TBLPPTPERMINTAANUKUR
ADD (LUAS_AMBIL_SAMBUNG NUMBER(30,4));

//26.9.2017
ALTER TABLE TBLPPTAWARD
ADD(PERATUS_NILAI VARCHAR2(3 BYTE));

//8.10.2017
ALTER TABLE TBLPPTULASANTEKNIKAL
ADD(NAMA_JPBD VARCHAR2(50 BYTE));

ALTER TABLE TBLPPTULASANTEKNIKAL
ADD(EMEL_JPBD VARCHAR2(50 BYTE));

ALTER TABLE TBLPPTULASANTEKNIKAL
ADD(NAMA_JPPH VARCHAR2(50 BYTE));

ALTER TABLE TBLPPTULASANTEKNIKAL
ADD(EMEL_JPPH VARCHAR2(50 BYTE));

// 23.1.2018
ALTER TABLE TBLPPTHAKMILIK
MODIFY(SEKATAN_KEPENTINGAN VARCHAR2(4000 BYTE));

//11.02.2020
ALTER TABLE TBLPPTHAKMILIK ADD TARIKH_PEMBAYARAN DATE;
COMMIT;