--TAMBAHAN FIELD UNTUK PU STANDALONE

ALTER TABLE TBLPPTPU
ADD (LUAS_ASAL_HM  NUMBER (30,4));

ALTER TABLE TBLPPTPU
ADD (ID_UNITLUASASAL NUMBER (1));

ALTER TABLE TBLPPTPU
ADD (NILAI_METERPERSEGI  NUMBER (30,2));


CREATE TABLE TBLPPTPUPB
(
  ID_PUPB    NUMBER,
  ID_PU   NUMBER,
  PENAMA VARCHAR(4000),
  ULASAN VARCHAR(4000),
  TARIKH_SEDIA_BAYARAN DATE,
  PAMPASAN_TANAH NUMBER(30,2),
  JUMLAH_PELARASAN NUMBER(30,2),
  TEMPOH_LEWAT VARCHAR(10),
  FAEDAH_SEBELUM_PU VARCHAR(10),
  FAEDAH_SELEPAS_PU VARCHAR(10),
  TARIKH_SURAT DATE,
  BIL_SURAT VARCHAR(10),
  TEMPOH_AKHIR_BAYAR_SEMULA DATE,
  STATUS_BAYAR VARCHAR(10),
  NAMA_PB VARCHAR(4000),
  ID_JENISNOPB NUMBER,
  NO_PB VARCHAR(50),
  ID_JENISPB NUMBER,
  ID_BANGSA NUMBER,
  ID_WARGANEGARA NUMBER,
  ID_NEGERI NUMBER,
  ID_BANDAR NUMBER,
  JENIS_LAIN2_PB NUMBER,
  SYER_ATAS NUMBER,
  SYER_BAWAH NUMBER,
  ALAMAT1 VARCHAR(4000),
  ALAMAT2 VARCHAR(4000),
  ALAMAT3 VARCHAR(4000),
  POSKOD VARCHAR(5),
  NO_TEL_RUMAH VARCHAR(20),
  NO_HANDPHONE VARCHAR(20),
  NO_FAX VARCHAR(20),
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE SEQUENCE TBLPPTPUPB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  ALTER TABLE TBLPPTPUPB ADD (
  CONSTRAINT TBLPPTPUPB_PK
 PRIMARY KEY
 (ID_PUPB));
  

CREATE OR REPLACE TRIGGER TBLPPTPUPB_BI    
before insert on    TBLPPTPUPB    for each row
begin    if :new.ID_PUPB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTPUPB_SEQ.NEXTVAL into :new.ID_PUPB from dual;    end if;    end;
/



--------------------------------------


--ADD JENIS HAKMILIK YANG BARU
INSERT INTO TBLRUJJENISHAKMILIK
(ID_JENISHAKMILIK, KOD_JENIS_HAKMILIK,KETERANGAN,STATUS_HAKMILIK,SIMPANAN)
VALUES
('333','TDK','Tidak Dapat Dikesan','','');


---EDIT DAN TAMBAH FIELD DALAM TBLPPTBORANGO 24/10/2012----
ALTER TABLE TBLPPTBORANGO
RENAME COLUMN TARIKH_LANJUTAN_MAHKAMAH TO TARIKH_LANJUTAN_MAHKAMAH_OB;

ALTER TABLE TBLPPTBORANGO
 ADD (TARIKH_LANJUTAN_MAHKAMAH_PT  DATE);

---OPEN LIST UAT 2 PUNYA PENAMBAHBAIKKAN---

--UPDATE BARU--
UPDATE TBLRUJJENISPB SET KETERANGAN = 'TIDAK DAPAT DIKESAN' WHERE ID_JENISPB = '99'

--PENAMBAHAN UNTUK SKRIN BANTAHAN LIST UAT 2 HIDAYAH----
ALTER TABLE TBLPPTBANTAHAN
ADD (MAKLUMAT_BANTAHAN_TAMAT_TEMPOH  VARCHAR2(400));

ALTER TABLE TBLPPTBANTAHAN
ADD (FLAG_SEMAKAN_ONLINE  VARCHAR2(1));

ALTER TABLE TBLPPTBORANGO
ADD (TARIKH_LANJUTAN_MAHKAMAH  DATE);

ALTER TABLE TBLPPTBORANGO
ADD (KOS_JPPH  NUMBER(11,2));

ALTER TABLE TBLPPTBORANGO
ADD (NAMA_JPPH  VARCHAR2(400));

ALTER TABLE TBLPPTBORANGO
ADD (KOS_SWASTA  NUMBER(11,2));

ALTER TABLE TBLPPTBORANGO
ADD (NAMA_SWASTA  VARCHAR2(400));

ALTER TABLE TBLPPTBORANGO
ADD (SYARIKAT_SWASTA  VARCHAR2(400));

ALTER TABLE TBLPPTMAINBORANGO
ADD (KOS_JPPH  NUMBER(11,2));

ALTER TABLE TBLPPTMAINBORANGO
ADD (NAMA_JPPH  VARCHAR2(400));

ALTER TABLE TBLPPTMAINBORANGO
ADD (KOS_SWASTA  NUMBER(11,2));

ALTER TABLE TBLPPTMAINBORANGO
ADD (NAMA_SWASTA  VARCHAR2(400));

ALTER TABLE TBLPPTMAINBORANGO
ADD (SYARIKAT_SWASTA  VARCHAR2(400));




---OPEN LIST UAT 2 PUNYA PENAMBAHBAIKKAN RAZMAN---

ALTER TABLE TBLPPTBANGUNAN ADD NILAIAN_JPPH NUMBER (11,2);




--ADD JENIS PB YANG BARU
INSERT INTO TBLRUJJENISPB
(ID_JENISPB, KOD_JENIS_PB,KETERANGAN,JENIS_DAFTAR_PB)
VALUES
('45','ABN','Administrator De Bonis Non','');

---CLOSE LIST UAT 2 PUNYA PENAMBAHBAIKKAN---


--Hazwan--
ALTER TABLE TBLPPTSIASATAN ADD ID_UNIT_LUAS_MUKTAMAD NUMBER;

ALTER TABLE TBLPPTSIASATAN ADD LUAS_MUKTAMAD NUMBER (30,4);

--RAZMAN---
--suma ni field lama--

ALTER TABLE TBLPPTBORANGO ADD TARIKH_LANJUTAN_MAHKAMAH DATE;

ALTER TABLE TBLPPTBORANGO ADD NO_RUJUKAN_MAHKAMAH VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTBORANGO ADD SYARIKAT_SWASTA VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTBORANGO ADD NAMA_SWASTA VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTBORANGO ADD KOS_SWASTA NUMBER(11,2);

ALTER TABLE TBLPPTBORANGO ADD KOS_JPPH NUMBER(11,2);

ALTER TABLE TBLPPTBORANGO ADD NAMA_JPPH VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTMAINBORANGO ADD SYARIKAT_SWASTA VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTMAINBORANGO ADD NAMA_SWASTA VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTMAINBORANGO ADD KOS_SWASTA NUMBER(11,2);

ALTER TABLE TBLPPTMAINBORANGO ADD KOS_JPPH NUMBER(11,2);

ALTER TABLE TBLPPTMAINBORANGO ADD NAMA_JPPH VARCHAR2(4000 BYTE);


ALTER TABLE TBLPPTBANTAHAN
ADD FLAG_SEMAKAN_ONLINE VARCHAR(1 BYTE);

--DROP SEQUENCE TBLPPTENDOSANBORANGK_SEQ;
CREATE SEQUENCE TBLPPTENDOSANBORANGK_SEQ
  START WITH 999999
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


ALTER TABLE TBLPPTPEMBATALAN
ADD FLAG_SEMAKAN_ONLINE VARCHAR(1 BYTE);

ALTER TABLE TBLPPTPENARIKANBALIK
ADD FLAG_SEMAKAN_ONLINE VARCHAR(1 BYTE);

ALTER TABLE TBLPPTBANTAHAN
ADD maklumat_bantahan_tamat_tempoh VARCHAR(4000 BYTE);

ALTER TABLE TBLPPTPIHAKBERKEPENTINGAN
ADD NAMA_PENYATA_BANK VARCHAR(1000 BYTE);

ALTER TABLE TBLPPTPERMOHONAN
ADD JUMLAH_HAKMILIK NUMBER;

ALTER TABLE TBLPPTSIASATAN
ADD ID_UNIT_LUAS_MUKTAMAD NUMBER;

ALTER TABLE TBLPPTSIASATAN
ADD LUAS_MUKTAMAD NUMBER(30,4);

-------------------------------------------------



--Run On DBServer : 06072012
ALTER TABLE TBLPPTPERMOHONAN
ADD FLAG_PEMOHON VARCHAR(2 BYTE);

ALTER TABLE TBLPPTHAKMILIK
ADD FLAG_SEGERA_SEBAHAGIAN VARCHAR(2 BYTE);


--Run On DBServer : ________

ALTER TABLE TBLPPTTANAH
ADD STRUKTUR_BANGUNAN_SO NUMBER (11,2);

ALTER TABLE TBLPPTTANAH
ADD STRUKTUR_BANGUNAN NUMBER (11,2);

ALTER TABLE TBLPPTBANGUNAN
ADD SAIZ_BANGUNAN_DUA VARCHAR2(10 BYTE);

ALTER TABLE TBLPPTBANGUNANPB
ADD SAIZ_BANGUNAN_DUA VARCHAR2(10 BYTE);

CREATE TABLE TBLPPTNOTISAWAMHAKMILIK
(
  ID_NOTISAWAMHAKMILIK    NUMBER,
  ID_NOTISAWAM            NUMBER,
  ID_HAKMILIK             NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE SEQUENCE TBLPPTNOTISAWAMHAKMILIK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  

CREATE OR REPLACE TRIGGER TBLPPTNOTISAWAMHAKMILIK_BI    
before insert on    TBLPPTNOTISAWAMHAKMILIK    for each row
begin    if :new.ID_NOTISAWAMHAKMILIK    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTNOTISAWAMHAKMILIK_SEQ.NEXTVAL into :new.ID_NOTISAWAMHAKMILIK            from dual;    end if;    end;
/


ALTER TABLE TBLPPTNOTISAWAMHAKMILIK ADD (
  CONSTRAINT TBLPPTNOTISAWAMHAKMILIK_PK
 PRIMARY KEY
 (ID_NOTISAWAMHAKMILIK)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
CREATE TABLE TBLPPTBORANGEHAKMILIK
(
  ID_BORANGEHAKMILIK      NUMBER,
  ID_BORANGE              NUMBER,
  ID_HAKMILIK             NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE SEQUENCE TBLPPTBORANGEHAKMILIK_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  

CREATE OR REPLACE TRIGGER TBLPPTBORANGEHAKMILIK_BI    
before insert on     TBLPPTBORANGEHAKMILIK    for each row
begin    if :new.ID_BORANGEHAKMILIK    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTBORANGEHAKMILIK_SEQ.NEXTVAL into :new.ID_BORANGEHAKMILIK            from dual;    end if;    end;
/


ALTER TABLE TBLPPTBORANGEHAKMILIK ADD (
  CONSTRAINT TBLPPTBORANGEHAKMILIK_PK
 PRIMARY KEY
 (ID_BORANGEHAKMILIK)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
CREATE TABLE TBLPPTBORANGFHAKMILIKPB
(
  ID_BORANGFHAKMILIKPB    NUMBER,
  ID_BORANGF              NUMBER,
  ID_HAKMILIKPB           NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE SEQUENCE TBLPPTBORANGFHAKMILIKPB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  

CREATE OR REPLACE TRIGGER TBLPPTBORANGFHAKMILIKPB_BI    
before insert on     TBLPPTBORANGFHAKMILIKPB    for each row
begin    if :new.ID_BORANGFHAKMILIKPB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTBORANGFHAKMILIKPB_SEQ.NEXTVAL into :new.ID_BORANGFHAKMILIKPB            from dual;    end if;    end;
/


ALTER TABLE TBLPPTBORANGFHAKMILIKPB ADD (
  CONSTRAINT TBLPPTBORANGFHAKMILIKPB_PK
 PRIMARY KEY
 (ID_BORANGFHAKMILIKPB)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));               
               
               
CREATE TABLE TBLPPTAGIHANHM
(
  ID_AGIHANHM             NUMBER,
  ID_HAKMILIK             NUMBER,
  USER_ID                 NUMBER,
  BARIS                   NUMBER,
  ID_MASUK                NUMBER,
  TARIKH_MASUK            DATE,
  ID_KEMASKINI            NUMBER,
  TARIKH_KEMASKINI        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE SEQUENCE TBLPPTAGIHANHM_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  

CREATE OR REPLACE TRIGGER TBLPPTAGIHANHM_BI    
before insert on     TBLPPTAGIHANHM    for each row
begin    if :new.ID_AGIHANHM    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTAGIHANHM_SEQ.NEXTVAL into :new.ID_AGIHANHM            from dual;    end if;    end;
/


ALTER TABLE TBLPPTAGIHANHM ADD (
  CONSTRAINT TBLPPTAGIHANHM_PK
 PRIMARY KEY
 (ID_AGIHANHM)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               )); 
               
ALTER TABLE TBLPPTAGIHANHM
ADD TARIKH_SERAH DATE;

ALTER TABLE TBLPPTBORANGL
ADD ID_HAKMILIK NUMBER;

--Run on Local : 24072012 | Run On DBServer : ________

INSERT INTO TBLRUJJENISPB (ID_JENISPB, KOD_JENIS_PB, KETERANGAN,TARIKH_MASUK)
VALUES ('99', 'TDK', 'TIDAK DAPAT DIKESAN',SYSDATE);

ALTER TABLE TBLPPTHAKMILIK
ADD CATATAN_STOP_SIASATAN VARCHAR2(4000 BYTE);


--Run on Local : 25072012 | Run On DBServer : __________
ALTER TABLE TBLPPTHAKMILIK
ADD FLAG_STOP_SIASATAN VARCHAR2(2 BYTE);

ALTER TABLE TBLPPTHAKMILIK
ADD TARIKH_STOP_SIASATAN DATE;


--Run on Local : 25072012 | Run On DBServer : 25072012

INSERT INTO TBLRUJSTATUS (KOD_STATUS, KETERANGAN,TARIKH_MASUK,ID_SEKSYEN)
VALUES ('79', 'SIASATAN TIDAK DITERUSKAN',SYSDATE,'1');

INSERT INTO TBLRUJSUBURUSANSTATUS (ID_SUBURUSANSTATUS,ID_SUBURUSAN,ID_STATUS, AKTIF,TARIKH_MASUK)
VALUES ('161283077','52','1612196', '1',SYSDATE);


--Run on Local : 26072012 | Run On DBServer : __________

ALTER TABLE TBLPPTHAKMILIKPB
ADD ID_PA1 NUMBER;

ALTER TABLE TBLPPTHAKMILIKPB
ADD ID_PA2 NUMBER;

ALTER TABLE TBLPPTHAKMILIKPB
ADD ID_PA3 NUMBER;

ALTER TABLE TBLPPTHAKMILIKPB
ADD ID_PA4 NUMBER;

ALTER TABLE TBLPPTPIHAKBERKEPENTINGAN
ADD UMUR NUMBER(4);


--Run on Local : 06082012 | Run On DBServer : __________

CREATE TABLE TBLPPTPU
(
  ID_PU                    NUMBER CONSTRAINT TBLPPTPU_C01 NOT NULL,
  NO_FAIL_PU               VARCHAR2(100 BYTE),
  NO_SURAT_PTG             VARCHAR2(100 BYTE),
  TARIKH_SURAT_PTG         DATE,
  NO_PELAN                 VARCHAR2(50 BYTE),
  NO_PU                    VARCHAR2(20 BYTE),
  TARIKH_PU                DATE,
  TARIKH_TERIMA_SP         DATE,
  NO_SP                    VARCHAR2(20 BYTE),
  TARIKH_TERIMA_SA         DATE,
  TARIKH_TERIMA_PA         DATE,
  NO_PA                    VARCHAR2(20 BYTE),
  TARIKH_SELESAI           DATE,
  TARIKH_KEMBALI_UKUR      DATE,
  CATATAN                  VARCHAR2(400 BYTE),
  NAMA_PEGAWAI             VARCHAR2(80 BYTE),
  TARIKH_SEDIA             DATE,
  TARIKH_BAYAR             DATE,
  TARIKH_HAKMILIK_SAMBUNG  DATE,
  JENIS_PELARASAN          NUMBER(1),
  AMAUN_PU                 NUMBER(30,2),
  ID_UNITLUASPU            NUMBER,
  LUAS_PU                  NUMBER(30,4),
  FAEDAH_SEBELUM           NUMBER(30,2),
  FAEDAH_SELEPAS           NUMBER(30,2),
  TARIKH_BAYAR_AWARD       DATE,
  TARIKH_BORANGK           DATE,
  TARIKH_TERIMA_AGENSI     DATE,
  TARIKH_AKHIR_AGENSI      DATE,
  TARIKH_HANTAR_JUPEM      DATE,
  ID_MASUK                 NUMBER,
  TARIKH_MASUK             DATE,
  ID_KEMASKINI             NUMBER,
  TARIKH_KEMASKINI         DATE,
  ID_DB                    NUMBER,
  BIL_SURAT                VARCHAR2(50 BYTE),
  TARIKH_SURAT_SUSULAN     DATE,
  TEMPOH_AKHIR_CEK         VARCHAR2(15 BYTE),
  BEZA_LUAS                NUMBER(30,4),
  NO_LOT_BARU              VARCHAR2(20 BYTE),
  TARIKH_BAYARAN_TAMBAHAN  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLPPTPU_PK ON TBLPPTPU
(ID_PU)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE TBLPPTPU_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
CREATE OR REPLACE TRIGGER TBLPPTPU_BI    
before insert on     TBLPPTPU    for each row
begin    if :new.ID_PU    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTPU_SEQ.NEXTVAL into :new.ID_PU        from dual;    end if;    end;
/


ALTER TABLE TBLPPTPU ADD (
  CONSTRAINT TBLPPTPU_PK
 PRIMARY KEY
 (ID_PU)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
ALTER TABLE TBLPPTPU
ADD BAKI_LUAS NUMBER(30,4);

ALTER TABLE TBLPPTPU
ADD LUAS_ASAL NUMBER(30,4);

ALTER TABLE TBLPPTPU
ADD LUAS_AMBIL NUMBER(30,4);

ALTER TABLE TBLPPTPU
ADD ID_NEGERI NUMBER;

ALTER TABLE TBLPPTPU
ADD ID_DAERAH NUMBER;

ALTER TABLE TBLPPTPU
ADD ID_MUKIM NUMBER;

ALTER TABLE TBLPPTPU
ADD ID_JENISHAKMILIK NUMBER;

ALTER TABLE TBLPPTPU
ADD NO_HAKMILIK VARCHAR2(50 BYTE);

ALTER TABLE TBLPPTPU
ADD NO_LOT VARCHAR2(50 BYTE);

ALTER TABLE TBLPPTPU
ADD TARIKH_BORANGK DATE;

ALTER TABLE TBLPPTPU
ADD LUAS_AMBIL_HM NUMBER(30,4);

ALTER TABLE TBLPPTPU
ADD ID_UNITLUASAMBIL NUMBER;


--Run on Local : 08082012 | Run On DBServer : __________

CREATE TABLE TBLPPTMAINBANTAHAN
(
  ID_MAINBANTAHAN                 NUMBER CONSTRAINT TBLPPTMAINBANTAHAN_C02 NOT NULL,
  NO_BANTAHAN                     VARCHAR2(50 BYTE),
  NO_HAKMILIK                     VARCHAR2(50 BYTE),
  NO_LOT                          VARCHAR2(50 BYTE),
  ID_JENISPB                      NUMBER,
  STATUS_HADIR                    NUMBER,
  TARIKH_TERIMA_BORANGH           DATE,
  JENIS_PEMBANTAH                 NUMBER(1),
  NAMA_PEMBANTAH                  VARCHAR2(100 BYTE),
  TARIKH_TERIMA                   DATE,
  TARIKH_BORANGN                  DATE,
  ALAMAT1                         VARCHAR2(100 BYTE),
  ALAMAT2                         VARCHAR2(100 BYTE),
  ALAMAT3                         VARCHAR2(100 BYTE),
  POSKOD                          VARCHAR2(5 BYTE),
  ID_NEGERI                       NUMBER,
  ID_BANDAR                       NUMBER,
  FLAG_PENERIMA_PAMPASAN          VARCHAR2(1 BYTE),
  FLAG_BAHAGIAN_PAMPASAN          VARCHAR2(1 BYTE),
  FLAG_UKUR_LUAS                  VARCHAR2(1 BYTE),
  FLAG_PAMPASAN                   VARCHAR2(1 BYTE),
  FLAG_SYARAT                     VARCHAR2(1 BYTE),
  NO_FAIL                         VARCHAR2(100 BYTE),
  AMAUN_AWARD                     NUMBER(11,2),
  TARIKH_TERIMA_AWARD             DATE,
  ALASAN                          VARCHAR2(400 BYTE),
  STATUS_BANTAHAN                 NUMBER,
  CARA_BAYAR                      NUMBER(1),
  NO_RUJUKAN_BAYARAN              VARCHAR2(50 BYTE),
  TARIKH_SURAT_BAYARDEPOSIT       DATE,
  TEMPOH_BAYAR                    VARCHAR2(2 BYTE),
  UNIT_TEMPOH                     NUMBER(1),
  TARIKH_AKHIR_BAYARDEPOSIT       DATE,
  TARIKH_TERIMA_RESIT             DATE,
  TARIKH_RESIT                    DATE,
  NO_RESIT                        VARCHAR2(20 BYTE),
  FLAG_TERIMADEPOSIT              VARCHAR2(1 BYTE),
  AMAUN_DEPOSIT                   NUMBER(11,2),
  NO_RUJUKAN_SURATTARIKBALIK      VARCHAR2(50 BYTE),
  TARIKH_TERIMA_TARIKBALIK        DATE,
  TARIKH_SURAT_TARIKBALIK         DATE,
  FLAG_TARIKBALIK                 VARCHAR2(1 BYTE),
  TARIKH_CETAK                    DATE,
  TARIKH_CETAK_SEMULA             DATE,
  ID_MASUK                        NUMBER,
  TARIKH_MASUK                    DATE,
  ID_KEMASKINI                    NUMBER,
  TARIKH_KEMASKINI                DATE,
  ID_DB                           NUMBER,
  KEPENTINGANKEATAS               VARCHAR2(400 BYTE),
  AMAUN_TUNTUTAN                  NUMBER(14,2),
  STATUS_BANTAHAN_AP              NUMBER,
  FLAG_BATAL_MAHKAMAH             VARCHAR2(1 BYTE),
  CATATAN_BATAL_MAHKAMAH          VARCHAR2(400 BYTE),
  NO_RUJUKAN_SURAT_BATALMAHKAMAH  VARCHAR2(50 BYTE),
  TARIKH_TERIMA_BATALMAHKAMAH     DATE,
  TARIKH_SURAT_BATALMAHKAMAH      DATE,
  FLAG_ONLINE                     NUMBER,
  TARIKH_MOHON                    DATE,
  FLAG_SEMAKAN_ONLINE             NUMBER,
  USER_ID_NEGERI                  NUMBER,
  NO_RUJUKAN_MAHKAMAH             VARCHAR2(100 BYTE),
  TARIKH_LANJUTAN_MAHKAMAH        DATE,
  MAKLUMAT_BANTAHAN_TAMAT_TEMPOH  VARCHAR2(4000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE UNIQUE INDEX TBLPPTMAINBANTAHAN_PK ON TBLPPTMAINBANTAHAN
(ID_MAINBANTAHAN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE SEQUENCE TBLPPTMAINBANTAHAN_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER TBLPPTMAINBANTAHAN_BI    
before insert on     TBLPPTMAINBANTAHAN    for each row
begin    if :new.ID_MAINBANTAHAN    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTMAINBANTAHAN_SEQ.NEXTVAL into :new.ID_MAINBANTAHAN            from dual;    end if;    end;
/


ALTER TABLE TBLPPTMAINBANTAHAN ADD (
  CONSTRAINT TBLPPTMAINBANTAHAN_PK
 PRIMARY KEY
 (ID_MAINBANTAHAN)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
               
               
ALTER TABLE TBLPPTMAINBANTAHAN
ADD NAMA_BANK VARCHAR2(100 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD NO_AKAUN VARCHAR2(100 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD NAMA_PENGHANTAR VARCHAR2(100 BYTE);


ALTER TABLE TBLPPTMAINBANTAHAN
ADD CATATAN_PEMULANGAN_DEPOSIT VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD NAMA_BANK_DEPOSIT VARCHAR2(100 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD NO_AKAUN_DEPOSIT VARCHAR2(100 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD CARA_BAYAR_DEPOSIT NUMBER(1);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD NO_RUJUKAN_BAYARAN_DEPOSIT VARCHAR2(50 BYTE);

ALTER TABLE TBLPPTMAINBANTAHAN
ADD AMAUN_PAMPASAN NUMBER(15,2);

CREATE TABLE TBLPPTMAINBORANGO
(
  ID_MAINBORANGO               NUMBER CONSTRAINT TBLPPTMAINBORANGO_C01 NOT NULL,
  NO_BORANGO                   VARCHAR2(20 BYTE),
  TARIKH_BORANGO               DATE,
  TARIKH_CETAK                 DATE,
  TARIKH_CETAK_SEMULA          DATE,
  ID_BANTAHAN                  NUMBER,
  RINGKASAN_BANTAHAN           VARCHAR2(400 BYTE),
  PERIHAL_TANAMAN              VARCHAR2(400 BYTE),
  TARIKH_TERIMA_PERINTAH       DATE,
  TARIKH_TERIMA_SURATMAHKAMAH  DATE,
  FLAG_PULANG_DEPOSIT          VARCHAR2(1 BYTE),
  TARIKH_PERINTAH              DATE,
  ID_BANK                      NUMBER,
  NO_AKAUN                     VARCHAR2(20 BYTE),
  KEPUTUSAN_MAHKAMAH           NUMBER(1),
  PERINTAH_MAHKAMAH            VARCHAR2(400 BYTE),
  AMAUN_DENDA                  NUMBER(11,2),
  TARIKH_AKHIR_BAYAR           NUMBER,
  TEMPOH_BAYAR_AWARD           NUMBER(3),
  NO_RUJUKAN_TANAH             VARCHAR2(50 BYTE),
  CARA_SELESAI                 NUMBER(1),
  ID_MASUK                     NUMBER,
  TARIKH_MASUK                 DATE,
  ID_KEMASKINI                 NUMBER,
  TARIKH_KEMASKINI             DATE,
  KOS_PENGAPIT_HAKIM           NUMBER(11,2),
  ID_DB                        NUMBER,
  ID_MAHKAMAH                  NUMBER,
  NAMA_PENGHANTAR              VARCHAR2(80 BYTE),
  NAMA_BANK                    VARCHAR2(80 BYTE),
  NAMA_PENGHANTAR_BORANGO      VARCHAR2(80 BYTE),
  NAMA_PENERIMA_BORANGO        VARCHAR2(80 BYTE),
  TARIKH_HANTAR_BORANGO        DATE,
  CATATAN_PEMULANGAN_DEPOSIT   VARCHAR2(400 BYTE),
  NO_RUJUKAN_MAHKAMAH          VARCHAR2(100 BYTE),
  TARIKH_LANJUTAN_MAHKAMAH     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TBLPPTMAINBORANGO_PK ON TBLPPTMAINBORANGO
(ID_MAINBORANGO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE SEQUENCE TBLPPTMAINBORANGO_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER TBLPPTMAINBORANGO_BI    
before insert on     TBLPPTMAINBORANGO    for each row
begin    if :new.ID_MAINBORANGO    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPPTMAINBORANGO_SEQ.NEXTVAL into :new.ID_MAINBORANGO            from dual;    end if;    end;
/


ALTER TABLE TBLPPTMAINBORANGO ADD (
  CONSTRAINT TBLPPTMAINBORANGO_PK
 PRIMARY KEY
 (ID_MAINBORANGO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE TBLPPTMAINBORANGO
ADD KETERANGAN_PAMPASAN VARCHAR2(4000 BYTE);

ALTER TABLE TBLPPTPERMOHONAN
ADD FLAG_SEMAKAN_ONLINE NUMBER;

--**DUMP DATA TBLPPTBORANGE DAN TBLPPTNOTISAWAM (ID_PK SHJ DAN ID_HAKMILIK)KE DALAM TBLPPTBORANGEHAKMILIK DAN TBLPPTNOTISHAKMILIK
/*
INSERT INTO TBLPPTBORANGEHAKMILIK (ID_BORANGEHAKMILIK, ID_BORANGE, ID_HAKMILIK)
SELECT TBLPPTBORANGEHAKMILIK_SEQ.nextval, a, b
FROM
(SELECT ID_BORANGE AS a, ID_HAKMILIK AS b FROM TBLPPTBORANGE);

INSERT INTO TBLPPTNOTISAWAMHAKMILIK (ID_NOTISAWAMHAKMILIK, ID_NOTISAWAM, ID_HAKMILIK)
SELECT TBLPPTNOTISAWAMHAKMILIK_SEQ.nextval, a, b
FROM
(SELECT ID_NOTISAWAM AS a, ID_HAKMILIK AS b FROM TBLPPTNOTISAWAM);*/

--RAZMAN ALTER

INSERT
WHEN (SELECT COUNT(*) FROM TBLPPTBORANGEHAKMILIK WHERE ID_BORANGE = a AND ID_HAKMILIK = b) = 0 THEN
  INTO TBLPPTBORANGEHAKMILIK (ID_BORANGE,ID_HAKMILIK)      
(SELECT ID_BORANGE AS a, ID_HAKMILIK AS b FROM TBLPPTBORANGE WHERE ID_HAKMILIK IS NOT NULL);

INSERT
WHEN (SELECT COUNT(*) FROM TBLPPTNOTISAWAMHAKMILIK WHERE ID_NOTISAWAM = a AND ID_HAKMILIK = b) = 0 THEN
  INTO TBLPPTNOTISAWAMHAKMILIK (ID_NOTISAWAM,ID_HAKMILIK)      
(SELECT ID_NOTISAWAM AS a, ID_HAKMILIK AS b FROM TBLPPTNOTISAWAM WHERE ID_HAKMILIK IS NOT NULL);

ALTER TABLE TBLPPTAWARD
MODIFY
(
TEMPOH_LEWAT    VARCHAR2(10)
);


--KAT LIVE DAH RUN NI
ALTER TABLE TBLPPTPERMOHONAN
ADD FLAG_REMOVE_LOG VARCHAR(1);


