--create tblstrpemilik
DROP TABLE TBLSTRPEMILIK CASCADE CONSTRAINTS;

CREATE TABLE TBLSTRPEMILIK
(
  ID_PEMILIK             NUMBER(16)             NOT NULL,
  NAMA_PEMILIK           VARCHAR2(200 BYTE),
  ALAMAT1_PEMILIK        VARCHAR2(80 BYTE),
  ALAMAT2_PEMILIK        VARCHAR2(80 BYTE),
  ALAMAT3_PEMILIK        VARCHAR2(80 BYTE),
  POSKOD_PEMILIK         NUMBER(5),
  ID_KODBANDARPEMILIK    NUMBER,
  ID_KODNEGERIPEMILIK    NUMBER,
  ID_TBLSTRBANGUNANKHAS  NUMBER(16),
  NOPENGENALAN_PEMILIK   VARCHAR2(12 BYTE),
  JENIS_PEMILIK          VARCHAR2(10 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    30
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP SEQUENCE TBLSTRPEMILIK_SEQ;

CREATE SEQUENCE TBLSTRPEMILIK_SEQ
  START WITH 348
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
--create tbltrtemp

CREATE TABLE TBLSTRTEMP
(
  ID                NUMBER                      NOT NULL,
  ID_JENISHAKMILIK  NUMBER,
  NO_HAKMILIK       NUMBER,
  ID_LOT            NUMBER,
  LOT               NUMBER,
  ID_HAKMILIK       NUMBER,
  KEMASKINI_OLEH    VARCHAR2(100 BYTE),
  TARIKH_KEMASKINI  DATE,
  FLAG_AKTIVITI     VARCHAR2(10 BYTE)
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP SEQUENCE TBLSTRTEMP_SEQ;

CREATE SEQUENCE TBLSTRTEMP_SEQ
  START WITH 2882
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
ALTER TABLE TBLSTRCF
ADD (Ulasan VARCHAR2(500));

ALTER TABLE TBLSTRBANGUNANKHAS
ADD (ULASANTIADASTRATA VARCHAR2(500));