

CREATE SEQUENCE TBLPDTWARTATRM_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;
  
  
  
CREATE TABLE TBLPDTWARTATRM
(
	ID_WARTATRM NUMBER(38),
	FLAG_JENISWARTA VARCHAR2(1 BYTE),
	FLAG_STATUSWARTA VARCHAR2(1 BYTE),
	NO_WARTA VARCHAR2(100 BYTE),
	TARIKH_WARTA DATE,
	NAMA_FAIL_WARTA VARCHAR2(200 BYTE),
	JENIS_MIME_WARTA VARCHAR2(200 BYTE),
	CONTENT_WARTA BLOB,
	NO_PELAN VARCHAR2(100 BYTE),
	KAWASAN VARCHAR2(1000 BYTE),
	NAMA_FAIL_PELAN VARCHAR2(200 BYTE),
	JENIS_MIME_PELAN VARCHAR2(200 BYTE),
	CONTENT_PELAN BLOB,
	ID_NEGERI NUMBER(38),
	ID_DAERAH NUMBER(38),
	ID_MUKIM NUMBER(38),
	LUAS NUMBER(30,4),
	ID_MASUK NUMBER,
	ID_KEMASKINI NUMBER,
	TARIKH_MASUK DATE,
	TARIKH_KEMASKINI DATE 
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;  



ALTER TABLE TBLPDTWARTATRM ADD (
  CONSTRAINT TBLPDTWARTATRM_PK
 PRIMARY KEY
 (ID_WARTATRM));
 
CREATE OR REPLACE TRIGGER TBLPDTWARTATRM_BI    
before insert on     TBLPDTWARTATRM    for each row
begin    if :new.ID_WARTATRM    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTWARTATRM_SEQ.NEXTVAL into :new.ID_WARTATRM  from dual; end if;    end;
/





CREATE SEQUENCE TBLSEJARAHWTRMUTAMA_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLSEJARAHWTRMUTAMA
( 
  ID_SEJARAHWTRMUTAMA NUMBER(20) NOT NULL,
  JENIS_AKTIVITI VARCHAR2(10) NOT NULL, --INSERT,UPDATE,DELETE
  ID_WARTATRM NUMBER NOT NULL,
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLSEJARAHWTRMUTAMA PRIMARY KEY (ID_SEJARAHWTRMUTAMA)
);

CREATE OR REPLACE TRIGGER TBLSEJARAHWTRMUTAMA_BI    
before insert on     TBLSEJARAHWTRMUTAMA    for each row
begin    if :new.ID_SEJARAHWTRMUTAMA    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLSEJARAHWTRMUTAMA_SEQ.NEXTVAL into :new.ID_SEJARAHWTRMUTAMA   from dual; end if;    end;
/


CREATE SEQUENCE TBLSEJARAHWTRMSUB_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLSEJARAHWTRMSUB
( 
  ID_SEJARAHWTRMSUB NUMBER(20) NOT NULL,
  ID_SEJARAHWTRMUTAMA NUMBER(20) NOT NULL,
  REKOD_SEBELUM VARCHAR2(4000),
  REKOD_SELEPAS VARCHAR2(4000),
  REKOD_LABEL VARCHAR2(500),
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLSEJARAHWTRMSUB PRIMARY KEY (ID_SEJARAHWTRMSUB)
);

CREATE OR REPLACE TRIGGER TBLSEJARAHWTRMSUB_BI    
before insert on     TBLSEJARAHWTRMSUB    for each row
begin    if :new.ID_SEJARAHWTRMSUB    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLSEJARAHWTRMSUB_SEQ.NEXTVAL into :new.ID_SEJARAHWTRMSUB  from dual; end if;    end;
/


CREATE SEQUENCE TBLPDTWARTATRMBATALGANTI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;

CREATE TABLE TBLPDTWARTATRMBATALGANTI
( 
  ID_WARTATRMBATALGANTI NUMBER NOT NULL,
  ID_WARTATRMMST NUMBER NOT NULL,
  ID_WARTATRMSUB NUMBER NOT NULL,
  TYPE VARCHAR2(1),
  ID_MASUK NUMBER NOT NULL,
  TARIKH_MASUK      DATE DEFAULT SYSDATE,
  CONSTRAINT TBLPDTWARTATRMBATALGANTI PRIMARY KEY (ID_WARTATRMBATALGANTI)
);

CREATE OR REPLACE TRIGGER TBLPDTWARTATRMBATALGANTI_BI    
before insert on     TBLPDTWARTATRMBATALGANTI    for each row
begin    if :new.ID_WARTATRMBATALGANTI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTWARTATRMBATALGANTI_SEQ.NEXTVAL into :new.ID_WARTATRMBATALGANTI  from dual; end if;    end;
/



CREATE SEQUENCE TBLPDTTRMREPTAHUNNEGERI_SEQ
  START WITH 1
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


CREATE TABLE TBLPDTTRMREPTAHUNNEGERI
(
  ID_TRMREPTAHUNNEGERI  NUMBER,
  TAHUN                 NUMBER(4),
  ID_NEGERI             NUMBER,
  LUAS                  NUMBER(30,4),
  ID_MASUK              NUMBER,
  TARIKH_MASUK          DATE                    DEFAULT SYSDATE,
  ID_KEMASKINI          NUMBER,
  TARIKH_KEMASKINI      DATE
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TBLPDTTRMREPTAHUNNEGERI ADD (
  CONSTRAINT TBLPDTTRMREPTAHUNNEGERI
 PRIMARY KEY
 (ID_TRMREPTAHUNNEGERI));

CREATE OR REPLACE TRIGGER TBLPDTTRMREPTAHUNNEGERI_BI    
before insert on     TBLPDTTRMREPTAHUNNEGERI    for each row
begin    if :new.ID_TRMREPTAHUNNEGERI    is null    then SELECT (SELECT kod_negeri FROM tbllookupstate) || TO_CHAR (SYSDATE, 'YY') || TBLPDTTRMREPTAHUNNEGERI_SEQ.NEXTVAL into :new.ID_TRMREPTAHUNNEGERI  from dual; end if;    end;
/


------------------------------------------------- added 14/06/2017

CREATE TABLE TBLPDTTRMPILIHANTAHUN
(
  TAHUN                 NUMBER(4)  
);

ALTER TABLE TBLPDTTRMPILIHANTAHUN ADD (
  CONSTRAINT TBLPDTTRMPILIHANTAHUN
 PRIMARY KEY
 (TAHUN));




