DROP TABLE EKPTGWP.TBLPPKTUKARPEMOHON CASCADE CONSTRAINTS;

CREATE TABLE EKPTGWP.TBLPPKTUKARPEMOHON
(
  ID_SIMATI         NUMBER                      NOT NULL,
  ID_PEMOHONLAMA    NUMBER                      NOT NULL,
  ID_PEMOHONBARU    NUMBER                      NOT NULL,
  SEBAB_TUKAR       VARCHAR2(20 BYTE)           NOT NULL,
  BUKTI             VARCHAR2(4000 BYTE),
  NAMA_PEMOHONLAMA  VARCHAR2(50 BYTE),
  NAMA_PEMOHONBARU  VARCHAR2(50 BYTE),
  JENIS_MIME        VARCHAR2(100 BYTE),
  CONTENT           BLOB
)
TABLESPACE ETAPP01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (CONTENT) STORE AS 
      ( TABLESPACE  ETAPP01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        RETENTION
        NOCACHE
        INDEX       (
          TABLESPACE ETAPP01
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;



SET DEFINE OFF;
Insert into EKPTGWP.TBLPPKTUKARPEMOHON
   (ID_SIMATI, ID_PEMOHONLAMA, ID_PEMOHONBARU, SEBAB_TUKAR, BUKTI, 
    NAMA_PEMOHONLAMA, NAMA_PEMOHONBARU, JENIS_MIME, CONTENT)
 Values
   (1416536857, 1416614923, 1617616577, 'kematian', 'slippendengaran.txt', 
    'LEE SEW MOOI', 'YAP SOOK VOON', 'text/plain', 'SELECT DISTINCT A.PEG_PENGENDALI,    
        (SELECT REPLACE(NVL(TO_CHAR(SUM(JUMLAH_HTA),''999,999,999.99''),''0.00''),'' '') FROM (SELECT J.JUMLAH_HTA_TARIKHMOHON AS JUMLAH_HTA
    FROM TBLPPKPERBICARAAN F,
TBLPFDFAIL G,
TBLPPKPEMOHON H,
TBLPPKKEPUTUSANPERMOHONAN I,
TBLPPKPERMOHONAN J
WHERE G.ID_FAIL = J.ID_FAIL
AND J.ID_PERMOHONAN = I.ID_PERMOHONAN
AND I.ID_KEPUTUSANPERMOHONAN = F.ID_KEPUTUSANPERMOHONAN
AND H.ID_PEMOHON = J.ID_PEMOHON
--AND TO_DATE(F.TARIKH_BICARA,''dd/MM/yyyy'') >= TO_DATE(''$P!{tarikhBicara}'',''dd/MM/yyyy'')
--AND TO_DATE(F.TARIKH_BICARA,''dd/MM/yyyy'') <= TO_DATE(''$P!{tarikhBicaraTo}'',''dd/MM/yyyy'')
AND TO_DATE(TO_CHAR(F.TARIKH_BICARA,''dd/MM/yyyy''),''dd/MM/yyyy'')  
BETWEEN TO_DATE(''$P!{tarikhBicara}'' , ''dd/MM/yyyy'') 
AND TO_DATE(''$P!{tarikhBicaraTo}'' , ''dd/MM/yyyy'') 
AND ((''$P!{id_pegawai}'' != ''000''  AND UPPER(F.PEG_PENGENDALI) IN (SELECT UPPER(NAMA_PEGAWAI) FROM TBLPPKRUJUNIT WHERE ID_UNITPSK = ''$P!{id_pegawai}''))
OR (''$P!{id_pegawai}'' = ''000''))
AND J.ID_DAERAHMHN = $P!{idDaerah})) AS SUM_JUM_HTA,
(SELECT REPLACE(NVL(TO_CHAR(SUM(JUMLAH_HA),''999,999,999.99''),''0.00''),'' '') FROM (SELECT J.JUMLAH_HA_TARIKHMOHON AS JUMLAH_HA
    FROM TBLPPKPERBICARAAN F,
TBLPFDFAIL G,
TBLPPKPEMOHON H,
TBLPPKKEPUTUSANPERMOHONAN I,
TBLPPKPERMOHONAN J
WHERE G.ID_FAIL = J.ID_FAIL
AND J.ID_PERMOHONAN = I.ID_PERMOHONAN
AND I.ID_KEPUTUSANPERMOHONAN = F.ID_KEPUTUSANPERMOHONAN
AND H.ID_PEMOHON = J.ID_PEMOHON
--AND TO_CHAR(F.TARIKH_BICARA,''dd/MM/yyyy'') = ''$P!{tarikhBicara}''
AND TO_DATE(TO_CHAR(F.TARIKH_BICARA,''dd/MM/yyyy''),''dd/MM/yyyy'')  BETWEEN TO_DATE(''$P!{tarikhBicara}'' , ''dd/MM/yyyy'') AND TO_DATE(''$P!{tarikhBicaraTo}'' , ''dd/MM/yyyy'') 
AND ((''$P!{id_pegawai}'' != ''000''  AND UPPER(F.PEG_PENGENDALI) IN (SELECT UPPER(NAMA_PEGAWAI) FROM TBLPPKRUJUNIT WHERE ID_UNITPSK = ''$P!{id_pegawai}''))
OR (''$P!{id_pegawai}'' = ''000''))
AND J.ID_DAERAHMHN = $P!{idDaerah})) AS SUM_JUM_HA,
(SELECT REPLACE(NVL(TO_CHAR(SUM(JUMLAH_SELURUH),''999,999,999.99''),''0.00''),'' '') FROM (SELECT (SUM(J.JUMLAH_HTA_TARIKHMOHON) + SUM(J.JUMLAH_HA_TARIKHMOHON)) AS JUMLAH_SELURUH
    FROM TBLPPKPERBICARAAN F,
TBLPFDFAIL G,
TBLPPKPEMOHON H,
TBLPPKKEPUTUSANPERMOHONAN I,
TBLPPKPERMOHONAN J
WHERE G.ID_FAIL = J.ID_FAIL
AND J.ID_PERMOHONAN = I.ID_PERMOHONAN
AND I.ID_KEPUTUSANPERMOHONAN = F.ID_KEPUTUSANPERMOHONAN
AND H.ID_PEMOHON = J.ID_PEMOHON
--AND TO_CHAR(F.TARIKH_BICARA,''dd/MM/yyyy'') = ''$P!{tarikhBicara}''
AND TO_DATE(TO_CHAR(F.TARIKH_BICARA,''dd/MM/yyyy''),''dd/MM/yyyy'')  BETWEEN TO_DATE(''$P!{tarikhBicara}'' , ''dd/MM/yyyy'') AND TO_DATE(''$P!{tarikhBicaraTo}'' , ''dd/MM/yyyy'') 
AND ((''$P!{id_pegawai}'' != ''000''  AND UPPER(F.PEG_PENGENDALI) IN (SELECT UPPER(NAMA_PEGAWAI) FROM TBLPPKRUJUNIT WHERE ID_UNITPSK = ''$P!{id_pegawai}''))
OR (''$P!{id_pegawai}'' = ''000''))
AND J.ID_DAERAHMHN = $P!{idDaerah})) AS SUM_JUM_KESELURUHAN,
        TO_CHAR(A.TARIKH_BICARA,''DD/MM/YYYY'') AS TARIKH_BICARA,
TO_DATE(A.TARIKH_BICARA) AS TARIKH_BICARA_DATE,
UU.NAMA_PEGAWAI,
TO_CHAR(NVL(BAY.JUMLAH_BAYARAN,0),''999,999,990.99'') AS BAYARAN_PERINTAH
FROM TBLPPKPERBICARAAN A,TBLPPKBAYARAN BAY,
TBLPFDFAIL B,
TBLPPKPEMOHON C,
TBLPPKKEPUTUSANPERMOHONAN D,
TBLPPKPERMOHONAN E,TBLPPKRUJUNIT UU
WHERE B.ID_FAIL = E.ID_FAIL AND UU.ID_UNITPSK = A.ID_UNITPSK AND BAY.ID_PERMOHONAN = E.ID_PERMOHONAN
AND E.ID_PERMOHONAN = D.ID_PERMOHONAN
AND D.ID_KEPUTUSANPERMOHONAN = A.ID_KEPUTUSANPERMOHONAN
AND C.ID_PEMOHON = E.ID_PEMOHON
--AND TO_CHAR(A.TARIKH_BICARA,''dd/MM/yyyy'') = ''$P!{tarikhBicara}''
--AND TO_DATE(TO_CHAR(A.TARIKH_BICARA,''dd/MM/yyyy''),''dd/MM/yyyy'')  BETWEEN TO_DATE(''$P!{tarikhBicara}'' , ''dd/MM/yyyy'') AND TO_DATE(''$P!{tarikhBicaraTo}'' , ''dd/MM/yyyy'') 
AND ((''$P!{id_pegawai}'' != ''000''  AND UPPER(A.PEG_PENGENDALI) 
IN (SELECT UPPER(NAMA_PEGAWAI) FROM TBLPPKRUJUNIT WHERE ID_UNITPSK = ''$P!{id_pegawai}''))
OR (''$P!{id_pegawai}'' = ''000''))
AND E.ID_DAERAHMHN = $P!{idDaerah}
ORDER BY TO_DATE(TARIKH_BICARA_DATE, ''dd/MM/yyyy'') ASC');
Insert into EKPTGWP.TBLPPKTUKARPEMOHON
   (ID_SIMATI, ID_PEMOHONLAMA, ID_PEMOHONBARU, SEBAB_TUKAR, BUKTI, 
    NAMA_PEMOHONLAMA, NAMA_PEMOHONBARU, JENIS_MIME, CONTENT)
 Values
   (1412526398, 1616616201, 1616616202, 'kesihatan', 'brandsi.gif', 
    'KAMARUL ZAMAN BIN NASRON', 'HASSAN BIN NASRON', 'image/gif', 'GIF87aÈ
