/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2020-02-12 09:09:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Edited by Hazwan -->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>MyeTaPP</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<!-- <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" /> -->\r\n");
      out.write("<meta http-equiv=\"Pragma\" Content=\"cache\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/prototype.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/scriptaculous.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/modalbox.js\" ></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"library/scriptaculous/modalbox.css\" />\r\n");
      out.write("<!-- auto complete part-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/effects.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/controls.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/scriptaculous/ajax.js\" ></script>\r\n");
      out.write("<!-- Jquery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("<script>var $jquery = jQuery.noConflict();</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/js/jquery.pstrength-min.1.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/js/jquery.captchaRefresh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"library/js/ekptgTools.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<!-- addBy zulfazdliabuas@gmail.com Date 06/10/2017 -->\r\n");
      out.write("<link href=\"css/eTapp_Login/login.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var _gaq = _gaq || [];\r\n");
      out.write("_gaq.push(['_setAccount', 'UA-21977563-1']);\r\n");
      out.write("_gaq.push(['_trackPageview']);\r\n");
      out.write("\r\n");
      out.write("(function() {\r\n");
      out.write("  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\r\n");
      out.write("  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\r\n");
      out.write("  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("var BrowserDetect = {\r\n");
      out.write("\tinit: function () {\r\n");
      out.write("\t\tthis.browser = this.searchString(this.dataBrowser) || \"An unknown browser\";\r\n");
      out.write("\t\tthis.version = this.searchVersion(navigator.userAgent)\r\n");
      out.write("\t\t\t|| this.searchVersion(navigator.appVersion)\r\n");
      out.write("\t\t\t|| \"an unknown version\";\r\n");
      out.write("\t\tthis.OS = this.searchString(this.dataOS) || \"an unknown OS\";\r\n");
      out.write("\t},\r\n");
      out.write("\tsearchString: function (data) {\r\n");
      out.write("\t\tfor (var i=0;i<data.length;i++)\t{\r\n");
      out.write("\t\t\tvar dataString = data[i].string;\r\n");
      out.write("\t\t\tvar dataProp = data[i].prop;\r\n");
      out.write("\t\t\tthis.versionSearchString = data[i].versionSearch || data[i].identity;\r\n");
      out.write("\t\t\tif (dataString) {\r\n");
      out.write("\t\t\t\tif (dataString.indexOf(data[i].subString) != -1)\r\n");
      out.write("\t\t\t\t\treturn data[i].identity;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (dataProp)\r\n");
      out.write("\t\t\t\treturn data[i].identity;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t},\r\n");
      out.write("\tsearchVersion: function (dataString) {\r\n");
      out.write("\t\tvar index = dataString.indexOf(this.versionSearchString);\r\n");
      out.write("\t\tif (index == -1) return;\r\n");
      out.write("\t\treturn parseFloat(dataString.substring(index+this.versionSearchString.length+1));\r\n");
      out.write("\t},\r\n");
      out.write("\tdataBrowser: [\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"Chrome\",\r\n");
      out.write("\t\t\tidentity: \"Chrome\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{ \tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"OmniWeb\",\r\n");
      out.write("\t\t\tversionSearch: \"OmniWeb/\",\r\n");
      out.write("\t\t\tidentity: \"OmniWeb\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.vendor,\r\n");
      out.write("\t\t\tsubString: \"Apple\",\r\n");
      out.write("\t\t\tidentity: \"Safari\",\r\n");
      out.write("\t\t\tversionSearch: \"Version\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tprop: window.opera,\r\n");
      out.write("\t\t\tidentity: \"Opera\",\r\n");
      out.write("\t\t\tversionSearch: \"Version\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.vendor,\r\n");
      out.write("\t\t\tsubString: \"iCab\",\r\n");
      out.write("\t\t\tidentity: \"iCab\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.vendor,\r\n");
      out.write("\t\t\tsubString: \"KDE\",\r\n");
      out.write("\t\t\tidentity: \"Konqueror\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"Firefox\",\r\n");
      out.write("\t\t\tidentity: \"Firefox\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.vendor,\r\n");
      out.write("\t\t\tsubString: \"Camino\",\r\n");
      out.write("\t\t\tidentity: \"Camino\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\t\t// for newer Netscapes (6+)\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"Netscape\",\r\n");
      out.write("\t\t\tidentity: \"Netscape\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"MSIE\",\r\n");
      out.write("\t\t\tidentity: \"Explorer\",\r\n");
      out.write("\t\t\tversionSearch: \"MSIE\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"Gecko\",\r\n");
      out.write("\t\t\tidentity: \"Mozilla\",\r\n");
      out.write("\t\t\tversionSearch: \"rv\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{ \t\t// for older Netscapes (4-)\r\n");
      out.write("\t\t\tstring: navigator.userAgent,\r\n");
      out.write("\t\t\tsubString: \"Mozilla\",\r\n");
      out.write("\t\t\tidentity: \"Netscape\",\r\n");
      out.write("\t\t\tversionSearch: \"Mozilla\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t],\r\n");
      out.write("\tdataOS : [\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.platform,\r\n");
      out.write("\t\t\tsubString: \"Win\",\r\n");
      out.write("\t\t\tidentity: \"Windows\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.platform,\r\n");
      out.write("\t\t\tsubString: \"Mac\",\r\n");
      out.write("\t\t\tidentity: \"Mac\"\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t   string: navigator.userAgent,\r\n");
      out.write("\t\t\t   subString: \"iPhone\",\r\n");
      out.write("\t\t\t   identity: \"iPhone/iPod\"\r\n");
      out.write("\t    },\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tstring: navigator.platform,\r\n");
      out.write("\t\t\tsubString: \"Linux\",\r\n");
      out.write("\t\t\tidentity: \"Linux\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t]\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("BrowserDetect.init();\r\n");
      out.write("\r\n");
      out.write("// -->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function checkBrowser() {\r\n");
      out.write("\tif (BrowserDetect.browser != \"Firefox\") {\r\n");
      out.write("\t\tvar browser = BrowserDetect.browser + \" \" + BrowserDetect.version + \" pada \" + BrowserDetect.OS;\r\n");
      out.write("\t\talert(\"Anda menggunakan \" + browser + \"\\nSila gunakan browser Mozilla Firefox untuk paparan terbaik\");\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!--\r\n");
      out.write("<body leftmargin=\"0\" topmargin=\"5\" rightmargin=\"0\" bottommargin=\"0\" onLoad=\"document.flogin.username.focus();\" marginwidth=\"0\">\r\n");
      out.write("-->\r\n");
      out.write("<body onLoad=\"document.flogin.username.focus();\">\r\n");
      out.write("<!--\r\n");
      out.write("remove checking browser\r\n");
      out.write("checkBrowser();\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!-- Start Ediby zulfazdliabuas@gmail.com for New design Login Page Date 06/10/2017-->\r\n");
      out.write("<center>\r\n");
      out.write("\t<div id=\"logincontent\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div align=\"center\" class=\"body-regular\">\r\n");
      out.write("\t\t<div class=\"body-header\"></div>\r\n");
      out.write("\t\t<div class=\"body-title\"></div>\r\n");
      out.write("\t\t<div class=\"body-content\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- <div class=\"content_login\">\r\n");
      out.write("\t\t\t\t<font size=\"1\"><b>Sebarang masalah sila hubungi <a href=\"mailto:etappsupport@kptg.gov.my\"><font size=\"1\"><b>etappsupport@kptg.gov.my</b></font></a><br />\r\n");
      out.write("\t\t\t\t<font size=\"2\"><b>Paparan terbaik menggunakan Mozilla Firefox 3 atas dengan resolusi 1280 x 960</b></font>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"login-body\">\r\n");
      out.write("\t\t\t\t<form name=\"flogin\" method=\"post\" action=\"javascript:submitLogin()\">\r\n");
      out.write("\t\t\t\t\t<table align=\"right\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"4\" class=\"login-header\">\r\n");
      out.write("\t\t\t\t    \t\t\t<div class=\"header_login\">\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"log_masuk_icon\"></div>\r\n");
      out.write("\t\t\t\t    \t\t\t\t<div class=\"log_masuk\"><span>LOG MASUK</span></div>\r\n");
      out.write("\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t    \t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"4\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td rowspan=\"5\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t            <td colspan=\"2\" style=\"padding-left:3px; padding-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t            \t<label for=\"username\"><span style=\"font-size:0.9em\">ID PENGGUNA</span></label>\r\n");
      out.write("\t\t\t\t            </td>\r\n");
      out.write("\t\t\t\t          \t<td rowspan=\"5\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t            <td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t            \t<input class=\"form-control\" id=\"username\" name=\"username\" type=\"text\" tabindex=\"1\" autocomplete=\"off\" onKeyPress=\"return OnKeyPressGotoNextTabIndex(this, event)\" style=\"width:100%\" maxlength=\"25\" bordercolor=\"ffffff\">\r\n");
      out.write("\t\t\t\t            </td>\r\n");
      out.write("\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t   \t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"2\" height=\"10\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t            <td colspan=\"2\" style=\"padding-left:3px; padding-bottom: 3px;\">\r\n");
      out.write("\t\t\t\t            \t<label for=\"password\"><span style=\"font-size:0.9em\">KATA LALUAN</span></label>\r\n");
      out.write("\t\t\t\t            </td>\r\n");
      out.write("\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t            <td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t            \t<input class=\"form-control\" name=\"password\" type=\"password\" tabindex=\"2\" onKeyPress=\"return submitenter(this,event)\"  style=\"width:100%\" maxlength=\"25\">\r\n");
      out.write("\t\t\t\t            </td>\r\n");
      out.write("\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t       \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\" height=\"20\"></td>\r\n");
      out.write("\t\t\t\t       \t</tr> \r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\" style=\"padding-right: 15px;\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"button\" type=\"submit\" value=\"\" onKeyPress=\"javascript:submitLogin();\" onClick=\"javascript:submitLogin();\" tabindex=\"3\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"4\" height=\"10\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- open Razman  -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"4\" style=\"padding-left: 5px;\" valign=\"middle\">&raquo;&nbsp;\r\n");
      out.write("\t\t\t\t    \t\t\t<a href=\"./portal/PermohonanIDInternal.jsp\" title=\"Permohonan ID Pengguna\" \r\n");
      out.write("\t\t\t\t\t    \t\t\tonclick=\"Modalbox.show(this.href, {title: this.title, height: 700, width: 700, evalScripts: true, afterLoad: function() { pwdStrength();} }); return false;\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t<span style=\"font-size:1.2em; font-weight:bold\">Permohonan ID Pengguna Dalaman</span>\r\n");
      out.write("\t\t\t\t    \t\t\t</a>\r\n");
      out.write("\t\t\t\t    \t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<!-- close Razman --> \r\n");
      out.write("                        \r\n");
      out.write("                        <!-- open Deeba  -->\r\n");
      out.write("\t\t\t\t\t<!--\t<tr>\r\n");
      out.write("\t\t\t\t    \t\t<td colspan=\"4\" style=\"padding-left: 5px;\" valign=\"middle\">&raquo;&nbsp;\r\n");
      out.write("\t\t\t\t    \t\t\t<a href=\"./portal/PermohonanIDAgensiKewangan.jsp\" title=\"Permohonan ID Pengguna bagi Agensi Kewangan\" \r\n");
      out.write("\t\t\t\t\t    \t\t\tonclick=\"Modalbox.show(this.href, {title: this.title, height: 700, width: 700, evalScripts: true, afterLoad: function() { pwdStrength();} }); return false;\">\r\n");
      out.write("\t\t\t\t\t    \t\t\t<span style=\"font-size:1.2em; font-weight:bold\">Permohonan ID Pengguna bagi Agensi Kewangan</span>\r\n");
      out.write("\t\t\t\t    \t\t\t</a>\r\n");
      out.write("\t\t\t\t    \t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>-->\r\n");
      out.write("\t\t\t\t\t\t<!-- close Deeba --> \r\n");
      out.write("                        \r\n");
      out.write("\t\t\t\t       \t<tr>\r\n");
      out.write("\t\t\t\t           \t<td align=\"center\" colspan=\"4\">\r\n");
      out.write("\t\t\t\t           \t\t<span style=\"font-size:0.55em; font-family:Arial; font-weight:bold; color:#696969\">Sebarang masalah sila hubungi</span>&nbsp;<a href=\"mailto:etappsupport@jkptg.gov.my\"><i>etappsupport@jkptg.gov.my</i></a>\r\n");
      out.write("\t\t\t\t           \t</td>\r\n");
      out.write("\t\t\t\t       \t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"loginType\" value=\"internal\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- <div class=\"body-banner\"></div> -->\r\n");
      out.write("\t\t<div class=\"body-footer\">\r\n");
      out.write("\t\t\t<div class=\"title_footer\">\r\n");
      out.write("\t\t\t\t<div class=\"hakcipta\"><span>Hakcipta Terpelihara @ Kerajaan Malaysia 2017</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"jabatan\"><span class=\"bold\">JABATAN KETUA PENGARAH TANAH DAN GALIAN PERSEKUTUAN</span></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("<!-- End Ediby zulfazdliabuas@gmail.com for New design Login Page Date 06/10/2017 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function submitLogin() {\r\n");
      out.write("    if ( document.flogin.username.value == \"\" ) { alert(\"Sila masukkan ID Pengguna!\"); document.flogin.username.focus(); return; }\r\n");
      out.write("    if ( document.flogin.password.value == \"\" ) { alert(\"Sila masukkan katalaluan!\"); document.flogin.password.focus(); return; }\r\n");
      out.write("    \r\n");
      out.write("    document.flogin.action = \"c/login\";\r\n");
      out.write("    document.flogin.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submitenter(myfield,e)\r\n");
      out.write("{\r\n");
      out.write("var keycode;\r\n");
      out.write("if (window.event) keycode = window.event.keyCode;\r\n");
      out.write("else if (e) keycode = e.which;\r\n");
      out.write("else return true;\r\n");
      out.write("\r\n");
      out.write("if (keycode == 13)\r\n");
      out.write("{\r\n");
      out.write("\tdocument.flogin.submit();\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("   return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function OnKeyPressGotoNextTabIndex(field, event)\r\n");
      out.write("{\r\n");
      out.write("if (event.keyCode == 13) {\r\n");
      out.write("for (i = 0; i < field.form.elements.length; i++)\r\n");
      out.write("if (field.form.elements[i].tabIndex == field.tabIndex+1) {\r\n");
      out.write("field.form.elements[i].focus();\r\n");
      out.write("if (field.form.elements[i].type == \"text\")\r\n");
      out.write("field.form.elements[i].select();\r\n");
      out.write("break;\r\n");
      out.write("}\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
