/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2020-02-24 15:43:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class logout_005faudittrail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Create By zulfazdliabuas@gmail.com Date 18-04-2017 for Paparkan maklumat audittrail selepas logout. Source File : logout_audittrail.jsp -->\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"./css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"./css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<meta http-equiv=\"Pragma\" Content=\"cache\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/prototype.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/scriptaculous.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/modalbox.js\" ></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./library/scriptaculous/modalbox.css\" />\r\n");
      out.write("<!-- auto complete part-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/effects.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/controls.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/scriptaculous/ajax.js\" ></script>\r\n");
      out.write("<!-- Jquery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("<script>var $jquery = jQuery.noConflict();</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/js/jquery.pstrength-min.1.2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/js/jquery.captchaRefresh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./library/js/ekptgTools.js\" ></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".style1 {font-size: small}\r\n");
      out.write("-->\r\n");
      out.write("#zpopup {\r\n");
      out.write("    background-color: #000 !important;\r\n");
      out.write("    border: 0 none;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    /*z-index: 9999;*/\r\n");
      out.write("\topacity: 0.65;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divRekodAudit {\r\n");
      out.write("    height: 700px;\r\n");
      out.write("    left: 324.5px;\r\n");
      out.write("    overflow: visible;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    background-color: #ccd7b1;\r\n");
      out.write("    z-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divAuditTrail table{\r\n");
      out.write("   font-size:12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".zScroll{\r\n");
      out.write("\t/*border: 1px solid #000;*/\r\n");
      out.write("\toverflow: scroll;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    margin: 30 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boxAudit1{\r\n");
      out.write("\twidth:75%;\r\n");
      out.write("\tmargin:0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".boxAudit2{\r\n");
      out.write("\t/*height:600px;*/\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\t/* width: 50%; */\r\n");
      out.write("    /*margin: 190px auto;*/\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divButton{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tpadding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table > thead > tr > th{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divButton .btn-lg{\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onLoad=\"getAuditTrail();\">\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t<div id=\"logincontent\">\r\n");
      out.write("\t\t<div class=\"body-regular\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"body-header\"></div>\r\n");
      out.write("\t\t\t<div class=\"body-title\"></div>\r\n");
      out.write("\t\t\t<div class=\"body-content\">\r\n");
      out.write("\t\t\t\t<div class=\"login-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form id=\"f1\" name=\"f1\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"zpopup\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"command\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"user_id\" name=\"user_id\" value=\"");
 out.print(session.getAttribute("_ekptg_user_id"));
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"boxAudit1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"boxAudit2\">\r\n");
      out.write("\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t<h4>REKOD TINDAKAN</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"divAuditTrail\" class=\"zScroll\">\r\n");
      out.write("\t\t\t\t\t\t\t\tTiada Rekod\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <input type=\"button\" id=\"okAudit\" name=\"okAudit\" value=\"OK\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"divButton\" name=\"divButton\" class=\"divButton\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary btn-lg\"  id=\"logoutOk\" value=\"logoutOk\" onclick=\"getLogoutOk()\">OK</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <a href='javascript:document.location.href = \"logout\"' class=\"font_welcome\"><u>Logout</u></a> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"body-banner\"></div>\r\n");
      out.write("\t\t\t<div class=\"body-footer\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//alert(\"1 : \"+document.getElementById(\"user_id\").value);\r\n");
      out.write("getAuditTrail = function() {\r\n");
      out.write("\t//alert(\"MASUK\");\r\n");
      out.write("\t//var user_id = document.getElementById(\"user_id\").value;\r\n");
      out.write("\turl = \"./servlet/ekptg.view.online.LogoutAuditTrail\";\r\n");
      out.write("\tactionName = \"getAuditTrail\";\r\n");
      out.write("\ttarget = \"divAuditTrail\";\r\n");
      out.write("\tdoAjaxUpdater(document.f1, url, target, actionName);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("getLogoutOk = function(){\r\n");
      out.write("\t//alert(\"MASUK X\");\r\n");
      out.write("//\turl = \"./servlet/ekptg.view.online.LogoutAuditTrail\";\r\n");
      out.write("//\tactionName = \"getLogoutOk\";\r\n");
      out.write("\t//target = \"divButton\";\r\n");
      out.write("//\ttarget = \"./logout_online.jsp\";\r\n");
      out.write("//\tdoAjaxUpdater(document.f1, url, target, actionName);\r\n");
      out.write("\twindow.top.location.replace(\"logout_online.jsp\");\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
